### ISSUE TITLE
Dialogue open URL example

### ISSUE THREAD

**Issue by gbaman** [MicrosoftDocs/minecraft-creator#105]
Could we get an example that implements the opening web URL option from NPCs with /dialogue, for use with custom scenes (when a button is pressed)? Can't find the syntax for it anywhere, but assuming it must be possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db96f8d1-4b84-da2b-68cd-3f0ef7a6f269
* Version Independent ID: 0577bd5f-9522-d3d8-0a3b-5cb928b0b443
* Content: [NPC Dialogue Command](https://docs.microsoft.com/en-us/minecraft/creator/documents/npcdialogue)
* Content Source: [creator/Documents/NPCDialogue.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/NPCDialogue.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by v-jeffreykim** [comment]
Currently, URL functionality is not supported in Bedrock Edition. I've reached out to the feature team and they are working on implementing support for this functionality in Bedrock Edition, so if you have any comments or would like to see any specific features, you can visit the [Minecraft Feedback](https://feedback.minecraft.net/hc/en-us) page and [post your suggestion](https://feedback.minecraft.net/hc/en-us/signin?return_to=https%3A%2F%2Ffeedback.minecraft.net%2Fhc%2Fen-us%2Fcommunity%2Fposts%2Fnew).

I will go ahead and close this issue, but please let us know if you have any other questions!
