### ISSUE TITLE
[Wrong property] 'Priority' key is either wrong, or needs more explanation

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#106]
![image](https://user-images.githubusercontent.com/18729296/128506112-e53afa15-6187-41e2-afd4-ac174254b162.png)

This property makes no sense in this context, so is therefor either wrong, or needs additional explanation. 

What does furnace output have to do with shapeless recipe, and why is it called priority?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6116e441-e949-f5bd-0f52-01f10474c481
* Version Independent ID: f4f7ad28-b2f5-6a8a-267b-46df67256de9
* Content: [Shapeless Recipe](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/recipedefinitions/minecraftrecipe_shapeless)
* Content Source: [creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_Shapeless.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_Shapeless.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Will adjust in hotfix. This has been corrected on our end.
