### ISSUE TITLE
Wrong parameter in minecraft:random_ticking component.

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#107]
`minecraft:random_ticking` block component doesn't allow Array of `range` as it's parameter, however this page says it does. It would be nice to fix that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60113683-a410-af31-dc53-cdfd017be644
* Version Independent ID: f6db4d73-5f65-c830-68e8-3f558dce6a71
* Content: [minecraft:random_ticking](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_random_ticking)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_random_ticking.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_random_ticking.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Will address in hotfix
