### ISSUE TITLE
minecraft:spell_effects needs clarification

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#108]
Page states this:

`remove_effects, type string, List of identifiers of effects to be removed from this entity after adding this component`

The example json is like this:

```json
"minecraft:spell_effects":{
    "add_effects":[
    {
        "effect": "heal",
        "duration": 25
    }
    ],
    "remove_effects": "poison"
}
```

The question is: Is it possible to also define a list, like this?

```json
"minecraft:spell_effects":{
    "remove_effects": ["poison", "heal"]
}
```

If so, than the documentation needs to be adjusted to allow this. If NOT, than the description needs to be updated to say something like:

"The name of the effect you want to remove. It is only possible to remove one effect at a time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 576fc3d9-fbf7-767b-293b-b7b6594415e0
* Version Independent ID: 41bddc84-5d1e-b388-5c5a-3ce7c4ed3607
* Content: [minecraft:spell_effects](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityattributes/minecraftattribute_spell_effects)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityAttributes/minecraftAttribute_spell_effects.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityAttributes/minecraftAttribute_spell_effects.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by tryashtar** [comment]
In addition, it is not clear what the names of effects are in this component. If the `heal` example is accurate, these names do not correspond to those in the `/effect` command (which would be `instant_health`). What is the reason these names are different, and what is the mapping of `/effect` names to `spell_effects` names?

**Comment by v-jeffreykim** [comment]
Thanks for the detailed feedback! I spoke with the devs to confirm the behavior and pushed an update that addresses this issue.

You can, indeed, use a list to define `remove_effects` exactly like your example. You should see the changes reflected here: https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityAttributes/minecraftAttribute_spell_effects.md

Thanks!
Jeff
