### ISSUE TITLE
query.is_jumping wrong description

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#109]
query.is_jumping has the following description:
Returns 1.0 if the entity is in water or rain, else it returns 0.0

It should possibly be something else

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e2f3cb-b70a-1f3b-b399-de78d15dd487
* Version Independent ID: 8955263e-956f-7ecf-d86b-5acdd6bf5fd6
* Content: [Query Functions](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/queryfunctions)
* Content Source: [creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Similar to the Entity Documentation, We are gonna start compiling a list of missing/incorrect information for Molang. This way, we can gather a large set of data in order to test against as we bug fix any issues and then begin to fix it on a larger scale.

**Comment by DaanV2** [comment]
Making a more tasklist friendly issues towards multiple queries, closing this one
