### ISSUE TITLE
Suggestion: Molang; Split off Animations, Animations controller queries

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#111]
For example:

query.all_animations_finished & query.any_animation_finished are animation controller specific queries that work on both client and server side, maybe their own table of queries would be in order? It would be able to remove the text: `Only valid in an animation controller.` from their descriptions and reduce clutter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e2f3cb-b70a-1f3b-b399-de78d15dd487
* Version Independent ID: 8955263e-956f-7ecf-d86b-5acdd6bf5fd6
* Content: [Query Functions](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/queryfunctions#feedback)
* Content Source: [creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Mentioned in another issue, (#116)[https://github.com/MicrosoftDocs/minecraft-creator/issues/116#issuecomment-898013184]

Will address this in our Molang reference doc restructuring.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
