### ISSUE TITLE
Documentation: Molang, wrong categorization

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#112]
The following queries are marked as Entity queries but in fact, belong to different sections or other parts of Minecraft.

- [ ] query.all_tags - Item / Block
- [ ] query.any_tag - Item / Block
- [ ] query.all_animations_finished - animations controllers
- [ ] query.any_animations_finished - animations controllers
- [ ] query.average_frame_time - global?
- [ ] query.approx_eq - global? Shouldn't this be a math function?
- [ ] query.block_face - Block
- [ ] query.block_property - Block
- [ ] query.camera_distance_range_lerp - Seems global for anything that is rendered?
- [ ] query.camera_rotation - Seems global for anything that is rendered?
- [ ] query.cardinal_block_face_placed_on - Block, Is deprecated though.
- [ ] query.cardinal_facing - Seems to retrieve data only for the player that is rendering the scene, can be used by anyone. Made a player section?
- [ ] query.cardinal_facing_2d - See Previous
- [ ] query.cardinal_player_facing - See Previous
- [ ] query.count - Global
- [ ] query.day - Global
- [ ] query.debug_output - Global or Debug? (This one needs more explanations on how to use it)
- [ ] query.delta_time - Global
- [ ] query.distance_from_camera - Global?
- [ ] query.effect_emitter_count - Particle
- [ ] query.effect_particle_count - Particle
- [ ] query.frame_alpha - Global / Rendering?
- [ ] query.get_animation_frame - Item / Render Controller?
- [ ] query.get_default_bone_pivot - Animations?
- [ ] query.get_locator_offset - Animations
- [ ] query.get_root_locator_offset - Animations
- [ ] query.has_block_property - Block
- [ ] query.heightmap - World?
- [ ] query.item_in_use_duration - Item?
- [ ] query.item_is_charged - Item?
- [ ] query.item_max_use_duration- Item?
- [ ] query.item_remaining_use_duration- Item?
- [ ] query.item_slot_to_bone_name- Item?
- [ ] query.key_frame_lerp_time - Global?
- [ ] query.life_time - Animation
- [ ] query.log - Debug
- [ ] query.max_durability - Item
- [ ] query.maximum_frame_time - Global / Rendering
- [ ] query.minimum_frame_time - Global / Rendering
- [ ] query.moon_brightness - Global
- [ ] query.moon_phase - Global
- [ ] query.noise - Global
- [ ] query.player_level - Player
- [ ] query.remaining_durability - Item
- [ ] query.rotation_to_camera - Global / Rendering
- [ ] query.texture_frame_index - Item?
- [ ] query.time_of_day - Global
- [ ] query.time_stamp - Global
- [ ] query.total_emitter_count - Particle
- [ ] query.total_particle_count - Particle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e2f3cb-b70a-1f3b-b399-de78d15dd487
* Version Independent ID: 8955263e-956f-7ecf-d86b-5acdd6bf5fd6
* Content: [Query Functions](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/queryfunctions#feedback)
* Content Source: [creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Will address this in a hotfix.

**Comment by JimSeaman42** [comment]
Thanks as always for your feedback. It seems like this issue is no longer applicable to the current documentation so I'm going to close it. If there are any issues, please don't hesitate to reach out.
