### ISSUE TITLE
Documentation: Molang Queries, wrong description

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#115]
The following queries have an error in their description or could use for more clarification:

- [ ] query.camera_rotation - Range of output?
- [ ] query.body_x_rotation - Range of output?
- [ ] query.body_y_rotation - Range of output?
- [ ] query.is_jumping - wrong description
- [ ] query.head_x_rotation - Range of output, I believe negative numbers are actually looking up
- [ ] query.head_y_rotation - Rnage of output
- [ ] query.item_max_use_duration - Unit of output?
- [ ] query.lie_amount - Unit of output
- [ ] query.modified_move_speed Unit of output
- [ ] query.noise - Range of output?
- [ ] query.shake_time - Unit of output
- [ ] query.tail_angle - Range of output, and if negative is forexample upwards or downwards
- [ ] query.time_stamp - Unix / Seconds, missing unit or format description
- [ ] query.walk_distance - Unit of output

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e2f3cb-b70a-1f3b-b399-de78d15dd487
* Version Independent ID: 8955263e-956f-7ecf-d86b-5acdd6bf5fd6
* Content: [Query Functions](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/queryfunctions#feedback)
* Content Source: [creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/MolangReference/Examples/MolangConcepts/QueryFunctions.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by qmagnet** [comment]
Previously commented, but here seems more appropriate. Found error for `query.is_jumping`
![image](https://user-images.githubusercontent.com/13902631/133344148-db76fda8-f1fa-4a92-ba06-2163790d1c2f.png)

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
