### ISSUE TITLE
Suggestion: Split Math functions into it's own page

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#116]
I frequently search for MoLang math functions and it's a bit unintuitive to have them in "Introduction to Molang". I think it would be much better as it's own page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b502d2e-471f-d263-1635-f32aaa375fce
* Version Independent ID: 0ce04ad7-8cbb-4a96-8778-6d995ee94903
* Content: [Introduction to Molang](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/molangintroduction)
* Content Source: [creator/Reference/Content/MolangReference/Examples/MolangConcepts/MolangIntroduction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/MolangReference/Examples/MolangConcepts/MolangIntroduction.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
The Molang reference docs are planned to be overhauled in a manner similar to how Entities was done. We are in the process of gathering any missing information and working on ways to break it down and structure it in a friendlier way. Intro to Molang is a large document that has a lot of the topics covered but would benefit from a re-write with more dedicated pages.

**Comment by stirante** [comment]
Hey,
It's not really what I had in mind in this issue.

The issue is that in Molang Introduction, there are more topics than just introduction:
1. Right away we're hit with versioned changes, which should also be a separate page for reference. It could be mentioned in Introduction, but definitely not as a first thing in the article.
2. Math functions should be literally a separate thing in the left sidebar (just like experimental and normal query functions have their own pages). Every time I want to look up whether some math function exist, I have to scroll quite a large amount to get exactly where those are
