### ISSUE TITLE
Documentation: Vague, bad molang descriptions

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#118]
Many queries are "documented" by simply restating the name of the query, which is not at all helpful. Many queries do not make clear when they are actually applicable.

I went through every documented query, and listed all of the ones I felt were insufficiently descriptive (except for the ones covered in #113). Enjoy! 😀

- [x] `query.approx_eq`: "Returns 1.0 if all of the arguments are within 0.000000 of each other"? What?
- [x] `query.armor_color_slot`: Is this dyed leather armor color, or something else? How are the colors returned, as a number or what?
- [x] `query.armor_material_slot`: Like above.
- [x] `query.blocking`: Blocking with what? A shield? Does this only work for players?
- [x] `query.can_climb`: What makes an entity able to climb? The `can_climb` component? If so, just say that.
- [x] `query.can_damage_nearby_mobs`: What does this mean? Is it true for creepers? End crystals? Anvils? Players?
- [x] `query.can_fly`: What makes an entity able to fly? The `can_fly` component? If so, this returns false for phantoms. Seems unintuitive, should be documented.
- [x] `query.can_power_jump`: Like above, is this just the `can_power_jump` component? If so, just say that.
- [x] `query.can_swim`: Like above. What does this mean?
- [ ] `query.can_walk`: Like above.
- [ ] `query.cape_flap_amount`: What determines this value? It seems like this exists purely as a hack to implement capes.
- [ ] `query.current_squish_value`: What does this mean? Is it for slimes? When does this value change, and what is its range?
- [ ] `query.day`: `/time query day`, or `/time query daytime`? Or something else altogether?
- [ ] `query.debug_output`: This does nothing.
- [ ] `query.distance_from_camera`: This does not work properly with particles.
- [ ] `query.equipment_count`: What does equipment count mean? The number of armor pieces? If so, just say that.
- [ ] `query.equipped_item_is_attachable`: What makes an item an attachable? Which items is this true for?
- [x] `query.eye_target_x_rotation`: How does this differ from `query.target_x_rotation`? What does "X eye rotation" even mean?
- [ ] `query.frame_alpha`: "Returns the ratio (from 0 to 1) of how much between AI ticks this frame is being rendered." This makes no sense.
- [ ] `query.get_actor_info_id`: What are these IDs? When is accessing this data useful?
- [x] `query.get_animation_frame`: "Returns the current texture of the item." That doesn't sound right.
- [ ] `query.get_default_bone_pivot`: "Gets specified axis of the specified bone orientation pivot." How do you specify a bone orientation pivot? What does this actually return? How is this used?
- [ ] `query.get_equipped_item_name`: Should document that this incorrectly omits namespaces.
- [ ] `query.get_locator_offset`: How do you specify a locator and axis? What does this actually return?
- [ ] `query.get_name`: What name? Only a custom name from a name tag? Does it work for players?
- [ ] `query.get_root_locator_offset`: Same as `query.get_locator_offset`. How do these two queries differ?
- [ ] `query.ground_speed`: Current moving speed, or maximum speed?
- [ ] `query.has_armor_slot`: How do you specify which slot?
- [ ] `query.has_owner`: What kind of owner? A tamed wolf owner, or a projectile owner? Why does this description say "true" and "false" instead of "1.0" and "0.0"?
- [ ] `query.has_target`: What kind of target? A target that it's attacking?
- [ ] `query.head_roll_angle`: What's the range of output? Which entities can even do this, and when?
- [ ] `query.head_x_rotation`: What is the point of the head index parameter? Is it just for withers? If so, just say that. Does this just check the current animated rotation of the "head" bone, or something else?
- [ ] `query.head_y_rotation`: Like above.
- [ ] `query.health`: Does this work for only mobs, or also items, boats, and minecarts?
- [ ] `query.heightmap`: "Queries Height Map." Completely useless description.
- [ ] `query.hurt_direction`: What does this mean?
- [ ] `query.hurt_time`: What does this mean?
- [ ] `query.invulnerable_ticks`: What does this mean? How is it different from `query.hurt_time`?
- [ ] `query.is_admiring`: When is this the case? Is this related to the `admire_item` component, or the `behavior.admire_item` behavior, or the `admire` field in the `shareables` component? Which, if any, of those are required in order to utilize this query?
- [ ] `query.is_angry`: When is this the case? Is this related to the `angry` component?
- [ ] `query.is_attached_to_entity`: When is this the case? Does holding a mob on a lead count? If so, for which of the two involved mobs?
- [ ] `query.is_avoiding_block`: Is this related to `avoid_water`/`avoid_damage_blocks`/`avoid_sun` in navigation components, or the `avoid_block` behavior? Does this work with blocks that are illegal due to negative cost in `preferred_path_blocks`?
- [ ] `query.is_avoiding_mobs`: Is this related to the `avoid_mob_type` behavior? Does it also work for the `panic` behavior, when mobs flee from damage?
- [ ] `query.is_baby`: Is this just the `is_baby` component? If so, just say that.
- [ ] `query.is_breathing`: Which entities breathe, and when? Is this related to the `breathable` component?
- [ ] `query.is_bribed`: When is this the case? Is this related to the `tempt` behavior?
- [ ] `query.is_carrying_block`: When is this the case? Is it just for endermen? Does it work for minecarts carrying chests/hoppers? Does it work for players holding blocks?
- [ ] `query.is_casting`: When is this the case? Is it just used for the evoker's `summon_entity`/`send_event` behaviors?
- [ ] `query.is_celebrating`: Is this related to the `celebrate` behavior?
- [ ] `query.is_celebrating_special`: How does this differ from `query.is_celebrating`? What makes a celebration "special"?
- [ ] `query.is_charged`: When is this the case? Do charged creepers count as charged?
- [ ] `query.is_charging`: When is this the case? Is this related to `query.is_charged`? Does a goat preparing to ram count as charging? Does a pillager loading a crossbow count as charging?
- [ ] `query.is_chested`: Is this just the `is_chested` component? If so, just say that. Does it work for chest minecarts?
- [ ] `query.is_critical`: When is this the case? I can't think of any time I would describe an entity as being "critical." Is it a fully charged arrow shot?
- [ ] `query.is_dancing`: When is this the case? Is this just a hack to implement parrot jukebox dancing? If so, just say that.
- [ ] `query.is_delayed_attacking`: Is this related to the `delayed_attack` component?
- [ ] `query.is_eating`: When is this the case? Does it count grazing sheep? Pandas eating bamboo? Players eating food? Foxes eating berries? Animals getting bred?
- [ ] `query.is_elder`: If this is just a hack to implement elder guardians, just say that.
- [ ] `query.is_emoting`: When is this the case? A player using an emote animation?
- [ ] `query.is_enchanted`: When is this the case? I can't think of any time I would describe an entity as being "enchanted."
- [ ] `query.is_fire_immune`: Is this just the `fire_immune` component? Does it count fire resistance potions? Does it count netherite armor items on the ground?
- [ ] `query.is_first_person`: I'm assuming this only works for players. That is not clear in the description if so. If not, it should definitely mention which entities it can be true for.
- [ ] `query.is_ghost`: If this is just a hack to implement the elder guardian jumpscare particle, just say that.
- [ ] `query.is_gliding`: When is this the case? Phantoms? Elytra?
- [ ] `query.is_grazing`: When is this the case? Sheep grazing? Random horse grazing? `eat_block` behavior?
- [ ] `query.is_idling`: When is this the case?
- [ ] `query.is_ignited`: When is this the case? Is it just creepers you've used flint and steel on? If so, there's no component for that. Does it work for primed TNT?
- [ ] `query.is_illager_captain`: Is this just the `is_illager_captain` component?
- [ ] `query.is_in_love`: When is this the case? When breeding mobs?
- [ ] `query.is_interested`: Interested in what? Is this related to the `tempt` behavior? The `admire_item` behavior? The `tameable` component, like wolves begging for bones?
- [ ] `query.is_invisible`: When is this the case? Does it work for a mob with no render controller? A mob with the invisibility effect? What if the mob has visible armor on?
- [ ] `query.is_laying_down`: When is this the case? Foxes sleeping? Dead mobs?
- [ ] `query.is_laying_egg`: Is this related to the `lay_egg` behavior?
- [ ] `query.is_leashed`: Using a lead? Does this count the player, or the mob, or both?
- [ ] `query.is_levitating`: With the levitation effect? Do bees count? Do ender crystals count?
- [ ] `query.is_lingering`: When is this the case? Only for area effect clouds?
- [ ] `query.is_onfire`: What is the difference between this and `query.is_on_fire`? Why do these both exist?
- [ ] `query.is_orphaned`: When is this the case?
- [ ] `query.is_playing_dead`: Is this related to the `play_dead` behavior?
- [ ] `query.is_powered`: When is this the case? Charged creepers?
- [ ] `query.is_pregnant`: When is this the case? Turtles? There is no component associated with this.
- [ ] `query.is_ram_attacking`: Is this related to the `ram_attack` behavior?
- [ ] `query.is_resting`: When is this the case?
- [ ] `query.is_roaring`: Is this related to the `knockback_roar` behavior?
- [ ] `query.is_rolling`: Is this related to the `roll` behavior?
- [ ] `query.is_saddled`: Is this just the `is_saddled` component?
- [ ] `query.is_scared`: Scared of what? Is this related to `query.is_avoiding_block`/`query.is_avoiding_mobs`?
- [ ] `query.is_selected_item`: Selected an item in the hotbar, or on their cursor?
- [ ] `query.is_shaking`: When is this the case? Converting zombie villagers? The `transformation` component? Wolves shaking off water? Striders outside of lava?
- [ ] `query.is_shaking_wetness`: When is this the case? Wolves shaking off water?
- [ ] `query.is_sheared`: Is this just the `is_sheared` component?
- [ ] `query.is_shield_powered`: Is this just for the wither? If so, just say that. Also, why does it say "1.0f" unlike all the other copy-pasted descriptions?
- [ ] `query.is_silent`: When is this the case? Does it work for any custom mob that doesn't have sounds implemented in `sounds.json`? Does it work for inanimate objects like minecarts and armor stands?
- [ ] `query.is_sitting`: When is this the case? Just wolves and cats sitting? Does it work for players sitting in a minecart?
- [ ] `query.is_sleeping`: Does it work for foxes sleeping? Players sleeping in a bed? Villagers?
- [ ] `query.is_sneaking`: Is this just players? Or can other mobs sneak sometimes?
- [ ] `query.is_sneezing`: Is this related to the `sneeze` behavior?
- [ ] `query.is_sprinting`: Is this just players? Or can other mobs like rabbits and ocelots sprint sometimes?
- [ ] `query.is_stackable`: Is this related to the `is_stackable` component?
- [ ] `query.is_stalking`: When is this the case? Ocelots? Creepers?
- [ ] `query.is_standing`: When is this the case? Is it the opposite of `query.is_sitting`/`query.is_sleeping`?
- [ ] `query.is_stunned`: Is this just the `is_stunned` component?
- [ ] `query.is_swimming`: Is this related to `query.can_swim`? What counts as swimming? The player bobbing through water? The new aquatic update swimming? Fish, dolphins, or guardians swimming?
- [ ] `query.is_tamed`: Is this related to the `tameable` component?
- [ ] `query.is_transforming`: Is this related to the `transformation` component?
- [ ] `query.is_using_item`: Using an item how? Placing a block? Eating food? Charging a bow? Throwing a snowball? Swinging a sword? Using a spyglass? Does this only work for players?
- [ ] `query.is_wall_climbing`: When is this the case? Spiders climbing walls? Mobs climbing ladders?
- [ ] `query.item_in_use_duration`: Just like `query.is_using_item`, which items and mobs is this applicable to?
- [ ] `query.item_is_charged`: What kind of item can be "charged"? Just crossbows? What about normal bows, or tridents?
- [ ] `query.item_max_use_duration`: Like above.
- [ ] `query.item_remaining_use_duration`: Like above.
- [ ] `query.item_slot_to_bone_name`: How do you specify the "name of an equipment slot"? How does the game determine how which bone is "mapped" to that slot?
- [ ] `query.key_frame_lerp_time`: "Returns the ratio between the previous and next key frames." What does this mean?
- [ ] `query.last_hit_by_player`: How long does this remember? Does it persist between relogs? Or is this just to implement the "you get experience if you hit the mob less than 5 seconds ago" behavior? Does it count damage from player-tamed wolves? Does it count attacks by bow or other non-hit damage?
- [ ] `query.lie_amount`: What does this mean?
- [ ] `query.life_span`: What determines whether an entity has a limited life span? Does primed TNT count? What about area effect clouds, or vexes?
- [ ] `query.life_time`: What is the difference between this and `query.animation_time`? Seems like a misleading name if the description is correct.
- [ ] `query.log`: This does not print to the screen, only the log file. The documentation should make this clear.
- [ ] `query.main_hand_item_max_duration`: What is the difference between this and `query.item_max_use_duration(0)`?
- [ ] `query.main_hand_item_use_duration`: Like above.
- [ ] `query.mark_variant`: Is this just the `mark_variant` component?
- [ ] `query.max_durability`: "Returns the max durability an item can take." An item can't "take" durability, it takes damage. Which is it?
- [ ] `query.max_health`: Same questions as `query.health`. Also, why is this documented so far away from `query.health`?
- [ ] `query.max_trade_tier`: Is this just for villagers? How does it relate to them?
- [ ] `query.model_scale`: What determines this? Does an animation that scales up the model count? Do the `scale`/`scale_by_age` components count? Does a creeper inflating count? What are the units?
- [ ] `query.modified_distance_moved`: "modified along the way by status flags such as is_baby or on_fire." Modified how?
- [ ] `query.modified_move_speed`: Like above.
- [ ] `query.moon_brightness`: All caps underscored names like `WANING_GIBBOUS` are ugly and hard to read, maybe add some screenshots instead?
- [ ] `query.moon_phase`: Like above.
- [ ] `query.movement_direction`: This returns an axis? Is that a number, or what?
- [ ] `query.noise`: "Queries Perlin Noise Map." Completely useless description.
- [ ] `query.on_fire_time`: Remaining time, or time so far?
- [ ] `query.out_of_control`: When is this the case? Is this related to the `panic` behavior? The `run_around_like_crazy` behavior?
- [ ] `query.overlay_alpha`: Why is it still in the game and (badly) documented if it's deprecated?
- [ ] `query.owner_identifier`: What is the format of the returned value? Does owner mean tamed pet owner, or like projectile owner?
- [ ] `query.player_level`: Experience points level?
- [ ] `query.position_delta`: Delta since when? Last frame?
- [ ] `query.previous_squish_value`: Same questions as `query.current_squish_value`. Also, why is this documented so far away from `query.current_squish_value`?
- [ ] `query.remaining_durability`: "Returns the how much durability an item has remaining." Typo?
- [ ] `query.roll_counter`: What does this mean? Is it related to `query.is_rolling`?
- [ ] `query.shake_angle`: What does this mean? Is it related to `query.is_shaking`?
- [ ] `query.shake_time`: Like above.
- [ ] `query.shield_blocking_bob`: How much it "should" translate down? According to what? What determines this value?
- [ ] `query.sit_amount`: What does this mean? Is it related to `query.is_sitting`?
- [ ] `query.skin_id`: Is this just the `skin_id` component?
- [ ] `query.sleep_rotation`: Does this only work for players, or villagers too?
- [ ] `query.sneeze_counter`: What does this mean? Is it related to `query.is_sneezing`?
- [ ] `query.spellcolor`: What is this? Is it related to evokers? Why is there no underscore? What does the returned value look like?
- [ ] `query.standing_scale`: "Returns the scale of how standing up the entity is." What?
- [ ] `query.structural_integrity`: What does this mean?
- [ ] `query.swell_amount`: What does this mean? Is it related to exploding creepers?
- [ ] `query.swelling_dir`: What does this mean?
- [ ] `query.swim_amount`: What does this mean? What are the units?
- [ ] `query.tail_angle`: Is this just to implement wolves and cats? If so, just say that.
- [ ] `query.texture_frame_index`: "Returns the icon index of the experience orb." What?
- [ ] `query.time_stamp`: What does this mean? Does it just go up one each tick? Does it persist relogs?
- [ ] `query.trade_tier`: Same questions as `query.max_trade_tier`. Also, why is this documented so far away from `query.max_trade_tier`?
- [ ] `query.unhappy_counter`: What determines this?
- [ ] `query.variant`: Is this just the `variant` component?
- [ ] `query.walk_distance`: Is this related to `query.modified_distance_moved`? If so, how? What are the units?
- [ ] `query.wing_flap_position`: What does this mean?
- [ ] `query.wing_flap_speed`: What does this mean?
- [ ] `query.yaw_speed`: What does this mean?

**Comment by SirLich** [comment]
Worth mentioning that we have some of our own docs, covering some of these components (slowly growing, as people painstakingly test + write. 

https://wiki.bedrock.dev/documentation/queries.html#top

As Tryashtar pointed out, one of the big failures of the current documentation is missing relational awareness between components, filters, and queries. We need five things for every query:
 - A short, meaningful description, that is not just a repetition of the name
 - An example
 - A full list of all possible parameters, and what they mean
 - A full list of the returns, and what they mean 
 - The relationship between the query, and existing filters. 
 
 See an example here, where we provide tables for the args: https://wiki.bedrock.dev/documentation/queries.html#top

**Comment by qmagnet** [comment]
This is a fantastic summary of the biggest problem with current documentation. The definitions should be explained in a way that you are not required to be a programmer or experience to understand what they do.

I'd also like to add this nugget, which is just simply incorrect
![image](https://user-images.githubusercontent.com/13902631/133343605-7c33d431-1257-4fe4-b70e-5295af06936e.png)

**Comment by iconicNurdle** [comment]
Your list was used to fix, update, and expand the Molang Query page. Changes should be visible after the next release. Thanks!

**Comment by tryashtar** [comment]
Thanks. Looks better now
