### ISSUE TITLE
Documentation: Empty loot table item example is missing.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#120]
Missing empty loot table item example the page only currently has a description of how to do it but does not show the user how it's used.

I found a working example in the vanilla loot tables at this path.
**"loot_tables\chests\abandoned_mineshaft.json"**

```json
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "item",
          "name": "minecraft:iron_pickaxe",
          "weight": 5
        },
        {
          "type": "empty",
          "weight": 5
        }
      ]
    }
  ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd485b26-f072-c98a-9e59-e5b12a3ce3ea
* Version Independent ID: 36631caa-b8f2-e4c4-78a1-82618cf95901
* Content: [Introduction to Loot Tables](https://docs.microsoft.com/en-us/minecraft/creator/documents/introductiontoloottables)
* Content Source: [creator/Documents/IntroductionToLootTables.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/IntroductionToLootTables.md)
* Product: **gaming**
* GitHub Login: @neonerz
[abandoned_mineshaft.json.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/7025769/abandoned_mineshaft.json.zip)

* Microsoft Alias: **v-jeffreykim**

**Comment by JimSeaman42** [comment]
Thank you for your feedback. It seems like this issue is no longer applicable, and I'm going to close it. If this is in error, please don't hesitate to reach out.
