### ISSUE TITLE
Documentation: Missing parameters of minecraft:behavior.move_to_random_block

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#122]
Missing Parameters "speed_multiplier", "priority", possibly others missing that are undocumented?
"minecraft:behavior.move_to_random_block"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8674eff-42b7-3710-e2da-f537e405d943
* Version Independent ID: 2c26198b-4f09-ad2c-2bae-a6a6995f7b4e
* Content: [minecraft:behavior.move_to_random_block](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_to_random_block)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_move_to_random_block.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_move_to_random_block.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
These have been added. Thanks! 

[Docs here](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_to_random_block)
