### ISSUE TITLE
Documentation: Missing parameters for minecraft:behavior.explore_outskirts

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#123]
Documentation missing parameters for **minecraft:behavior.explore_outskirts**

Here's a list of missing ones, I noticed there may be others as well possibly?
1.     "priority"
2.     "next_xz"
3.     "next_y"
4.     "min_wait_time"
5.     "max_wait_time"
6.     "max_travel_time"
7.     "min_perimeter"
8.     "min_dist_from_target"
9.     "timer_ratio"
10.     "dist_from_boundary"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e384ecb-0fa0-3fb0-2b76-858b28d31796
* Version Independent ID: 22ee0178-36c7-cf5d-6063-41d0eb794062
* Content: [minecraft:behavior.explore_outskirts](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_explore_outskirts)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_explore_outskirts.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_explore_outskirts.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
Many of these are updated now, but I will be following up on priority.

[Current page](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_explore_outskirts)

**Comment by docsbryce** [comment]
These are all live now. Thanks for reporting!

[Docs here.](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_explore_outskirts)
