### ISSUE TITLE
Documentation: "minecraft:can_fly" weird formatting in ghast example.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#126]
This example is messed up and should be changed to not include **"minecraft:loot": {** in the formatting.
```

"minecraft:can_fly": {
},
"minecraft:loot": {

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50700775-cbfd-e19c-5bf2-89163f17d834
* Version Independent ID: 30e1703b-94aa-e6f1-f206-afdea1ae398e
* Content: [minecraft:can_fly](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_can_fly)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_can_fly.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_can_fly.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Adjusting sample to move up a line to reflect the change.
