### ISSUE TITLE
query.log usage example mssing

### ISSUE THREAD

**Issue by tinedpakgamer** [MicrosoftDocs/minecraft-creator#127]
query.log is a query that logs a value to  the logger, but wheres that log
 debug log ( if debugger is attached)
 content log(if logging is active)
how to pass parameter to this query is also missing
how and where to use it is also missing

**Comment by SirLich** [comment]
This query is actually broken for non-developer-clients :/ 

Would be great if that could be fixed.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!

**Comment by tinedpakgamer** [comment]
It needs to be reopened because there was no fix provided. There is no syntax usage details. It has not been fixed as well
