### ISSUE TITLE
Signature.json documentation  missing

### ISSUE THREAD

**Issue by tinedpakgamer** [MicrosoftDocs/minecraft-creator#128]
This file is used to validate if a pack is edited or not,  this should be documented so that  content creators can safely eliminate cheating in gameplay via addons, like they can make anti x-ray ,   disable player x-ray,  disabling kill aura etc.

**Comment by v-josjones** [comment]
Adding this to our investigation work. We are investigating this task to see how we can properly handle documenting this JSON file.

**Comment by iconicNurdle** [comment]
Hi @tinedpakgamer - after some investigation, it seems like this is used mainly on the Minecraft Education edition side and it is not used as widely by Bedrock creators. I love learning new things, so if there is a process you use with signature.json, I would like to learn more about it. I'm going to close this issue for now. Thank you!
