### ISSUE TITLE
Missing experimental flag explanation

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#129]
**Describe the missing content**
Experimental flags are only recently documented in a not so obvious article on minecraft.net, it would be good to get this in the creator docs as a living document - ref - https://feedback.minecraft.net/hc/en-us/articles/4403610710797#h_01F9ES4SKJXY6AVK9FMFVCXMBQ

**Additional context**
I see people questioning what each toggle does pretty often, I really think it's worth having this doc in the creator docs rather than a random minecraft.net article

**Comment by v-josjones** [comment]
Adding this. Will look at bringing a variation of this material to the documentation site.

**Comment by GTB3NW** [comment]
Thanks Joshua!
