### ISSUE TITLE
Block Addons, Missing block states

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#130]
The following block states are missing:

- [x] allow_underwater_bit
- [x] attached_bit
- [x] attachment
- [x] bamboo_leaf_size
- [x] bamboo_stalk_thickness
- [x] big_dripleaf_head
- [x] big_dripleaf_tilt
- [x] bite_counter
- [ ] block_light_level
- [x] brewing_stand_slot_a_bit
- [x] brewing_stand_slot_b_bit
- [x] brewing_stand_slot_c_bit
- [x] button_pressed_bit
- [x] cauldron_liquid
- [x] chemistry_table_type
- [x] chisel_type
- [x] cluster_count
- [x] color
- [x] color_bit
- [ ] composter_fill_level
- [x] conditional_bit
- [x] coral_color
- [x] coral_direction
- [ ] coral_fan_direction
- [x] coral_hang_type_bit
- [x] covered_bit
- [x] cracked_state
- [x] damage
- [x] dead_bit
- [ ] deprecated
- [x] direction
- [x] dirt_type
- [x] disarmed_bit
- [x] door_hinge_bit
- [x] double_plant_type
- [x] drag_down
- [x] dripstone_thickness
- [x] end_portal_eye_bit
- [x] explode_bit
- [ ] extinguished
- [x] facing_direction
- [x] fill_level
- [x] flower_type
- [x] ground_sign_direction
- [ ] growing_plant_age
- [x] growth
- [x] hanging
- [x] head_piece_bit
- [x] height
- [ ] honey_level
- [x] huge_mushroom_bits
- [x] in_wall_bit
- [x] infiniburn_bit
- [x] item_frame_map_bit
- [ ] kelp_age
- [ ] lever_direction
- [x] liquid_depth
- [x] moisturized_amount
- [x] monster_egg_stone_type
- [ ] multi_face_direction_bits
- [x] new_leaf_type
- [x] new_log_type
- [x] no_drop_bit
- [x] occupied_bit
- [x] old_leaf_type
- [x] old_log_type
- [x] open_bit
- [x] output_lit_bit
- [x] output_subtract_bit
- [x] persistent_bit
- [ ] pillar_axis
- [x] powered_bit
- [ ] prismarine_block_type
- [x] rail_data_bit
- [x] rail_direction
- [x] redstone_signal
- [x] repeater_delay
- [ ] respawn_anchor_charge
- [ ] rotation
- [x] sand_stone_type
- [x] sand_type
- [x] sapling_type
- [x] sea_grass_type
- [x] sponge_type
- [x] stability
- [x] stability_check
- [x] stone_brick_type
- [x] stone_slab_type
- [x] stone_slab_type_2
- [x] stone_slab_type_3
- [x] stone_slab_type_4
- [x] stone_type
- [x] stripped_bit
- [x] structure_block_type
- [x] structure_void_type
- [x] suspended_bit
- [x] tall_grass_type
- [x] toggle_bit
- [x] top_slot_bit
- [x] torch_facing_direction
- [x] triggered_bit
- [x] turtle_egg_count
- [ ] twisting_vines_age
- [x] update_bit
- [x] upper_block_bit
- [x] upside_down_bit
- [x] vine_direction_bits
- [x] wall_block_type
- [x] wall_connection_type_east
- [x] wall_connection_type_north
- [x] wall_connection_type_south
- [x] wall_connection_type_west
- [x] wall_post_bit
- [ ] weeping_vines_age
- [x] weirdo_direction
- [x] wood_type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6978987c-6bc0-72ea-8bec-c068c6c12ee2
* Version Independent ID: f9b69e60-5ce9-499a-e582-fb6a077e469b
* Content: [Addons Documentation - Blocks](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonblocks)
* Content Source: [creator/Reference/Content/AddonsReference/Examples/AddonBlocks.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AddonsReference/Examples/AddonBlocks.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Looks like we've got 100 of these. 16 to go!

- [ ] block_light_level
- [ ] composter_fill_level
- [ ] coral_fan_direction
- [ ] deprecated
- [ ] extinguished
- [ ] growing_plant_age
- [ ] honey_level
- [ ] kelp_age
- [ ] lever_direction
- [ ] multi_face_direction_bits
- [ ] pillar_axis
- [ ] prismarine_block_type
- [ ] respawn_anchor_charge
- [ ] rotation
- [ ] twisting_vines_age
- [ ] weeping_vines_age

**Comment by DaanV2** [comment]
> Looks like we've got 100 of these. 16 to go!

Very nice! 😄

**Comment by JDHeaden** [comment]
- [ ]  block_light_level
- [ ]  composter_fill_level
- [ ]  coral_fan_direction
- [ ]  deprecated
- [ ]  extinguished
- [ ]  growing_plant_age
- [ ]  honey_level
- [ ]  kelp_age
- [ ]  lever_direction
- [ ]  multi_face_direction_bits
- [ ]  pillar_axis
- [ ]  prismarine_block_type
- [ ]  respawn_anchor_charge
- [ ]  rotation
- [ ]  twisting_vines_age
- [ ]  weeping_vines_age

**Comment by JDHeaden** [comment]
I could not find a block with "rotation" as a block state. I see that "rotation" is a block component, and it is covered here: https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_rotation

**Comment by JDHeaden** [comment]
Added 'rotation' - it is used with jigsaw blocks.
