### ISSUE TITLE
Missing loot table conditions and functions

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#131]
Loot Table and trade table pages are missing few functions and conditions.

**_Missing loot table conditions:_**
- `entity_properties`
- `has_mark_variant`
- `killed_by_player_or_pets`
- `random_chance`
- `random_chance_with_looting`
- `random_difficulty_chance`
- `random_regional_difficulty_chance`
- `match_tool`

**_Missing loot table functions:_**

- `random_dye`
- `trader_material_type`

All of those mentioned above _except for `match_tool`_ are documented here: [Minecraft Wiki - Loot table functions](https://minecraft.fandom.com/wiki/Bedrock_Edition_function/loot_tables/trade_tables_documentation#trader_material_type)
and should be mentioned in the loot table category of _Adding Content_ page as they all are even used within the vanilla game. `match_tool` has been tested as a working condition by the players.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd485b26-f072-c98a-9e59-e5b12a3ce3ea
* Version Independent ID: 36631caa-b8f2-e4c4-78a1-82618cf95901
* Content: [Introduction to Loot Tables](https://docs.microsoft.com/en-us/minecraft/creator/documents/introductiontoloottables)
* Content Source: [creator/Documents/IntroductionToLootTables.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/IntroductionToLootTables.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JDHeaden** [comment]
`match_tool` is being added.
