### ISSUE TITLE
Invalid Json Schemas

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#134]
The provided JSON schemas are in an intermediate format made by Minecraft itself but cannot be used to validate files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f749b4-6cc9-eb10-5e7e-99f9e7b74409
* Version Independent ID: 9837d16d-c61d-6b63-50d4-54f93d6bf5d3
* Content: [Schemas List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/schemasreference/schemaslist#feedback)
* Content Source: [creator/Reference/Content/SchemasReference/SchemasList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/SchemasReference/SchemasList.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by v-josjones** [comment]
Adding this issue as a part of our investigation. We are currently talking about how to proceed with JSON Schema on the documentation portal.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!

**Comment by ChristopherHaws** [comment]
@ghost What kind of progress? I am still unable to find any official JSON schemas.
