### ISSUE TITLE
Entity Animation Format Examples - Invalid Json

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#135]
The Entity Animation Format Examples is written in an intermediate format. and not json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc77c1d3-1268-fad1-9545-d51836b64c91
* Version Independent ID: 4f2f3124-1b7d-5c30-bd27-f82f73873e7c
* Content: [Animation Documentation - Animation Controllers](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/animationsreference/examples/animationcontroller)
* Content Source: [creator/Reference/Content/AnimationsReference/Examples/AnimationController.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AnimationsReference/Examples/AnimationController.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Will rewire the example, both in documentation and look at adding the new example to the autogen documentation tool as well to keep it in sync.

**Comment by docsbryce** [comment]
Hi, @DaanV2, I've rewritten this documentation to include a table of parameters and checked it with the team. This should go out with the July release. I'll update when it's live.

**Comment by docsbryce** [comment]
This change is now [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/animationsreference/examples/animationcontroller). Thanks for bringing this up! It was a doozy of a page.
