### ISSUE TITLE
Render Controllers - More comments and explanation

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#138]
This page could use more comments in the examples or explanations outside of the examples

Made a PR with examples: https://github.com/MicrosoftDocs/minecraft-creator/pull/137

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc18d47a-e328-c81a-b3e6-3f8400b0d060
* Version Independent ID: 9587d402-df15-2a0e-a690-cb0bb6ebe3f1
* Content: [Animation Documentation - Render Controllers](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/animationsreference/examples/animationrendercontroller#feedback)
* Content Source: [creator/Reference/Content/AnimationsReference/Examples/AnimationRenderController.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AnimationsReference/Examples/AnimationRenderController.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Merged the PR into our main branch. Will close issue once hotfix is released.
