### ISSUE TITLE
GameTest - Re-use of some API's for Minecraft module

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#143]
**Is your feature request related to a problem? Please describe.**
The `mojang-gametest` module currently contains lots of functions which users who aren't testing would like to make use of.

**Describe the solution you'd like**
Some of the functions are scoped to tests (such as `killAllEntities`), making those generic (and/or taking appropriate filters) and being made available in `mojang-minecraft` instead would mean people have to create less of their own helpers. Generally I'd say this list of helpers (but only because it's easy to copy and paste lol)

- killAllEntities
- pressButton
- print
- pullLever
- pulseRedstone
- relativeBlockLocation
- relativeLocation
- rotateDirection
- setFluidContainer
- setTntFuse
- spawn
- spawnAtLocation
- spawnItem
- spawnWithoutBehaviors
- spawnWithoutBehaviorsAtLocation
- spreadFromFaceTowardDirection

Most of these are achievable with commands or manipulating blocks, but I do feel like if `mojang-minecraft` is to be a friendly API it should have helpers like these.

**Describe alternatives you've considered**
Alternatives would be either a helper module for convenience functions like these so the main `mojang-minecraft` is sans convenience code, or provide some helpers in optional typescript bindings for convenience.

**Additional context**

A user is the gametest discord was asking if these were usable "normally", eg. without unit testing and more like a plugin.

**Comment by mammerla** [comment]
We still look to get all of these methods to have mojang-minecraft "more full API" equivalents where possible. In some cases, this may still be a while in coming (e.g., spawnWithoutBehaviors implies a more full set of AI APIs which will take some time.)  In the meanwhile, and probably permanently, we'll have a few of these very targeted helpers in mojang-gametest.

**Comment by GTB3NW** [comment]
> We still look to get all of these methods to have mojang-minecraft "more full API" equivalents where possible. In some cases, this may still be a while in coming (e.g., spawnWithoutBehaviors implies a more full set of AI APIs which will take some time.) In the meanwhile, and probably permanently, we'll have a few of these very targeted helpers in mojang-gametest.

Understandable, cheers Mike!
