### ISSUE TITLE
[GameTest] MoLang execution within GameTest API

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#144]
**Is your feature request related to a problem? Please describe.**
Working with GameTest API is missing MoLang, which I find many times blocking me from continuing to work using GameTest and rather considering using other parts of MCBE addon system. For example, I needed to detect if player is exposed to sky within GameTest, which would be simple using MoLang's `query.above_top_solid(x,z)`, however there isn't such thing in GameTest so I needed to use alternatives.

**Describe the solution you'd like**
There should be some way of running any MoLang code/expression in GameTest API. Maybe as class with method taking expression and actor context, similarly to `Commands.run`, or a method for each actor(Entity or Block) to run MoLang expression on it.

**Describe alternatives you've considered**
I've considered using animation controllers from `player.json` entity file, however that is bad practice and isn't directly interactive with GameTest API.

**Additional context**
This feature could potentially be useful for debugging/testing MoLang within GameTest tests as well as to create more advanced creations in non-testing GameTest API environment.

**Comment by mammerla** [comment]
We have this on our list to consider. At the moment, our higher priority is to ensure that many of the execution scenarios (e.g., variable persistence) and test utility methods (e.g., like above_top_solid) are more directly represented with straight APIs where we can help it, though of course we know there is a long road ahead.
