### ISSUE TITLE
No Server Entity JSON documentation

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#145]
**Describe the missing content**
I'd love to have something like [Client Entity JSON](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/cliententitydocumenation/cliententitydocumentationintroduction) page, but for Behavior pack. Currently going to [Entity Documentation Homepage](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/) in `Behavior Pack/Entity JSON  links to Client Entity JSON as JSON Entity Introduction and I feel like it should be split into two documents about entities in different packs.

**Vanilla usage example**
Every behavior pack entity.

**Comment by v-josjones** [comment]
Investigating how we can address this.
