### ISSUE TITLE
minecraft:damage_sensor is missing list of "cause" types

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#148]
The **minecraft:damage_sensor** is missing a list of documented "cause" types and it only specifies the default value is none.

However, a list of known types by the community that should probably be tested and documented include as provided.
`
<html>
<body>

all |  
-- | --
anvil |  
block_explosion |  
charging |  
contact |  
drowning |  
entity_attack |  
entity_explosion |  
fall |  
falling_block |  
fire |  
fire_tick |  
fireworks |  
fly_into_wall |  
freezing |  
lava |  
lightning |  
magic |  
magma |  
none |  
override |  
piston |  
projectile |  
stalactite |  
stalagmite |  
starve |  
suffocation |  
suicide |  
temperature |  
thorns |  
void |    
wither

</body>
</html>`

There may be others that are undocumented that should probably be looked into?

```jsonc
"minecraft:damage_sensor": {
  "triggers": {
    "cause": "fall",
    "deals_damage": true,
    "damage_modifier": -20
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9508d013-e181-fe37-cd9f-c1ee229b1575
* Version Independent ID: a8a78e2a-3fb7-6a67-2e44-76e6346d0c38
* Content: [Entity Documentation - minecraft:damage_sensor](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_damage_sensor)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_damage_sensor.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_damage_sensor.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by SirLich** [comment]
Relates to #98...?

**Comment by StealthyExpertX** [comment]
Yeah, I guess though since they said it was addressed and it wasn't in the documentation, I figured it may have to be reopened.

**Comment by v-josjones** [comment]
Information for damage sensor is located in the Addon Reference documentation located here: [Addons Documentation - Entity List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonentities?branch=main#entity-damage-source)

Will add the information to damage sensor, and other damage related docs that call for a damage type.

**Comment by tryashtar** [comment]
That table is not very helpful since it is not clear what kinds of damage have those causes.
Like, when would a damage sensor with cause `none` trigger? What about `override`? Or `suicide`? Is `temperature` death by powder snow freezing, or snowman melting in warm biomes? Or neither?
