### ISSUE TITLE
Missing properties: projectile_on_hit, particle_type

### ISSUE THREAD

**Issue by qmagnet** [MicrosoftDocs/minecraft-creator#149]
**Describe the missing content**
The `particle_type` property is assumed to be hardcoded. I can't locate documentation on what strings are valid in the property.

**Vanilla usage example**
`minecraft:egg` entity uses the following code:
```
"particle_on_hit": {
    "particle_type": "iconcrack",
    "num_particles": 6,
    "on_entity_hit": true,
    "on_other_hit": true
}
```
I would love a list of all other available particle types other than `iconcrack`

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
