### ISSUE TITLE
There should be getDimension() in Entity Class

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#151]
It's tricky to know which dimension an entity is in.

**Describe the solution you'd like**
Add getDimension() into Entity Class!

**Describe alternatives you've considered**
> Commands.run(\`testfor @e[name="${random string}",rm=0]\`, overworld)

**Comment by PavelDobCZ23** [comment]
I agree a lot, this would be a nice addition, maybe a property would be a better option tho, considering they are remaking lot of property-like methods to properties, so like `<Entity>.dimension` would be a better solution, but I like the idea nonetheless.
