### ISSUE TITLE
Documentation mismatch: minecraft:behavior.knockback_roar

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#156]
There is a documentation mismatch between the generated documentation and the documentation on the website

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce07b46-0e9e-77e6-0a32-f4e8d91d128e
* Version Independent ID: a70773dc-ea91-ec28-fe90-d200356bbcd7
* Content: [Entity Documentation - minecraft:behavior.knockback_roar](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_knockback_roar)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_knockback_roar.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_knockback_roar.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Addressing in next hotfix
