### ISSUE TITLE
Missing documentation: minecraft:behavior.pickup_items -> excluded_items

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#157]
minecraft:behavior.pickup_items in 1.17.30 (see drowned.json in the BP) has the property excluded_items but is not documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1a9c7b-f04c-4460-9586-7281e824ec40
* Version Independent ID: 313ad175-5cd9-8202-fc3b-a2815f335bd6
* Content: [Entity Documentation - minecraft:behavior.pickup_items](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_pickup_items)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_pickup_items.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_pickup_items.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Addressing in the next hotfix.
