### ISSUE TITLE
Spawn_rules: Missing conditions

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#158]
The following conditions are missing from the documentation, which can be found in the 1.17.30 axolotl spawn_rules
- [ ] minecraft:disallow_spawns_in_bubble
- [ ] minecraft:spawns_above_block_filte

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbb56c6-1b3f-effd-e17d-4293cd4ecb28
* Version Independent ID: 212d4b6c-84d1-8786-3647-1a0a32212918
* Content: [Entity Documentation -  Spawn Rules and Data-Driven Spawning](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/cliententitydocumenation/datadrivenspawning)
* Content Source: [creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/DataDrivenSpawning.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/DataDrivenSpawning.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Addressing in next hotfix.

**Comment by PavelDobCZ23** [comment]
There are many more missing conditions tho, I've listed them all in my issue [#141](https://github.com/MicrosoftDocs/minecraft-creator/issues/141).

**Comment by JimSeaman42** [comment]
It appears the document has been revised from this point; I'm going to close the issue. If there are any continuing issues with spawn rule documentation, please don't hesitate to let us know. Thanks!

**Comment by DaanV2** [comment]
Thanks for all the work so far :D

Will keep an eye out
