### ISSUE TITLE
Missing Block Components

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#160]
The following block properties are missing from documentation:

- [x] minecraft:creative_category
- [ ] minecraft:part_visibility

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2d3b8d-1c13-9c44-e452-d358e9a275cd
* Version Independent ID: dacf9f8f-0632-e8dd-092f-80b0c378ba9e
* Content: [Block Documentation - Block Components List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponentslist)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponentsList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponentsList.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by PavelDobCZ23** [comment]
There's also missing `minecraft:crafting_table` component.

**Comment by v-josjones** [comment]
- minecraft:creative_category has been added.
- minecraft:part_visibility has been added but needs further work including a breakdown of the JSON object and an example.
- Will need to investigate minecraft:crafting_table.

**Comment by JimSeaman42** [comment]
Thanks for the feedback! All of the items noted have either been deprecated or added to the documentation as applicable.
