### ISSUE TITLE
Minecraft:scaffolding deprecation?

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#161]
It seems through the automated documentation `scaffolding` has been deprecated for: `Minecraft:block_climber`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb9790f-cb56-ada9-41f8-1c7a55b5e1d7
* Version Independent ID: 993c4e6d-3e09-b610-b43d-52096408e9d7
* Content: [Entity Documentation - minecraft:scaffolding_climber](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_scaffolding_climber)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_scaffolding_climber.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_scaffolding_climber.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by v-josjones** [comment]
Addressed. Will be added in next release.
