### ISSUE TITLE
How to use "console"?

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#164]
`console.log()
console.warn()
console.debug()
console.error()
console.info()`
Where will the output be?
BDS stdout? BDS log file? Content Log?
(I'm using `console.warn` to print text on Content Log)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54e64e75-0ce4-9d26-da13-072bf3d2d46d
* Version Independent ID: 3f471315-e86e-49b0-cf33-2ad21f7bab29
* Content: [Building your first GameTest](https://docs.microsoft.com/en-us/minecraft/creator/documents/gametestbuildyourfirstgametest)
* Content Source: [creator/Documents/GameTestBuildYourFirstGameTest.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/GameTestBuildYourFirstGameTest.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by CreepycreeperMw** [comment]
console.warn? Doesnt work for me ;-;

**Comment by kakinnun** [comment]
I was able to use console.warn() in the latest beta and it outputs to the in-game console visible via the Creator - Content Log in the General game Settings. Does this resolve your issue?

**Comment by Worldwidebrine** [comment]
I want to know is `console.warn`'s behavior settled officially? The documentations didn't mention this behavior, so I just want to know is it likely that this behavior could be removed in any future version.

**Comment by CreepycreeperMw** [comment]
Please note this was 2 months ago its fine by now but thanks for the help

**Comment by kakinnun** [comment]
> I want to know is `console.warn`'s behavior settled officially? The documentations didn't mention this behavior, so I just want to know if this behavior would be removed in any future version.

We haven't officially settled on a final behavior for "console" as of yet so it may change, but it's also handy for folks today so I don't see it going away. Today, console.warn() will output to the Creator Console Log, and both console.warn() and console.log() will output into a VSCode debug console.

I'll keep this issue open though as a reminder for us to document console usage when we have a final position on its use.

> Please note this was 2 months ago its fine by now but thanks for the help

I know, sorry for the late reply. Cleaning up older issues on here.

**Comment by kakinnun** [comment]
Late breaking info. Chatted with the developers on this. Current implementation should be pretty solid and we don't foresee changes unless there's feedback to the contrary. So I'll close this issue for now. If you have any issues, let us know. I'll look at potentially adding a section to our "how to debug" sections on console usage, though I suspect we'll use implementations of it throughout the site in example code as a way to teach it.

Sorry for all the back and forth. Thanks for the original issue and triggering a good conversation!
