### ISSUE TITLE
Debugger and /script command issues.

### ISSUE THREAD

**Issue by CreepycreeperMw** [MicrosoftDocs/minecraft-creator#165]
**Missing Content and Issue**
I tried to debug the code today because I need to and need to listen and get variables and in the docs it says enter /script command but there simply is no /script command when I do the exact thing that is being showed in the docs. I checked everything and nothing was wrong... When I entered the Cmd Command ("CheckNetIsolation.exe LoopbackExempt –a –p=S-1-15-2-1958404141-86561845-1752920682-3514627264-368642714-62675701-733520436")
 it said Ok too and I believe this is an issue.

Just to fill in this field its used by players to connect visual studio code and minecraft to the debugger

**Additional context**
Referring to this: https://docs.microsoft.com/en-us/minecraft/creator/documents/scriptdevelopertools#step-5-run-your-minecraft-behavior-pack

**Comment by mammerla** [comment]
Sorry - you may need to use either beta or the recently released main update.  Also, the GameTest Framework experiment would need to be on.

**Comment by CreepycreeperMw** [comment]
> Sorry - you may need to use either beta or the recently released main update. Also, the GameTest Framework experiment would need to be on.

I cant confirm that. I already got it working now and I changed the launch.json file. I just put ../../ in the place of ${workPlace}/ where you are told to not change that.

**Comment by kakinnun** [comment]
Closing this issue as I believe the initial issue was resolved.
