### ISSUE TITLE
Tutorials > Adding NPCs

### ISSUE THREAD

**Issue by Etanarvazac** [MicrosoftDocs/minecraft-creator#167]
**Create a Custom NPC:**
- Dialog box commands are missing the new "On Enter" and "On Exit" toggles introduces in the recent updates.
- Missing dialogue call tagging ability.
- **On Enter:** Commands to trigger upon a player interaction with the NPC.
- **On Exit:** Commands to trigger when a player ends their interaction with the specific NPC dialog.

**NPC Dialogue Command:**
- Linking an NPC in-game with it's respective JSON file is not made clear. Should note to use the _On Enter_ calling on the NPC dialogue. For example: _/dialogue open @e[tag=MyNPC] @p npc_greeting_
- It should also be noted that an NPC could be called by using the Radius & Type selector instead of by a tag. This method is seems to work better in the case there is an issue with tagged NPC's. Example: _/dialogue open @e[type=NPC,r=2] @p npc_greeting_
- Lastly, in terms of new content creators, it should be noted how multiple buttons are added to a single scene via the JSON file.

**Comment by docsbryce** [comment]
Thanks for this detailed request. These updates are live!

[Create NPC](https://docs.microsoft.com/en-us/minecraft/creator/documents/createnpcs)
[NPC Dialogue](https://docs.microsoft.com/en-us/minecraft/creator/documents/npcdialogue)
