### ISSUE TITLE
Missing "on_hit" property of "minecraft:projectile" component for entity.

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#168]
There is a very important property of `minecraft:projectile` entity component called `on_hit` which is missing. It covers big part of projectiles' functionality and many vanilla projectiles already use it like `minecraft:arrow`, `minecraft:ender_pearl` and more. It isn't explained nor mentioned, only shown within provided vanilla example.  

[This fan-made article](https://wiki.bedrock.dev/documentation/projectiles.html#on-hit) was made to help creators as an alternative for documentation of it.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b64aa40-f231-4fa4-9641-df94f37d5ea2
* Version Independent ID: d10f887a-4b9b-5725-937b-99e1a4024891
* Content: [Entity Documentation - minecraft:projectile](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_projectile)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by DaanV2** [comment]
@v-josjones This one is resolved :)

**Comment by PavelDobCZ23** [comment]
Finally resolved, thx a lot ppl :D
