### ISSUE TITLE
Document textures/{terrain,item}_texture.json

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#17]
The following files:

- `textures/terrain_texture.json`
- `textures/item_texture.json`

are not documented well. The following fields look to be optimisations but since they're not explained, content creators (and marketplace partners) have been unable to take advantage of this.

- `num_mip_levels` (Mipmap stuff? Sacrifice gpu mem for render performance?)
- `texture_name` (Creates a new texture for gpu? How would this benefit people?)
- `resource_pack_name` (Association? Is it used to merge textures?)

**Comment by docsbryce** [comment]
Hi, @GTB3NW,

I did some research and talked to the team and it appears this way of making custom terrain and item terrain using textures are no longer used. Check out this Resource Pack tutorial for customizing those textures. 

https://docs.microsoft.com/minecraft/creator/documents/resourcepack
