### ISSUE TITLE
Chunker.app unable to convert 1.17.30 save file or render preview the save.

### ISSUE THREAD

**Issue by troilus** [MicrosoftDocs/minecraft-creator#172]
![image](https://user-images.githubusercontent.com/1055100/135991918-f9f298c4-e142-432f-8e84-58731cc5f696.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://docs.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by clankstar** [comment]
Thank you for reporting this. We believe this issue to be resolved in Chunker CLI 1.12.6, which is now live. If you do continue to have issues please follow-up on this report and we will look into it.

**Comment by troilus** [comment]
@v-josjones @clankstar Works fine on Chunker.app now, thanks!
