### ISSUE TITLE
Minecraft texturepack making tutorial missing things.

### ISSUE THREAD

**Issue by Arasander** [MicrosoftDocs/minecraft-creator#187]
[At the end of the tutorial, it shows how to activate /open the pack with bedrock edition. How do I do it with Java edition?]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://docs.microsoft.com/en-gb/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Hi there! This site only focuses on Bedrock currently. We are thinking through how we can provide similar documentation for Java in the future though.
