### ISSUE TITLE
generated_with - pack manifest metadata field

### ISSUE THREAD

**Issue by kakinnun** [MicrosoftDocs/minecraft-creator#189]
**Describe the missing content**
The "**generated_with**" field in the pack manifest metadata is not documented. This data is useful for tool makers to include as it allows content made with their tool to be accurately tracked by Mojang.

     ...
    "metadata": {
        "authors": ["MyName"],
        "license": "MIT",
        "generated_with": {
            "some_tool" : ["1.0.0", "1.1.0"],
            "some_other_tool" : ["0.0.1"]
        }
    }

We should add an explanation of this field at this page: [addonmanifest](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest)

**Additional context**
- The tool name must be [a-zA-Z0-9_-], 32 characters max
- After the tool name comes a list of versions of the tool that have modified the pack. Versions should be semver strings.

**Comment by docsbryce** [comment]
This is live! https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest
