### ISSUE TITLE
minecraft:projectile missing documentation

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#190]
This issues is made based upon 1.17.40 that seems to introduce more components to the projectile component

The projectile property is missing the following documentation:

- [x] hit_ground_sound
- [x] on_hit
  - [x] stick_in_ground
    - [x] shake_time
  - [x] thrown_potion_effect
- [x] stop_on_hurt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b64aa40-f231-4fa4-9641-df94f37d5ea2
* Version Independent ID: d10f887a-4b9b-5725-937b-99e1a4024891
* Content: [Entity Documentation - minecraft:projectile](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_projectile)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
I added this to a larger improvement we're making around the Reference documentation.  Thank you for reporting these! I'll update when these changes go through.

**Comment by docsbryce** [comment]
This change is now [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_projectile). Thanks!
