### ISSUE TITLE
Biome Tag list is either incomplete or wrong.

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#193]
I'm not too knowledgeable about this topic, but your information on this page differs nearly 100% from the information we maintain on the wiki.

From speaking with members of our community, it seems out information is more up to date. 

**Your page:** https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/definitions/biome_filter

**Our page:** https://wiki.bedrock.dev/world-generation/biome-tags.html#biome-per-biome-tag

Specific example of missing biome tag, found on our page: `soulsand_valley`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7fd0631-6230-0151-a8d1-6a9699ca3cb9
* Version Independent ID: 0cb164e8-ad57-f1f1-a70d-19b1eb72f4bb
* Content: [Entity Documentation - minecraft:biome_filter](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/definitions/biome_filter)
* Content Source: [creator/Reference/Content/EntityReference/Examples/Definitions/biome_filter.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/Definitions/biome_filter.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JimSeaman42** [comment]
Thank you for your feedback; I apologize for the delayed response. Our documentation has been updated. Thanks again!
