### ISSUE TITLE
I cannot upload bedrock worlds from 1.17.40.6

### ISSUE THREAD

**Issue by burtvadr** [MicrosoftDocs/minecraft-creator#194]
[I cannot upload bedrock worlds from 1.17.40.6
![image](https://user-images.githubusercontent.com/67408916/139353833-b3a0a564-a478-4cc0-8e55-70022df5840f.png)
 https://drive.google.com/file/d/1gCThfltkW-flccpkF3E6lzqfPMNEmLD2/view  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://docs.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by clankstar** [comment]
Thanks for reporting this issue. Currently, Chunker.app has a file size limit which is exceeded by the file you're attempting to use. 

We plan to significantly raise this limit by the end of November, which should resolve this issue for you. We will also improve the error messaging where possible to prevent this confusion.
