### ISSUE TITLE
[Information Request] Dialogue.json structure

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#197]
The article about NPC dialogue doesn't go in depth or reference any documentation about the structure of dialogue json format

https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/NPCDialogue.md

Would it be possible that the information regarding the json format of dialogues to be released?
This would include what is an object, integer, string, or required, optional. Patterns that needs to be followed and so forth.

**Comment by v-josjones** [comment]
For clarification, this is requesting to go into further details than what is covered in the NPC scene struct. Is that correct?

**Comment by DaanV2** [comment]
Yes. It's about everything that goes into the dialogue files

**Comment by docsbryce** [comment]
@DaanV2 Hi, Dan, based on this feedback I've done a light edit of this page. I did check with the team and it looks like all the relevant scene properties were listed. I'm reformatting that into a table with more information about the type of each parameter.

Was there more information you wanted to be included?

**Comment by DaanV2** [comment]
I was looking for something similar to [minecraftcomponent_breedable](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_breedable)

whereby there is an in-depth structure depiction of the dialogue.json file.

**Comment by docsbryce** [comment]
That's a great reference! I have created a table with the scene properties towards the top so we're on the same page. And I'm glad your issue gave me a reason to refresh the NPC Dialogue page too.

These changes should land for the next release.

**Comment by docsbryce** [comment]
[I updated these docs to convert the existing info to a table](https://docs.microsoft.com/en-us/minecraft/creator/documents/npcdialogue#scene-properties) and ran this info by a subject matter expert. Thanks for submitting!
