### ISSUE TITLE
I want to make an animation of a mob attack in minecraft

### ISSUE THREAD

**Issue by Kybomaster** [MicrosoftDocs/minecraft-creator#198]
Hello everyone, I'm creating a mob in minecraft bedrock and I want to add 3 attack animations to it. So that with each attack of the mob, one of the three with equal chances is lost. *Thanks*

**Comment by kakinnun** [comment]
Hi there! Answering this is definitely outside the scope of our humble doc GitHub issues repository! But we'll add this to our list of potential future topics to write an article about. 

In the meantime...
Places I can suggest continuing to learn about animations if you aren't finding all the answers here...

**Blockbench documentation:** Blockbench is certainly the tool I'd recommend you use to author animations. https://www.blockbench.net/wiki/guides/bedrock-modeling

**Bedrock.dev:** This community wiki has some excellent tutorials that cover some areas we don't fully cover yet. I'd look at their topics on animation and MoLang. https://wiki.bedrock.dev/animation-controllers/animation-controllers-intro.html

**Discord:** Blockbench has a Discord, and there's also the Bedrock Addons Discord (linked from bedrock.dev). Both of these Discords are full of community members that may be able to help.
