### ISSUE TITLE
Typo in Sample Command in "Commands - How To Make a Complete the Monument Map" Article

### ISSUE THREAD

**Issue by gloganms** [MicrosoftDocs/minecraft-creator#199]
In the final set of sample commands for this article ( https://docs.microsoft.com/en-us/minecraft/creator/documents/commandshowtomakeactmmap ), there is set of typos where "##total_wool" should be "#total_wool". Copying and pasting these commands will cause errors and will require the reader to troubleshoot.

/scoreboard players set ##total_wool totals 0
/scoreboard players operation ##total_wool totals += * wool_placed
/scoreboard players test ##total_wool totals 3 3
/give @a diamond 64
/scoreboard players set #red wool_placed 2

Should be 

/scoreboard players set #total_wool totals 0
/scoreboard players operation #total_wool totals += * wool_placed
/scoreboard players test #total_wool totals 3 3
/give @a diamond 64
/scoreboard players set #red wool_placed 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d1e7115-8b5d-ef03-c655-1dd2de1505bf
* Version Independent ID: 2a603cb4-d0bd-4d95-42f6-27169de729b5
* Content: [How To Make a Complete the Monument Map](https://docs.microsoft.com/en-us/minecraft/creator/documents/commandshowtomakeactmmap)
* Content Source: [creator/Documents/CommandsHowToMakeACTMMap.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CommandsHowToMakeACTMMap.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by v-josjones** [comment]
Addressed and staged for release
