### ISSUE TITLE
Missing cow.json?

### ISSUE THREAD

**Issue by joshuadwarby** [MicrosoftDocs/minecraft-creator#201]
Inside the vanilla resource pack, as downloaded from the link provided, I don't see the file 'entities\cow.json'.  All I see is 'entity\cow.entity.json', but this file is missing most of the sections described in the tutorial.  What am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3ad989-cd74-1b9a-d07c-500fc80fdaf7
* Version Independent ID: 2403daea-89fc-ce01-badf-56e6752f562b
* Content: [Introduction To Behavior Packs](https://docs.microsoft.com/en-us/minecraft/creator/documents/behaviorpack)
* Content Source: [creator/Documents/BehaviorPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/BehaviorPack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Hello,

Both Behavior and Resource Packs have a dedicated folder containing entity json files. However, `entity\cow.entity.json` is a file that is located in the Vanilla Resource Pack, not the Behavior Pack. Can you verify that when you click on the link provided in the Requirements that the Behavior Pack is downloaded? Once downloaded and extracted, the cow.json file will be located in `Vanilla_Behavior_Pack_1.17.40\entities\cow.json`.

I've attached a screenshot of what the Behavior Pack folder structure looks like when downloaded.
![image](https://user-images.githubusercontent.com/75804667/140786980-a4331735-98c9-49e8-82c5-d04e74659621.png)

**Comment by joshuadwarby** [comment]
Thank you for your help, I think that did the trick!
