### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by EastBBQ** [MicrosoftDocs/minecraft-creator#202]
Hi, Just tried following this and the resource pack is not showing when I go to open the game - addons - resource packs. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Hi there,
We just updated the tutorial to be a bit clearer in places. We verified that it should still work. Could you try again and let us know if you're still running into issues?

**Comment by EastBBQ** [comment]
Hi I can now see the resource pack and add it however the dirt block hasn't changed at all

**Comment by EastBBQ** [comment]
> Hi I can now see the resource pack and add it however the dirt block hasn't changed at all

**Comment by v-josjones** [comment]
Now that the resource pack is visible in the launcher, two quick follow up questions:

- Are there any other packs being loaded at the same time as your custom resource pack? With pack stacking, another resource pack could be overwriting the change. 
- If there are no other packs enabled, is the dirt.png file saved specifically as `dirt.png` located in the `/my_Resource_pack/textures/blocks` folder?

**Comment by EastBBQ** [comment]
Hi I have checked both those questions. It is labelled correctly and in correct folder. Also the pack is at the top and is the only one enabled in the new world I create.Sent from my Galaxy
-------- Original message --------From: Joshua Jones ***@***.***> Date: 22/11/2021  17:08  (GMT+00:00) To: MicrosoftDocs/minecraft-creator ***@***.***> Cc: EastBBQ ***@***.***>, Author ***@***.***> Subject: Re: [MicrosoftDocs/minecraft-creator] not working (Issue #202) 
Now that the resource pack is visible in the launcher, two quick follow up questions:

Are there any other packs being loaded at the same time as your custom resource pack? With pack stacking, another resource pack could be overwriting the change.
If there are no other packs enabled, is the dirt.png file saved specifically as dirt.png located in the /my_Resource_pack/textures/blocks folder?

**Comment by JDHeaden** [comment]
Would you mind zipping up your behavior pack and resource pack folders and sending them to me so I can take a look?

**Comment by JDHeaden** [comment]
@EastBBQ - I am going to close this issue, but if you are still having problems, please feel free to let us know.

**Comment by EastBBQ** [comment]
Oops sorry I forgot to email the files!Sent from my Galaxy
-------- Original message --------From: Jill Headen ***@***.***> Date: 30/11/2021  19:13  (GMT+00:00) To: MicrosoftDocs/minecraft-creator ***@***.***> Cc: EastBBQ ***@***.***>, Mention ***@***.***> Subject: Re: [MicrosoftDocs/minecraft-creator] not working (Issue #202) 
@EastBBQ - I am going to close this issue, but if you are still having problems, please feel free to let us know.

**Comment by JDHeaden** [comment]
Not a problem! I will be glad to take a look if you send them.

**Comment by EastBBQ** [comment]
Hi this is the resource pack

**Comment by JDHeaden** [comment]
@EastBBQ I can't find the attachment - would you mind putting your folders in a repo and sharing it with me?

**Comment by JDHeaden** [comment]
@EastBBQ I am closing this, but I am still glad to help you solve this problem! If you can put your com.mojang folder in a repo and send me a link, I will be glad to take a look.

**Comment by EastBBQ** [comment]
Hi 

Did you get my resource pack?

Sending again

 

Melanie

**Comment by JDHeaden** [comment]
@EastBBQ I don't think attachments are coming through on here.  Can you put your folders in a repo on your Github page? I can see you have one on there called "Multiverse-Core." If you put your folders next to that, I should be able to get them.

**Comment by JDHeaden** [comment]
@EastBBQ I zipped my own packs and put them in a repo along with a diagram of the folder structure you'll need to create in com.mojang. The manifest.json files will need GUIDS added in. Please let me know if this is helpful. :)

**Comment by EastBBQ** [comment]
Hi I added My Resource Pack to repo - think I have done it right - new to this! I will have a look at what you have posted

**Comment by EastBBQ** [comment]
> Hi I added My Resource Pack to repo - think I have done it right - new to this! I will have a look at what you have posted


> @EastBBQ I zipped my own packs and put them in a repo along with a diagram of the folder structure you'll need to create in com.mojang. The manifest.json files will need GUIDS added in. Please let me know if this is helpful. :)

Hi I added My Resource Pack to repo - think I have done it right - new to this! I will have a look at what you have posted

**Comment by JDHeaden** [comment]
@EastBBQ - Yay! I got your resource pack. Try changing "Blocks" to "blocks" and try it again.
