### ISSUE TITLE
Tutorial does not work in 1.17.41

### ISSUE THREAD

**Issue by mcneij** [MicrosoftDocs/minecraft-creator#203]
Attempted the tutorial per instructions for both the resource pack (dirt texture) and behavior pack (attack cows).  

1. Minecraft recognizes the add-on and lists it in "my packs"
2. Both the resource pack and behavior pack can be activated in world creation
3. Resource pack can be activated in global resources
4. Neither the new texture or the cow behavior actually appear in world.  
5. I attempted it with several world creations, selecting experimental features & other options, which had no effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3ad989-cd74-1b9a-d07c-500fc80fdaf7
* Version Independent ID: 2403daea-89fc-ce01-badf-56e6752f562b
* Content: [Introduction To Behavior Packs](https://docs.microsoft.com/en-us/minecraft/creator/documents/behaviorpack)
* Content Source: [creator/Documents/BehaviorPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/BehaviorPack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Hi there,
We just updated the tutorial to be a bit clearer in places. We verified that it should still work. Could you try again and let us know if you're still running into issues?

**Comment by mcneij** [comment]
Tested it again; the behavior pack does not work, but resource pack will replace the dirt texture.  
Steps:
1. Deleted all folders from resource_packs, behavior_packs, development_behavior_packs, and development_resource_packs
2. Created files per tutorial (copy/pasted, see 1st image below)
3. Started minecraft (1.17.41)
4. Created a new world (survival, normal, cheats on, all other options default), activated resource & behavior packs in world creation
5. Checked behavior packs in settings after world creation: attack cow pack shows as active (see 2nd image below)
6. Result is the dirt texture is replaced, however cow behavior is normal vanilla passive.
7. Exited world, restarted minecraft, same result

Either I made a really simple error or there's something not being recognized with behaviors.

![image](https://user-images.githubusercontent.com/15671683/142700731-79d3223d-3702-4503-8e58-d0e35e8c9638.png)

![image](https://user-images.githubusercontent.com/15671683/142700705-3d6381d0-e742-4791-aed6-6ab125dc95a1.png)

**Comment by kakinnun** [comment]
Hmmm..
From your screenshot, it looks like you have a red warning at the top of your cow.json file. Scroll up to the top there and see if you can see anything. You could even open the "Problems" pane (Ctrl-Shift-M) in VS Code to see if there are any JSON errors. Often these errors can be traced back to missing/extra/misplaced braces or commas.

**Comment by mcneij** [comment]
Resolved!
I had copied the components section of the cow.json file verbatim, but that excluded the "minecraft:entity" section.  This probably would have been obvious to someone who's worked with json before but I thought the "components" would be sufficient.

**Comment by kakinnun** [comment]
yay! I'm so glad!
