### ISSUE TITLE
[minecraft:interact] Example code shows old format

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#204]
The format of `mincraft:interact` component changed quite a lot, in 1.12 (If I recall correctly).

However, not all entities in the vanilla behavior pack were updated, which means some entities are still showing the old (and much worse) version. 

In your document, your example actually shows this wrong code. I believe it might have been copied from the old cow entity. 

Later on the page, you show correct example from cow. 

The old interaction component style is considered completely outdated, bad practice, and won't even work on new format version. Please update this example to reflect new style. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b51382-166e-b788-0518-3a2380f2951e
* Version Independent ID: f5e8a1dd-7026-f121-5cf6-5b7e5bbc4d91
* Content: [Entity Documentation - minecraft:interact](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_interact)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_interact.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_interact.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by JDHeaden** [comment]
Updated cow code, merged to Main.
