### ISSUE TITLE
[Gametest] Can't get the whole inventory of a Double Chest

### ISSUE THREAD

**Issue by amon28** [MicrosoftDocs/minecraft-creator#207]
**Describe the bug**
Before this update 1.17.40, In 1.17.30 getting the whole inventory of a double chest is possible by only getting a single side of the double chest. Now in 1.17.40 even in the Beta 1.18.10.20, getting only a single side will not fill up the whole double chest.

During Testing when I tried getting the inventory size I was expecting to get only 27 slot size but I got 54 which is the whole double chest.
![image](https://user-images.githubusercontent.com/22851168/142850060-89cb669d-ac84-4a00-a1e7-d7b798aeaae0.png)
But when using setItem to every slot up to 54 it only fills up the bottom or top part depends which side of the double chest you set the items.
Setting item in right side:
![image](https://user-images.githubusercontent.com/22851168/142850111-26671ab4-1b4c-4280-b92a-7242f7c94db5.png)
Setting item in left side:
![image](https://user-images.githubusercontent.com/22851168/142850127-7a91df0c-04e4-4bde-9ba0-151d6dc1f052.png)
You can test this for yourself the addon is in the attachment. You chat !test while standing on the chest.

[Container Test.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/7580444/Container.Test.zip)

**To Reproduce**
1. Open in Beta version
2. Import container test addon
3. place a double chest
4. stand on top on one of the side of the double chest
5. chat !test

**Expected behavior**
Fills up the whole double chest

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mammerla** [comment]
Tracking an internal issue for this one.

**Comment by mammerla** [comment]
Should be resolved in current beta builds 1.18.20.
