### ISSUE TITLE
How to define a non-solid block?

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#208]
I have tried all those block components but I still get this.
### **Solid blocks interfere the rendering of liquid.**
I need custom non-solid blocks that behave like gaseous thing, just like glass, air, slabs and structure_void.
But I just can't figure out how to define one.

![image](https://user-images.githubusercontent.com/40757969/143373273-a6642d8d-d692-4079-908d-ee2d92c4ba37.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 461ae8d5-a555-30c8-ac12-c2aa7b5ba18e
* Version Independent ID: 27e6f2c0-afef-4bbd-c5c8-0282ab679fc6
* Content: [How to add a Custom Block](https://docs.microsoft.com/zh-cn/minecraft/creator/documents/customblock)
* Content Source: [creator/Documents/CustomBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CustomBlock.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Thank you for your comment. Unfortunately, we cannot provide addon support via this Github repository. This repo is for issues that relate specifically to the published articles and content we have on the docs.microsoft.com site.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.
