### ISSUE TITLE
Phone structure export

### ISSUE THREAD

**Issue by Kybomaster** [MicrosoftDocs/minecraft-creator#209]
is it possible to add the "export" button in the structural block using the addon?

**Comment by JDHeaden** [comment]
@Kybomaster I asked the devs and got this answer: "The restriction that we have today is that there's no way to pop up a save dialog on iOS/Android, so until that happens we can't put that functionality in." - BUT there is a request to get support for it. 

So, I'm sorry I don't have a better answer yet, but this is something that should be addressed at some point.  

Does that help?

**Comment by JDHeaden** [comment]
@Kybomaster Hi again. I'm going to close this ticket. Thank you!
