### ISSUE TITLE
Missing properties; minecraft:behavior.knockback_roar

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#21]
Missing property details:

- knockback_filters (filter)
- damage_filters (filter)
- on_roar_end (event/trigger)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce07b46-0e9e-77e6-0a32-f4e8d91d128e
* Version Independent ID: a70773dc-ea91-ec28-fe90-d200356bbcd7
* Content: [minecraft:behavior.knockback_roar](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_knockback_roar)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_knockback_roar.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_knockback_roar.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by mardb** [comment]
Addressed in [Hotfix for R17: Caves and Cliffs: Part 1](https://github.com/MicrosoftDocs/minecraft-creator-pr/pull/189#event-4930380792)
