### ISSUE TITLE
[Request] Clarrification on path length

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#210]
Could there be a section on paths length?

There are no clear rules on how long file paths can be, though I know there is some trouble with too long filenames, and folders names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45db6623-7d17-68da-867c-eba6ad80375b
* Version Independent ID: 3bd7fbd1-46da-2fe1-a8f1-1d4fbee797de
* Content: [Packaging a World Template](https://docs.microsoft.com/en-us/minecraft/creator/documents/packagingaworldtemplate)
* Content Source: [creator/Documents/PackagingAWorldTemplate.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingAWorldTemplate.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by v-josjones** [comment]
We can add it to the docs on our end as well but the default max file path allowed for Windows 10 is 260 characters.

**Comment by DaanV2** [comment]
Well I know there is a limit somewhere of 80 characters in packs counted from a certain point (root or world root) because other consoles are unable to deal with anything longer

**Comment by DaanV2** [comment]
Or in the document linked the folder name of the RP / BP can only be 10 characters because of limits
