### ISSUE TITLE
I can't use query functions in particles whose host entity is dead.

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#211]
`"minecraft:particle_lifetime_expression": {
  "max_lifetime": 60,
  "expiration_expression": "query.time_of_day > 0.5"
}`
`/particle this_particle`
> Nothing happens. query.time_of_day always returns 0

It's killing FPS when there are too many client entities.
I just want my entity to despawn after spawning the particle but without the host entity I can do nothing.

**Describe alternatives you've considered**
I have tried to store the player into a variable for invoking an entity context using `->` but I failed.
`"pre_effect_script": "for_each(temp.player, query.get_nearby_entities(128, 'minecraft:player'), { variable.player = temp.player; break; });"`

**Describe the solution you'd like**
There are many queries not related to any entity. Why not allow us to use them without an entity?

**Comment by kakinnun** [comment]
Thank you for your comment. We will consider this when we update our particles documentation. Unfortunately, we cannot provide addon support via this Github repository. This repo is for issues that relate specifically to the published articles and content we have on the docs.microsoft.com site.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.

For Minecraft bugs or feature requests, I recommend the official Minecraft Feedback Site here: https://feedback.minecraft.net/hc/en-us
