### ISSUE TITLE
[Particles DoS] Particles live forever.

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#212]
`"max_lifetime": 1`
Sounds good.
But...
I have a custom entity with server animation.
`animation_length": 1`
Every second, `/particle` is called by the animation spawning 100 my particles.
But something happened when I spawn 10 my entity.

**The particles just won't expire!!!**

I executed `/kill @e` then finally they started to expire.

I guess that too many requests of `/particle` will block the calculation of particle lifetime.

**Particle lifetime should NOT be interrupted!!!**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed21a506-3146-0dd8-48a4-465a98fbcb10
* Version Independent ID: 3efbca76-1bbf-99dc-4338-a4c4e50588db
* Content: [Particle Documentation - Particle Lifetime Expression component](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/particlesreference/particlecomponents/minecraftparticle_lifetime_expression)
* Content Source: [creator/Reference/Content/ParticlesReference/ParticleComponents/minecraftParticle_lifetime_expression.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ParticlesReference/ParticleComponents/minecraftParticle_lifetime_expression.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by kakinnun** [comment]
Thank you for your comment. We will consider this as we work on our particles documentation. 

Unfortunately, we cannot provide addon support via this Github repository. This repo is for issues that relate specifically to the published articles and content we have on the docs.microsoft.com site.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.

For Minecraft bugs or feature requests, I recommend the official Minecraft Feedback Site here: https://feedback.minecraft.net/hc/en-us
