### ISSUE TITLE
how to create a new "geometry": "geometry.humanoid.customX"

### ISSUE THREAD

**Issue by ErTony13** [MicrosoftDocs/minecraft-creator#213]
How can I create a custom "geometry": "geometry.humanoid.custom", for example if I want to enlarge the head or reduce an arm, or change the shape of a leg? Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Packaging a Skin Pack](https://docs.microsoft.com/en-us/minecraft/creator/documents/packagingaskinpack)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingASkinPack.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by kakinnun** [comment]
Thank you for your comment. Unfortunately, we cannot provide addon support via this Github repository. This repo is for issues that relate specifically to the published articles and content we have on the docs.microsoft.com site.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.

For Minecraft bugs or feature requests, I recommend the official Minecraft Feedback Site here: https://feedback.minecraft.net/hc/en-us
