### ISSUE TITLE
I'm writing a new leaf block in a plugin with "render_method": "alpha_test" the transparent part in the middle is black

### ISSUE THREAD

**Issue by HeadOfKingship** [MicrosoftDocs/minecraft-creator#215]
[在此处输入反馈]
I am writing a new leaf block in a plugin with "render_method" but the transparent part in the middle is still black after using "alpha_test"
By the way, it seems to be fine at 1.16, but not at 1.18

        "minecraft:material_instances": {
          "*": {
            "texture": "sakura_sakuraleaves",
            "render_method": "alpha_test"
          }
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 11a717d0-e1a6-84ac-9739-08cef6c82caf
* Version Independent ID: c187c9a6-a98c-101b-fed6-2270baa772da
* Content: [Block Documentation - minecraft:material_instances](https://docs.microsoft.com/zh-cn/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_material_instances)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_material_instances.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_material_instances.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Thank you for your comment. Unfortunately, we cannot provide addon support via this Github repository. This repo is for issues that relate specifically to the published articles and content we have on the docs.microsoft.com site.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.

For Minecraft bugs or feature requests, I recommend the official Minecraft Feedback Site here: https://feedback.minecraft.net/hc/en-us
