### ISSUE TITLE
Improving Typescript documentation for GameTest

### ISSUE THREAD

**Issue by kakinnun** [MicrosoftDocs/minecraft-creator#216]
GameTest users are primarily interacting with the API with pure JavaScript. Others in the community are seeing a strong benefit using TypeScript.

**Describe the solution you'd like**
Getting started with TypeScript documentation.
Code examples that use TypeScript.

**Comment by mammerla** [comment]
@kakinnun love the idea :) I think we'd want to document this when we have more of a recommended initial toolchain to support typescript compilation, which ideally we can address soon

**Comment by ConsoleTerm** [comment]
This issue could be closed now, Thank you.
