### ISSUE TITLE
Weird flow in Introduction to Add Entity

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#218]
There is a confusing and weird transition in that tutorial between:
`Client Entity Definition` and `Visuals`

People have assumed that the given example was a render controller, but it isn't and its just a weird flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ded1495c-5233-8717-83d5-5e3092513c5e
* Version Independent ID: dcbe991c-bf73-690c-a9c2-988e1170e224
* Content: [Introduction to Add Entity](https://docs.microsoft.com/en-us/minecraft/creator/documents/introductiontoaddentity#feedback)
* Content Source: [creator/Documents/IntroductionToAddEntity.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/IntroductionToAddEntity.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JDHeaden** [comment]
@DaanV2 Hi! I rewrote the Visuals section like this. Is this flow less weird?

## Visuals

Before we can add the entity into the game, it needs a model. The [Entity Modeling and Animation](EntityModelingAndAnimation.md) article explains how to create a custom model and texture, but creating a model is a lot to learn and we are not done with this tutorial yet. So, for now, you can pretend you already created a model by copying and pasting the files from the robot resource pack. Use these same steps later to add the model you create.

- Save the model inside the folder `models/entity` as `robot.geo.json`.
- Save the texture in `textures/entity` as `robot.png`.

Now that the model files are in place, we need a render controller to link the model, texture, and material that's used for the entity.

Open the `robot.entity.json` file in the  `entities` folder in your resources pack.

For most entities (such as our robot), we can use the default render controller that's provided by the game. We will talk more about render controllers later in the more advanced half of this tutorial. For now, just know that this is where it goes.

**Comment by DaanV2** [comment]
Looks wonderful @JDHeaden!

**Comment by JDHeaden** [comment]
update - I made these edits and some others to the document and it's waiting for review.

**Comment by JDHeaden** [comment]
Updated file is staged for release.
