### ISSUE TITLE
Real player simulated actions

### ISSUE THREAD

**Issue by evil-makima** [MicrosoftDocs/minecraft-creator#220]
Some events simulating actions on a player could be attributed to real players.

Example:
player.interactWithEntity(...);

These interaction simulations would allow to automate some fakeblocks with inventory (among other things).

I have a practical example of an addon that would use these features (it's not a crafting table)

[Video on twitter](https://twitter.com/evil_makima/status/1469312393935261697?t=ZS0S2KHPMgr9ZXFKaBafCA&s=19) 

![Minecraft_2021-12-10-11-21-12](https://user-images.githubusercontent.com/83883254/147204448-3d93f56b-29c8-4d5d-b661-21e392bddd31.png)

**Comment by mammerla** [comment]
@evil-makima is this a suggestion for new APIs for the [SimulatedPlayer API](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-gametest/simulatedplayer) or broader player simulation capabilities?

**Comment by kakinnun** [comment]
Closing due to lack of communication. For Minecraft bugs or feature requests, I recommend the official Minecraft Feedback Site here: https://feedback.minecraft.net/hc/en-us
