### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by anthoXkev** [MicrosoftDocs/minecraft-creator#221]
In the "blocks" file : 
Suppose I want to change the texture of a random item : 
How do we know how to rename our file to change the texture of this object ? Should we simply use the name of the object in the game, with underscores if there are spaces ? If so, I don't have my game in English, should I put it in "UK English" or "US English"?

Thank you for your answer and for this tutorial that works, 

Thank you very much

**Comment by SirLich** [comment]
First of all, `blocks.json` isn't used for items. The correct file is `textures/item_texture.json`. 

To answer your question: These files work based on a short-name system, that exists outside of the actual localization that the game uses. 

The best way to overwrite this kind of content is by downloading the vanilla resource packs, and searching for the texture path/name you want to overwrite. 

We actually provide a full, [step-by-step tutorial](https://wiki.bedrock.dev/concepts/overwriting-assets.html#top) for this on the community-created Bedrock Wiki.

Additionally, this github isn't the right place to seek addon help. 

@Maintainers, is there a reason this hasn't been closed yet?

**Comment by kakinnun** [comment]
Thanks for the assist @SirLich and thanks for the link to a helpful article on the community wiki! @anthoXkev I can also recommend the Bedrock Addons Community Discord that is linked from the community Bedrock Wiki to seek help from other community members.

Closing this issue.
