### ISSUE TITLE
Add a command for the damage cooldown time setting of entities in MCBE

### ISSUE THREAD

**Issue by D4rkerender** [MicrosoftDocs/minecraft-creator#222]
As a PVP server owner, I really want if there is a command that can make achieve a perfect combat system in MCBE. This requires a shorter attack cooling time and better knockback power in the X-axis and Y-axis, the latter can already be implemented through the Behavior Pack, but the former does not seem to have a solution. (In fact, since 1.16.230, detecting players when attack the entity, to add instant_damage directly to the entity and immediately delete this effect have worked to get rid of damage cooling time. I hope that it could be remained for long.) In order to solve this problem, I think it is very necessary to add a command for defining the injury cooling of a entity, which helps to a very PVP and PVE map producers or BDS server owner. I hope that my suggestion can be adopted, I will be very appriciated if it does happen.

**Comment by D4rkerender** [comment]
As a matter of fact, I haven't found a solution for defining injury cooling time from the new function 
"gametest", and I did read these complex documents. However, no idea I have. In my opinion, that adding a command is the best, we can do many things in MCBE but making a better combat is nothing cheerful.

**Comment by kakinnun** [comment]
Thank you for your comment. For Minecraft bugs or feature requests, I recommend the official Minecraft Feedback Site here: https://feedback.minecraft.net/hc/en-us

This GitHub repo is only for logging issues with the specific documentation we have published.
