### ISSUE TITLE
In short, it isn't working

### ISSUE THREAD

**Issue by thelabcat** [MicrosoftDocs/minecraft-creator#223]
As far as I can tell, I have done everything according to the docs, but the skin pack is still not loading. Here is my folder: 

[Among_Us.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/7786600/Among_Us.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Packaging a Skin Pack](https://docs.microsoft.com/en-us/minecraft/creator/documents/packagingaskinpack)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingASkinPack.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JDHeaden** [comment]
Hi @thelabcat! I've been researching your issue and I have gotten Minecraft to open the .png and geometry file.

<img width="1766" alt="among_us_geometry" src="https://user-images.githubusercontent.com/93944549/147833352-8f7aca79-42b1-475c-a3a6-5b6885ef6c75.png">

To get here, I created a super-basic skin pack with only manifest.json, skins.json, and different skin .png that uses the basic humanoid geometry. After I got it to open, I added your .png and geometry file. 

[test_skins.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/7796730/test_skins.zip)

Please let me know how it goes!

**Comment by JDHeaden** [comment]
Hi @thelabcat! I am going to close this issue, but I will keep following it in case you want to share your progress.

**Comment by thelabcat** [comment]
Hi,
I just now got a chance to look into this. Thanks for getting back to me, and I'm sorry for the late reply.

The results of my test are:
- Placing the pack in development_skin_packs does nothing.
- Placing the pack in skin_packs causes it to load properly*.
- *The custom geometry.json file is being ignored: the astronaut.png is just being laid over a slimArmed geometry.

I read at one point that custom geometry support had been dropped "because it was abused," which makes sense, but isn't skin abuse part of the problem solved by "Only allow trusted skins" in Profile settings? I might think the unsupport was because making a resource pack inherently bypasses that safety, but the game _does support_ custom geometry from paid store resource packs, so that can't be the problem.

What do you think is going on here?

**Comment by JDHeaden** [comment]
Reopening while I wait for an answer about whether custom skin pack geometry has been dropped. 

Thank you for you patience!

**Comment by JDHeaden** [comment]
Hi @thelabcat - You are correct that custom geometry is only supported from marketplace resource packs.

**Comment by thelabcat** [comment]
Thanks for your help! Kind of a bummer, but I understand. Okay, bye!
