### ISSUE TITLE
Base Resource Pack File Missing From Official Site Page

### ISSUE THREAD

**Issue by fakeforsure** [MicrosoftDocs/minecraft-creator#225]
There used to be a download file where you could download the base resource pack. What happened to it? I used it before 1.18 and now it's gone. Was it removed or is it still there somewhere? Thank you for your time.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://docs.microsoft.com/fr-fr/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by fakeforsure** [comment]
Sorry, I should had read the very bottom of the document.

**Comment by kakinnun** [comment]
No worries at all! In addition to the links at the bottom of the main index, the resource file links are also available from the top nav under the "Resources" drop-down.
