### ISSUE TITLE
minecraft:repairable feature doesn't work

### ISSUE THREAD

**Issue by Futrime** [MicrosoftDocs/minecraft-creator#226]
minecraft:repairable component never works. I've tried two forms as below.
But when applying the behavior pack to the world and attempting to repair with anvil using iron ingot, it just keep displaying the red cross.

```json
"minecraft:repairable":{
  "repair_items": ["iron_ingot"]
}
```

```json
"minecraft:repairable": {
  "repair_items": [
    {
      "items": [
        "minecraft:iron_ingot"
      ],
      "repair_amount": "query.max_durability * 0.33"
    }
  ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0edb3e4-d79d-49e9-90e0-42f119e8a14e
* Version Independent ID: 2f19aa1d-477f-8695-e746-1c9e6cec5da9
* Content: [Item Documentation - minecraft:repairable](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_repairable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_repairable.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_repairable.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Thank you for your comment. Unfortunately, we cannot provide addon support via this Github repository. This repo is for issues that relate specifically to the published articles and content we have on the docs.microsoft.com site.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.

For Minecraft bugs or feature requests, I recommend the official Minecraft Feedback Site here: https://feedback.minecraft.net/hc/en-us
