### ISSUE TITLE
No "Edit Model" button on web.blockbench.net

### ISSUE THREAD

**Issue by mfripp** [MicrosoftDocs/minecraft-creator#227]
I would like to use the Minecraft Entity Wizard plugin with the web app at web.blockbench.net. The tutorial mentions that this is a supported configuration, and also says that there should be an "Edit Model" button on the last page of the wizard. However that button does not appear on the web app. So there doesn't seem to be any way to use this wizard to create new entities based on existing Minecraft entities using the Minecraft Entity Wizard via web.blockbench.net. Would it be possible to add this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79c7652f-5c4e-768c-ca52-1ac2ff1790f5
* Version Independent ID: 794cb3ed-7c30-59af-7d62-3f109de1d553
* Content: [Getting Started with Minecraft Entity Wizard](https://docs.microsoft.com/en-us/minecraft/creator/documents/minecraftentitywizard)
* Content Source: [creator/Documents/MinecraftEntityWizard.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/MinecraftEntityWizard.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
We've passed this feedback along to the Blockbench team. For assistance on that product and any feature requests, I'd recommend you visit their site here: https://www.blockbench.net/ or their Github repo here: https://github.com/JannisX11/blockbench

Closing this issue as this Github is for logging issues specific to the documentation on our site.
