### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by CoredMiner** [MicrosoftDocs/minecraft-creator#229]
[Very good Tutorial that shows the basics of creating an Add-On]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://docs.microsoft.com/de-de/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Glad to hear it! Thank you :)
