### ISSUE TITLE
ToC does not match menu

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#23]
![Screenshot from 2021-06-09 13-39-52](https://user-images.githubusercontent.com/1408278/121355884-40532e00-c928-11eb-9ad0-9d8ea356efae.png)
![Screenshot from 2021-06-09 13-39-45](https://user-images.githubusercontent.com/1408278/121355886-40ebc480-c928-11eb-8620-968722fea77f.png)

See attached screenshots

**Comment by kakinnun** [comment]
L2 Headers (what we call that top nav) have to be submitted to a different repo for publish so there is a delay in updating it after we update the main site. Looking now, the new L2 header is live. It isn't designed to be exactly 1 to 1 of what the side nav has, but interested in feedback.

**Comment by kakinnun** [comment]
closing issue as I believe the original ask has been resolved.
