### ISSUE TITLE
Render offset Defaults?

### ISSUE THREAD

**Issue by ahmed4363** [MicrosoftDocs/minecraft-creator#230]
The documentation site is great and is very useful, but i would like to see the default values for render offset and other item components too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22f8f8d-58a2-c0ed-c8e7-66edd4e7bb0e
* Version Independent ID: 05fc5b5a-3dcd-3ab2-6e2b-a76206f2aa6b
* Content: [Item Documentation - minecraft:render_offsets](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_render_offsets)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_render_offsets.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_render_offsets.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
I'll add it to the documentation page, but the default values will divert to a Vec3 of [0,0,0] for both if no value is set.
