### ISSUE TITLE
Totem of undeading

### ISSUE THREAD

**Issue by Kybomaster** [MicrosoftDocs/minecraft-creator#231]
What is the name of the file in the ui in which the animation of tomim immortality is registered?

**Comment by kakinnun** [comment]
Thank you for your comment. Unfortunately, we cannot provide addon support via this Github repository. This repo is for issues that relate specifically to the published articles and content we have on the docs.microsoft.com site.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.
