### ISSUE TITLE
I can't understand the tutorial

### ISSUE THREAD

**Issue by SorridenteGames303711** [MicrosoftDocs/minecraft-creator#232]
You didn't explain how to organize the models, animation or other folders in the files, you simply had the json files and such a place and also presented commands but they don't teach you to put them in the script, and although you presented a link to learn about the .JSON but it doesn't teach anything right, if you can, please review your tutorials and also send me the tutorials in Portuguese Brazil, for example, you showed me a "view" command of the cow mob and asked me to "play" with it and then they say "now with the behavior package ready...." this really caught my mind, please try to help me as much as possible. 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 249e76d5-1b78-7a9f-85ff-ebb04366d0ed
* Version Independent ID: 00f36d44-ebfc-213d-ef1a-353acd1f9842
* Content: [Entity Modeling and Animation](https://docs.microsoft.com/pt-br/minecraft/creator/documents/entitymodelingandanimation)
* Content Source: [creator/Documents/EntityModelingAndAnimation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EntityModelingAndAnimation.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by kakinnun** [comment]
Thank you for your feedback.

**Comment by SorridenteGames303711** [comment]
> Thank you for your feedback.

You didn't solve my problem to close it.
