### ISSUE TITLE
Lack of explanation in some areas.

### ISSUE THREAD

**Issue by SorridenteGames303711** [MicrosoftDocs/minecraft-creator#234]
**Describe the missing content**
It gives an example of a cow view command without even explaining where that script was taken from, nor how to use it, it also highlights a supposed "ready behavior package" but I didn't do anything in which the tutorial asked me to question to this, and going back to the previous session it asks to save such files in folders in which they were not taught how to organize and obtain these files nor how to save lps correctly, because in the complete example of the file it is in such a way more complex, but there are no specific explanations of how to obtain such results, and there are also Scripts that are not taught how to insert into .JSON files, which makes programming very difficult.  Please, if you can, review your content and update it so that I can understand.. 
![Screenshot_20220117-224554_Chrome.jpg](https://user-images.githubusercontent.com/76926526/149863451-16e710cb-a310-4881-8d97-66b875e2b7fc.jpg)
![Screenshot_20220117-224604_Chrome.jpg](https://user-images.githubusercontent.com/76926526/149863469-8cd81b91-e19a-48d3-a0df-31de023ac07e.jpg)

**Comment by kakinnun** [comment]
Thank you for your comment. We are always reviewing our content to make it more understandable over time, especially as we add more supporting documentation. We are also working on localizing our content into other languages in the future which may help with some miscommunications that may arise when using an auto-translation service.

If you are unable to find an answer to your addon question here, I can recommend the Bedrock Wiki community site (https://wiki.bedrock.dev/). This community-run site has different documentation than we host, and they also have a very welcoming Discord community that may be able to help you.
