### ISSUE TITLE
Can I use pictures from the documentation?

### ISSUE THREAD

**Issue by Kybomaster** [MicrosoftDocs/minecraft-creator#237]
I would like to use pictures from the documentation and articles on my YouTube channel. Will there be copyright issues?

**Comment by kakinnun** [comment]
For information on this...

Our license is here:
https://github.com/MicrosoftDocs/minecraft-creator/blob/main/LICENSE

And our Code of Conduct is here:
https://opensource.microsoft.com/codeofconduct/

I can't provide legal advice, unfortunately.
