### ISSUE TITLE
wither JSON snippet incorrect

### ISSUE THREAD

**Issue by kakinnun** [MicrosoftDocs/minecraft-creator#24]
Current JSON snippet for wither is malformed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fae7e399-de8b-37e2-3fbf-fbb4db386ed8
* Version Independent ID: e3c9547b-466f-df6b-ccdd-dd43c1152660
* Content: [minecraft:boss](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_boss)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_boss.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_boss.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Addressed. Added to next hotfix.

**Comment by v-josjones** [comment]
Also, duplicate issue #22

**Comment by mardb** [comment]
Addressed in [Hotfix for R17: Caves and Cliffs: Part 1](https://github.com/MicrosoftDocs/minecraft-creator-pr/pull/189#event-4930380792)
