### ISSUE TITLE
[GameTest] What does the event loop look like?

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#240]
# [My answer](#the-answer)

## Just an imaginary example:

I want the player to be always in water.

```javascript
while (true) {
    fill_16x16x16();
}
```
Of course, it blocks the thread.
Everything stops.

```javascript
function handleTick () {
    fill_16x16x16();
}
```
Lag!
`fill_16x16()` takes more than 20ms!

```javascript
handleTick () {
    fill_next_1_of_16x16x16();
}
```
No lag but too slow! The player escapes from the water!

```javascript
handleTick () {
    fill_next_16x1x16();
}
```
Snapdragon: Good! No lag. Not slow (It's impossible to be faster on ARM, actually);
Core i9: Slow! It can be faster!

Assume that `fill_next_one();` takes 2ms on i9 and 5ms on Snapdragon
What if:
```javascript
const resolved = Promise.resolve();
async function start () {
    while (true) {
        await resolved;
        fill_next_one();
    }
}
```
Slow!

## <span id="the-answer">Every tick, the GameTest Framework processes ONLY ONE `"message"` in the message queue besides my tick event listener</span>
Evidence:
```javascript
import { world } from "mojang-minecraft";
const resolved = Promise.resolve();

let n = 0;
async function test() {
    while (true) {
        await resolved;
        n++
    }
};

world.events.tick.subscribe(function () {
    console.warn(n); // always 1
    n = 0
});

test();
test();
test();
```
So we have message loop like:
```cpp
void this_function_is_called_synchronously_by_BedrockEngine_every_tick ()
{
    synchronously_execute_all_tickEvent_listeners();
    synchronously_process_one_message_if_exists();
}
```
**There is no loop.**

### What if every tick, the framework will always try to process all the messages, which will pause only when 15ms(?) be run out?

Here's a simple impl. It is definitely not the best but it may work.
```cpp
void this_function_is_called_synchronously_by_BedrockEngine_every_tick ()
{
    bool loop = true;
    std::thread t([&loop] {
            constexpr std::chrono::milliseconds timeout(15);
            std::this_thread::sleep_for(timeout);
            loop = false;
        });
    while (loop && queue_is_not_empty())
    {
        synchronously_process_one_message();
    }
}
```
On Snapdragon, `while (true)` in the async function should only be processed 3 times.
On i9, 8 times!

Again, it's imaginary. Please point out what is wrong.
If it makes sense, I hope we can get it.

**Comment by mammerla** [comment]
This is good feedback! We definitely know that there is more work that needs to be done in this area - both in terms of more restrictions to prevent script from impacting broader game execution, but also in terms of providing more tools to run things on the background to better balance the performance characteristics of different devices.

**Comment by Worldwidebrine** [comment]
> This is good feedback! We definitely know that there is more work that needs to be done in this area - both in terms of more restrictions to prevent script from impacting broader game execution, but also in terms of providing more tools to run things on the background to better balance the performance characteristics of different devices.

> providing more tools

Why `tools`?
When I wrote my examples, I merged everything into one function call, which is not real.
This is real.
```
for x...
for y...
for z...
if (is_air()) {
    setblock()
}
if (can_waterlog()) {
    waterlog()
}
...
```
**If the `tools` receive tasks as callback, it will be not convenient.**
Why not just give us a good event loop?
So we can simply use `await Promise.resolve();` as `Thread.yield();` to allow the script to be paused by the engine.
```
if (is_air()) {
    await resolved;
    setblock()
}
await resolved;
if (can_waterlog()) {
    await resolved;
    waterlog()
}
await resolved;
```

**Comment by Worldwidebrine** [comment]
@mammerla 
It seems that recently you developers are working on `system.run`.
Afaik, in `system.run(fn, 0);` `fn` should be executed in the current tick.
But it is not working properly.

**Why didn't you reuse microtask's scheduling to implement `system.run(fn, 0)`?**

They have the same intended behavior, don't they?
