### ISSUE TITLE
[Gametest] BlockExplodeEvent is only getting air blocks

### ISSUE THREAD

**Issue by amon28** [MicrosoftDocs/minecraft-creator#242]
**Describe the bug**
I am using the mojang-minecraft module, I want to get the blocks that got affected by the explosion. When I explode a tnt above glass blocks or any other blocks it only gets air blocks. This is in the new stable release 1.18.10.

**Expected behavior**
Get other blocks other than air blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/22851168/153208675-80b83a4c-8afd-4088-8626-b59807044eec.png)
![image](https://user-images.githubusercontent.com/22851168/153208842-fd4f10cf-cc41-491f-80b9-a4547f1f7b25.png)

**Desktop:**
 - OS: Windows 10

**Comment by ConsoleTerm** [comment]
Not sure since this issue was current, but its not issue anymore, Thank you for your report @amon28, please close your issue
