### ISSUE TITLE
getPlayers()

### ISSUE THREAD

**Issue by DEAD10CK-23** [MicrosoftDocs/minecraft-creator#243]
I want to see players name that inside in the "overworld" dimension but all i got is error and undefined when i type
 
Minecraft.world.getDimension("overworld").getPlayers("Steve") - its not working

Minecraft.world.getDimension("overworld").getPlayers().name - it return undefined

im currently using minecraft bedrock 1.18.20.23

btw is there a way to see the players currentdimension?

**Comment by Aditya-148** [comment]
getPlayers() returns all the players in the world. You cannot pass it anything so your first code is wrong. getPlayers() returns an iterator so to access it's values, we need to spread it in an array and iterate over it to get its values. `[...Minecraft.world.getDimension("overworld").getPlayers()]`
This will return an array of all players in the overworld dimension. You can remove the getDimension() part to return all players in the world.
Now we can iterate over this array like so:
```js
[...Minecraft.world.getDimension("overworld").getPlayers()].forEach((player) => { 
  Minecraft.world.getDimension("overworld").runCommand(`say ${player.name}`);
});
```
This will output all player's name currently in the overworld.

> btw is there a way to see the players current dimension?

In the latest beta you can use `player.dimension.id` to get a players dimension. In stable you need to use the above method to get all players in all three dimensions seperately and find in which dimension your player is.

**Comment by ConsoleTerm** [comment]
@DEAD10CK-23 Could you please close this issue, it`s not current anymore, Thank you
