### ISSUE TITLE
Something went wrong communicating with server

### ISSUE THREAD

**Issue by NITENOOBS** [MicrosoftDocs/minecraft-creator#244]
After my world was prepared for uploading, I pressed the "upload world" button and the message "Something went wrong communicating with the server" popped out. I tried to do it several times and everytime the same thing happens

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://docs.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview#converting-a-world-with-chunker)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by kakinnun** [comment]
Closing as more info is needed to help.
