### ISSUE TITLE
What this doc mean?

### ISSUE THREAD

**Issue by NguyenDuck** [MicrosoftDocs/minecraft-creator#245]
[Enter feedback here]
`subscribe(callback: (arg: BlockBreakEvent) => void): (arg: BlockBreakEvent) => void`
Double `: (arg: BlockBreakEvent) => void` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af18ebca-5cd4-e0ee-2196-46eb42e3f46d
* Version Independent ID: af18ebca-5cd4-e0ee-2196-46eb42e3f46d
* Content: [mojang-minecraft.BlockBreakEventSignal Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/blockbreakeventsignal)
* Content Source: [creator/ScriptAPI/mojang-minecraft/BlockBreakEventSignal.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/BlockBreakEventSignal.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by kakinnun** [comment]
Closing as need more info.
