### ISSUE TITLE
Duplicate doc page

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#246]
This page is duplicated in the navigation, it's presumably meant to have a link to the sister class `Signal`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 190fbe41-a629-bf1c-4fa7-d82da0857602
* Version Independent ID: 190fbe41-a629-bf1c-4fa7-d82da0857602
* Content: [mojang-minecraft.BeforeDataDrivenEntityTriggerEvent Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/beforedatadrivenentitytriggerevent)
* Content Source: [creator/ScriptAPI/mojang-minecraft/BeforeDataDrivenEntityTriggerEvent.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/BeforeDataDrivenEntityTriggerEvent.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by GTB3NW** [comment]
![Screenshot from 2022-02-15 18-00-02](https://user-images.githubusercontent.com/1408278/154121438-48e78971-0512-4d2b-8ca0-f7d05c7bbff3.png)

Visual reference to what it shows

**Comment by GTB3NW** [comment]
related: https://github.com/MicrosoftDocs/minecraft-creator/issues/238

**Comment by JakeShirley** [comment]
@GTB3NW Fixed internally, this will hopefully roll out with the next push of docs.  Thanks for reporting!

**Comment by JakeShirley** [comment]
cc @mammerla
