### ISSUE TITLE
Documentation missing on "tick.json" in behavior packs "functions" folder.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#25]
After sifting through the documentation, I noticed no documents relating to the tick.json file being actively being used by content creators and add-on developers.

### Source of external community documentation that the community currently uses.
[https://wiki.bedrock.dev/concepts/mcfunction#creating-tickjson](https://wiki.bedrock.dev/concepts/mcfunction#creating-tickjson)

### Here's some information that may be helpful.
_1. This file does not exist in the vanilla example behavior pack but can be created following the above tutorial. 
     - You can also take a look at the below example at the bottom of this issue._

_2. This file needs to be created in this directory of a behavior pack. "functions/tick.json"_

_3. It's unknown what keys are supported besides "values":[]
"values": ["function1", "function2"] which is the only known key._

_4. This file executes function files continuously without the need for command blocks,  entities, or ticking areas._

### Here's a working test example from one of my many Marketplace maps that use this feature.
[tickjson_BP.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/6627602/tickjson_BP.zip)

**Comment by v-jeffreykim** [comment]
We have compiled a list of missing reference documentation and tick.json is included in this list. I will go ahead and close this issue, please be on the lookout for an update to the docs in the future.

**Comment by StealthyExpertX** [comment]
Awesome thanks, you dudes are epic!

**Comment by JDHeaden** [comment]
TickJsonIntroduction,md and FunctionIntroduction.md have been created.
