### ISSUE TITLE
A method is required to customize entity attacks

### ISSUE THREAD

**Issue by d4rkOfficial** [MicrosoftDocs/minecraft-creator#251]
In the update of 1.18.20.27, we obtained 'EntityHitEvent', which made us all overjoyed. PvP server based on Gametest Framework will have better and better prospects along with these great updates again and again. 

We can now detect an entity attacking completely without help of commands. However, we still need to customize the horizontal and the vertical knockback power to get adapted to different pvp game modes. At the same time, to shorten the attack cooldown is necessary, the reason are the same. 

My advice is to add a "BeforeEntityHitEvent" , and give some variables to edit by developers.

1.knockback.x float
2.knockback.y float
if target is a block, knockback should be ignored
3.attackCooldown int(ticks)
 
At last, I hope that the "clicks per second" can be read someways

That's all.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
