### ISSUE TITLE
Confusing Documentation

### ISSUE THREAD

**Issue by fluffyball9** [MicrosoftDocs/minecraft-creator#253]
[This](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockevents/minecraftblock_set_block_property#feedback) page is really confusing, does this run Molang or does it set a block property? Can somebody update this to be more clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcee78cc-fccd-46c2-c179-c4335ed16c5d
* Version Independent ID: 95171a37-8828-f5a4-9398-10578290443f
* Content: [Block Documentation - set_block_property](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockevents/minecraftblock_set_block_property)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_set_block_property.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_set_block_property.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
///TODO

change to this:

```
"set_block_property": {
  "property name here": "Molang expression here"
}
```
