### ISSUE TITLE
How to add enchantement texture to items

### ISSUE THREAD

**Issue by ByLex-69bits** [MicrosoftDocs/minecraft-creator#257]
[Enter feedback here]
Hey, i would like to know how to add an enchantement texture to items like enchanted golden apple. Someone can help me pls ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
Hi @ByLex-69bits - An enchanted apple is just a regular golden apple with the purply enchantment overlay. If you edit the skin of a golden apple, that design will still be there when you get an enchanted apple.

Starting with a resource pack created by the Resource Pack Tutorial, inside the textures folder, add a folder named **items**

Then, copy over the apple_golden.png from the Vanilla Resource Pack and edit that however you want. 

When you load the resource pack like usual and give yourself both a golden apple and an enchanted apple, that should have your design on it.

I hope that answers your question. If it doesn't, please let me know.

I am closing this ticket for now, but I will be glad to open it back up again if you want more help.
