### ISSUE TITLE
[Gametest] Dimension.getEntities() returns an invalid/null entity

### ISSUE THREAD

**Issue by EvanHite** [MicrosoftDocs/minecraft-creator#261]
I was trying to use getTag() but got an error that the function couldn't be called, upon further investigation it looks to be easy to recreate and I confirmed none of the entities properties are initialised or callable
The [docs ](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/dimension#getentities) show that it should be returning correctly 

**Instructions on how to recreate:**
_Video instructions:_
[MinecraftClip.mp4](https://cdn.discordapp.com/attachments/854033525546942464/946829649604919306/Minecraft_2022-02-25_12-01-59.mp4)
_Breakdown:_
download both the mcworld and gametest and load up the world
press the 3 labeled "TP" commands in this order: Tp1 - Tp2 -Tp3
this will load and unload the 2 entities in the world.

**DOWNLOADS**
gametest:
[bugGT.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/8143414/bugGT.zip)
McWorld:
[bugWorld.mcworld](https://cdn.discordapp.com/attachments/854033525546942464/946833018763481088/bugWorld.mcworld)

**Comment by ConsoleTerm** [comment]
Thank you for your report, this issue is not current, could you please close this issue? Thank you
