### ISSUE TITLE
minecraft:throwable may be inaccurate

### ISSUE THREAD

**Issue by SYUMJOBA** [MicrosoftDocs/minecraft-creator#263]
In simple terms. I'm trying to make things work in several ways for the "throwable" component, but it looks like something's missing. The game is not giving any error, but it is definitely not making use of the throwing component. 

I'm afraid there's some extra needed with the component for it to work, or some arrangement isn't really precise.
Thanks for your time

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c558b-12b6-118c-bc08-fb609226ac05
* Version Independent ID: 73d4ea82-1e03-85a6-0580-6a556cd85f30
* Content: [Item Documentation - minecraft:throwable](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_throwable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_throwable.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_throwable.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
