### ISSUE TITLE
[Gametest] using addItem while the player has selected the first hotbar slot doesn't add the item.

### ISSUE THREAD

**Issue by amon28** [MicrosoftDocs/minecraft-creator#264]
**Describe the bug**
My code adds an item to the player's inventory but when a player's inventory has no items and the first hotbar is selected it doesn't add the item in the inventory. Selecting the 2nd slot and repeating the process will add the item.

**To Reproduce**
1. Use this code in this screenshot
2. select first hotbar slot
3. break a block

**Expected behavior**
should add the item in the inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/22851168/155904706-7cdfe81f-f387-4307-93d0-520a72d095ed.png)

**Desktop (please complete the following information):**
 - OS:Windows 10

**Comment by ConsoleTerm** [comment]
I know this was problem since 1.19.0 > 1.19.20, can u test it again?
