### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Amayamaize2022** [MicrosoftDocs/minecraft-creator#265]
Hey I'm trying to make a pack and everything's worked up until me trying to change netherite textures, the png it named right and idk what to do

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
Hi, @[Amayamaize2022](https://github.com/Amayamaize2022), can you send me a zip of your resource pack so I can take a look? Thanks!

**Comment by docsbryce** [comment]
Hi, @Amayamaize2022, I'm going to close this issue for now. Feel free to reopen this issue if it persists. I'm happy to take another look in the future. Thank you!
