### ISSUE TITLE
Sidebar URLs lead to 404

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#266]
**Describe the bug**
Clicking on some entity components in the sidebar leads to 404

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/'
2. Expand 'AI Goals' in sidebar
3. Click on 'behavior.move_indoors' or 'behavior.move_to_poi'
4. See error 404

**Expected behavior**
A proper documentation page should show up.

**Comment by JDHeaden** [comment]
Change is made and staged for review.
