### ISSUE TITLE
Multiple components document event field as string instead of an object

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#267]
**Describe the bug**
Multiple entity component pages document 'event' field as string type instead of an object.

Affected pages:
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_attack_cooldown
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_equippable
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_genetics
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_giveable
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_leashable
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_tameable
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_tamemount

**To Reproduce**
1. Go to provided URL
2. Compare example with any vanilla example
3. See error

**Expected behavior**
Example should be valid.

**Comment by docsbryce** [comment]
These corrections are made and staged for review.
