### ISSUE TITLE
Incorrect offset for the vanilla example

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#268]
**Describe the bug**
A number of entity component pages have incorrect offsets when referencing a part of vanilla file.

Affected pages:
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_annotation_break_door
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_annotation_open_door
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_breathable
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_burns_in_daylight
 - https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_follow_target_captain

**To Reproduce**
1. Go to the URL
2. Look at the vanilla example
3. See error

**Expected behavior**
Vanilla example should properly show a full example of vanilla component.

**Comment by JDHeaden** [comment]
Corrections are made. Staged for review.
