### ISSUE TITLE
Various example issues

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#269]
**Describe the bug**

| **Issue**                                                                             | **Page**                                                                                                                                                |
|---------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
| `Item` should be `item` since JSON is case sensitive                                  | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_boostable             |
| Example uses unsupported `jsonc` syntax                                               | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_environment_sensor    |
| Missing `items` value                                                                 | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_giveable              |
| Example is not really useful                                                          | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_inside_block_notifier |
| Missing values for `on_activate` and `on_deactivate`                                  | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_rail_sensor           |
| `autoRejectItems` should be snake case and `feed_items` should be an array of objects | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_tamemount             |
| Missing `table` value                                                                 | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_trade_table           |
| `on home` should be `on_home`                                                         | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_go_home                     |
| Bad indentation in example                                                            | https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_hurt_by_target              |

**Comment by docsbryce** [comment]
These corrections are made and staged for review.
