### ISSUE TITLE
EntitySkinIdComponent Class ID error

### ISSUE THREAD

**Issue by smell-of-curry** [MicrosoftDocs/minecraft-creator#274]
On the EntitySkinIdComponent Class, in the ID property it says this Id should always be "minecraft:variant"
This is wrong because its the skinid component

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f00ddc-54f7-bba6-0a36-9895fa1bd3cb
* Version Independent ID: 13f00ddc-54f7-bba6-0a36-9895fa1bd3cb
* Content: [mojang-minecraft.EntitySkinIdComponent Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/entityskinidcomponent)
* Content Source: [creator/ScriptAPI/mojang-minecraft/EntitySkinIdComponent.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/EntitySkinIdComponent.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by ConsoleTerm** [comment]
This issue is fixed, u can close this issue

**Comment by ConsoleTerm** [comment]
Hello, @smell-of-curry is this issue still current? It was fixed as far as i know? Do you have more information please? If not please close this issue, Thank you
