### ISSUE TITLE
[GameTest] EntityIterator is not iterator

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#275]
[EntityIterator](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/entityiterator)

Method `getPlayers().next` is undefined.
There is only `getPlayers()[Symbol.iterator]` method.
We have to do `getPlayers()[Symbol.iterator]().next().value`.

So what `getPlayers()` returns is an iterable collection.

I would name it "EntityIterableCollection" instead of "EntityIterator".

I have created a pull request.
https://github.com/MicrosoftDocs/minecraft-creator/pull/460
1. `EntityIterator` implements `Iterable<Entity>` instead of `Iterator<Entity>`.
2. Just remove `then()`.
3. `PlayerIterator` is the same.

[Iterable](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es2015_iterable_d_.iterable.html)
[Iterator](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es2015_iterable_d_.iterator.html)

**Comment by Worldwidebrine** [comment]
```js
import { world } from "mojang-minecraft";
const ow = world.getDimension("overworld");
world.events.chat.subscribe(() => {
    const entities = ow.getEntities();
    for (const e of entities) {
        e.runCommand("say test");
    }
    ow.runCommand("say again");
    for (const e of entities) {
        e.runCommand("say test");
    }
});
```
> [Steve] test
[Armor Stand] test
[Script Engine] again
[Steve] test
[Armor Stand] test

Please
Please don't call it "iterator"

**Comment by Worldwidebrine** [comment]
https://github.com/MicrosoftDocs/minecraft-creator/pull/460

**Comment by Worldwidebrine** [comment]
I made a mistake.
Actually the iterator returned by `[Symbol.iterator]()` is not iterable.
```js
const itr = world.getPlayers()[Symbol.iterator]();
for (const p of itr) {
  console.log(p.name);
}
```
so the doc is corrent.
`[Symbol.iterator]()` returns `Iterator`

**Comment by ConsoleTerm** [comment]
This problem is still isn´t fixed for Generator yield from syntax, object is still not IterableIterator, if i am correct

**Comment by ConsoleTerm** [comment]
Most of the Native operators have been replaced by a regular field, that report is no longer current, Thank you for reporting, but this issue can be closed now.
