### ISSUE TITLE
Suggested feature for the Block class in gametest

### ISSUE THREAD

**Issue by Zelioz273** [MicrosoftDocs/minecraft-creator#276]
The Block class for mojang-minecraft module should have a method to retrieve the current block as an item. Or at least change the permutation class to have a data value so blocks can be easily converted to items. The current way would be creating a method for every group of blocks and looking through their tags specifically to tell if a stone block is andesite or granite, then telling if a log is acacia or oak. It'd be much easier to just use data values like /give does in game.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd4d97a-2534-1f7f-89d8-f018bc8db317
* Version Independent ID: 05fe59d9-8067-38bb-16e3-0f4452287c96
* Content: [mojang-minecraft.Block Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/block)
* Content Source: [creator/ScriptAPI/mojang-minecraft/Block.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/Block.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by ConsoleTerm** [comment]
the system of numerical data designations for blocks has already been completely abandoned, and it is being abandoned for items as well. as for converting blocks to items or permutations, this is now available in the API, Thank you for your suggest, you can close the issue now.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
