### ISSUE TITLE
Get rid of the resilience from method Player.setVelocity() 

### ISSUE THREAD

**Issue by d4rkOfficial** [MicrosoftDocs/minecraft-creator#277]
As a matter of fact, when Method Player.setVelocity applied to a client player, a resilience happens, which prevents us to give particular player an instant velocity and move to a expected place. However when it comes to an entity which is not a client player, including simulated player, the method runs well. I hope that it could be working well on client players soon. That's all.

**Comment by ConsoleTerm** [comment]
This method runs also on client players, i have done some tests and velocity was applied always on player, there was problem with client side, client side didn´t know about velocity change.
Player.prototype.setVelocity is disabled on players.
U can close this issue.
