### ISSUE TITLE
Docs Missing

### ISSUE THREAD

**Issue by D4rKCN** [MicrosoftDocs/minecraft-creator#278]
As mentioned, since the EntityHurtEvent was updated, the development documentation of the gametest framework has not changed for a long time.
Such as EntityHurtEvent, leverActivateEvent, and other deleted or renewed contents that mentioned in the game update message have not been recorded in the docs.
If not solved as sooner as possible, it could lead to big trouble. That's all.

**Comment by mammerla** [comment]
We may not always be day-and-date up to date with the latest beta APIs - but you can check out the change logs for a basic summary of new APIs: https://feedback.minecraft.net/hc/en-us/categories/115000410252-Knowledge-Base

(but there should be basic docs for EntityHurt/LeverActivate now)

**Comment by D4rKCN** [comment]
> We may not always be day-and-date up to date with the latest beta APIs - but you can check out the change logs for a basic summary of new APIs: https://feedback.minecraft.net/hc/en-us/categories/115000410252-Knowledge-Base
> 
> (but there should be basic docs for EntityHurt/LeverActivate now)


To be frank, it doesn't a big deal for me as long as **basic summaries of new APIs** there is.

As a matter of fact, most of we add-on-creators are able to figure out what's new with a document-missing update by doing something like:

```js
import * as mc from "mojang-minecraft";
mc.world.events.entityHurt.subscribe( CallBack => {
   for (let property of CallBack) {
      let name = property;
      let type = typeof property;
      let value = CallBack.property;
      mc.world
         .getDimension("minecraft:overworld")
         .runCommand(`me ${name} ${type} ${property}`);
   }
});
```
Emm... for half a week not updating docs, I guess you were all busy with new pocket UIs? Whatever it is, thanks for your hard work.
