### ISSUE TITLE
[GameTest Bug]

### ISSUE THREAD

**Issue by RavinMaddHatter** [MicrosoftDocs/minecraft-creator#279]
**Describe the bug**
Game test framework hard crashes to desktop when invalid arguments are sent to block.permutation.getProperty()

**To Reproduce**
in a javascript file subcribe to block place event and add the following lines of code

`
world.events.blockPlace.subscribe((eventData) => {
    let tempPerm=eventData.block.permutation.getAllProperties()
    console.warn(tempPerm)//works
    
    for(var i =0; i<tempPerm.length;i++){
        console.warn(tempPerm[i])//gives me an object
        console.warn(eventData.block.permutation.getProperty(tempPerm[i]))//hard crashes the game and doesnt print anything to the console also doesnt write console log of previous tasks (ie the file write never completes and the content log in the logs folder is empty.
    }
}
`

**Expected behavior**
Game test framwork prints an error to the log stating that the argument type object is not a valid input parameter to method getProperty

**actual behavior**
Minecraft closes
Content log does not write to disk

**Comment by ConsoleTerm** [comment]
This bug was fixed some months ago, thank you for you to reporting this issue, you can close it.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
