### ISSUE TITLE
[Improvement] [GameTest] Load chunk function

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#28]
**A function which takes an X,Z pair and loads the chunk at that location, generating it if required**

Not sure how the internal of this would work, perhaps it could return a chunk class which can then be manually closed, otherwise it will keep ticking until the server stops. This could be represented in game as ticking areas but not editable by in game users.

**Comment by kakinnun** [comment]
Closing the oldest GameTest feedback issues. I've collated these for feedback and consideration internally. Closing these issues will save us from having to try and keep these issues up to date. :)
