### ISSUE TITLE
[Gametest] nameTag property breaks vanilla commands in World

### ISSUE THREAD

**Issue by Visual1mpact** [MicrosoftDocs/minecraft-creator#280]
**Describe the bug**
Modifying the property nameTag from Player Class breaks the functionality of vanilla commands while loaded in the world.

**To Reproduce**
1. Write a script using any event. beforeChat Event would be a good test.
2. Get player object then modify the property nameTag of that player. Example: ```player.nameTag = `§4[§6${Admin}§4]§r §7${player.name}§r`;```
3. Refresh the player object with the new nameTag in the world by making the player do something such as using player.teleport() so the new nameTag takes effect.
4. Load your world with your test script and be sure the new nameTag has taken effect. Then try to use any vanilla commands. For example: ```/tp Visual1mpact```

**Expected behavior**
Visual1mpact has been teleported to Visual1mpact
You have been teleported to Visual1mpact

**Erroneous behavior**
No target found

**Desktop (please complete the following information):**
 - OS: Windows 10
 

**Smartphone (please complete the following information):**
 - Device: Moto G Stylus 5G
 - OS: Android 11

**Demonstration**

![nameTag](https://user-images.githubusercontent.com/97915078/159123349-0dce1228-eacb-4be3-9cf6-ebaa2c780561.gif)

**Comment by tryashtar** [comment]
https://minecraft.fandom.com/wiki/Commands/team
