### ISSUE TITLE
Repeating information.

### ISSUE THREAD

**Issue by DarkTaarna84** [MicrosoftDocs/minecraft-creator#285]
In the "Entity Definition" and "Entity Definition Example" The text is repeated. This is confusing for first time learners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62528cbd-cb13-b8f2-290e-af4440daa504
* Version Independent ID: 2fe2addc-b69b-fc50-c13f-d7ea7cfac7ad
* Content: [Animation Documentation - Getting Started](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/animationsreference/examples/animationgettingstarted#feedback)
* Content Source: [creator/Reference/Content/AnimationsReference/Examples/AnimationGettingStarted.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AnimationsReference/Examples/AnimationGettingStarted.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
Staged for next release.
