### ISSUE TITLE
invalid example

### ISSUE THREAD

**Issue by Kybomaster** [MicrosoftDocs/minecraft-creator#287]
"minecraft:on_use": {
        "on_use": {
          "event": "event_name",
          "target": "self"
        }
      }

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: aa4bba1d-2a63-d0ad-5153-50aa45ff3b76
* Version Independent ID: 8b22c993-1610-c17d-5348-aa8592cf5883
* Content: [Item Documentation - minecraft:on_use](https://docs.microsoft.com/ru-ru/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_on_use)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_on_use.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_on_use.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
Looks like this has been updated. Thanks for reporting! https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_on_use
