### ISSUE TITLE
ScriptAPI Documentation doesn't mark Vector static methods

### ISSUE THREAD

**Issue by MajestikButter** [MicrosoftDocs/minecraft-creator#288]
Vector static methods aren't marked as static so it's very confusing to try to understand this page. The API treats the methods from add onwards as static in-game but the docs don't explain that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f893d9-0b43-d55d-d4e8-8883c7586050
* Version Independent ID: c0f893d9-0b43-d55d-d4e8-8883c7586050
* Content: [mojang-minecraft.Vector Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/vector)
* Content Source: [creator/ScriptAPI/mojang-minecraft/Vector.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/Vector.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by JakeShirley** [comment]
Good call, I don't think we are calling out any static methods here.

**Comment by JakeShirley** [comment]
cc @mammerla

**Comment by ConsoleTerm** [comment]
This issue can be closed now.
