### ISSUE TITLE
1.18 seed parity

### ISSUE THREAD

**Issue by gerrybrano** [MicrosoftDocs/minecraft-creator#289]
As of 1.18 Bedrock and Java have seed parity so long as the seed number is 9 or fewer characters. This change should be reflected in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8293cbae-4896-4d03-9764-09e23027db99
* Version Independent ID: 6ada8e59-a330-e8ca-5967-8c5dc67db846
* Content: [Differences Between Minecraft Bedrock Edition and Minecraft Java Edition](https://docs.microsoft.com/en-us/minecraft/creator/documents/differencesbetweenbedrockandjava)
* Content Source: [creator/Documents/DifferencesBetweenBedrockAndJava.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DifferencesBetweenBedrockAndJava.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
I removed the reference to seeds in "World Differences." I'll close this issue for our next release in April. Thanks for reporting!

**Comment by docsbryce** [comment]
This is now live: https://docs.microsoft.com/en-us/minecraft/creator/documents/differencesbetweenbedrockandjava
