### ISSUE TITLE
[Improvement] [GameTest] Register custom commands

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#29]
**Register custom commands with the ability to pass a function to handle usage**

A few specific things which would be important I feel:

- Able to register at any time and per-user (pseudo-permission based systems could be achieved with this)
- Able to unregister a command
- Able to register custom enums as part of the command
- Allow some of the special types such as player and coordinates to be field options
  - Those fields should ideally be presented as the correct type, eg. `~ ~ ~` would be received as a Location

**Comment by kakinnun** [comment]
Closing the oldest GameTest feedback issues. I've collated these for feedback and consideration internally. Closing these issues will save us from having to try and keep these issues up to date. :)
