### ISSUE TITLE
1.18 Seed Parity

### ISSUE THREAD

**Issue by gerrybrano** [MicrosoftDocs/minecraft-creator#290]
As of 1.18, Bedrock and Java have seed parity so long as the seed number is 9 or fewer characters. This is not reflected in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac49a34-4319-3f2b-87f9-44dbe47a77c5
* Version Independent ID: 2ad52a25-afff-b9d5-036b-fdf08574919e
* Content: [Survival Spawn Creation](https://docs.microsoft.com/en-us/minecraft/creator/documents/survivalspawncreation)
* Content Source: [creator/Documents/SurvivalSpawnCreation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/SurvivalSpawnCreation.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JDHeaden** [comment]
Change is made.
