### ISSUE TITLE
[GameTest][feature] function* subscribe TickEventSignal

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#291]
Re:
> This is good feedback! We definitely know that there is more work that needs to be done in this area - both in terms of more restrictions to prevent script from impacting broader game execution, but also in terms of providing more tools to run things on the background to better balance the performance characteristics of different devices.

_Originally posted by @mammerla in https://github.com/MicrosoftDocs/minecraft-creator/issues/240#issuecomment-1034047150_

## Update:
**Since v1.19.10.20, `await null;` behaves just like my `yield;`.**

## Original:
I've come up with `await null;` but now I think it can still be better.
I think it's possibly not good to add a timeout every tick.
Instead, let a `tool` add the timeout dynamically.
[JEP 425: Virtual Threads](https://openjdk.java.net/jeps/425)

Note that we still will need Coroutine even if we have `Worker`(or client scripting).
`Worker`s are for calculating. They won't help preventing server lag during I/O, which in Minecraft is getting/setting blocks and entities.
Green Thread is for I/O.
We need both Green Thread and `Worker`(or client scripting).

JS's original coroutine(Green Thread) `await` is broken in GameTest (**fixed in v1.19.10.20**), but coroutine can also be implemented with iterators.

## My impl:
<details>
<summary>

#### Featured version
`yield;`=`java.lang.Thread.yield();`=`std::this_thread::yield();`;
`yield NEXT_TICK;`="await for the next tick";
`yield ENQUEUE_NEXT_TICK;`="await for any other tick"
</summary>

Code before the first `yield;` will now be processed syncly by `thread();`.
```javascript
//@ts-check
"use strict";

import { world } from "mojang-minecraft";

class YieldEnum {
    constructor() {
        if (Object.isFrozen(YieldEnum)) {
            return YieldEnum.ENQUEUE;
        }
    }
    /** @type {YieldEnum} */
    static ENQUEUE = new String("YieldEnum");
    /** @type {YieldEnum} */
    static NEXT_TICK = new String("YieldEnum");
    /** @type {YieldEnum} */
    static ENQUEUE_NEXT_TICK = new String("YieldEnum");
}
for (const key of Object.keys(YieldEnum)) {
    const value = YieldEnum[key];
    if (value == "YieldEnum" && value !== "YieldEnum") {
        YieldEnum[key] = new YieldEnum
    }
}
Object.freeze(YieldEnum);

/**
 * @typedef {Generator<YieldEnum, void, void>} ThreadRunnableContext
 * @typedef {() => ThreadRunnableContext} ThreadRunnable
 * @typedef {IteratorResult<YieldEnum, never>} ThreadRunnableYield
 */

const /** @type {WeakSet<ThreadRunnableContext>} */runnables = new WeakSet;
const /** @type {ThreadRunnableContext[]} */tasks = new Array;
const /** @type {ThreadRunnableContext[]} */nextTickTasks = new Array;
const /** @type {ThreadRunnableContext[]} */tmpTasks = new Array;

const { ENQUEUE, ENQUEUE_NEXT_TICK, NEXT_TICK } = YieldEnum;

/**
 * @typedef {YieldEnum | any} TaskResult
 */
const processTask_MACRO = `${function (/** @type {ThreadRunnableContext} */task, /** @type {number} */index) {
    try {
        const result = task.next();
        if (result.done) {
            return null;
        }
        const { value } =  /** @type {ThreadRunnableYield} */(result);
        switch (value) {
            case NEXT_TICK:
                nextTickTasks.unshift(task);
                break;
            case ENQUEUE_NEXT_TICK:
                tmpTasks.push(task);
                break;
            default:
                "use strict";
                return ENQUEUE;
        }
        return value;
    } catch (e) {
        if (e instanceof YieldEnum) {
            return null;
        }
        return e;
    }
}}`;
function evalTaskProcessings(/** @type {any} */obj) {
    const argName = "obj";
    const ctx = {
        YieldEnum,
        ENQUEUE, ENQUEUE_NEXT_TICK, NEXT_TICK,
        tasks,
        nextTickTasks,
        tmpTasks
    };
    (Function(`{${Object.keys(ctx).join(",")}}`, argName, Object.keys(obj).map((key) => `${argName}["${key}"]=${obj[key]}`).join(";")))(ctx, obj);
    return obj;
}
const { processTask, processTaskSplice } = /** @type {{ processTask: (task: ThreadRunnableContext) => TaskResult; processTaskSplice: (task: ThreadRunnableContext, index: number) => TaskResult; }} */(evalTaskProcessings({
    processTask: processTask_MACRO.replace("\"use strict\"", "tasks.unshift(task)"),
    processTaskSplice: processTask_MACRO.replace("\"use strict\"", "tasks.splice(index, 0, task)")
}));

let unsubscribed = true;
const redispatcher = () => {
    if (unsubscribed) {
        return;
    }
    const ms = Date.now();
    let nextTickTaskTaskCount = 0;
    let index = nextTickTasks.length;
    for (let i = index; i > 0; i--) {
        index--;
        const task = nextTickTasks[index];
        switch (processTask(task)) {
            case ENQUEUE:
                nextTickTaskTaskCount++;
                break;
            case NEXT_TICK:
                index++;
                nextTickTasks[index] = null;
                break;
        }
    }
    nextTickTasks.length = index;
    with_timeout: {
        with_prefix: {
            const prefixLength = nextTickTaskTaskCount;
            if (prefixLength === 0) {
                break with_prefix;
            }
            while (tasks.length > prefixLength) {
                const task = tasks.pop();
                processTaskSplice(task, prefixLength);
                if (Date.now() - ms < 32) {
                    continue;
                }
                break with_timeout;
            }
        }
        do {
            const task = tasks.pop();
            processTask(task);
            if (tasks.length === 0) {
                break;
            }
        } while (Date.now() - ms < 32)
    }
    for (let i = tmpTasks.length - 1; i >= 0; i--) {
        tasks.push(tmpTasks[i]);
        tmpTasks[i] = null
    }
    tmpTasks.length = 0;
    if (tasks.length === 0 && nextTickTasks.length === 0) {
        unsubscribed = true;
        world.events.tick.unsubscribe(redispatcher)
    }
};

export default function thread(/** @type {ThreadRunnable} */task) {
    const runnableContextIterator = task();
    if (runnables.has(runnableContextIterator)) {
        throw new Error("double start");
    }
    runnables.add(runnableContextIterator);
    const result = processTask(runnableContextIterator);
    if (result === null) {
        return;
    }
    if (!(result instanceof YieldEnum)) {
        throw result;
    }
    if (unsubscribed) {
        unsubscribed = false;
        world.events.tick.subscribe(redispatcher)
    }
};
export { thread, YieldEnum as ThreadYieldEnum };
```
</details>
<details>
<summary>

#### Simple version
Only `yield;`
</summary>

```javascript
import { world } from "mojang-minecraft";

const tasks = new Array;

let subscribed = false;
const listener = function () {
    const ms = Date.now();
    while (Date.now() - ms < 32) {
        const task = tasks.pop();
        if (task.next().done) {
            if (subscribed && tasks.length === 0) {
                subscribed = false;
                world.events.tick.unsubscribe(listener);
                return;
            }
            continue
        }
        tasks.unshift(task)
    }
};

function thread(task) {
    tasks.unshift(task());
    if (!subscribed) {
        subscribed = true;
        world.events.tick.subscribe(listener)
    }
}
export { thread };
```
</details>

`Date.now() - ms < 32` is just an example. #296
It should be replaced with a better C++ condition actually related to the ticking of game, which is impossible to implement using only GameTest API.

### Usage:
```javascript
//@ts-check
"use strict";
import { world } from "mojang-minecraft";
import { thread, ThreadYieldEnum } from "./thread.js";

let id = 0;
let showtick = false;
world.events.chat.subscribe(() => {
    thread(function* () {
        const name = `thread${++id}`;
        for (let i = 32767; i > 0; i--) {
            yield;
            console.warn(`${name} ${i}`)
        }
        id--
    });
    if (showtick) {
        return;
    }
    thread(function* () {
        showtick = true;
        while (id > 0) {
            yield ThreadYieldEnum.NEXT_TICK;
            console.warn("tick")
        }
        showtick = false
    })
});

thread(function* () {
    console.warn("current tick");
    for (let i = 100; i > 0; i--) {
        yield ThreadYieldEnum.NEXT_TICK;
    }
    console.warn("100 ticks later")
});
thread(function* () {
    console.warn("current tick");
    for (let i = 0; i < 10; i++) {
        yield ThreadYieldEnum.NEXT_TICK;
        console.warn(`tick ${i + 1}`)
    }
});
thread(function* () {
    console.warn("current tick");
    yield ThreadYieldEnum.ENQUEUE_NEXT_TICK;
    console.warn("another tick than current tick")
});
```
```javascript
thread(function* () {
  while (true) {
    yield;
    for (const player of world.getPlayers()) {
      const { x, y, z } = player.location;
      const [X, Y, Z] = [Math.floor(x), Math.floor(y), Math.floor(z)];
      for (let x = -16; x !== 16; x++) {
        for (let y = -16; y !== 16; y++) {
          for (let z = -16; z !== 16; z++) {
            yield;
            try {
              player.runCommand(`setblock ${X + x} ${Y + y} ${Z + z} water 0 keep`);
            } catch (e) {
            }
          }
        }
      }
      break
    }
  }
});
```

**Comment by D4rKCN** [comment]
```kotlin
this is "a good idea";
```

**Comment by Worldwidebrine** [comment]
It should be possible to also implement `yield true;`="await for the next tick".
Subscribe tick event for next 4 ticks:
```js
for (let i = 0; i < 4; i++) {
    yield true;
    console.warn(`This is tick${i}`);
}
```

**Comment by D4rKCN** [comment]
> It should be possible to also implement `yield true;`="await for the next tick".
> Subscribe tick event for next 4 ticks:
> ```js
> for (let i = 0; i < 4; i++) {
>     yield true;
>     console.warn(`This is tick${i}`);
> }
> ```

Why not 'setTimeout()'

**Comment by Worldwidebrine** [comment]
> It should be possible to also implement `yield true;`="await for the next tick". Subscribe tick event for next 4 ticks:
> 
> ```js
> for (let i = 0; i < 4; i++) {
>     yield true;
>     console.warn(`This is tick${i}`);
> }
> ```

My new impl with this new feature is now in `<details></details>`

**Comment by Worldwidebrine** [comment]
Now `yield NEXT_TICK;`="await for the next tick" and `yield ENQUEUE_NEXT_TICK;`="await for any other tick".
NEXT_TICK: equals to tick event; if use too many in one tick, the next tick may lag.
ENQUEUE_NEXT_TICK: the code just shouldn't run in the current tick; suitable for awaiting in-game changes that could happen not very soon.

Note that duplex communication is possible: `yield` can not only "return" a value from `function*` to `next().value`, the but also receive an argument from `itr.next(arg);` to `console.log(yield);`.
This impl should work also for other events but I think it's necessary only for tick event

**Comment by nobu-sh** [comment]
I am pretty positive something similar to this can be achieved asynchronously. From my understanding from the way QuickJS was implemented, it appears the event loop dumps 1 extra task per frame.

So:
```js
world.events.blockBreak.subscribe(async (event) => {
  for await (const index of Array(50).fill(undefined).map((_, i) => i)) {
    console.warn(index)
  }
})
```

I may be mistaken, however;

**Comment by Worldwidebrine** [comment]
> I am pretty positive something similar to this can be achieved asynchronously. From my understanding from the way QuickJS was implemented, it appears the event loop dumps 1 extra task per frame.
> 
> So:
> 
> ```js
> world.events.blockBreak.subscribe(async (event) => {
>   for await (const index of Array(500).fill(undefined).map((_, i) => i)) {
>     console.warn(index)
>   }
> })
> ```
> 
> I may be mistaken, however;

@nobu-sh What are you talking about? Is there any `tick` thingy involved in your code?
#240

**Comment by nobu-sh** [comment]
> > I am pretty positive something similar to this can be achieved asynchronously. From my understanding from the way QuickJS was implemented, it appears the event loop dumps 1 extra task per frame.
> > So:
> > ```js
> > world.events.blockBreak.subscribe(async (event) => {
> >   for await (const index of Array(500).fill(undefined).map((_, i) => i)) {
> >     console.warn(index)
> >   }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I may be mistaken, however;
> 
> @nobu-sh What are you talking about? Is there any `tick` thingy involved in your code? To see if it's useful, you need to subscribe the real tick event and run multiple async functions in parallel. **See #240** Only one task. You really think that 1 task per tick is enough even though it is shared? Also, `/reload` doesn't clear the task queue of `async`. Or, are you suggesting that I replace my `tick.subscribe(redispatcher)` with `await null;`? Yes, I can, but I don't want to. This is a feature request. I think tick event is more readable to Minecraft developers. Again, `/reload` doesn't clear the task queue of async.

I wasn't necessarily stating that this is a good implementation for your use case, nor was I stating it is a multi threading options. This is simply just a non blocking way to execute a loop with the sacrifice of speed. You should keep in mind however you are suggesting we implement a threading option in a language that is meant to be single threaded.

Either way I was not suggesting you change anything nor questioning your authority/code. Simply was adding to the conversation.

**Comment by Worldwidebrine** [comment]
Our scripts are processed syncly between ticks. To prevent blocking, we have to suspend our functions if too long, right?

Candidates:
1. Aync game API.
2. Let scripts use another thread.
3. Let the GameTest Framework suspend scripts.
4. Everything still blocks but let scripts use `Thread.yield();`.

Disadvantages:
1. Scripts have to await for many things.
2. Scripts have to await for many things.
3. Many unexpected things may happen. Scripts will also need something like Java `synchronized` for preventing suspending.
4. Very verbose. Scripts can use `yield*` but functions not `function*` still exist.

I guess impl for 4 is the easiest one and the only one can have impl without modifying the GameTest Framework.

**Comment by D4rKCN** [comment]
> Our scripts are processed syncly between ticks. To prevent blocking, we have to suspend our functions if too long, right?
> 
> Candidates:
> 1. Async game API.
> 2. Let scripts use another thread.
> 3. Let the GameTest Framework suspend scripts.
> 4. Everything still blocks but let scripts use `Thread.yield();`.
> 
> Disadvantages:
> 1. Scripts have to await for many things.
> 2. Scripts have to await for many things.
> 3. Many unexpected things may happen. Scripts will also need something like Java `synchronized` for preventing suspending.
> 4. Very verbose. Scripts can use `yield*` but functions not `function*` still exist.
> 
> I guess impl for 4 is the easiest one and the only one can be made without modifying the GameTest Framework.
> Btw, method `runCommandAsync` has been added in the latest beta. 1 and 2 are also possible.

## ヾ(๑╹ヮ╹๑)ﾉ”
We have not only `yield*` but also Function Coritization.

Here is an example in which it achieves the effect of executing commands once per second, like command blocks do:

```js
import { world } from "mojang-minecraft";

let i = 0;

function fun() {
    i++;
    if (i < 20) return fun;
    else hi();
}

function hi() {
    i = 0;
    world.getDimension("overworld")
        .runCommand("say hello");
}

let f = fun;
world.events.tick.subscribe(() => {
    f = f();
});

```

If simply modified, it can really realize `setTimeout`. For instance, bind the timer and commands/function to the properties/methods of players or entities. And use event listening as trigger, like `beforeChat` or `entityHurt`.

Another funnier version:
```js
import { world } from "mojang-minecraft";

let i = 0;
let hi;
//VERY VERY LOOOOOONG CHAIN OF 'f=>'
let fun = f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=>f=> {
    world.events.runCommand("say hello");
    hi = fun();
}

hi = fun();
world.events.tick.subscribe(() => {
    hi = hi();
});
```

i.e. There are always more ways than difficulties.

**Comment by Worldwidebrine** [comment]
@D4rKCN
I'm talking about code in one tick.
Your code takes ticks. That's not the point.

**Comment by Worldwidebrine** [comment]
**Note that v1.19.10.20 has fixed JS async.**
But I still think the `function*` tick event listener is a good idea.
So I'm not going to close it until I get official response.
