### ISSUE TITLE
[GameTest] Filterting out unknown blocks from MinecraftBlockTypes

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#292]
**Is your feature request related to a problem? Please describe.**
When I was trying to get a random block from the `MinecraftBlockTypes.getAllBlockTypes()` method and it often returns a block type that is available only via education edition setting or something normally unobtainable *(like reserved6)* which is then an update block in the game.

**Describe the solution you'd like**
Some way to filter out any specific group of blocks which might not be always functional in the world like education edition blocks. Maybe a parameter for the function would be a good idea.

**Describe alternatives you've considered**
Obvious one is just to create an array of block names that would cause the issue and generate a new random block type again if the name is contained in the array, however this is far less efficient than a native way to do it would be.

**Additional context**
The same could also apply to experimental blocks as not always the experimental gameplay like "Wild Update" is enabled and it still returns those blocks like froglight too, even though I don't have the options enabled and it shows as update blocks.

**Comment by ConsoleTerm** [comment]
This issue was fixed some betas ago, u can close this issue, same for items

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
