### ISSUE TITLE
A crash occurs when the damage command is executed in the gametest-framework scripts.

### ISSUE THREAD

**Issue by d4rkOfficial** [MicrosoftDocs/minecraft-creator#293]
## Bug Description

Since **BETA1.18.20.27** this bug has existed, and It is still there in **BETA1.18.30.32**

```js
import { world } from "mojang-minecraft";
//This causes crash.
world.events.entityHit.subscribe((evt) => {
      evt.hitEntity.runCommand("damage @s 1" )
})
//This causes crash, too.
world.events.entityHurt.subscribe((evt) => {
      evt.hurtEntity.runCommand("damage @s 1")
 })
```
At first I thought it must be something wrong with my codes. However, After many troubleshooting, I come to the following conclusion:

- When execute ```/damage``` command in **EntityHitEvent**, as well as **EntityHurtEvent**, the crash is **100%** to happen.

- When execute ```/damage``` command in other event listener, the crash will happen inexplicably and probabilistically, but not hundred percent.

## Expected behavior
1. Run the command successfully.
2. Delay the command execution until the entity's build-in injury cooling time ends.
3. Return an error message indicating that the command fails but does not cause the game program to crash.

## Additional context
I hope that a method can be designed to cause damage to entities in Gametest-Framework script, whose effect is similar to the '/damage' command, but it can have more functions, such as to customize an invincible time for an entity after an injury is caused. So that we can less rely on commands.

~~(⁎⚈᷀᷁ᴗ⚈᷀᷁⁎)~~

**Comment by D4rKCN** [comment]
In addition, each platform, beta or preview has this bug.

**Comment by ConsoleTerm** [comment]
This is not bug, also is not related anymore,
as u can see it crashes, because its infinite cycle, /damage command take damage to entity so entityHit and entityHurt events are fired again, and again. Now we can use runCommandAsync only so this is not possible anymore, runCommandAsync runs commands in the new tick to prevent this behavior.
Can u close this issue?

**Comment by ConsoleTerm** [comment]
IF u want to take hearts off, u can use EntityHealthComponent now

**Comment by d4rkOfficial** [comment]
> IF u want to take hearts off, u can use EntityHealthComponent now

emm actually i wanto make knockbacks with a shorter interval instead of taking hearts off, which is used to mimic the knockback system of pvp servers(At first, they have shorter attack cooldown). yet i couldnt find a suitable scripting interface to implement this function, so I took advantage of the feature(bug, maybe?) of the game itself to break the built-in cooldown of the attack by causing higher damage then the last one.

And I am eagerly expecting for an interface to remove or modify player's attack cooldown.


For example:
```
entityHit.subscribe((evt) => {
  evt.attackCD = 0
})
//seems like:
beforeChat.subscribe((evt) => {
  evt.cancel = true
})
```

or as player's prototype property
```
steve.attackCD = 0
```

**Comment by d4rkOfficial** [comment]
> IF u want to take hearts off, u can use EntityHealthComponent now

emm actually i wanto make knockbacks with a shorter interval instead of taking hearts off, which is used to mimic the knockback system of pvp servers(At first, they have shorter attack cooldown). yet i couldnt find a suitable scripting interface to implement this function, so I took advantage of the feature(bug, maybe?) of the game itself to break the built-in cooldown of the attack by causing higher damage then the last one.

And I am eagerly expecting for an interface to remove or modify player's attack cooldown.


For example:
```
entityHit.subscribe((evt) => {
  evt.attackCD = 0
})
//seems like:
beforeChat.subscribe((evt) => {
  evt.cancel = true
})
```

or as player's prototype property
```
steve.attackCD = 0
```
