### ISSUE TITLE
Up and down should not have z as the example it should be y

### ISSUE THREAD

**Issue by mrpatches123** [MicrosoftDocs/minecraft-creator#297]
https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/direction
---
#### Document Details
instead of 
Represents an object located or facing in the down (z - 1) direction.
Represents an object located or facing in the up (z + 1) direction.

it should be 
Represents an object located or facing in the down (y - 1) direction.
Represents an object located or facing in the up (y + 1) direction.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad38603b-e2af-e312-5784-471897741d3e
* Version Independent ID: 68306076-6b63-30ac-e7c9-f855a8fe7416
* Content: [mojang-minecraft.Direction Enumeration](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/direction)
* Content Source: [creator/ScriptAPI/mojang-minecraft/Direction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/Direction.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by JimSeaman42** [comment]
Thank you so much for your feedback; this issue has been remedied.
