### ISSUE TITLE
Numbers bug gametest 

### ISSUE THREAD

**Issue by Aex66** [MicrosoftDocs/minecraft-creator#298]
**Describe the bug**
God, my head hurts so much to think about the cause of the problem, it's me again, the person who has said on 2 occasions (bug reports) that Date did not work for me, today I realized doing even more proof that it is not really Date, is that gametest simply does not let me write large numbers, for example I am working on a ban and mute system, for this I need the timeStamp, I get it with Date.now() So far, everything is perfect, since it will return the correct Date.now(), I mean the Stamp time that is from January 1, 1970 to today, but if I do this: Date.now() +1 LITERALLY, just like adding that 1 to it, the number becomes directly:  2147483647 But why??? I don't understand why just by adding a 1 to the number that Date.now() gives me, that happens, I really need a solution, it says that in 1.19 beta they fixed the Date.now() thing The int32 thing, which was only limited to this one, I think it's true since before it didn't even return the real Date.now(), now it does return it but just by adding one more, it automatically becomes In this number that I already mentioned, another thing is that if I do this: new Date(Date.now()) or if I simply store the Date.now() in a variable and then in the parameter of new Date() I place it, although there It is not adding any 1 or more to it, it also returns the same number, 2147483647 and therefore it returns the same date as always, January 25, 1970, I have already tried in the browser in which Date works correctly and apparently this number is the time stamp of January 25January 1970, I hope you can please fix this soon or give me a solution if it is something with my device, I need an answer, a solution. One thing I don't understand about this, is why all the people I ask them it works correctly and they also do the same thing, even adding +180000 to the number that the Date.now gives or even typing bigger numbers :(

**Smartphone (please complete the following information):**
 - Device: [Xioami mi note 10 lite]
 - OS: [MIUI 13]
 - Browser [GOOGLE CHROME]

**Comment by mammerla** [comment]
I believe this should be fixed in current builds (probably since 1.19.10?)
