### ISSUE TITLE
Unable to upload bedrock world to Chunker

### ISSUE THREAD

**Issue by markumo-moon** [MicrosoftDocs/minecraft-creator#300]
Uploading a bedrock world of the file type **.mcworld** will produce the following:

---
Oops, Failed to upload world
Something went wrong communicating with the server.
---

I've tested this with other worlds, different browsers, all producing similar results. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580f040-3bea-d14d-301f-bb46dc87f29e
* Version Independent ID: c580f040-3bea-d14d-301f-bb46dc87f29e
* Content: [World Height Changes in Caves and Cliffs Part 2](https://docs.microsoft.com/en-us/minecraft/creator/documents/worldheightchange)
* Content Source: [creator/Documents/WorldHeightChange.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/WorldHeightChange.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Closing as need more info.
