### ISSUE TITLE
Followed instructions: resource pack not showing up

### ISSUE THREAD

**Issue by dangermom21** [MicrosoftDocs/minecraft-creator#301]
I followed the instructions exactly, and the resource pack is not showing up in my resources.  I started over, and tried it all again, and it still is not working.  I am not sure what I did wrong, or how to fix it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by docsbryce** [comment]
Hi, @dangermom21, I'm sorry to hear that! I think something might be off with your manifest.json. I'd love to take a look if you could copy it here. 

Or, you can take a look at these troubleshooting guide and let me know if something here helps. https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack#troubleshooting

**Comment by dangermom21** [comment]
Hey! sorry for the late reply, I was on holiday. 

Here is the file, (I am still new at this stuff, so I think I uploaded it properly) any help you can give me would be appreciated.  Thanks!
[manifest.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/8523667/manifest.zip)

**Comment by docsbryce** [comment]
Hm, I see what you mean! This looks right to me so far. Two UUIDs, the json looks right, and it does match our tutorial. 

I'm happy to take a look at your whole pack if need be.

I have a few ideas of things to check for now:
- Are you using Bedrock Edition?
- Is this in a resource pack in the com.mojang folder? (I assume so since you mentioned the directions)

It took me a few times to get my manifest working the first time I tried them too.

**Comment by dangermom21** [comment]
Thanks, and yep I am using the bedrock edition.  Here is my com.mojang folder (I definitely could have messed something else up lol) 


[com.mojang.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/8525606/com.mojang.zip)

**Comment by docsbryce** [comment]
Okay! I have good but maybe strange news: it works!

- I copied your my_RESOURCE_packs into my development_resource_packs
- I created a new world
- Navigated to the Resource Packs section of the add-ons while editing the world
- Saw your pack with the dirt description
- Clicked activate on the resource pack

Now I have green dirt.

So it looks like you did everything right. Let me know if I could take more pictures of activating the pack or if you have more questions.

<img width="757" alt="Screenshot 2022-04-20 153742" src="https://user-images.githubusercontent.com/100614333/164336248-97c7ee76-8a2a-430a-9f2a-cc96f3d22089.png">

<img width="475" alt="Screenshot 2022-04-20 153454" src="https://user-images.githubusercontent.com/100614333/164336152-76d4820d-371f-4263-b2c2-dff95cdb5f4c.png">

**Comment by dangermom21** [comment]
Super weird, but that's awesome it works!

**Comment by docsbryce** [comment]
Congrats on your first add-on! 

I'm going to close this for now, but you can reply to reopen it if you have any more questions.

I'm making some improvements to this page soon, so I think I'll add a similar screencap to the docs for clarity.

**Comment by dangermom21** [comment]
Sounds good, thanks!
