### ISSUE TITLE
Search not finding results

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#310]
## Small search window
Typed `behavior.send_event` and nothing popped up even though the page is right there
![image](https://user-images.githubusercontent.com/26075577/164611457-a533e662-a5c8-4b18-adb9-bb8a6a34cd25.png)

Works fine for `behavior.celebrate`
![image](https://user-images.githubusercontent.com/26075577/164611557-cb0b7435-9d79-47e9-b731-d2d3fc6326be.png)

## Large search page
Typed `behavior.avoid_block` and no relevant results were found
![image](https://user-images.githubusercontent.com/26075577/164611696-0757070a-329a-4c8a-9402-404bd22c9a20.png)

Works fine in the small window
![image](https://user-images.githubusercontent.com/26075577/164611732-a75ee000-a495-40c9-9cb2-ab44cc091726.png)

**Comment by JDHeaden** [comment]
Hypothesis: send_event is missing from a TOC or other index used by the search engine... Researching...

**Comment by JDHeaden** [comment]
@tryashtar I added `send_event` to the TOC and it should show up after the next sync. What an excellent catch! Thank you!

 By "large search window" do you mean the search box in the upper right corner next to the **sign in** link? If so, I think that one is intended for searching the whole Microsoft site, so it's more generalized. I prefer to use the small search box or the search feature in Visual Studio Code.
