### ISSUE TITLE
Minecraft Bedrock Documentation: Create a custom block

### ISSUE THREAD

**Issue by PokiXDPolski** [MicrosoftDocs/minecraft-creator#314]
I found a issue in code "blocks.json" 
correct name of oak log in minecraft is "log_top", not "log_oak_top"
and the name of sound is "grass", not "dirt", after writing dirt, minecraft changed sound to log sound, probably because of name of textures

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 461ae8d5-a555-30c8-ac12-c2aa7b5ba18e
* Version Independent ID: 27e6f2c0-afef-4bbd-c5c8-0282ab679fc6
* Content: [How to add a Custom Block](https://docs.microsoft.com/en-us/minecraft/creator/documents/customblock)
* Content Source: [creator/Documents/CustomBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CustomBlock.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
Good catch! Thank you. Fix will be in next release.
