### ISSUE TITLE
Typing mistake in "manifest.json" documentation.

### ISSUE THREAD

**Issue by Raphyah** [MicrosoftDocs/minecraft-creator#315]
Hi, I want to report an issue about the [`Addons Documentation - manifest.json`](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest) page.
I've tried to write the file to a .js file, so I could try to create my own addon editing tool. I've created an object called `rp`, and added a new object called `"manifest.json"` to it.
After copying and pasting the JSON content from the website, I've found a typing mistake in the example. When running the code, it told me that there's an `unexpected token '['`.

```javascript
const rp = {
	"manifest.json": {
		"format_version": 1,
		"header": {
			"description": "Example vanilla behavior pack",
			"name": "Vanilla Behavior Pack",
			"uuid": "ee649bcf-256c-4013-9068-6a802b89d756",
			"version": [1, 0, 0],
			"min_engine_version": [1, 16, 0]
		},
		"modules": [
			{
				"description": "Example behavior pack module",
				"type": "data",
				"uuid": "fa6e90c8-c925-460f-8155-c8a60b753caa",
				"version": [1, 0, 0]
			},
			{
				"description": "Example client scripts module",
				"type": "client_data",
				"uuid": "c05a992e-482a-455f-898c-58bbb4975e47",
				"version": [1, 0, 0]
			}
		],
		"dependencies": [
			{
				"uuid": "66c6e9a8-3093-462a-9c36-dbb052165822",
				"version": [1, 0, 0]
			}
		],
		"metadata": {
			"authors": ["exampleAuthor"],
			"license": "MIT",
			"url": "http://www.exampleurl.com",
			// Here is the first issue.
			"generated_with:" [ // <===
				"example_tool": ["1.0.0", "1.1.0"]
			]
		}
	}
}

console.log(JSON.stringify(rp,null,"\t"));
```

Of course, the code cannot reach the `console.log` because it's missing the `:` after the name, and before it's content. After solving this issue, I've found another one, where there's an `"example_tool": ["1.0.0", "1.1.0"]` inside an array.

```json
"metadata": {
	"authors": ["exampleAuthor"],
	"license": "MIT",
	"url": "http://www.exampleurl.com",
	"generated_with": [
		"》》》》》The second issue is this one. Passing a named object inside an array is raising another error.《《《《《",
		"example_tool": ["1.0.0", "1.1.0"]
	]
}
```

They are not hard to solve, but for some people that are learning to create addons from the official documentation it is a big problem that will probably make them give up little after they started.

Here is the fixed code:
```json
{
	"format_version": 1,
	"header": {
		"description": "Example vanilla behavior pack",
		"name": "Vanilla Behavior Pack",
		"uuid": "ee649bcf-256c-4013-9068-6a802b89d756",
		"version": [1, 0, 0],
		"min_engine_version": [1, 16, 0]
	},
	"modules": [
		{
			"description": "Example behavior pack module",
			"type": "data",
			"uuid": "fa6e90c8-c925-460f-8155-c8a60b753caa",
			"version": [1, 0, 0]
		},
		{
			"description": "Example client scripts module",
			"type": "client_data",
			"uuid": "c05a992e-482a-455f-898c-58bbb4975e47",
			"version": [1, 0, 0]
		}
	],
	"dependencies": [
		{
			"uuid": "66c6e9a8-3093-462a-9c36-dbb052165822",
			"version": [1, 0, 0]
		}
	],
	"metadata": {
		"authors": ["exampleAuthor"],
		"license": "MIT",
		"url": "http://www.exampleurl.com",
		"generated_with": {
			"example_tool": ["1.0.0", "1.1.0"]
		}
	}
}
```
Please, forgive me for my bad English, it's not my main language.

---
#### Document Details

* ID: 156a5c71-e42d-7075-74ef-03230369797b
* Version Independent ID: e0fbfe84-ce3a-9a97-6b45-009ad16ae4a9
* Content: [Addons Documentation - manifest.json](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest)
* Content Source: [creator/Reference/Content/AddonsReference/Examples/AddonManifest.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AddonsReference/Examples/AddonManifest.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by docsbryce** [comment]
Hi, @Raphyah, thanks for reporting this issue! I got a fix out this afternoon for this. And your bug report is definitely one of the most thorough I've ever received. Thanks for reporting and good luck coding! 

Fix here: https://docs.microsoft.com/minecraft/creator/reference/content/addonsreference/examples/addonmanifest
