### ISSUE TITLE
[GameTest] About "life cycle" things in the events docs

### ISSUE THREAD

**Issue by AbbottMc** [MicrosoftDocs/minecraft-creator#316]
I'm wandering if you can add some introductions to the "life cycle" things for the events, for example, when playerJoin event been triggered, we may still cannot get the player object, and the same as tick event, and these two events also got a sequence of execution, ofc, here are just two small examples. In fact, with the increase of events in the future, we will have more and more confusion about this matter, and for developers, we may take a lot of energy to test to get these conclusions. I think if you can provide some intro about these things, that couldn't be better any more. 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 13cecc4b-4234-7834-8c52-77b9e8e1ab9d
* Version Independent ID: a06a8ca4-6d01-4c08-f6ef-ad6a7bf6b3f2
* Content: [mojang-minecraft.Events Class](https://docs.microsoft.com/zh-cn/minecraft/creator/scriptapi/mojang-minecraft/events)
* Content Source: [creator/ScriptAPI/mojang-minecraft/Events.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/Events.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!

**Comment by AbbottMc** [comment]
> Hello!
> 
> It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!
> 
> Thanks!

yeah I've noticed recently in metadata, it's quite cool!
