### ISSUE TITLE
Version of Gametest Feature

### ISSUE THREAD

**Issue by FrankyRay** [MicrosoftDocs/minecraft-creator#318]
**Is your feature request related to a problem? Please describe.**
Because gametest always gets an update every Beta/Preview, I always get confused because is the feature available in Stable or Beta. Kinda hard to remember all features they added in every version. So can the docs say what version did the feature was added?

**Describe the solution you'd like**
The docs add a note that this feature was added in a specific version.

**Describe alternatives you've considered**
The docs at least say that the feature was stable or still in Beta/Preview.

**Comment by ConsoleTerm** [comment]
This request isn't current and could be closed, we got a versioning system like 8 months ago. Thank you for your suggestion.
