### ISSUE TITLE
[Improvement] [GameTest] Server forms

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#32]
**Allow server form to be sent from api**

Custom forms would be a really useful system to allow developers top use. Addons can't make use of it at the moment, despite the millions of customizable options. Users in the server modding scene are making use of the form to create menus and a better user experience.

It would be ideal if:

- Factory/builder function to build up a form with its various elements
  - Add handler for response to this as part of the factory/builder

**Comment by Luminoso-256** [comment]
Potentially adding a way to leverage Core UI components to create even more rich UI down the line would also be a way to extend this and integrate it into the webtech parts of the bedrock ecosystem.

**Comment by GTB3NW** [comment]
Latest beta addressed this issue - great work thanks guys! :)
