### ISSUE TITLE
[GameTest] Cannot Get ItemStack Components from Item Entity

### ISSUE THREAD

**Issue by frostice482** [MicrosoftDocs/minecraft-creator#320]
While I was messing around with ItemStack, I found out that I cannot get ItemStack components from an item entity, like I usually do.
```ts
import { world } from "mojang-minecraft";

world.events.entityCreate.subscribe(({entity}) => {
    const item = entity.getComponent('item')?.itemStack
    if (!item) return
    item.getComponents()
    const enchComp = item.getComponent('enchantments').enchantments // <-- err: Failed to get property 'enchantments'
})
```

## Expected
When using ItemStack from player inventory to get components of that ItemStack, it works as expected.
<img src="https://user-images.githubusercontent.com/92860250/165699277-a4dacaad-4877-472a-81b5-30b59df35560.PNG" width=40%>

## Observed
However, when using ItemStack from item entity to get components of that ItemStack, it doesn't work.
Also, when trying to access one of the `[Unknown]` properites, it throws an error.
<img src="https://user-images.githubusercontent.com/92860250/165699736-e07e4c4a-c3e3-4985-b1ed-2c2efc4a011f.PNG" width=40%>

## Tested Versions
- Preview 1.19.0.27
- 1.18.31

**Comment by ConsoleTerm** [comment]
Thank you for your report, you can close this issue now. This bug was fixed some days ago, issue is not current.
