### ISSUE TITLE
conditional_bandwidth_optimization docs need improving

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#321]
https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_conditional_bandwidth_optimization.md

1. It says `conditional_values` is a list, but `default_values` is an object. This seems accurate given the examples. However, it's not clear *why* `conditional_values` is a list, and both are described as "the object containing [...]".
2. The two tables for `conditional_values` and `default_values` are identical, making them redundant. The first one is described as "`conditional_values` is a list defined by three parameters" and the second as "`default_values` is a JSON object defined by two parameters." Both tables list three fields, so I have no idea why the second one says two. And again, lists don't have parameters.
3. `max_dropped_ticks` is described as "In relation to the optimization value, determines the maximum ticks spatial update packets can be not sent," which just makes no sense whatsoever. This needs to be explained better.
4. `max_optimized_distance` is described as "The maximum distance considered during bandwidth optimizations. Any value below the max is interpolated to find optimization, and any value greater than or equal to this max results in max optimization." This also doesn't explain anything. Distance between what? What does "interpolated to find optimization" mean? What does "max optimization" mean?
5. `use_motion_prediction_hints` is much more clear, although it's unclear what "drop packet intervals" means, and it's unclear what the tradeoff is (e.g. why not just always enable this?)
6. The `conditional_values` filter used by some entities is undocumented
7. I would like to see a video demonstrating the visual effects of different values of this component on entities
8. Some entities have this component but it's completely empty. It's not clear what the effect of this is, compared to not having the component at all.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!

**Comment by tryashtar** [comment]
I don't see any changes to this file, either on github or the live site. Can you please direct me where this progress took place?
