### ISSUE TITLE
[Turtorial] Translate error

### ISSUE THREAD

**Issue by AbbottMc** [MicrosoftDocs/minecraft-creator#323]
In Chinese MCBE community, Addon(Add-ons) is translated to "附加包", not “加载项” or "附加内容"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 63ee92b3-df1e-3f02-7b62-e13798b131a8
* Version Independent ID: 7d9f0488-2919-4cca-20ee-097af4e47a05
* Content: [《我的世界》加载项入门](https://docs.microsoft.com/zh-cn/minecraft/creator/documents/gettingstarted)
* Content Source: [creator/Documents/GettingStarted.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.zh-CN/blob/live/creator/Documents/GettingStarted.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Thank you for this. I will pass this feedback along to our translators.
