### ISSUE TITLE
Batch of Translation errors in zh_CN

### ISSUE THREAD

**Issue by MiemieMethod** [MicrosoftDocs/minecraft-creator#324]
> We now publish articles and tutorials in: • de-DE • es-MX • fr-FR • it-IT • ja-JP • ko-KR • zh-CN We are looking forward to evolving our multilingual offering here. Thank you for the suggestion! Sorry it took so long to fulfill. :)

Could I ask for any chance to edit these translations by community? I see the translating style of the current translations is almost the same with the translations in Bedrock Edition game which contains super large amounts of machine translations, errrors, typos, wrongly picked terms and inconsistencies with JE (maybe especially in zh_CN since zh is one of the languages mostly shouldn't be translated by machine.) 

So I have taken an exploration through all translated zh_CN articles, finding that there's still lots of articles machine-translated without any post-edits. Even the titles looks in a mass. Moreover, even in those articles seemingly post-edited, MT errors and wrong terms can be seen everywhere. For example, in Chinese Simplified (China Mainland variant), Add-on should be 附加包 not 附加组件 or 加载项, tick (n.) be 刻 not 节拍, texture be 纹理 not 材质 (as similar as texture pack be 纹理包 not 材质包), material be 材质 not 材料, base be 基 not 基础 (for 基础 it's basic not base). Moreover, Minecraft the word shouldn't be translated as it's a brand name, and GameTest the word shouldn't be translated as it's a feature name, a proper noun, like JavaScript. Moreover, some MC-coined words are translated with inconsistency to community popularly/commonly used ones, like feature (in world generation) should be 地物 not 功能/特征, and volume (referred as a modding subject) should be 功能域 not 卷 (and it doesn't affect other words like volume fog 体积雾, volume light 体积光. Don't use the fucking "glossary find and replace" I am begging you!!!)

So after all, if the outsourcing translation team is still giving so unsatisfactory translations, then in my opinion, it's better to let the community in like JE with Crowdin.

_Originally posted by @MiemieMethod in https://github.com/MicrosoftDocs/minecraft-creator/issues/47#issuecomment-1113903324_

**Comment by kakinnun** [comment]
Thank you for this. I followed up with the localization team and unfortunately the translation process setup does not support community translations. I can, however, pass along feedback to the translators.

These suggestions are understood, and we agree with them. I will pass these along to our translators.
•	Add-on should be 附加包 not 附加组件 or 加载项, 
•	tick (n.) be 刻 not 节拍, 
•	texture be 纹理 not 材质 (as similar as texture pack be 纹理包 not 材质包), 

These translations need more context: - can you help with a link to the page(s) you found each of these translations on, and the sentence?
•	material be 材质 not 材料, 
•	base be 基 not 基础 (for 基础 it's basic not base). 
•	feature (in world generation) should be 地物 not 功能/特征 
•	volume (referred as a modding subject) should be 功能域 not 卷 (and it doesn't affect other words like volume fog 体积雾, volume light 体积光.

**Comment by MiemieMethod** [comment]
Thank you for your reply. Words context:
1. *material* be 材质 not 材料 in https://docs.microsoft.com/en-us/minecraft/creator/documents/introductiontoaddentity#visuals *In most cases, a custom material is not required. Instead, you can use a default material. In this example, we use entity. If the texture has transparent parts, you can use entity_alphatest, or if your texture is translucent (like stained glass), you can use entity_alphablend.* <br>In Chinese, *material* can be translated into three different words in Computer Science and related fields. 材料 when it is referred as some make-up component of something, like material of blocks/tools; 材质 when it is referred as a property set for rendering; 物质 when it is referred as a kind of thing, like deepslate is a kind of material undergroud.
2. *base* be 基 not 基础 in https://docs.microsoft.com/en-us/minecraft/creator/documents/basegameversioning about all *base game* (should be 基游戏 or 基底游戏 but not 基础游戏)<br>In Chinese, *base* is always referred as 基底 and abbreviated as 基 in Computer Science and Mathematics, and 基础 more means simple and general. (In other fields it may have other translations. eg. if it is referred as a place to hide, produce and development, it should be 基地. Don't obfuscate if there are some tutorials to teach *how to build a base* later)
3. *feature* should be 地物 not 功能/特征 and *volume* should be 功能域 not 卷 are currently only shown at the menu bar as the Reference Docs have not be translated yet. These two cases are only valid when referred as a subject to add-on because 地物 is inherited from a Geographical term and hardly used in normal life and 功能域 is a word totally created by and widespread around community (and MCWzh of course) to only refer this meaning. <br>Btw, the translation of words on menu bar cannot be more wrong. Just for the Reference Documentation menu, *Add-on* needless to say, *Block* should be 方块 not 块, *Feature* should be 地物 not 功能, *Item* should be 物品 not 项, *Schema* should be 模式 not 方案 (*scheme* is 方案 not *schema*), *Volume* should be 功能域 not 卷. And for Tutorial menu, *Command Block* should be 命令方块 not 命令块 etc. 

Please review my comments. Thank you!

**Comment by kakinnun** [comment]
Thank you so much! Your comment on the menu bar isn't surprising. That menu was translated by a different team that doesn't have the same Minecraft context as our other translators. I'll follow up with that team as well about these. I appreciate these suggestions!

**Comment by MiemieMethod** [comment]
> Thank you so much! Your comment on the menu bar isn't surprising. That menu was translated by a different team that doesn't have the same Minecraft context as our other translators. I'll follow up with that team as well about these. I appreciate these suggestions!

Well, there isn't only the menu bar now. The new translations for Ref Docs titles are also incorrect now.

- **word(s): wrong -> correct: reasons**
- GameTest API: 游戏测试 API -> GameTest API: *GameTest* as a compound non-space proper noun shouldn't be translated due to Chinese habit
- Addons: 追加内容 -> 附加包: Sooooo many kinds of translations for *Addon* lmao
- Block Tiggers: 方块触发 -> 方块触发器: *Tigger* here is a noun not verb
- AI Goal: AI 目标 -> AI 意向: Word *Goal* in *AI Goal* should be translated into 意向 because it is the community consensus in the China Bedrock developer community
- Feature: 功能 -> 地物: Reason sees above, a academic inherited word also a community consensus
- Schemas: 架构 -> 模式: *Schema* into 模式 is the standard translation in China Computer Science academic world
- Texture Set: 材质集 -> 纹理集: *Texture* is 纹理 not 材质 right? Again, if *texture* is 材质, then *material* is nothing

That's wrong translations so far, thank you for the review!

**Comment by kakinnun** [comment]
It looks as though the table of contents and menu are no longer translated, so I believe this feedback is no longer valid.
