### ISSUE TITLE
[GameTest][feature request] EntityRaycastOptions: add option to choose hitbox or collision_box

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#326]
[`minecraft:collision_box`](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_collision_box) 
[`minecraft:custom_hit_test`](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_custom_hit_test)
There is difference.
`EntityRaycastOptions` should allow us to choose.

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
