### ISSUE TITLE
[Particles] `custom_events` is not a real property!

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#327]
Hello! This page documents something called `custom_events`, which is a feature that has long been documented, but doesn't actually exist within the Bedrock Codebase. 

The entire section should likely be deleted:

![image](https://user-images.githubusercontent.com/18729296/166163134-adab7c4d-6dd1-433a-93ee-1088c7e04195.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 208dec3b-3bce-adcc-b595-4c9d2f5292d5
* Version Independent ID: 83951b72-d9fd-c7af-2504-1c630566750e
* Content: [Particle Documentation - Particle Lifetime Events component](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/particlesreference/particlecomponents/minecraftparticle_lifetime_events)
* Content Source: [creator/Reference/Content/ParticlesReference/ParticleComponents/minecraftParticle_lifetime_events.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ParticlesReference/ParticleComponents/minecraftParticle_lifetime_events.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by tryashtar** [comment]
Alternative idea: add it to the game 🙂

**Comment by D4rKCN** [comment]
> Alternative idea: add it to the game 🙂

### add it！
## add it！
# add it！

**Comment by SirLich** [comment]
Yeah I would also like this added. Particles didn't get so much love lately.

**Comment by JimSeaman42** [comment]
Thank you for your feedback; this issue has been remedied.
