### ISSUE TITLE
Android add-ons installing documentation not working

### ISSUE THREAD

**Issue by jarn123** [MicrosoftDocs/minecraft-creator#329]
[Enter feedback here]
[The documentation](https://docs.microsoft.com/en-gb/minecraft/creator/documents/addonpackinstallation?tabs=android#feedback) says I need to click on explore BUT
The explore button is missing in the storage tab on the defualt settings app on ColorOS 11.1/Android 11 on a Oppo A52
![Screenshot_2022-05-02-13-33-46-69_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/69686962/166227777-72b74e28-c543-4ce5-8cc2-1dcc9ab020f0.jpg)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a88ce5-d418-c1bf-0edc-cc1836d68ee4
* Version Independent ID: 50d65cea-41e6-8478-048b-cf192b12503a
* Content: [Installing Add-Ons in Minecraft: Bedrock Edition](https://docs.microsoft.com/en-gb/minecraft/creator/documents/addonpackinstallation?tabs=Windows10)
* Content Source: [creator/Documents/AddonPackInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AddonPackInstallation.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! If there is no "Explore" option in your settings, you will need to install a file explorer app.
