### ISSUE TITLE
[Improvement] [GameTest] Pre world-gen  hook

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#33]
**Add a hook before a chunk generates**

This would call a function before the chunk actually generates, this wouldn't have much use other than cancelling and/or overriding with "custom" generation (pretty grim way to do it lol but :man_shrugging: )

**Comment by kakinnun** [comment]
Closing the oldest GameTest feedback issues. I've collated these for feedback and consideration internally. Closing these issues will save us from having to try and keep these issues up to date. :)
