### ISSUE TITLE
I don't find the folder "blocks"

### ISSUE THREAD

**Issue by nathabon** [MicrosoftDocs/minecraft-creator#333]
I don't find the folder "blocks" in the Behavior_Pack folder which is provision in the same website... It's normal ?
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 461ae8d5-a555-30c8-ac12-c2aa7b5ba18e
* Version Independent ID: 27e6f2c0-afef-4bbd-c5c8-0282ab679fc6
* Content: [Comment ajouter un bloc personnalisé](https://docs.microsoft.com/fr-fr/minecraft/creator/documents/customblock)
* Content Source: [creator/Documents/CustomBlock.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.fr-FR/blob/live/creator/Documents/CustomBlock.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
Yes, you will be creating one yourself I believe. Our resource packs doc might be good to look at. I also plan to add a sample for this tutorial in the next few weeks.

**Comment by docsbryce** [comment]
We now have a resource pack sample that includes the blocks folder. I hope this helps! Let me know if you have more questions and I can reopen this issue.

https://github.com/microsoft/minecraft-samples/tree/main/resource_pack_sample
