### ISSUE TITLE
Skin pack player Models

### ISSUE THREAD

**Issue by Crispot123** [MicrosoftDocs/minecraft-creator#337]
so I can see in the market place some skin packs use a player model that is fully custom to the skin pack like that sonic one
however the skin pack doc doesn't say how you can make custom models for the skin pack or how to make the models work for the skin pack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Packaging a Skin Pack](https://docs.microsoft.com/en-us/minecraft/creator/documents/packagingaskinpack)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingASkinPack.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by mammerla** [comment]
We need to document that unfortunately it's not possible to add custom models to skin packs at this time using the skin pack JSON capability.

**Comment by JDHeaden** [comment]
Done and queued for the next release.
