### ISSUE TITLE
"Where do I put the file"

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#338]
A user was just asking me where to put the dialogue files, despite it being reasonably clear. The actual location is in the paragraph above the codeblock location. This makes it hard to pull out information quickly because eyes are drawn towards the code blocks. I think having it in one codeblock and highlighting the important parts:

`%localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\development_behavior_packs\`*`<your behavior pack folder>\`***`dialogue\`**

This highlighting still kind of looks bad because it has to be split to apply the style, hopefully you can come up with something better. I just thought it might be useful to have a user story from how someone got confused reading the guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db96f8d1-4b84-da2b-68cd-3f0ef7a6f269
* Version Independent ID: 0577bd5f-9522-d3d8-0a3b-5cb928b0b443
* Content: [NPC Dialogue Command](https://docs.microsoft.com/en-us/minecraft/creator/documents/npcdialogue)
* Content Source: [creator/Documents/NPCDialogue.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/NPCDialogue.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
Hi, @GTB3NW, I actually just updated that page and one of the changes I made addresses this. That change will land for the next release. Thanks for sending this in!

**Comment by docsbryce** [comment]
These docs got a refresh (https://docs.microsoft.com/en-us/minecraft/creator/documents/npcdialogue) and we now have a sample for the completed tutorial (https://github.com/microsoft/minecraft-samples/tree/main/npc_dialogue_sample). Thanks!

**Comment by GTB3NW** [comment]
Thanks Bryce!
