### ISSUE TITLE
[GameTest] The BlockProperty in minecraft:bed is missing a color.

### ISSUE THREAD

**Issue by SShobon** [MicrosoftDocs/minecraft-creator#339]
# The BlockProperty in minecraft:bed is missing a color.
## While trying to copy a block with GameTest's BlockPermutation.clone(), I noticed that I could not copy just the color of the bed.
![2022_05_19_13_55_46](https://user-images.githubusercontent.com/81018134/169211529-b6e42040-fecb-4c2d-9f3d-223c050d6580.png)
## Is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f206913c-75a4-f07d-a159-5c8ec4119024
* Version Independent ID: e2f02593-fb50-772d-5a34-edbbd9886116
* Content: [mojang-minecraft.BlockPermutation Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/blockpermutation)
* Content Source: [creator/ScriptAPI/mojang-minecraft/BlockPermutation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/BlockPermutation.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by Aex66** [comment]
I suppose that the way to get the color is not with a property, it is with its data value

**Comment by mammerla** [comment]
Not sure that color block properties apply to beds (just things like direction or occupiedBit) - but this highlights the need to better document blockstates on our end.

**Comment by SShobon** [comment]
# I used getAllProperties() to show the properties, but there were no color.
```js
import { world } from "mojang-minecraft";

//When a block is placed, all properties of the placed block are displayed
world.events.blockPlace.subscribe((event) => {
    const block = event.block;
    const blockId = block.id;
    const blockProperty = block.permutation.getAllProperties().map(x => x.name);
    const player = event.player;
    player.runCommand(`tellraw @s {"rawtext":[{"text":"BlockProperty in ${blockId}: ${blockProperty}"}]}`);
});
```
![2022_06_14_14_36_22](https://user-images.githubusercontent.com/81018134/173501122-899b0617-cacc-4bb9-a45c-6a54ad1b49a6.png)

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
