### ISSUE TITLE
[Improvement] [GameTest] Pre entity spawn event

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#34]
**Fire an event before an entity spawns**

Allow event handlers to modify entities before they spawn, essentially acting as a pre admission hook. The ability to cancel this (where appropriate, for example would cancelling on a player kick them?) would probably come in use as a filter or forcing components to be added/modified (rainbow sheep world anyone?)

**Comment by kakinnun** [comment]
Closing the oldest GameTest feedback issues. I've collated these for feedback and consideration internally. Closing these issues will save us from having to try and keep these issues up to date. :)
