### ISSUE TITLE
Oops, Failed to upload world Something went wrong communicating with the server.

### ISSUE THREAD

**Issue by SimplyJuanjo** [MicrosoftDocs/minecraft-creator#340]
Hey, I don't know if this is the right place to put this feedback but don't know where to ask for help

I tried to upload the save of my favourite Java 1.15.2 world (directly from my AppData/Roaming/.minecraft/saves), and after preparing and loading the file right. It starts to upload but after finishing the % uploading progress bar, I receive this error:

"Oops, Failed to upload world. Something went wrong communicating with the server."

The only action available is Restart, and it gives the same mistake again and again.

Thx for the Chunker App, it's an amazing idea and I hope you can help me solve this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://docs.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by FormallyMyles** [comment]
We should have fixed the bug which caused it not to show the full error if you wanted to try again and hopefully, you'll get a more specific error.

**Comment by SimplyJuanjo** [comment]
@FormallyMyles Ye, it shows the error now
"""
Oops, Failed to upload world
The uploaded files are too big.

RESTART
"""

Should I zip it or something?

**Comment by FormallyMyles** [comment]
Chunker unfortunately isn't designed for large maps and has a limitation of 512MB for uploads on Chunker.app. You could try trimming your world using third-party software like MCASelector, MCEdit or manually deleting region files you don't need if you would still like to try and use Chunker.

**Comment by SimplyJuanjo** [comment]
Ohh, ye, ill try with one of those, which one u recommend me the most? (my world is 0.99GB hehe) 

And in the other line, are u planning to double the size to 1024MB in a near future?

Thx for ur attention Myles! Best regards.

**Comment by FormallyMyles** [comment]
I'd give MCASelector a try as it allows you to run filters, e.g. Discard chunks that haven't been inhabited. I'll pass on your feedback regarding the size to the team, but as of currently we don't have any plans to increase.

**Comment by JimSeaman42** [comment]
It seems like this issue was resolved in the comments, so I'm going to go ahead and close it... If you have any other documentation-related issues, please don't hesitate to let us know! Thanks so much.

**Comment by BBloom81** [comment]
> Chunker unfortunately isn't designed for large maps and has a limitation of 512MB for uploads on Chunker.app. You could try trimming your world using third-party software like MCASelector, MCEdit or manually deleting region files you don't need if you would still like to try and use Chunker.

So are exceptions made for big creators?  How did they convert the Hermitcraft, multiple GB world?  I've got a zipped world that's 492 MB and it still tells me the size is too large.

**Comment by FormallyMyles** [comment]
> > Chunker unfortunately isn't designed for large maps and has a limitation of 512MB for uploads on Chunker.app. You could try trimming your world using third-party software like MCASelector, MCEdit or manually deleting region files you don't need if you would still like to try and use Chunker.
> 
> So are exceptions made for big creators? How did they convert the Hermitcraft, multiple GB world? I've got a zipped world that's 492 MB and it still tells me the size is too large.

Chunker was originally made for partners and is also offered to the public, we do have things in the future which should help with larger worlds. Though I can recommend MCASelector if you are able to trim down your world for now, the limit is based on uncompressed size so I would assume it's larger than 1GB when uncompressed.

**Comment by BBloom81** [comment]
Eh, I found an app in the Microsoft store that works and is faster.  It also didn't rotate any of the repeaters Chunker constantly rotates.

1.00 GB uncompressed
