### ISSUE TITLE
Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by EatMYSHOORTS** [MicrosoftDocs/minecraft-creator#341]
It Doesn't Work On Bedrock

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 461ae8d5-a555-30c8-ac12-c2aa7b5ba18e
* Version Independent ID: 27e6f2c0-afef-4bbd-c5c8-0282ab679fc6
* Content: [How to add a Custom Block](https://docs.microsoft.com/en-gb/minecraft/creator/documents/customblock)
* Content Source: [creator/Documents/CustomBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CustomBlock.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by SIsilicon** [comment]
@EatMYSHOORTS What doesn't work?

**Comment by JDHeaden** [comment]
Can you send a screenshot or a description of what happens instead of it working?

**Comment by EatMYSHOORTS** [comment]
putting custom blocks or block mods onto bedrock edition does not work

**Comment by JDHeaden** [comment]
There are some new tutorials about how to add custom blocks on Bedrock.  https://learn.microsoft.com/minecraft/creator/documents/addcustomdieblock

If these don't work for you, feel free to open this ticket again with more information. 

Thanks!

**Comment by EatMYSHOORTS** [comment]
I have forgotten this
