### ISSUE TITLE
Are Custom Biomes Really Working?

### ISSUE THREAD

**Issue by AoWuCatMC** [MicrosoftDocs/minecraft-creator#343]
Hmm, I followed the custom biome tutorial and had something similar to the example. When I tried it in-game (mcpe 1.18.31.04), the biome doesn't spawn. I've tried increasing the weight to let it appear, but resulted a world with almost nothing other than badlands and water.

Just wanna know if I did something wrong or custom biomes are not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ea0ea4-401b-c411-891f-59df4058d01f
* Version Independent ID: 4e1f21b4-a593-339f-f5b0-e3f67900ac7c
* Content: [Biome Documentation - Overview](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/biomereference/examples/biomeoverview)
* Content Source: [creator/Reference/Content/BiomeReference/Examples/BiomeOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BiomeReference/Examples/BiomeOverview.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by SmokeyStack** [comment]
As per the [1.18.0 changelog](https://feedback.minecraft.net/hc/en-us/articles/4414284658701-Minecraft-Caves-Cliffs-Part-II-1-18-0-Bedrock-), custom biomes no longer work. You can find the bug report [here](https://bugs.mojang.com/browse/MCPE-100700)
![image](https://user-images.githubusercontent.com/84206875/171418217-ebaf02ce-a67d-4022-b61b-87036091d3e5.png)

**Comment by JDHeaden** [comment]
@AoWuCatMC Yes, custom biomes are still broken, but the team is aware. I'm going to close this issue for now. Thanks!
