### ISSUE TITLE
setDynamicProperty not a function

### ISSUE THREAD

**Issue by kbaker4v** [MicrosoftDocs/minecraft-creator#344]
When using setDynamicProperty, I get an error that it is not a function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1089f39d-3863-a163-d69a-5b40730b5791
* Version Independent ID: 919e2958-ed69-c56b-80dc-b6f1ff80b4cc
* Content: [mojang-minecraft.World Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/world)
* Content Source: [creator/ScriptAPI/mojang-minecraft/World.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/World.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by Dingsel** [comment]
you can use it in 1.19+

**Comment by kbaker4v** [comment]
Thanks for the reply, it would be nice to designate function versions in the documentation.

**Comment by mammerla** [comment]
Sorry about this - we're working on improved documentation around versioning.
