### ISSUE TITLE
Duplicate event description for "minecraft:on_friendly_anger"

### ISSUE THREAD

**Issue by SIsilicon** [MicrosoftDocs/minecraft-creator#345]
The event `minecraft:on_friendly_anger` in this page is using the same description as the event before it, `minecraft:on_death`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31ace03-95ec-f9ea-9c0a-7da1aa3e253a
* Version Independent ID: b3e27eba-e777-d3f9-d885-8d0f0e997eca
* Content: [Entity Documentation - Trigger List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/triggerlist)
* Content Source: [creator/Reference/Content/EntityReference/Examples/TriggerList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/TriggerList.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by docsbryce** [comment]
Thanks! This change will go out with the next release.

**Comment by docsbryce** [comment]
This change is live. Thanks for reporting!
