### ISSUE TITLE
[GameTest][Bug] /reload not working with existing imports at all.

### ISSUE THREAD

**Issue by mrpatches123** [MicrosoftDocs/minecraft-creator#347]
**Describe the bug**
/reload and gametest doesn't work correctly as if I /reload on existing imports file, game test just stops except for main with no error until I load back into the worldthe world
.

**To Reproduce**
1. import files in the main manifest import 
2. tick something in one files
3. run /reload 

**Expected behavior**
nothing happens

**Resulting behavior**
main runs except for the unchanged imports

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.19.10 beta
 
Nothing was changed in the files after world load.
https://user-images.githubusercontent.com/49619048/171726736-996b7d81-fd91-4cfd-84f5-9ec96260ce57.mp4

**Comment by mammerla** [comment]
Opened an issue for tracking.

**Comment by mrpatches123** [comment]
It might be that import scoped vars do not reset but idk

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
