### ISSUE TITLE
Missing properties, for gametests

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#349]
**Describe the missing content**
Following the gametest tutorial: https://docs.microsoft.com/en-us/minecraft/creator/documents/gametestbuildyourfirstgametest
It adds to the module:

```json
    "modules": [
        {
            "description": "Script that implements basic starter tests.",
            "type": "script",
            "language": "javascript",
            "uuid": "1A1B53FC-5653-4A75-91B7-9CDF027674AE",
            "version": [0, 0, 1],
            "entry": "scripts/StarterTests.js"
        }
    ]
```

property `type` and `language` are not documented or incomplete in documentation about this

**Vanilla usage example**
see above

**Comment by mammerla** [comment]
Should be updated with the reference that these are basically the acceptable values for these two. @docsbryce can we also update addon reference doc?

**Comment by ConsoleTerm** [comment]
> **Describe the missing content** Following the gametest tutorial: https://docs.microsoft.com/en-us/minecraft/creator/documents/gametestbuildyourfirstgametest It adds to the module:
> 
> ```json
>     "modules": [
>         {
>             "description": "Script that implements basic starter tests.",
>             "type": "script",
>             "language": "javascript",
>             "uuid": "1A1B53FC-5653-4A75-91B7-9CDF027674AE",
>             "version": [0, 0, 1],
>             "entry": "scripts/StarterTests.js"
>         }
>     ]
> ```
> 
> property `type` and `language` are not documented or incomplete in documentation about this
> 
> **Vanilla usage example** see above

This issue can be closed now, right?

**Comment by DaanV2** [comment]
I checked: https://learn.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest
Ands its missing the language field

**Comment by ConsoleTerm** [comment]
> I checked: https://learn.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest Ands its missing the language field

Yeah! I see, but its optional isn´t it? Ya, you should keep this issue open
