### ISSUE TITLE
[Improvement] [GameTest] Structure workflow

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#35]
**Improve the workflow for structures to allow Minecraft module to load structures**

Currently the GameTest framework doesn't require a structure to be saved to a world, it is loaded from the behaviour pack itself. I think this should be updated to allow the Minecraft module to load structures too without requiring commands, it to be saved into the world or the gametest framework.

This decouples the structure from the world, allowing flexible usage of resource packs.

Perhaps a bool for the function could specify to prefer loading off disk instead of level? Therefore allowing structure updates.

**Comment by mammerla** [comment]
@GTB3NW  - Just to clarify - you're asking for the structures associated with GameTest to be loadable from in the level itself, in addition to being able to load Structures from the resource pack?  Or something else (e.g., GameTest to be decoupled from structures?)

**Comment by GTB3NW** [comment]
Thanks for getting back. So same system you currently use for structures which currently resides in gametest module, essentially I think that should be decoupled, it's not test specific and I can see massive use cases outside of tests which aren't coupled to world generation. What are your thoughts on it?

**Comment by kakinnun** [comment]
Closing the oldest GameTest feedback issues. I've collated these for feedback and consideration internally. Closing these issues will save us from having to try and keep these issues up to date. :)
