### ISSUE TITLE
Feedback for new /execute functionality

### ISSUE THREAD

**Issue by Mat384** [MicrosoftDocs/minecraft-creator#351]
I'm all for more flexibility in commands, especially /execute, but these changes as they are would be terrible for my realm and many others. It's a minigame realm that uses a ton of command blocks, a lot of them using the current /execute command syntax. We also have tens of staff who can access these command blocks. If we were to edit them after the update including the new /execute functionality, accidentally or not, they would stop working and we may not know about it until something really bad happens due to a command not running.

I can't see why the old /execute syntax can't exist alongside the new syntax, they're easy to differentiate. It would remove the need for realms and servers running on command blocks to rewrite their commands and some people might prefer the old syntax as it's shorter and quicker to type if you're not using the features of the new syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09220772-3ef8-13bb-33e1-c28b9b0f039e
* Version Independent ID: 09220772-3ef8-13bb-33e1-c28b9b0f039e
* Content: [New execute command support in Minecraft version 1.19.10](https://docs.microsoft.com/en-us/minecraft/creator/documents/commandsnewexecute)
* Content Source: [creator/Documents/CommandsNewExecute.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CommandsNewExecute.md)
* Product: **gaming**
* GitHub Login: @MikeAM
* Microsoft Alias: **mikeam**

**Comment by kakinnun** [comment]
Thank you for your feedback. Which versions of features we support is always a balanced decision. In this instance, it is not possible for us to support both versions of execute.
