### ISSUE TITLE
[Gametest] /reload breaks dynamic properties

### ISSUE THREAD

**Issue by frostice482** [MicrosoftDocs/minecraft-creator#354]
In 1.19, `/reload` is able to reload gametest scripts. However, it will cause issue with packs that tries to define dynamic properties when `/reload`ing.

## To Reproduce
1. Paste the following code into a Gametest pack:
```ts
import { DynamicPropertiesDefinition, world } from "mojang-minecraft"

world.events.worldInitialize.subscribe(({propertyRegistry}) => {
    const reg = new DynamicPropertiesDefinition
    reg.defineString('soup', 2)
    propertyRegistry.registerWorldDynamicProperties(reg)
})
```
2. Load a world with the Gametest pack enabled
3. Run the following command: `/reload`
4. The following error should appear in content log file / gui: `Name conflict detected for dynamic property 'soup' on 'World'`

https://user-images.githubusercontent.com/92860250/172851973-ab2dffa6-4d40-4b7c-ac39-dfd5a8b79ecb.mp4

## Expected behavior
The dynamic property `soup` should be defined correctly without errors

## Device
OS: Windows 10 (10.0.19044.1526)
Minecraft: Preview 1.19.10.22

**Comment by Visual1mpact** [comment]
I learned that if you run the command `/reload` twice then it works again. It comes off like the first execution disables everything and the second execution jump starts it.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
