### ISSUE TITLE
[Gametest][Bug] Dynamic Properties are not fully functional in Realms and BDS

### ISSUE THREAD

**Issue by Visual1mpact** [MicrosoftDocs/minecraft-creator#356]
**Describe the bug**
If you define and register a dynamic property either for the World or a specific Entity then you set that property for either the World or that entity type and you later log off the world from the server or realms then the data is not written and stored as intended. The property will return undefined when you login to the world either on BDS or Realms and your code will have to re-apply the property to either the World or that Entity type again.

**To Reproduce**
1. Create a simple pack that utilizes the Gametes API
2. Write a simple script to define a property for the World
3. Have the code Register that property to the world
4.  Have the code set that property in the world with either a boolean, string, or number respectively
5. Apply the pack to either a Realm or BDS
6. Activate the pack for the world and log on to that world
7. Insure the code executes and that the property has been defined, registered, and set in the World
8. Log off the world or restart BDS/Realm
9. Log back on again and execute code to verify if property is still defined or if it returns undefined again

**Expected behavior**
Properties should persist but they do not.

**Desktop (please complete the following information):**
 - OS: Debian 11, Windows 10
 - Minecraft 1.19.1 (Stable)

**Smartphone (please complete the following information):**
 - Device: Moto G 5g
 - OS: Android 12
 - Minecraft Version 1.19.1 (Stable)

**Additional context**
Dynamic Properties will work properly in a local world and the set properties will persist between logging off and back on. The issue is only pertaining to BDS and Realms at the moment.

**Comment by Visual1mpact** [comment]
There is also concern that this other bug report may have a play with the bad experience as well. Or could be something else entirely different but still making an impact. I will share it here just in case.

https://bugs.mojang.com/browse/REALMS-10333

**Comment by mrpatches123** [comment]
[dynamic-properties-test.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/8911296/dynamic-properties-test.zip)
test pack
apply it to a world with gametest on and it will have the same number every world load, but on bds it will be different each time. make sure you have the content log on for either test

**Comment by Visual1mpact** [comment]
> [dynamic-properties-test.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/8911296/dynamic-properties-test.zip) if the property is not defined, it runs Math.random(). ^^^
> 
> test pack apply it to a world with gametest on and it will have the same number every world load, but on bds it will be different each time. make sure you have the content log on for either test

Appreciate the test pack. I never got around to it lol. This is a good example at demonstrating how it doesn't persist on BDS or Realms but will persist on a local world.

**Comment by mammerla** [comment]
This should be fixed in 1.19.30.
