### ISSUE TITLE
mojang-minecraft-ui usage

### ISSUE THREAD

**Issue by kbaker4v** [MicrosoftDocs/minecraft-creator#358]
Observation
I like the new mojang-minecraft-ui dialog which I can use on events within Minecraft. There are 2 areas I can't use the dialogs. First, is on player join. It just fails silently. I can overcome that with a tick delay, but that is a pain. The second is through chat. I think the chat method will be common, but the dialog just fails silently with the chat ui  open.

Expectation
Allow the mojang-minecraft-ui dialog to work with the beforeChatEvent/chatEvent and the playerJoin events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992b1f7f-433c-c3cc-fbce-30700c5419e5
* Version Independent ID: 992b1f7f-433c-c3cc-fbce-30700c5419e5
* Content: [mojang-minecraft-ui Module](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft-ui/mojang-minecraft-ui)
* Content Source: [creator/ScriptAPI/mojang-minecraft-ui/mojang-minecraft-ui.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft-ui/mojang-minecraft-ui.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by ConsoleTerm** [comment]
there is /closechat command maybe just add it to the game.
@kbaker4v you can wait after player is testable like testfor @s everyTick

**Comment by kbaker4v** [comment]
/closechat would be nice, but it doesn't seem to be a runnable command. The following does not appear to work:
```
public static close(player: Player) {
    player.runCommand(`closechat`);
}
```

Also my tests with running the command /testfor @s do not work as expected. I get a positive hit on /testfor @s, but if I try to start the UI dialog then it doesn't work. If I wait an extra 1 or 2 seconds then it works. There is just nothing to indicate that the opening of the dialog failed. 

```
const unregisteredPlayers: Player[] = [];
world.events.playerJoin.subscribe((eventData) => {
    unregisteredPlayers.push(eventData.player);
});  
world.events.tick.subscribe((eventData) => {
    if (eventData.currentTick % 20 === 0) {
        unregisteredPlayers.forEach((player, index) => {
            let ready = false;
            try {
                ready = player.runCommand('testfor @s');
            } catch {}
            if (ready !== false) {
                const form = new ModalFormData();
                form.title('Test')
                    .textField('test', 'test');
                form.show(player).then((response) => {}); 
                unregisteredPlayers.splice(index, 1);
            }
        });
    }
});
```

**Comment by ConsoleTerm** [comment]
The command has not yet been officially added to the game, but it is there.  I meant the developer command design.

**Comment by mammerla** [comment]
For the player join event, we have a load of problems where it fires even though the player construct isn't fully baked yet in the rest of the system.  We'll likely look into (a separate?) event for something like playerSpawned that might fire later in the cycle - or move the existing event around.

The chat side feels like a bug (probably work aroundable with some ticks and delays.)

**Comment by ConsoleTerm** [comment]
This can be tagged as closed issue, we can now read cancelationReason.

**Comment by ConsoleTerm** [comment]
New Event was added to Creator API u can use PlayerSpawnEvent to be sure if player is ready to display ui form, u can close this issue now.
