### ISSUE TITLE
Compund ticking with an event that depends on a parameter.

### ISSUE THREAD

**Issue by yemheno** [MicrosoftDocs/minecraft-creator#359]
Hey! I was wondering how do you compound the "minecraft:ticking" with an event that needs parameters. For example:
```
"minecraft:ticking":{
    "condition": 1,
    "event": "set_block"
    "target": "self",
}
```
But "set:block" requires the input "block_type". How can I do that? I tried several combinations to no avail. 

Also, how do you negate a bool in the json in minecraft? I tried the usual

`
{'!', "bool"}
`
but the json is not parsing.
Thanks a lot in advance!

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab40cbe-f15e-e32e-c03a-5bbfef406957
* Version Independent ID: b76401b2-3878-9055-8d1a-8970cf92882c
* Content: [Block Documentation - set_block](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockevents/minecraftblock_set_block)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_set_block.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_set_block.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
