### ISSUE TITLE
[BUG] [GameTest] Structure command fails

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#36]
**An issue occurs with spawning structures, the error output is unknown**

I suspect it may be a command origin issue. The exact same command works when ran in console and in game, it still fails when the user is in game and the chunks are loaded.

```
  try {
    Commands.run("structure load my:structure 0 4 0");
  } catch (error) {
    console.log("Problem with command: " + error);
  }
```

Out: `{"statusCode":-2147352576,"statusMessage":"An unknown error occurred while attempting to perform this command"}`

**Comment by GTB3NW** [comment]
Workaround is to put the commands into a function and execute that instead

**Comment by mammerla** [comment]
Looking to fix this soon with Commands.run that takes a Dimension - this should unblock a number of commands.

**Comment by mammerla** [comment]
Should be fixed in beta builds with the addition of a Dimension parameter.

**Comment by GTB3NW** [comment]
> Should be fixed in beta builds with the addition of a Dimension parameter.

thanks Mike!

**Comment by mammerla** [comment]
Closing as we've added Dimension into the mix.
