### ISSUE TITLE
Add to Recommended content

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#361]
Add to Recommended content a link to the article on Loot Tables

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f691dd6-742f-a238-8590-3dbbc810e57c
* Version Independent ID: 7f691dd6-742f-a238-8590-3dbbc810e57c
* Content: [Block Documentation - minecraft:loot](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_loot)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_loot.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_loot.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JDHeaden** [comment]
You're right that it should be in there, and if I could add it, I would - but the Recommended Content section is actually auto-generated.

**Comment by JDHeaden** [comment]
Final answer - that feature is auto-generated and we can't get our grubby little hands on it. Sorry about that.
