### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by TEMG02** [MicrosoftDocs/minecraft-creator#362]
its 2 Minecraft versions behind is it never going to get support for newer versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06734f1c-1303-fdb2-115e-8c3b07bbcf7a
* Version Independent ID: 43d1e5dc-75b7-bc97-7a5b-7226f71c7a76
* Content: [Converting Texture Packs from Java Edition to Bedrock Edition](https://docs.microsoft.com/en-us/minecraft/creator/documents/convertingtexturepacks)
* Content Source: [creator/Documents/ConvertingTexturePacks.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ConvertingTexturePacks.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by kakinnun** [comment]
I don't understand what you're referring to as "2 versions behind". Closing this issue due to its age, but if you still have specific issues with this article, please feel free to elaborate.
