### ISSUE TITLE
"Java Edition" links to this page, and very confused

### ISSUE THREAD

**Issue by Zashy** [MicrosoftDocs/minecraft-creator#363]
I got linked here when searching for the Java documentation multiple times. Is Java edition even documented? I can't tell, but gosh darn do I remember my early years of coding and the numerous times I was weeding through documentation on Microsoft controlled websites only to find I was on the wrong version of Visual Studio's docs, or a language or whatever. Glad to see the documentation hasn't really changed since then. It took another independent source to actually verify this documentation was only for Bedrock edition. I was immediately suspicious due to my years of using Microsoft products, but gosh like 15 minutes of searching to realise the documentation was for the wrong version of the product. Are there even Java syntax documentations?! Sure doesn't seem like you guys put effort into a Bedrock syntax definition (not that I can ever find useful syntax documentation on Microsoft sites...).

Basically tl;dr:
* This isn't obvious it is only for Bedrock edition (maybe cause it likes only listing itself as Minecraft and not Minecraft: Bedrock)
* I don't know where any Java documentation is from this page, I think you own that now 😉 
* The SEO really pushed me to look at this page when searching for "Java Edition" in quotes
* Where is the syntax documentation located, would be good to link it here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed671f3-fe39-198e-118b-e5a507a48760
* Version Independent ID: effddaa6-fc77-a2c2-94bc-c44d9aa45f79
* Content: [Getting Started with Command Blocks](https://docs.microsoft.com/en-us/minecraft/creator/documents/commandblocks)
* Content Source: [creator/Documents/CommandBlocks.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CommandBlocks.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
I hear you!

The CommandBlock page mentions "Bedrock Edition" in the first sentence and in the "Setting the world up" instructions. I added it to the meta data for the page, too. That should help with the SEO. 

I also added a link to the Command Introduction page that has more syntax information. 

I hesitate to add anything about Java in case the SEO grabs that in error. 

We do have a page about the differences between Bedrock and Java... 

https://docs.microsoft.com/en-us/minecraft/creator/documents/differencesbetweenbedrockandjava

... do you have any updates for this page that might help?
