### ISSUE TITLE
[Gametest][request] /script and /reload being added to gametest.

### ISSUE THREAD

**Issue by mrpatches123** [MicrosoftDocs/minecraft-creator#364]
Both being added to the permissions of gametest would allow them to work with wrappers that break due to either command not resetting that feature which might annoy the people who don't want anything to be reset, or just debugging before the player can manually type a command,  so being able to run the commands on script load and/or on-call would solve those issues. 

_Below is the reasons for each command being added to gametest permissions._

**/script**
Adding the script command would allow for debugging using the debugger and the stack trace to occur before the player can load in and run a command. For example, if I want to debug my dynamic property wrapper, I would just run the script command in gametest before the worldInitialize event runs and it would connect to VSC; at the moment, I can't do that as the player loads in after that, and I cannot force the player to run commands.

**/reload**
Adding the reload command would allow for us to fix, https://github.com/MicrosoftDocs/minecraft-creator/issues/347, (vars scored in memory are not reset), If reload was added to the permissions of gametest then we could create our own reload commands that work with our wrappers. (worldInit offers a fix for this but the property reload bug is not fixable via a workaround)

**Comment by mammerla** [comment]
We'd need a more nuanced permissions model here to allow this in opted-into cases while still not letting every map possible open up script debuggers, etc.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
