### ISSUE TITLE
How to make working URLs in NPCs

### ISSUE THREAD

**Issue by FlamingNuke** [MicrosoftDocs/minecraft-creator#366]
Hello, I've been looking to find a way to put working links in Minecraft using NPCs since in the newer version of Minecraft bedrock edition it says "Only URLs beginning with "http" or "https" are supported"

If u have any idea of doing this please help.

![Screenshot_20220702-090718](https://user-images.githubusercontent.com/108571581/176994474-92360961-6f7c-4caf-9fdd-0d0d74a47e23.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db96f8d1-4b84-da2b-68cd-3f0ef7a6f269
* Version Independent ID: 0577bd5f-9522-d3d8-0a3b-5cb928b0b443
* Content: [NPC Dialogue Command](https://docs.microsoft.com/en-us/minecraft/creator/documents/npcdialogue)
* Content Source: [creator/Documents/NPCDialogue.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/NPCDialogue.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
