### ISSUE TITLE
Missing example of the default hurt and damage colors

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#369]
Missing example of the default hurt and damage colors that vanilla uses, please provide examples on the 
https://docs.microsoft.com/en-us/minecraft/creator/reference/content/animationsreference/examples/animationrendercontroller page of the default values/colors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc18d47a-e328-c81a-b3e6-3f8400b0d060
* Version Independent ID: 9587d402-df15-2a0e-a690-cb0bb6ebe3f1
* Content: [Animation Documentation - Render Controllers](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/animationsreference/examples/animationrendercontroller)
* Content Source: [creator/Reference/Content/AnimationsReference/Examples/AnimationRenderController.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AnimationsReference/Examples/AnimationRenderController.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
