### ISSUE TITLE
[Improvement] [GameTest] Access to player's inventory

### ISSUE THREAD

**Issue by Joelant05** [MicrosoftDocs/minecraft-creator#37]
Ideally you should be able to access a player's inventory by calling `getComponent()` to get the inventory component, exactly like you can on other entites. 

Unfortunately this doesn't seem to be possible yet and the `inventory` component is inaccessible on players.

This should return the `Inventory` class for access to its properties and methods.

**Comment by mammerla** [comment]
Should be resolved in the next beta.
