### ISSUE TITLE
Example manifest no longer works

### ISSUE THREAD

**Issue by Ian1971** [MicrosoftDocs/minecraft-creator#371]
I think something may have changed because "type": "javascript" no longer works in the manifest and kicks out an error

e.g.
"Provided '/modules/1/type' element has an invalid value in pack manifest."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74a371cf-594b-26d5-21e0-8a77121c256b
* Version Independent ID: 74a371cf-594b-26d5-21e0-8a77121c256b
* Content: [Build a gameplay experience with TypeScript](https://docs.microsoft.com/en-us/minecraft/creator/documents/scriptinggettingstarted)
* Content Source: [creator/Documents/ScriptingGettingStarted.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ScriptingGettingStarted.md)
* Product: **gaming**
* GitHub Login: @MikeAM
* Microsoft Alias: **mikeam**

**Comment by mammerla** [comment]
OK, I updated the GitHub repo and the doc should have this note on the format change to 1.19: 

> This sample now represents the manifest format for registering JavaScript for version 1.19. Prior to version 1.19, the type attribute should be set to "javascript", and the language attribute should be omitted.
