### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by 9ineven** [MicrosoftDocs/minecraft-creator#377]
There is typo in the first example: "control_item:":"iron_sword"
It should be: "control_items":"iron_sword"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b0b245-3553-c0cc-4734-45c9ba7c7cb9
* Version Independent ID: 5c19f82a-358e-cdff-e98a-2d01bfe73b5c
* Content: [Entity Documentation - minecraft:item_controllable](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_item_controllable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_item_controllable.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_item_controllable.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
Good catch! Change is made and queued for next release.

**Comment by 9ineven** [comment]
Thank you for your work!
