### ISSUE TITLE
Not appearing in the creative menu

### ISSUE THREAD

**Issue by Voda-Clovek** [MicrosoftDocs/minecraft-creator#379]
The helloworld:canvasblock or Canvas Block is not in the creative menu even though it is set to. I can obtain it by using "/give @s helloworld:canvasblock", and when it is in my inventory its name is "Canvas Block". I don't know what I'm doing wrong if anything, and I don't know how to get it to work.

![Screenshot (8)](https://user-images.githubusercontent.com/109321161/179125383-ab293799-f8ca-4183-82b1-b6a8fda1a7b8.png)
![Screenshot (9)](https://user-images.githubusercontent.com/109321161/179125424-f560e658-425a-4f18-b80b-1e61e34de5d5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 461ae8d5-a555-30c8-ac12-c2aa7b5ba18e
* Version Independent ID: 27e6f2c0-afef-4bbd-c5c8-0282ab679fc6
* Content: [How to add a Custom Block](https://docs.microsoft.com/en-us/minecraft/creator/documents/customblock)
* Content Source: [creator/Documents/CustomBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CustomBlock.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by kakinnun** [comment]
We've updated documentation on custom blocks. Closing this issue due to its age, but if you're still running into issue, please let us know.
