### ISSUE TITLE
What is the size limit? 

### ISSUE THREAD

**Issue by KemMuammer** [MicrosoftDocs/minecraft-creator#381]
I have a world that is 1.18.1 and i want to go to 1.19.1. I get an error "Recoverable errors when loading section" when I start the server and I read that chunker kan help with that issue, but I cant upload world because it is 526MB big. Is there a way to still do it? I tried to zip it and compress but nothing was better than 526MB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://docs.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by FormallyMyles** [comment]
For Chunker.app the file size is currently limited to 512mb, if you're converting from Java Edition you can try tools such as MCASelector / MCEdit to prune chunks if you would still like to use Chunker.

**Comment by kakinnun** [comment]
Closing this as answered.
