### ISSUE TITLE
Better Examples

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#382]
It states boolean or json object with definition....  please give an example of what this looks like.

**Comment by JDHeaden** [comment]
Hi! I don't think all the information for this came over - can you put a link to the document you mean? I'll be glad to take a look.

**Comment by JDHeaden** [comment]
Closing this for now. If you see this message and send over the info, I will be glad to re-open the issue and do what I can to help. Thanks!
