### ISSUE TITLE
Doesn't explain Switch add-on installation

### ISSUE THREAD

**Issue by creidieki** [MicrosoftDocs/minecraft-creator#383]
Document doesn't explain how to install add-ons for the Switch version of Minecraft.  (At https://help.minecraft.net/hc/en-us/articles/4409140076813-Minecraft-Add-Ons-for-Bedrock-Versions-FAQ   it says "Add-Ons will work on any platform that runs the Bedrock Edition").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a88ce5-d418-c1bf-0edc-cc1836d68ee4
* Version Independent ID: 50d65cea-41e6-8478-048b-cf192b12503a
* Content: [Installing Add-Ons in Minecraft: Bedrock Edition](https://docs.microsoft.com/en-us/minecraft/creator/documents/addonpackinstallation?tabs=Windows10)
* Content Source: [creator/Documents/AddonPackInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AddonPackInstallation.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
(Note to self - also put Realm add-on instructions)

**Comment by JDHeaden** [comment]
I added an update about how to use Realms to play a particular world on a console. That was the way I could get it to work consistently.
