### ISSUE TITLE
Missing documentation for minecraft:max_stack_size

### ISSUE THREAD

**Issue by depressed-pho** [MicrosoftDocs/minecraft-creator#385]
Items support component "minecraft:max_stack_size" but it isn't documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e43e50ff-ba33-036b-f395-e01f225d5e3e
* Version Independent ID: 707cfc91-6885-cf1c-0a1a-65988a473516
* Content: [Item Documentation - Item Component List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponentlist)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponentList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponentList.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JimSeaman42** [comment]
Thank you for your feedback. This issue has been remedied, and documentation for 'minecraft:max_stack_size' can be found [here.](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_max_stack_size)
