### ISSUE TITLE
Missing documentation for minecraft:foil

### ISSUE THREAD

**Issue by depressed-pho** [MicrosoftDocs/minecraft-creator#386]
Items support component "minecraft:foil" that gives them enchantment glint effect, but it's not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e43e50ff-ba33-036b-f395-e01f225d5e3e
* Version Independent ID: 707cfc91-6885-cf1c-0a1a-65988a473516
* Content: [Item Documentation - Item Component List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponentlist)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponentList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponentList.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JDHeaden** [comment]
Good catch! minecraft:foil item component page has been added and will be visible after the next release. Thanks!
