### ISSUE TITLE
The GameTest Framework ignores source maps

### ISSUE THREAD

**Issue by depressed-pho** [MicrosoftDocs/minecraft-creator#387]
Throwing `Error`s shows stacktraces to the content log, but it ignores source maps attached to scripts. This is quite inconvenient when scripts are transpiled from some other languages such as TypeScript. Neither inline source maps nor external ones are recognized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b392d86-8199-5081-07fe-8852b494883f
* Version Independent ID: ed92b970-1f98-e573-7343-1d9e7d729f7b
* Content: [mojang-minecraft Module](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/mojang-minecraft)
* Content Source: [creator/ScriptAPI/mojang-minecraft/mojang-minecraft.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/mojang-minecraft.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by JakeShirley** [comment]
@depressed-pho Do run times like Node output source-map-ified call stacks?  I thought that was more of a debugger role.  

I will say our debugger does support source maps but it seems that we don't currently support in-lined source maps.

**Comment by depressed-pho** [comment]
@JakeShirley Yes, Node.js does that. Web browsers do that too.

**Comment by Worldwidebrine** [comment]
What about QuickJS?

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
