### ISSUE TITLE
"blocks_to_avoid": [] in all the minecraft:navigation.* components is missing notes/documentations on supported values?

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#388]
"blocks_to_avoid": [] in all the minecraft:navigation.* components is missing notes/documentations on supported values?

So basically as a player/addon creator, I want to know what values are supported here and how would I know this information because it's currently missing on this page there is no explanation on what is supported and what can be put in these components for the **blocks_to_avoid**

Does it say that it's a list/array but my question is what can go in there?

Does it support block states, does it support string id values? or what about the prefix "minecraft:" and does it support custom block prefixes?

[navigation.climb](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.climb)
[navigation.float](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.float)
[navigation.fly](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.fly)
[navigation.generic](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.generic)
[navigation.hover](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.hover)
[navigation.swim](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.swim)
[navigation.walk](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.walk)

I found an example of using block state format this is undocumented and probably should be so that we can know how to format the block states fully.
```jsonc
      "minecraft:navigation.walk": {
        "is_amphibious": true,
        "can_pass_doors": true,
        "can_open_doors": true,
        "can_swim": true,
        "can_sink": false,
        "can_open_iron_doors": true,
	"can_path_over_water": true,
        "blocks_to_avoid": [
          {
            "name": "minecraft:campfire"
          },
          {
            "name": "minecraft:soul_campfire"
          },
          {
            "name": "minecraft:fire"
          },
          {
            "name": "minecraft:water"
          },
          {
            "name": "minecraft:flowing_water"
          },
          {
            "name": "minecraft:lava"
          },
          {
            "name": "minecraft:flowing_lava"
          },
          {
            "name": "minecraft:web"
          },
          {
            "name": "minecraft:portal"
          },
          {
            "name": "minecraft:magma"
          },
          {
            "name": "minecraft:soul_fire"
          },
          {
            "name": "minecraft:kelp"
          },
          {
            "name": "minecraft:seagrass"
          },
          {
            "name": "minecraft:sea_pickle"
          },
          {
            "name": "minecraft:conduit"
          },
          {
            "name": "minecraft:bubble_column"
          },
          {
            "name": "minecraft:sweet_berry_bush"
          },
          {
            "name": "minecraft:cactus"
          },
          {
            "name": "minecraft:trapdoor"
          },
          {
            "name": "minecraft:iron_trapdoor"
          },
          {
            "name": "minecraft:birch_trapdoor"
          },
          {
            "name": "minecraft:acacia_trapdoor"
          },
          {
            "name": "minecraft:dark_oak_trapdoor"
          },
          {
            "name": "minecraft:jungle_trapdoor"
          },
          {
            "name": "minecraft:spruce_trapdoor"
          },
          {
            "name": "minecraft:crimson_trapdoor"
          },
          {
            "name": "minecraft:warped_trapdoor"
          }
        ],
        "can_walk": true,
        "can_break_doors": true
      }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09a85eea-9707-681a-0c49-944b704f48c1
* Version Independent ID: 6e5c8985-5238-67cc-d4bd-8e4140b06ff0
* Content: [Entity Documentation - minecraft:navigation.generic](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.generic)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_navigation.generic.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_navigation.generic.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!

**Comment by StealthyExpertX** [comment]
@v-jeffkim Seems this isn't fully documented there is no added documentation on the syntax of "blocks_to_avoid" so this shouldn't have been closed.
