### ISSUE TITLE
minecraft:behavior.float examples have a trailing comma syntax errors.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#389]
minecraft:behavior.float example has a trailing comma syntax error in the first example shown.

```jsonc
"minecraft:behavior.float":{
    "priority": 0,
}
```

it should be corrected to this.

```jsonc
"minecraft:behavior.float":{
    "priority": 0
}
```

The second example has an issue as well.
```jsonc
"minecraft:behavior.float": {
  "priority": 0
},
```

Should be corrected to
```jsonc
"minecraft:behavior.float": {
  "priority": 0
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4efb69-8337-671e-5c6d-7fdc20eba236
* Version Independent ID: f9faf110-e671-94b7-8932-cb5c465aa98f
* Content: [Entity Documentation - minecraft:behavior.float](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_float)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_float.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_float.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
Thanks for reporting. This change is now live!

[Docs here](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_float)
