### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by def-python-programmer** [MicrosoftDocs/minecraft-creator#39]
[Enter feedback here]
thankyou i think this is best now i learn about minecraft bedrock moding thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ee92b3-df1e-3f02-7b62-e13798b131a8
* Version Independent ID: 7d9f0488-2919-4cca-20ee-097af4e47a05
* Content: [Getting Started With Minecraft Add-Ons](https://docs.microsoft.com/en-us/minecraft/creator/documents/gettingstarted)
* Content Source: [creator/Documents/GettingStarted.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/GettingStarted.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by kakinnun** [comment]
Thank you so much for the lovely comment!

**Comment by def-python-programmer** [comment]
Nice👏
