### ISSUE TITLE
Item components

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#391]
**Describe the missing content**
The item components `can_place_on`, `can_destroy`, `item_lock`, and `keep_on_death` aren't documented anywhere I can find, aside from some random references strewn about tutorials. We don't even know if there are more components than this that are just undocumented.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
