### ISSUE TITLE
Raw text documentation

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#392]
**Describe the missing content**
The raw text format used in `/tellraw` etc isn't documented anywhere I can find, aside from a few vague mentions in some tutorials.

I want to know:
* What fields are available
* Where it can and can't be used
* How it compares to Java's format

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
