### ISSUE TITLE
A syntax error in the document

### ISSUE THREAD

**Issue by NIANIANKNIA** [MicrosoftDocs/minecraft-creator#396]
I think the example here should be removed from {}, otherwise there will be a syntax error
`"minecraft:loot":{
    "<path_to_behavior_pack>/loot/customblockloot.json"
}`

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7f691dd6-742f-a238-8590-3dbbc810e57c
* Version Independent ID: 7f691dd6-742f-a238-8590-3dbbc810e57c
* Content: [Block Documentation - minecraft:loot](https://docs.microsoft.com/zh-cn/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_loot)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_loot.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_loot.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by tryashtar** [comment]
Also `<path_to_behavior_pack>` should not be there, and it should be `loot_tables, not `loot`

**Comment by JDHeaden** [comment]
Good point! I changed the example to reflect the actual contents of the loot path for the blaze. The change will be seen after the next release.
