### ISSUE TITLE
Missing loot table functions/conditions

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#397]
**Describe the missing content**
The following loot table conditions/functions don't seem to be documented anywhere:
* `has_variant`
* `killed_by_player`
* `killed_by_entity`
* `set_stew_effect`
* `random_dye`
* `explosion_decay`

Are there more that nobody knows about?

I have a few more problems with the docs in [LootAndTradeTableFunctions](https://github.com/MicrosoftDocs/minecraft-creator/tree/main/creator/Documents/LootAndTradeTableFunctions.md) and [IntroductionToLootTables](https://github.com/MicrosoftDocs/minecraft-creator/tree/main/creator/Documents/IntroductionToLootTables.md).

* First, why are the various functions documented at random between the two? Wouldn't it make more sense to keep the introduction as a simple tutorial, and the other page to be comprehensive?
* `enchant_book_for_trading` says "At this time, defining these parameters won’t affect the enchantment received. Currently, the default values above are hard-coded. In the future, you’ll be able to tweak these values to help narrow down what enchantments and enchantment levels this function results in." Does this mean it actually *doesn't* take any parameters? Let's not mislead users by implying they work
* The description for `looting_enchant` is pretty bad, it doesn't explain what `count` actually does and how it interacts with the level of looting
* `trader_material_type` is extremely vague
* `entity_properties`: is there anything other than `on_fire`? Also description is wrong
* `has_mark_variant` description is wrong
* `random_regional_difficulty_chance` needs an explanation of what regional difficulty is

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
