### ISSUE TITLE
World format

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#398]
**Describe the missing content**
The actor storage article has great information about a *change* made to the Bedrock world format, but we need to know more.

* Every key in leveldb
* What each value looks like (strings? NBT? Multiple NBTs appended together? Some weird custom thing?)
* For all versions of Minecraft

**Comment by StealthyExpertX** [comment]
Yes, I second this!

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
