### ISSUE TITLE
GameTest API Sidebar TOC is not Alphabetical

### ISSUE THREAD

**Issue by kakinnun** [MicrosoftDocs/minecraft-creator#40]
GameTest API (both GameTest and Minecraft modules) sidebar TOC is not in alphabetical order. The main pages for these modules similarly do not list the classes in alphabetical order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a4cf6b-d41e-c83b-b872-ba7c7d91ff19
* Version Independent ID: c0300ca9-b5f7-c57e-6d73-9278a009e01d
* Content: [Minecraft Module](https://review.docs.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/minecraft?branch=main)
* Content Source: [creator/ScriptAPI/Minecraft/Minecraft.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/Minecraft/Minecraft.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by JakeShirley** [comment]
Fixed in Mojang/MinecraftScriptingApiDocsGenerator@1ec2435c299881b56abf833de41e556b009a833c!

**Comment by mardb** [comment]
Addressed in [Hotfix for R17: Caves and Cliffs: Part 1](https://github.com/MicrosoftDocs/minecraft-creator-pr/pull/189#event-4930380792)
