### ISSUE TITLE
[Feature Request] entityDie event

### ISSUE THREAD

**Issue by DumbassDev** [MicrosoftDocs/minecraft-creator#401]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to detect the death of an entity without using workarounds involving animation contollers. This is higly annoying if, for example, you want to detect the deaths of all entity types. In order to do this, you would need to edit the json of every entity type in order to add an animation controller.

**Describe the solution you'd like**
I am suggesting a new event along the lines of _Events.entityDie_. The properties should include:

- entity (the entity that died)
- killer (the entity that killed it, or undefined)
- cause (the cause of death)

**Describe alternatives you've considered**
The current solution is to add an animation controller to the entity which gives it a tag upon death, then use a tick event to find all entities with that tag and execute code.

**Additional context**
N/A

**Comment by docsbryce** [comment]
Hi again, @DumbassDev! Please include this on the feedback site as well. :)
https://feedback.minecraft.net/hc/en-us
