### ISSUE TITLE
[Feature Request] Custom Commands

### ISSUE THREAD

**Issue by DumbassDev** [MicrosoftDocs/minecraft-creator#402]
**Is your feature request related to a problem? Please describe.**
It is currently quite annoying to develop features that require user interaction in a user-friendly manner. Although the tools do exist to gather user input using things such as UI, finding a UX-friendly way to trigger these things can be complicated.

**Describe the solution you'd like**
I am suggesting some way to create custom commands that users can run in game. It would also be nice for this to come with some form of permissions system (or maybe just the ability to check if a player is opped). The best implementation of this that I can think of is a new class:
`new minecraft.CustomCommand(String commandName, ?CommandArgument[] arguments)`

As for hanling arguments, I would recommend another class. As mentioned in the above CustomCommand constructor, you will be able to pass an array of these to the command's constructor.
`new minecraft.CommandArgument(string name, string type, bool required)`

**Describe alternatives you've considered**
The current solution is to create "commands" which use a prefix. See my [prefix command handler](https://github.com/DumbassDev/Gametest-CommandHandler) for a very basic implementation of this.

**Additional context**
N/A

**Comment by docsbryce** [comment]
Hi, @DumbassDev! The best place to make feedback like this is here on the Minecraft website. I'm sure this type of detailed feedback will be appreciated!
https://feedback.minecraft.net/hc/en-us

**Comment by DumbassDev** [comment]
> Hi, @DumbassDev! The best place to make feedback like this is here on the Minecraft website. I'm sure this type of detailed feedback will be appreciated!
> https://feedback.minecraft.net/hc/en-us

Will do, thanks!
