### ISSUE TITLE
[feature request][gametest] method for entity class that lets it pathfind to a certain location

### ISSUE THREAD

**Issue by ANightDazingZoroark** [MicrosoftDocs/minecraft-creator#403]
it would be great if there was a method for the entity class that made it so you can make entities pathfind to a location like this:
```
entity.pathfindToLocation(location: IVec3, number: speed)
```
it should take into account the pathfinding components of the entity ur using it on, and make it return false if it cannot pathfind to that location

**Comment by docsbryce** [comment]
Hey, @ANightDazingZoroark! Thank you for raising this request. The best place to make feedback like this is here on the Minecraft website. 
https://feedback.minecraft.net/hc/en-us
