### ISSUE TITLE
rider_count filter examples are using invalid syntax.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#405]
**These two examples are using invalid syntax as the value.**

Example `#1` has an invalid string value `"0"`,
`{ "test": "rider_count", "subject": "self", "operator": "equals", "value": "0" }`

Example `#2` has an invalid string value `"0"`,
`{ "test": "rider_count", "value": "0" }`

The last example is showing the correct integer value usage of `0`
`{ "test": "rider_count", "subject": "self", "operator": "==", "value": 0 } `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb078a47-321e-c6d8-da62-764209999d79
* Version Independent ID: 124fa3fa-c428-4115-cc63-6757782e41bd
* Content: [Entity Documentation - rider_count](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/filters/rider_count)
* Content Source: [creator/Reference/Content/EntityReference/Examples/Filters/rider_count.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/Filters/rider_count.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-josjones**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!

**Comment by StealthyExpertX** [comment]
@v-jeffkim Seems this was not fully fixed, I just reviewed the page and it still has syntax errors with it using strings for the count for the other two examples?
