### ISSUE TITLE
.mcstructure NBT file format

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#406]
**Describe the missing content**
The NBT structure of `.mcstructure` files doesn't appear to be documented anywhere.

I attempted to [post my findings](https://gist.github.com/tryashtar/87ad9654305e5df686acab05cc4b6205), but there's only so much experimentation can do. We need complete documentation that can only be written by people with access to the source code.

**Comment by IanSSenne** [comment]
hey @tryashtar I have found the documentation here to be fairly accurate and have successfully used it to read/write structure files.
https://wiki.bedrock.dev/nbt/mcstructure.html

**Comment by tryashtar** [comment]
@JimSeaman42 Was this added? If so, would you mind linking to the page? :)
