### ISSUE TITLE
"behavior.avoid_block" missing docs on "target_selection_method" supported values

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#407]
minecraft:behavior.avoid_block is missing documentation on "target_selection_method" supported values like the only one that seems to be shown is "nearest", with no others listed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c33eb1af-5377-48b1-c769-e4f4b9a45e0c
* Version Independent ID: c33eb1af-5377-48b1-c769-e4f4b9a45e0c
* Content: [Entity Documentation - minecraft:behavior.avoid_block](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_avoid_block)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_avoid_block.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_avoid_block.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by JDHeaden** [comment]
It looks like you're right. Every mob example that uses "avoid_block" uses "nearest." 

When bees use a similar behavior, move_to_block, which also uses target_selection_method, the default is "random" - but that wouldn't make sense for a mob to avoid random blocks.
