### ISSUE TITLE
[Syntax Issues] I found a few syntax issues with the examples provided.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#408]
Here's a list of the behavior examples:

I picked ones at random that ended up having bad syntax with trailing commas and my suggestion to the documentation team would be that you need to do a pass through all documentation to check for there are commas or other syntax errors.

Here are examples of current known issues, I'm sure there are many more that I haven't listed.
**minecraft:behavior.barter**
```
this has a trailing comma in the second example.

"minecraft:behavior.barter": {
  "priority": 3
},
```

**minecraft:behavior.break_door**
```
this has a trailing comma in the example.

"minecraft:behavior.break_door":{
    "priority": 2,
}
```

**minecraft:behavior.breed**
```
this has a trailing comma in all examples.

"minecraft:behavior.breed":{
    "priority": 1,
    "speed_multiplier": 3.0,
}

"minecraft:behavior.breed": {
  "priority": 3,
  "speed_multiplier": 1.0
},
```

**minecraft:behavior.drink_milk**
```
this has a trailing comma in the example.

"minecraft:behavior.drink_milk": {
    "cooldown_seconds": 5.00
},
```

**minecraft:behavior.door_interact**
```
this has a trailing comma in the example.

"minecraft:behavior.door_interact":{
    "priority": 2,
}
```

**minecraft:behavior.dragondeath**
```
this has a trailing comma in the example.

"minecraft:behavior.dragondeath":{
    "priority": 1,
}
```

**Comment by JDHeaden** [comment]
Good catches! I have fixed all the ones in the behavior files, and I'll keep an eye out for more. Thanks!
