### ISSUE TITLE
[GAMETEST] sub ms time fetching

### ISSUE THREAD

**Issue by IanSSenne** [MicrosoftDocs/minecraft-creator#409]
**Is your feature request related to a problem? Please describe.**
with the new watchdog system warning of ticks more than 2ms it would be useful to be able to get a sub ms time value.
this would enable us to better be able to facilitate custom task dispatching where a task can run for less than a millisecond

**Describe the solution you'd like**
I would like to see an implementation similar to the browser/node performance api where you can query time since initialization with a high resolution time stamp.

**Describe alternatives you've considered**
N/A - There are no alternative solutions without making native calls unavailable to gametest scripts

**Comment by mammerla** [comment]
Feature request for high resolution timer - got it! We're looking at ways to add this in.
