### ISSUE TITLE
[GameTest][feature] Player Permissions

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#410]
BDS can't set player permissions.
There are just 3 permission levels (Visitor, Member and Operator).

> I've tried `/ability` but
I have to enable Education Edition;
It doesn't have most of those permissions;
The permissions it has are kinda broken.

**Describe the solution you'd like**
Add API for player permissions.
Or just fix `/ability` and allow us to use without Education Edition.
> Member
Operator
Visitor
Custom
>> attackmobs
attackplayers
build
doorsandswitches
flySpeed
flying
instabuild
invulnerable
lightning
mayfly
mine
op
opencontainers
teleport
walkSpeed

**Describe alternatives you've considered**
`/ability` broken

**Comment by ConsoleTerm** [comment]
I love this idea we need more stuff for server managment in the Gametest.

**Comment by mammerla** [comment]
Server admin API likely. @Worldwidebrine would this be OK if it was dedicated-server only?

**Comment by Worldwidebrine** [comment]
> Server admin API likely. @Worldwidebrine would this be OK if it was dedicated-server only?

No, I think. I don't get it.
Isn't abilities related to players? They exist not only in permissions.json but also in player NBT.
What can be bad if it doesn't reuqire dedicated server?
If we are talking about allowlist then it's okay to be dedicated-server only, I guess.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
