### ISSUE TITLE
Material documentation

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#411]
**Describe the missing content**
Materials (e.g. `entity.material`) don't seem to be documented anywhere. We need to know:
* What is the full schema? What do all the fields do, and what possible values are there?
* How does inheritance work?
* What do all of the vanilla materials look like? As in, visually, with screenshots.

**Comment by MiemieMethod** [comment]
> **Describe the missing content** Materials (e.g. `entity.material`) don't seem to be documented anywhere. We need to know:
> 
> * What is the full schema? What do all the fields do, and what possible values are there?
> * How does inheritance work?
> * What do all of the vanilla materials look like?

If you are skilled with machine translator or familiar with Chinese, you can refer these Chinese docs:
Full schemas: https://wiki.bedev.cn/page/Manual:%E6%9D%90%E8%B4%A8
Fields / Inharitance usage: above and https://mc.163.com/dev/mcmanual/mc-dev/mcguide/16-%E7%BE%8E%E6%9C%AF/7-%E6%9D%90%E8%B4%A8%E4%B8%8E%E7%9D%80%E8%89%B2%E5%99%A8/%E6%9D%90%E8%B4%A8%E7%9A%84%E5%88%86%E7%B1%BB.html?catalog=1
Vanilla usage: https://mc.163.com/dev/mcmanual/mc-dev/mcguide/16-%E7%BE%8E%E6%9C%AF/7-%E6%9D%90%E8%B4%A8%E4%B8%8E%E7%9D%80%E8%89%B2%E5%99%A8/%E6%9D%90%E8%B4%A8%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E.html?catalog=1

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
