### ISSUE TITLE
ReleaseBuildDocumentation folder

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#412]
Can we please incorporate the docs in [ReleaseBuildDocumentation](https://github.com/MicrosoftDocs/minecraft-creator/tree/main/Utilities/ReleaseBuildDocumentation) to the repo proper?

It's just a bunch of folders with mostly identical files. This stuff does need to be documented somewhere but doing it per-version isn't very helpful, especially since you can't tell what's different between changes unless you compare back and forth looking for differences that may not even exist.

**Comment by JDHeaden** [comment]
Those were files we were using for internal parts of the release process. They have been removed. Thanks for bringing it to our attention.
