### ISSUE TITLE
[GameTest] entityHurt and entityHit event doesn't trigger when the player dies

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#413]
**Describe the bug**
When listening to `entityHurt` or `entityHit` event, death of a player doesn't trigger the event, however death of any other entity does, which causes inconsistency and missing functionality. 

**To Reproduce**
1. Enter a world with the script below loaded.
```
world.events.entityHit.subscribe(event => entityHitEvent(event));
world.events.entityHurt.subscribe(event => entityHurtEvent(event));

function entityHitEvent(eventData) {
    console.warn(eventData.hitEntity.id);
    console.warn(eventData.hitEntity.getComponent('health').current);
}

function entityHurtEvent(eventData) {
    console.warn(eventData.hurtEntity.id);
    console.warn(eventData.hurtEntity.getComponent('health').current);
}
```
2. Kill a player.
3. No data will be returned to the content log by the `console.warn()` functions when the player dies.

**Expected behavior**
`entityHurt` and `entityHit` should trigger when the player dies.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19.30.22

**Additional context**
This bug makes it impossible to detect player deaths, which could be useful for many creations and while testing add-ons.

**Comment by ConsoleTerm** [comment]
This is fixed! in ![Changelog 1.19.40.22](https://feedback.minecraft.net/hc/en-us/articles/9329824511629-Minecraft-Beta-Preview-1-19-40-22)

**Comment by ConsoleTerm** [comment]
Also for entityHit was fixed some time ago, i can´t remember now but both now works. Can close this issue

**Comment by PavelDobCZ23** [comment]
As @ConsoleTerm mentions, it was fixed - closing the issue.
