### ISSUE TITLE
[Missing Component] "game_event_movement_tracking" is missing in the docs

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#416]
**Describe the missing content**
This component is found on the Allay mob but does not seem to have any documentation on what arguments it supports or what it actually does.

**Vanilla usage example**
```json
      "minecraft:game_event_movement_tracking": {
        "emit_flap": true
      }
```
     

**Additional context**
Please make sure to document thoroughly so no arguments/parameters get missed during documenting.

**Comment by JDHeaden** [comment]
This document has been created. To save you a click, here is more information about it. Thanks!

minecraft:game_event_movement_tracking allows an entity to emit entityMove, swim and flap game events, depending on the block the entity is moving through. It is added by default to every mob. Add it again to override its behavior.
