### ISSUE TITLE
[Documentation Issue] Please provide up-to-date docs on "ambient_sound_interval"

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#417]
The current documentation of the **minecraft:ambient_sound_interval** is out of date and does not have good examples of the new supported syntax for molang usage which can be found in the latest Allay mob behavior files.

Please update the examples and documentation on this component to show that molang is supported and fully documents the structure and any other missing arguments/parameters.

My suggestion to the docs team is to go and check for all 1.19 behavior additions for any other changes that were not mentioned or noted in any official changelog having up-to-date documentation is very important for creators in the community and ones that work full-time on the Minecraft Marketplace if you need any help, I'm happy to volunteer my time.

My gut tells me if this was missed then some other stuff was missed as well.

```json
      "minecraft:ambient_sound_interval": {
        "value": 5.0,
        "range": 5.0,
        "event_name": "ambient",
        "event_names": [
          {
            "event_name": "ambient.tame",
            "condition": "query.is_using_item"
          },
          {
            "event_name": "ambient",
            "condition": "!query.is_using_item"
          }
        ]
      }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9623a9-fdc3-0d63-3680-28446d8aae6b
* Version Independent ID: e751da80-5106-7d8c-5382-e81f623a0e57
* Content: [Entity Documentation -minecraft:ambient_sound_interval](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_ambient_sound_interval)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_ambient_sound_interval.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_ambient_sound_interval.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
