### ISSUE TITLE
[Missing Component] "vibration_listener" is missing in the docs

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#418]
This component is found on the Allay and many other mobs but does not seem to have any documentation on what arguments it supports or what it actually does with the new vibration behaviors added by the shulk blocks and warden.

Vanilla usage example

`"minecraft:vibration_listener": {}`

Please make sure to document thoroughly so no arguments/parameters get missed during documenting.

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!

**Comment by StealthyExpertX** [comment]
Can you link me to the source where this was added?
