### ISSUE TITLE
[Documentation Issue] Please provide up-to-date docs on "minecraft:interact"

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#419]
The documentation on **"minecraft:interact"** is out of date and missing some arguments in the new 1.19+ update.

New arguments that I saw in the vanilla examples, there are probably others that are missing please go through and double-check any new 1.19 or changed behavior files for additions.

```

"give_item": true,
"take_item": true
						
```

**Vanilla usage example**
```json
			"minecraft:interact": {
				"interactions": [
					{
						"on_interact": {
							"filters": {
								"all_of": [
									{
										"test": "is_family",
										"subject": "other",
										"value": "player"
									}
								]
							}
						},
						"give_item": true,
						"take_item": true,
						"interact_text": "action.interact.allay"
					}
				]
			}
```

**Additional context**
Double-check for any other missing arguments or new parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b51382-166e-b788-0518-3a2380f2951e
* Version Independent ID: f5e8a1dd-7026-f121-5cf6-5b7e5bbc4d91
* Content: [Entity Documentation - minecraft:interact](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_interact)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_interact.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_interact.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
