### ISSUE TITLE
Missing filters

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#42]
The following filters are missing from the filters list

- in_block
- in_contact_with_water
- in_water
- weather

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c55f411-260d-d48c-c333-af03709fea6a
* Version Independent ID: 81e10c05-9c63-1499-c1b2-151fdabd6c2c
* Content: [FilterList](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/filterlist)
* Content Source: [creator/Reference/Content/EntityReference/Examples/FilterList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/FilterList.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Investigating.

**Comment by JDHeaden** [comment]
Added: in_block and in_contact_with_water

confirmed: in_water and weather 

Staged for next release.
