### ISSUE TITLE
[Filter Issues] Missing json syntax highlighting with "has_silk_touch" and missing in filter list.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#420]
The filter "has_silk_touch" is missing syntax highlighting.
![image](https://user-images.githubusercontent.com/17806994/185777110-1bbd8eb1-5f8f-4e8a-84f5-d70a78ef3dc5.png)

It's also missing in the filters list here.
https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/filterlist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19deb7d4-e51d-e58a-4871-3a4d6b42845f
* Version Independent ID: 19deb7d4-e51d-e58a-4871-3a4d6b42845f
* Content: [Entity Documentation - has_silk_touch](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/filters/has_silk_touch)
* Content Source: [creator/Reference/Content/EntityReference/Examples/Filters/has_silk_touch.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/Filters/has_silk_touch.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
