### ISSUE TITLE
Current location of resource packs

### ISSUE THREAD

**Issue by mattfoster-zindred** [MicrosoftDocs/minecraft-creator#422]
For those following this tutorial... current location of minecraft appdata folder can be found by typing:
win+r
%appdata%\.minecraft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ee92b3-df1e-3f02-7b62-e13798b131a8
* Version Independent ID: 7d9f0488-2919-4cca-20ee-097af4e47a05
* Content: [Getting Started With Minecraft Add-Ons](https://docs.microsoft.com/en-us/minecraft/creator/documents/gettingstarted)
* Content Source: [creator/Documents/GettingStarted.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/GettingStarted.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by JimSeaman42** [comment]
Thank you for your feedback!
