### ISSUE TITLE
[GameTest] Entity components are missing the property 'id'.

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#425]
**Describe the bug**
All classes extending `IEntityComponent` class should have a constant property `id`, however it isn't actually present on the objects returned by functions like `Entity.getComponents()`.

**To Reproduce**
1. Enter a world with the script below running
```
world.events.itemUse.subscribe(eventData => {
    const player = eventData.source;
    const item = eventData.item.id;
    if (item === "minecraft:stick") {
        for (const entity of [...player.dimension.getEntities()]) {
            for (const component of entity.getComponents()) {
                console.warn(component.id);
            }
        }
    }
});
```
2. Use the stick item in game and watch the result from content log (GUI must be enabled). The only result is `undefined`.

**Expected behavior**
Accessing property `id` of classes extending `IEntityComponent` should return their id, like `minecraft:health`.

**Actual behavior**
Accessing property `id` of classes extending `IEntityComponent` returns `undefined`.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19.30.22

**Additional context**
This problem makes it impossible to tell apart entity components by their ids.

**Comment by ConsoleTerm** [comment]
I also don´t get it, what is problem? There is execepted behavior but no Actual behavior.

**Comment by PavelDobCZ23** [comment]
> I also don´t get it, what is problem? There is expected behavior but no Actual behavior.

My bad, I've just updated it to include the *actual* behavior.

**Comment by ConsoleTerm** [comment]
This issue is better to close because is tagged as `[[Missing Content](https://github.com/MicrosoftDocs/minecraft-creator/labels/Missing%20Content)]`, also can i ask when did you did last test because it works for me but i am not sure.
I will look at this issue, in next week.

**Comment by PavelDobCZ23** [comment]
> This issue is better to close because is tagged as `[[Missing Content](https://github.com/MicrosoftDocs/minecraft-creator/labels/Missing%20Content)]`, also can i ask when did you did last test because it works for me but i am not sure. I will look at this issue, in next week.

I've just checked it and the issue still persists.

**Comment by ConsoleTerm** [comment]
> > This issue is better to close because is tagged as `[[Missing Content](https://github.com/MicrosoftDocs/minecraft-creator/labels/Missing%20Content)]`, also can i ask when did you did last test because it works for me but i am not sure. I will look at this issue, in next week.
> 
> I've just checked it and the issue still persists.

I have test in the latest beta, for Object prototype is .typeId for static property its called componentId
so
```js
let component = entity.getComponent(EntityInventoryComponent.componentId);
console.warn(component.typeId); //minecraft:inventory
```
I think its not time to close this issue bc some class dont have typeId for prototypes

**Comment by PavelDobCZ23** [comment]
> > > This issue is better to close because is tagged as `[[Missing Content](https://github.com/MicrosoftDocs/minecraft-creator/labels/Missing%20Content)]`, also can i ask when did you did last test because it works for me but i am not sure. I will look at this issue, in next week.
> > 
> > 
> > I've just checked it and the issue still persists.
> 
> I have test in the latest beta, for Object prototype is .typeId for static property its called componentId so
> 
> ```js
> let component = entity.getComponent(EntityInventoryComponent.componentId);
> console.warn(component.typeId); //minecraft:inventory
> ```
> 
> I think its not time to close this issue bc some class dont have typeId for prototypes

Which classes don't have it for their prototypes though?

**Comment by ConsoleTerm** [comment]
> > > > This issue is better to close because is tagged as `[[Missing Content](https://github.com/MicrosoftDocs/minecraft-creator/labels/Missing%20Content)]`, also can i ask when did you did last test because it works for me but i am not sure. I will look at this issue, in next week.
> > > 
> > > 
> > > I've just checked it and the issue still persists.
> > 
> > I have test in the latest beta, for Object prototype is .typeId for static property its called componentId so
> > 
> > ```js
> > let component = entity.getComponent(EntityInventoryComponent.componentId);
> > console.warn(component.typeId); //minecraft:inventory
> > ```
> > 
> > I think its not time to close this issue bc some class dont have typeId for prototypes
> 
> Which classes don't have it for their prototypes though?

For components of entities its fine I think its missing from item components and block one`s

**Comment by ConsoleTerm** [comment]
This issue should be closed, i will create new one for item components

**Comment by PavelDobCZ23** [comment]
> This issue should be closed, i will create new one for item components

Yeah.
