### ISSUE TITLE
[gametest][bug] Missing iterators from natively given arrays. (beforeExplosion and explosion events)

### ISSUE THREAD

**Issue by ConsoleTerm** [MicrosoftDocs/minecraft-creator#426]
When trying to use Symbol.iterator from the native given array [impactedBlocks](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/explosionevent#impactedblocks) from the events ([explosion](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/explosionevent) and [beforeExplosion](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/beforeexplosionevent)), then Symbol.iterator completly missing from the given [impactedBlocks](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/explosionevent#impactedblocks) array.

## **To Reproduce** 
- `subscribe explosion or beforeExplosion event`
- `try to for-of impactedBlocks or get iterator from the array.`

### Test code
```js
world.events.explosion.subscribe(({impactedBlocks})=>{
    console.warn('Has Iterator: ' + (Symbol.iterator in impactedBlocks));
    for(const loc  of impactedBlocks) {} //throws errro: TypeError: value is not iterable
});
```
Unexcepted output
```txt
[Scripting][warning]- Has Iterator: false
[Scripting][error]- TypeError: value is not iterable  <>...(stack trace)
```

### **Expected behavior**
Natively given arrays should always have an Symbol.iterator available.

### **Testing information:**
 - Platform: Laptop - Windows 11
 - MC Version: 1.19.21 - Client UWP
 - Gametest modules versions: [0, 1, 0]

**Comment by mrpatches123** [comment]
forEach works.

**Comment by ConsoleTerm** [comment]
> forEach works.

Ya basic for too but natively given arrays doesn´t have iterator symbol.

**Comment by FrankyRay** [comment]
This has some issue with `BlockPermutation` -> `validValues` too
![image](https://user-images.githubusercontent.com/61337607/188907456-50d16f96-e321-4983-9d72-f6c07d5e1e3c.png)

**Comment by InnateAlpaca** [comment]
Hello http headers too give this error.
the following expression doesn't work
```
for (const header of response.headers){
     //something
}
```
while accessing the headers by index `response.headers[0]` (or by `response.headers.ForEach()`) would seem to work.

**Comment by ConsoleTerm** [comment]
> Hello http headers too give this error. the following expression doesn't work
> 
> ```
> for (const header of response.headers){
>      //something
> }
> ```
> 
> while accessing the headers by index `response.headers[0]` (or by `response.headers.ForEach()`) would seem to work.

My example was fixed, API gets new Vector3 implementation and get/set methods for property,
i am closing this issue, but you can create new one if this is still current for yours use case
