### ISSUE TITLE
Location in a resource/behavior pack for minecraft:records JSON information

### ISSUE THREAD

**Issue by DonkeyCow74** [MicrosoftDocs/minecraft-creator#429]
I am trying to change the duration of how long a record plays (I am putting in my own song). I found the example and understand that I should replace parts of it to match my record. I cannot find where to place this information though. Is there a certain file path I need to put the JSON file into? or an already existing JSON file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea43975-88db-e45b-d5a9-fb1ad31527bf
* Version Independent ID: cea43975-88db-e45b-d5a9-fb1ad31527bf
* Content: [Item Documentation - minecraft:record](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_record)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_record.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_record.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
