### ISSUE TITLE
Blockbench Settings

### ISSUE THREAD

**Issue by i-am-rad** [MicrosoftDocs/minecraft-creator#432]
Note: The web based version of blockbench does not show the settings > preferences > export > Minecraft education edition setting as of 9/2/2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79c7652f-5c4e-768c-ca52-1ac2ff1790f5
* Version Independent ID: 794cb3ed-7c30-59af-7d62-3f109de1d553
* Content: [Getting Started with Minecraft Entity Wizard](https://docs.microsoft.com/en-us/minecraft/creator/documents/minecraftentitywizard)
* Content Source: [creator/Documents/MinecraftEntityWizard.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/MinecraftEntityWizard.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by JDHeaden** [comment]
Good catch! I have noted this in the Entity Wizard tutorial and the change will be visible after the next release. Thank you!
