### ISSUE TITLE
click minecraft:crafting_table will redirect to wrong place

### ISSUE THREAD

**Issue by HappyTigerX** [MicrosoftDocs/minecraft-creator#433]
minecraft:crafting_table will redirect to minecraft:creative_category

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2d3b8d-1c13-9c44-e452-d358e9a275cd
* Version Independent ID: dacf9f8f-0632-e8dd-092f-80b0c378ba9e
* Content: [Block Documentation - Block Components List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponentslist)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponentsList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponentsList.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by docsbryce** [comment]
This change is live! Thanks for reporting.
