### ISSUE TITLE
skinpack minecraft PE (BedRock) Not Showing

### ISSUE THREAD

**Issue by SoniaAguirre** [MicrosoftDocs/minecraft-creator#434]
I followed the steps here and my skin pack is running ok excepting the skin preview not showing when selected

any reason why this happens? how can I fix it?

![Screenshot_2022-09-04-18-31-14-277_com mojang minecraftpe](https://user-images.githubusercontent.com/110629622/188339826-57bffb35-8a19-455b-a4ad-3d313d594451.jpg)
![Screenshot_2022-09-04-18-31-17-985_com mojang minecraftpe](https://user-images.githubusercontent.com/110629622/188339832-94d22731-d640-4a2d-8c2a-ca05a95712cf.jpg)

[Escribir comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Cómo empaquetar un pack de aspecto](https://docs.microsoft.com/es-mx/minecraft/creator/documents/packagingaskinpack)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.es-MX/blob/live/creator/Documents/PackagingASkinPack.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
