### ISSUE TITLE
Change in the Loot Table for Written books.

### ISSUE THREAD

**Issue by Caparnicus** [MicrosoftDocs/minecraft-creator#438]
[Enter feedback here]
I think the setup for the loot table isn't used anymore it is writting on the forum like:
          "type": "item",
          "name": "minecraft:written_book",
          
This sends back error codes when tried. The two lines now work as one line:
          "item": "minecraft:written_book",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014c7765-6d2e-34ec-1cf1-81cc763368f7
* Version Independent ID: 6bfd8d2e-4893-6fa2-2fd3-a63bad5104b4
* Content: [Loot and Trade Table Functions](https://docs.microsoft.com/en-us/minecraft/creator/documents/lootandtradetablefunctions)
* Content Source: [creator/Documents/LootAndTradeTableFunctions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/LootAndTradeTableFunctions.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JDHeaden** [comment]
Good catch! Thank you. The change is made and should be visible after the next document release.
