### ISSUE TITLE
The "header" field is incorrectly shown as "heSader" in the example.

### ISSUE THREAD

**Issue by abrightmoore** [MicrosoftDocs/minecraft-creator#44]
There is a typo in the example text for the behavior pack manifest.json. The "header" field is incorrectly shown as "heSader" in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3ad989-cd74-1b9a-d07c-500fc80fdaf7
* Version Independent ID: 2403daea-89fc-ce01-badf-56e6752f562b
* Content: [Introduction To Behavior Packs](https://docs.microsoft.com/en-us/minecraft/creator/documents/behaviorpack)
* Content Source: [creator/Documents/BehaviorPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/BehaviorPack.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
Addressed, Added to hotfix #1

**Comment by mardb** [comment]
Addressed in [Hotfix for R17: Caves and Cliffs: Part 1](https://github.com/MicrosoftDocs/minecraft-creator-pr/pull/189#event-4930380792)
