### ISSUE TITLE
Chunker - Bedrock Maps not preserved when trimming

### ISSUE THREAD

**Issue by SkgSadrCom** [MicrosoftDocs/minecraft-creator#441]
After trimming a Bedrock 1.19.20 world, maps (in hand, frames, etc.) went from unlocked with a zoom range 3/4, to locked with a zoom range of 4/4. Problem also appeared with Treasure Maps (became 4/4 + locked) and will probably happen with all maps.

**To Reproduce**
1) Create bedrock world with maps. (Treasure, regular zoomed to 3/4, etc.)
2) Upload world to chunker. 
3) Select same version to export.
4) Trim some small, unrelated part. (I used the Nether.) (Trimming may not be required, but was what I was doing.)
5) Download world and load in minecraft.
6) Look at maps in downloaded world. Map is now marked Locked (new icon) and is range 4/4. Location on the map is not right compared to 3/4 range.

Original Map is 3/4, unlocked.
![OriginalMap1](https://user-images.githubusercontent.com/114077609/191503345-bccb7687-0b04-493f-9377-b3dec33f9262.png)
Note player location, etc.
![OriginalMap2](https://user-images.githubusercontent.com/114077609/191503338-06ddcf72-cbdf-4f8b-8860-f4736894bb71.png)
After Conversion, map is 4/4 and locked:
![AfterChunker1](https://user-images.githubusercontent.com/114077609/191503478-b80365de-08cb-41a1-8764-114f6d7113c7.png)
Player location is changed:
![AfterChunker2](https://user-images.githubusercontent.com/114077609/191503533-202c9c1d-b288-441d-ac0d-aafbabb2fbee.png)

**Expected behavior**
Maps should be preserved.

**Comment by JimSeaman42** [comment]
Thank you for reaching out, and I'm sorry to hear that you're having problems!

We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
