### ISSUE TITLE
Issue when trying to upload a world folder/zip to convert.

### ISSUE THREAD

**Issue by Hauntmore** [MicrosoftDocs/minecraft-creator#442]
I am trying to convert my Java world to bedrock and I am getting the following issue:

**To Reproduce**
1. Go to "https://chunker.app/#/".
2. Click on "Choose world folder" or "Upload archive".
3. Wait for the upload to continue.4. 
4. Click the button to convert and wait.
5. See the error in web console (developer tools), which is either "WebSocket connection to 'wss://chunker.app/' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 54 - Connection reset by peer)" or "The request timed out"

**Expected behavior**
I expected the folder to convert itself.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS M1 Silicon
 - Browser: Safari

**Additional context**
I don't see why I would get the issue as my folder of the world save is only ~350 MB.

Please comment if further details need to be provided/solution is presented.

**Comment by FormallyMyles** [comment]
Would you be able to try a different browser? / Try with a smaller world?

**Comment by kakinnun** [comment]
Closing as no response from original reporter.
