### ISSUE TITLE
Chunker does not convert colored signs correctly

### ISSUE THREAD

**Issue by Fabrimat** [MicrosoftDocs/minecraft-creator#444]
**Describe the bug**
Chunker does not convert signs colored with a dye correctly, they will be just with default color.
I tryied only from Java 1.18.2 to Bedrock 1.18.30.

**To Reproduce**
1. Create a world on Java
2. Place a sign and write something on it
3. Use a white dye
4. Convert the world to Bedrock
5. See the sign not being colored

**Chunker version:**
- UI 1.5.14
- APP 1.7.8
- CLI 1.17.3

**Comment by FormallyMyles** [comment]
This should now be fixed (though it's not 1:1 since Bedrock allows any color), thank you for reporting it!

**Comment by Fabrimat** [comment]
Can confirm the issue is fixed on Chunker 1.17.4. Thanks!
