### ISSUE TITLE
Broken link to class SimulatedPlayer

### ISSUE THREAD

**Issue by depressed-pho** [MicrosoftDocs/minecraft-creator#446]
In this page there is a broken link to a very interesting class `SimulatedPlayer`, which is not only undocumented but also not exported by the module `mojang-minecraft`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72aa95ec-25dc-300d-8d91-b37900e24935
* Version Independent ID: cd884fd2-aa41-a836-782b-f419c7327426
* Content: [mojang-minecraft.Player Class](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/player)
* Content Source: [creator/ScriptAPI/mojang-minecraft/Player.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/Player.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by AdamRaichu** [comment]
Found it.

[https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-gametest/simulatedplayer](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-gametest/simulatedplayer)

**Comment by kakinnun** [comment]
I've updated the link internally. It should be correct on our next content push.
