### ISSUE TITLE
`minecraft:durability` documentation #example does not match #parameters

### ISSUE THREAD

**Issue by AdamRaichu** [MicrosoftDocs/minecraft-creator#447]
The example code gives `minecraft:durability.damage_chance` as a float, and the table labels it as float, but the table shows "Defined as an int range with min and max value."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f5e6749-eda6-8475-3493-2b0fbaf2d13b
* Version Independent ID: 5959dcb4-f342-b02a-3168-46195001a203
* Content: [Item Documentation - minecraft:durability](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_durability)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_durability.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_durability.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JDHeaden** [comment]
Good catch! Fixed and should be out with the next release :)
