### ISSUE TITLE
`SimulatedPlayer` class is missing

### ISSUE THREAD

**Issue by AdamRaichu** [MicrosoftDocs/minecraft-creator#448]
The `mojang-minecraft.Player` page says the `Player` class is extended by the `SimulatedPlayer` class. However, the link to the page leads to a 404 page. (links to [this nonexistent page](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/SimulatedPlayer.md))

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72aa95ec-25dc-300d-8d91-b37900e24935
* Version Independent ID: cd884fd2-aa41-a836-782b-f419c7327426
* Content: [mojang-minecraft.Player Class](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/player#getitemcooldown)
* Content Source: [creator/ScriptAPI/mojang-minecraft/Player.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/Player.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by AdamRaichu** [comment]
Found it. Should link to this page.

[https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-gametest/simulatedplayer](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-gametest/simulatedplayer)

**Comment by ConsoleTerm** [comment]
> Found it. Should link to this page.
> 
> https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-gametest/simulatedplayer

U should close this issue.
