### ISSUE TITLE
Permute Type spawn rule component has incorrect type for `guaranteed_count`

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#451]
`guaranteed_count` field is documented as string, but should be integer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8ba0269-f5c8-888c-1069-4c07e842ec85
* Version Independent ID: b8ba0269-f5c8-888c-1069-4c07e842ec85
* Content: [Entity Documentation - minecraft:permute_type](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/definitions/nestedtables/permute_type)
* Content Source: [creator/Reference/Content/EntityReference/Examples/Definitions/NestedTables/permute_type.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/Definitions/NestedTables/permute_type.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by JimSeaman42** [comment]
Thanks for reaching out! The documentation will be updated with the next release.
