### ISSUE TITLE
There are serious errors when converting the world to chunker.

### ISSUE THREAD

**Issue by DGKaru** [MicrosoftDocs/minecraft-creator#453]
**Describe the bug**
When I convert the world from Bedrock Edition to Java Edition, most sea lantern blocks disappear. Also, map images within the world are all mixed up.

**To Reproduce**
When I convert the Bedrock Edition World to the 1.19 version of Java Edition World with the chunker app, most of the sea lanterns disappear except for the sea lanterns close to the spawn point when I run the world. Even if I replace the sea lantern with another block, the replaced block disappears. And my world has a lot of map images, and when I convert the world, all of these maps are mixed up and unrecognizable.

**Screenshots**
![2022-10-04_21 46 52](https://user-images.githubusercontent.com/89735034/193824380-c7283bbb-57b0-4f17-a13f-e873044802c8.png)
![2022-10-04_21 46 59](https://user-images.githubusercontent.com/89735034/193824388-96aace6e-9f6b-4db9-9ff1-705995ebccb6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
My World is a Bedrock edition that I worked very hard on for four years. If I open the server with a bedrock edition, the game often stops, so I have to convert it to a Java edition and open it. Therefore, please correct the error as soon as possible so that I can open the server with my world.

**Comment by kakinnun** [comment]
Closing this as it has the same outcome as this issue: https://github.com/MicrosoftDocs/minecraft-creator/issues/482
