### ISSUE TITLE
Change daylight sensor info on inverting it.

### ISSUE THREAD

**Issue by linux-coding649** [MicrosoftDocs/minecraft-creator#456]
Don't you right-click a daylight sensor to invert it? If you left click it, shouldn't it start to break?

I think this is what it should be changed to, to become more accurate:

Daylight sensor: produces different levels of power depending on the level of light it detects. It can be inverted to emit light when it detects darkness. To invert it, place one and right-click it. It will turn blue.

I play Minecraft, so I know how this works. I think before you add the info, you should check the info is correct by testing what you put up on Minecraft.

* from @linux-coding649 *
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e527e5a1-6738-9706-852a-acf24cb1ae0b
* Version Independent ID: e527e5a1-6738-9706-852a-acf24cb1ae0b
* Content: [Guide to Redstone](https://learn.microsoft.com/en-us/minecraft/creator/documents/redstoneguide)
* Content Source: [creator/Documents/RedstoneGuide.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/RedstoneGuide.md)
* Product: **gaming**
* GitHub Login: @JDHeaden
* Microsoft Alias: **v-jillheaden**

**Comment by JimSeaman42** [comment]
The word 'left' has been changed to 'right' as per your suggestion, and will display as such after the next update. Thank you for your feedback.
