### ISSUE TITLE
Using example code in `minecraft:shooter` produces errors

### ISSUE THREAD

**Issue by AdamRaichu** [MicrosoftDocs/minecraft-creator#457]
Adding the example code provided to an item components object produces the following content error. (Using `format_version: "1.16.100"`)

```
[Json][error]-upgrade items/machine.json |  -> minecraft:item -> components -> minecraft:shooter -> ammunition:  expected an array
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d69d710e-7d85-f601-ef16-c802d57013b8
* Version Independent ID: 23d79a6b-e4c7-749a-9f58-04411aafe805
* Content: [Item Documentation - minecraft:shooter](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_shooter)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_shooter.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_shooter.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by V1beR8er** [comment]
Needs to look like 

`{
					"item": "minecraft:arrow",
					"use_offhand": true,
					"search_inventory": true,
					"use_in_creative": true
				}`

As opposed to just 

`"ammunition": "arrow"`

**Comment by JimSeaman42** [comment]
Thank you for your feedback! This code has been updated in the documentation.
