### ISSUE TITLE
[Entity][feature] Why not add entity filter "molang"?

### ISSUE THREAD

**Issue by Worldwidebrine** [MicrosoftDocs/minecraft-creator#458]
Filters and molang queries have similar functions.
But molang is more flexible.
Why not merge them?
Just add a new filter "molang".
So every new molang queries can be used also in entity json.
#### I think Minecraft should focus on molang queries
Molang queries and entity filters are doing the same thing
* is_sleeping: both
* is_sneaking: both
* is_mark_variant: both
* in_water_or_rain: both
* in_water: both

But both are incomplete
* light_level: filter
* player_level: molang
* is_transforming: molang
* weather: filter

Please
1. Add all filters as queries in molang
2. Add molang as a new filter
3. Focus on molang

```json
{ // variable is true
  "test": "molang",
  "subject": "target",
  "operator": "!=", // ignored, makes no difference
  "value": "v.my_var"
  // readonly, equivalent to "q.target->v.my_var", because subject is target
}
```
```json
{ // target's target is not current entity
  "test": "molang",
  "subject": "self",
  "operator": "==", // doesn't change anything
  "value": "q.target->q.target != q.self"
}
```
```json
{ // damager is transforming
  "test": "molang",
  "subject": "damager",
  "value": "q.is_transforming"
}
```

**Comment by JimSeaman42** [comment]
Thank you for reaching out!

We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
