### ISSUE TITLE
Missing documentation for `on_hit` field in `minecraft:projectile` component

### ISSUE THREAD

**Issue by stirante** [MicrosoftDocs/minecraft-creator#46]
Projectile docs are missing the documentation for `on_hit` field. The entity examples all have this field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b64aa40-f231-4fa4-9641-df94f37d5ea2
* Version Independent ID: d10f887a-4b9b-5725-937b-99e1a4024891
* Content: [minecraft:projectile](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_projectile)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by v-josjones** [comment]
Investigating

**Comment by SirLich** [comment]
Hi, while we would obviously like definitive source-of-truth documentation, you may find it useful to know what documentation we are currently using: https://wiki.bedrock.dev/documentation/projectiles

**Comment by docsbryce** [comment]
Hi, @stirante, these changes are in review. They are currently planned for the July release. I'll update when these changes are live.

**Comment by docsbryce** [comment]
These changes are [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_projectile). Thanks for reporting!
