### ISSUE TITLE
What is the log function shown in `spawnItem.ts` code sample?

### ISSUE THREAD

**Issue by AdamRaichu** [MicrosoftDocs/minecraft-creator#461]
This page shows the following code sample

```TS
  const featherItem = new mc.ItemStack(mc.MinecraftItemTypes.feather, 1, 0);
  overworld.spawnItem(featherItem, targetLocation);
  log("New feather created!");
```

However, I can't figure out how to define the `log` function. How do I `import` this function into my code?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 681288ac-5fab-2957-46ea-c64aa520ab36
* Version Independent ID: a62f4fd8-67fd-95c5-d9c3-8c68e33e8325
* Content: [mojang-minecraft.ItemStack Class](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/itemstack)
* Content Source: [creator/ScriptAPI/mojang-minecraft/ItemStack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/ItemStack.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by AdamRaichu** [comment]
I tried using `console.log` to see if that was the function used, but using `console.log`, while it does not generate errors, also does not show in the content log. How does this work?

**Comment by DumbassDev** [comment]
@AdamRaichu If you want it to show in the content log, use `console.warn`.

**Comment by ConsoleTerm** [comment]
> Thank you!

Can you close the issue now?
