### ISSUE TITLE
Table headers are incorrect in Item Definition

### ISSUE THREAD

**Issue by AdamRaichu** [MicrosoftDocs/minecraft-creator#462]
Type is listed under Name, Name is listed under Default Value, and Default Value is listed under Type. Description column seems to be ok.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bde5bb9-4590-e158-f55f-9bb35cd47759
* Version Independent ID: a721fc70-74cb-49b8-34a7-37b27ad4691c
* Content: [Item Documentation - Item Definition Properties](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemdefinition)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemDefinition.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemDefinition.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by DumbassDev** [comment]
I've fixed this in PR #464, just waiting for it to be merged.

**Comment by kakinnun** [comment]
Looks like the PR didn't take. I've made a PR on our internal repo. This should be reflected the next time we release.
