### ISSUE TITLE
Description markdown errors

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#467]
The articles "LootReplaceEntity", "LootSpawnAndKill", and "TickJsonIntroduction" use tick marks in the description in an attempt to do `inline code`, however it doesn't render properly on the site.

![image](https://user-images.githubusercontent.com/26075577/197279065-6e3134d9-80ea-48d4-8ee0-b961bc4e45c8.png)

![image](https://user-images.githubusercontent.com/26075577/197279441-b9c3b1b4-6dc0-41ae-9a37-57762ba3ff30.png)

**Comment by kakinnun** [comment]
I don't think the original author was trying to attempt in-line code with the description. I think the wrong tick-mark was used. I've cleaned these up to use '. And this should be pushed to live in our next update.
