### ISSUE TITLE
1.19.50 components

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#468]
Please add documentation for all the components and other features added in 1.19.50

**Comment by kakinnun** [comment]
Which components/features are you referring to?

Closing as several pushes of reference documentation has gone live since this message so this may be resolved. If it isn't, let us know which components you see are missing.

**Comment by tryashtar** [comment]
I see at least these in the vanilla pack that I can't find on this repo:
* `persist_sit`
* `damage_cooldown` in `area_attack`
