### ISSUE TITLE
Missing "cameras" directory and file documentation.

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#469]
**Describe the missing content**
the new folder directory added to vanilla resource packs recently called **"cameras"** is undocumented 
and we as creators don't know how to utilize them or how the game uses them can you please provide documentation on this folder and the default camera files?

**Vanilla usage example**
Here are the vanilla files zipped up.
[cameras.zip](https://github.com/MicrosoftDocs/minecraft-creator/files/9843298/cameras.zip)

**Additional context**

![image](https://user-images.githubusercontent.com/17806994/197311388-306865d7-fb71-409b-9259-db67dbe915c2.png)

![image](https://user-images.githubusercontent.com/17806994/197311399-13482a6b-0ab2-4f35-b5a6-821fa5fd30e0.png)

![image](https://user-images.githubusercontent.com/17806994/197311407-4590cbaa-01c5-4cc9-bcb2-44fbb7dca354.png)

All of these are located here.
![image](https://user-images.githubusercontent.com/17806994/197311426-60886713-3632-4f4a-becb-f395688c778d.png)

**Comment by kakinnun** [comment]
This is not a feature currently usable by creators. When and if it ever is, we will document it accordingly. I promise. :)
