### ISSUE TITLE
Code highlighting incomplete on `minecraft:material_instances`

### ISSUE THREAD

**Issue by AdamRaichu** [MicrosoftDocs/minecraft-creator#473]
![image](https://user-images.githubusercontent.com/91494019/197898563-017975e9-c826-48cc-a052-e0cdf28b5cda.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11a717d0-e1a6-84ac-9739-08cef6c82caf
* Version Independent ID: c187c9a6-a98c-101b-fed6-2270baa772da
* Content: [Block Documentation - minecraft:material_instances](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_material_instances)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_material_instances.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_material_instances.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by AdamRaichu** [comment]
![image](https://user-images.githubusercontent.com/91494019/197898713-b0ad47a6-c0c6-4d09-b104-93ea016a1cc4.png)

**Comment by JDHeaden** [comment]
Hi Adam - Thank you for the example code! Just to confirm, you're requesting to add the examples you've given to the article?

**Comment by AdamRaichu** [comment]
I was trying to report that the colorization of the JSON seems to be slightly buggy.

**Comment by JDHeaden** [comment]
Oh! I see the issue - see the smart quotes in there? I've been on a mission to eradicate them from all of our code examples. I made sure this page didn't have any and I'm going to do some more checks. Thanks for the find!

**Comment by JDHeaden** [comment]
p.s. I fixed the missing commas, too.
