### ISSUE TITLE
Minor typo in "Dd you copy a file without updating a name?"

### ISSUE THREAD

**Issue by abrightmoore** [MicrosoftDocs/minecraft-creator#477]
[Enter feedback here]
Minor typo:

"Dd you copy a file without updating a name?"

should be

"Did you copy a file without updating a name?"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 735e3e50-fa47-9df5-a5bd-79be5c4f3618
* Version Independent ID: 735e3e50-fa47-9df5-a5bd-79be5c4f3618
* Content: [Custom Blocks Oversized Geometry](https://learn.microsoft.com/en-us/minecraft/creator/documents/customblockoversized)
* Content Source: [creator/Documents/CustomBlockOversized.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CustomBlockOversized.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JDHeaden** [comment]
Good catch - thank you! Change will be apparent after the next release.
