### ISSUE TITLE
When copying the sample json text, invalid tab characters are pasted (Win11)

### ISSUE THREAD

**Issue by abrightmoore** [MicrosoftDocs/minecraft-creator#478]
[Enter feedback here]
When copying the sample json text, invalid tab characters are pasted when using a unicode aware editor (Win11)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a69abde4-29ff-b418-da93-d3f9a3674c26
* Version Independent ID: a69abde4-29ff-b418-da93-d3f9a3674c26
* Content: [Custom Blocks Part 2 Geometry and Materials](https://learn.microsoft.com/en-us/minecraft/creator/documents/advancedcustomblocks)
* Content Source: [creator/Documents/AdvancedCustomBlocks.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AdvancedCustomBlocks.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JDHeaden** [comment]
These edits have been made to this and other documents. The change will be seen after the next release.
