### ISSUE TITLE
Detect clicks per second

### ISSUE THREAD

**Issue by keepsimple1** [MicrosoftDocs/minecraft-creator#479]
Hi, 

I'm trying to learn Minecraft scripting to record CPS (click per second) during a game play. I've read the docs but could not find a way to detect the click event. Is it something already existed but I missed? Or is the click event called a different name in Minecraft?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d089746-9c4b-101f-71f4-34140c0a6b05
* Version Independent ID: 0d089746-9c4b-101f-71f4-34140c0a6b05
* Content: [minecraft/server-ui Module](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server-ui/minecraft-server-ui)
* Content Source: [creator/ScriptAPI/minecraft/server-ui/minecraft-server-ui.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/minecraft/server-ui/minecraft-server-ui.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by mrpatches123** [comment]
https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/entityhitevent

**Comment by kakinnun** [comment]
Closing as the previous comment provides the best solution to the problem presented. There is currently no way to directly capture input, so you need to do it via another event.
