### ISSUE TITLE
Use /tp @p in Command Block NOT /tp @s. Please Document 

### ISSUE THREAD

**Issue by teachingvalues** [MicrosoftDocs/minecraft-creator#480]
[Enter feedback here]
/tp command is very useful. /tp @s in Command Block won't work. /tp @p does.  Please document this well

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 308afc9e-0653-f1eb-6637-968d0d58b6a0
* Version Independent ID: 9406eeab-b4bc-e7ad-3bc3-5810e4a4746b
* Content: [Introduction to Commands](https://learn.microsoft.com/en-us/minecraft/creator/documents/commandsintroduction)
* Content Source: [creator/Documents/CommandsIntroduction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CommandsIntroduction.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by JDHeaden** [comment]
Hi @teachingvalues - Good point! I added it to the '/tp' section of the Popular Commands Page: https://learn.microsoft.com/minecraft/creator/documents/commandspopularcommands
