### ISSUE TITLE
Minecraft Entity Wizard Exporting to Minecraft Education Edition

### ISSUE THREAD

**Issue by emilebosman39154** [MicrosoftDocs/minecraft-creator#481]
Exporting to Minecraft Education Edition

Does anyone know where the "Entity Wizard: Target Education Edition checkbox" is that according to the Minecraft Entity Wizard reference page (https://learn.microsoft.com/en-us/minecraft/creator/documents/minecraftentitywizard) is suppose to be: Go to File > Preferences > Settings > Export and scroll down to find the Entity Wizard: Target Education Edition checkbox (in the Desktop version) - BUT it is not?

Extract from Above reference pertaining to this question:

In the desktop version of Blockbench, there is a checkbox for the option to target Minecraft Education Edition. Go to File > Preferences > Settings > Export and scroll down to find the Entity Wizard: Target Education Edition checkbox. (The web-based version does not have this option.)

Thank you so much

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79c7652f-5c4e-768c-ca52-1ac2ff1790f5
* Version Independent ID: 794cb3ed-7c30-59af-7d62-3f109de1d553
* Content: [Getting Started with Minecraft Entity Wizard](https://learn.microsoft.com/en-us/minecraft/creator/documents/minecraftentitywizard)
* Content Source: [creator/Documents/MinecraftEntityWizard.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/MinecraftEntityWizard.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by JDHeaden** [comment]
@emilebosman39154 Hi! Here is a screenshot of where I can find it in my desktop version of Blockbench. I updated the article to say "radio button" instead of checkbox and added a screenshot. Please let me know if this helps. Thanks!

![Blockbench_Edu_Edition](https://user-images.githubusercontent.com/93944549/200030484-6ab6dadf-ba89-4b8f-b1fd-8d1f2c24679f.png)
