### ISSUE TITLE
Sea lanterns are not converted properly in Chunker app.

### ISSUE THREAD

**Issue by DGKaru** [MicrosoftDocs/minecraft-creator#482]
**Describe the bug**
In the former version of MCBE, sea lanterns are saved in the world as "seaLantern". However, in Chunker app, only "sea_lantern"s are converted properly. Therefore, all of "seaLantern"s are disappeared and only remain "sea_lantern"s near to the spawn point.

**To Reproduce**
1. Convert BE world (1.19.20) into JE world (1.19.2) using Chunker app.
2. When I open the world in JE, all of "seaLantern"s are disappeared.

**Screenshots**
![2022-11-02_14 38 35](https://user-images.githubusercontent.com/89735034/199409738-bc5f0914-d18f-4e0d-af64-45b1779be75e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

Chunker Version: UI 1.5.14, APP 1.7.9, CLI 1.17.6

**Additional context**
My World is made in Bedrock edition that I worked very hard on for four years. If I open the server with a bedrock edition, the game often stops, so I have to convert it to a Java edition and open it. Therefore, please correct the error as soon as possible so that I can open the server with my world.

**Comment by FormallyMyles** [comment]
The seaLantern issue should be fixed in the latest release of Chunker, unfortunately, due to the world being from a legacy format there may still be other issues.

**Comment by kakinnun** [comment]
Closing issue based on the response from the Chunker team.
