### ISSUE TITLE
blocks.json sample is missing a closing brace

### ISSUE THREAD

**Issue by abrightmoore** [MicrosoftDocs/minecraft-creator#486]
blocks.json sample is missing a closing brace

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Version Independent ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Content: [How to Add a Simple Custom Block](https://learn.microsoft.com/en-us/minecraft/creator/documents/addcustomdieblock)
* Content Source: [creator/Documents/AddCustomDieBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AddCustomDieBlock.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by Dinkelcrack95** [comment]
Hey Sir, did you get the custom block tutorial to work? I also stumbled upon the missing brace and the name of the texture-json being "terrain_texture.json" - why terrain? Also the text tutorial states you need to put "TITLE.demo:die.name=Die" into the en_US.lang, while the video says "TILE.demo:die_name=Die".

**Comment by abrightmoore** [comment]
Yes I got it to work. Here's a thread and a repo with a working sample set of files

https://twitter.com/abrightmoore/status/1588668784638046211?t=NHPGHxl04CJjzCcPsvPQqw&s=19

**Comment by JimSeaman42** [comment]
Thank you for your feedback. This issue will be resolved after the next release.
