### ISSUE TITLE
"title.demo:die.name=Die" or "tile.demo:die.name=Die" ?

### ISSUE THREAD

**Issue by Dinkelcrack95** [MicrosoftDocs/minecraft-creator#488]
[The text page says the the .lang-file needs to contain the entry "title.demo:die.name=Die", with a T while the video says it needs to be "tile.demo:die.name=Die"]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Version Independent ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Content: [How to Add a Simple Custom Block](https://learn.microsoft.com/en-us/minecraft/creator/documents/addcustomdieblock)
* Content Source: [creator/Documents/AddCustomDieBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AddCustomDieBlock.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JimSeaman42** [comment]
There was an errant 't' in the text; the field should be tile.demo:die.name=Die. This will be remedied after the next update; thank you for your feedback.
