### ISSUE TITLE
Expand the documentation for the "manifest.json" file

### ISSUE THREAD

**Issue by kgsbowtie** [MicrosoftDocs/minecraft-creator#49]
Currently, the `manifest.json` file is explained with what parts it has in it in the QuickStart, but nowhere is it documented what these parts actually do or how they function in a way that is helpful to a beginner or someone with little knowledge.

This file is the backbone of your entire Add-on or Resource Pack. Getting this file wrong is the difference between things working and not working. Bug fixes can't even begin if your `manifest.json` is malformed.

So with there being `modules`, `dependencies`, and `header` all possible requiring their own separate UUID or maybe the same UUID? I don't know, and I can't tell, and that's the problem. 

There's no clear explanation of what constitutes a dependency vs. a module or how the `manifest.json` file can be structured to obtained desired behaviors. The current documentation amounts to "put these numbers here and it should work." And that's fine for getting started, quickly, but it's not conducive for helping people truly *develop* anything. It doesn't give you an understanding of what any of the parts do or how Minecraft interprets the different parts of the file. These are important things to know if you are to build out more complicated Add-Ons or simply are trying to understand why your Add-On is failing to load or be read by Minecraft.

**Comment by docsbryce** [comment]
Hi, @kgsbowtie,

I found that we have a reference document that more clearly lays out what each of those various sections means. I'm moving a note into the `manifest.json` creation session. 

Additionally, I added a couple of Troubleshooting sections based off my own first experiences with a malformed `manifest.json` file. (Okay... maybe more than one.)
- https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack#troubleshooting
- https://docs.microsoft.com/en-us/minecraft/creator/documents/behaviorpack#troubleshooting

Let me know if you can think of more ways to improve these sections! I agree this is a key part of Add-Ons development.

I'll leave this open until those changes are live on the site. Thanks!

**Comment by docsbryce** [comment]
This link update is now live on Behavior Packs and Resource Packs. Let me know if this needs more information!
