### ISSUE TITLE
Duplicated paragraph

### ISSUE THREAD

**Issue by fabio-stein** [MicrosoftDocs/minecraft-creator#491]
I found a duplicated text on that page, suggesting to remove it.

`That means when designing experiences in Bedrock Edition, you should be aware of the different types of input players will be using. Also, keep in mind how your players are playing. While spam clicking might be OK with a mouse or even a controller, it would provide a poor experience for touch players. Keyboard players with a bow might have perfect aim, but it's a lot more difficult when using a controller or touch controls. Complex parkour might even be game-breaking for a mobile player.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8293cbae-4896-4d03-9764-09e23027db99
* Version Independent ID: 6ada8e59-a330-e8ca-5967-8c5dc67db846
* Content: [Differences Between Minecraft Bedrock Edition and Minecraft Java Edition](https://learn.microsoft.com/en-us/minecraft/creator/documents/differencesbetweenbedrockandjava)
* Content Source: [creator/Documents/DifferencesBetweenBedrockAndJava.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DifferencesBetweenBedrockAndJava.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by LRNKN** [comment]
Hey, I was just about to raise the same issue. I've made a quick edit and submitted pull request.
https://github.com/MicrosoftDocs/minecraft-creator/pull/502

**Comment by JimSeaman42** [comment]
Great catch! This will be updated with the next release.
