### ISSUE TITLE
[Script-API] [Feature Request] BlockUpdateEvent triggered when block update occurs.

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#493]
**Is your feature request related to a problem? Please describe.**
Working with block updates is currently difficult as there isn't any API that triggers with block update in a specific location.

**Describe the solution you'd like**
A simple event that gets triggered when block update happens, that is when block state changes in any way (type, permutation, opening/closing doors etc.)

**Describe alternatives you've considered**
The only few APIs that do a similar job are BlockBreak, BlockPlace, PistonActivate, LeverAction... events, however those are very abstract and lack coverage in many areas which could be solved by this proposed universal solution.

**Additional context**
None

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
