### ISSUE TITLE
[Script-API] [Feature Request] console.log() for console output on BDS

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#494]
**Is your feature request related to a problem? Please describe.**
There is no way to directly send an output console message on Bedrock Dedicated Server to the server terminal.

**Describe the solution you'd like**
Use for `console.log()` function to output to the server terminal.

**Describe alternatives you've considered**
`console.warn()` to output to the content log file or `world.say()` to output to the chat which aren't as convenient to use as direct console output.

**Additional context**
None

**Comment by ConsoleTerm** [comment]
maybe New Module what will be avialable on BDS only, so maybe features like readLine and write/writeLine, could be useful.

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
