### ISSUE TITLE
Missing Import Button?

### ISSUE THREAD

**Issue by ActionWaters** [MicrosoftDocs/minecraft-creator#495]
[Enter feedback here]
Hello MC Team!

From this article under the Load Options this shows an Import function on the Windows version of MC BEdrock.
I cannot seem to find this button, when I put this block into Load Mode it just shows a greyed out Export button.
Wondering if theres any other info out there for this cool feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad779972-c39a-f5a6-8774-2c8c2690e176
* Version Independent ID: ad779972-c39a-f5a6-8774-2c8c2690e176
* Content: [Introduction to Structure Blocks](https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontostructureblocks#load-mode)
* Content Source: [creator/Documents/IntroductionToStructureBlocks.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/IntroductionToStructureBlocks.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by kakinnun** [comment]
This feature went live with 1.19.50 on November 29th. We accidentally published the documentation to this a bit early. Sorry about that! It should be working for you now.
