### ISSUE TITLE
Error when converting bedrock to Java

### ISSUE THREAD

**Issue by Rivet0153** [MicrosoftDocs/minecraft-creator#497]
I seem to be having issues when trying to convert from Bedrock 1.19.40 to java 1.19.2. The world converts and is downloadable but none of the things I built nor any blocks I've broken get saved to the Java edition zip. In the advanced mode world preview I can see my builds. It seems like nothing is saving except the seed. My world is only 78.5Mb. 

I followed the prompts as directed but when I get to the download screen I get this error message [(see Imgur)](https://imgur.com/a/w2pDhI2)

 - OS: Windows 10 - Home
 - Browser: Chrome, Firefox
 - Version: Chrome 107, Firefox 107.0 (x64)

**Comment by kakinnun** [comment]
Are you still running into this issue?

**Comment by JimSeaman42** [comment]
There haven't been any updates on this issue, so I'm going to close it. If you are still having issues, please let us know. Thanks!
