### ISSUE TITLE
incomplete documentation

### ISSUE THREAD

**Issue by RavinMaddHatter** [MicrosoftDocs/minecraft-creator#5]
I am trying to decipher any way to read block state and have conditionals before failures, however the documentation here is pretty light and incomplete. 

For instance:
assertBlockState
takes and argument: 

blockStateName | string
-- | --

 

one would think that would link to the block state late mentioned in the same article, however it actually is a string from the NBT of the structure file used to produce the test framework. some statement to that effect would help clarify the document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe607b5-38f5-f2e1-03db-24c0cbe091c1
* Version Independent ID: 1dc0180e-9dbd-882b-3ee3-d7e9c1204d05
* Content: [GameTest.Helper Class](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/gametest/helper)
* Content Source: [creator/ScriptAPI/GameTest/Helper.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/GameTest/Helper.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by JakeShirley** [comment]
Hey @RavinMaddHatter! The current API set that is out for blocks actually don't directly expose that so I don't think it's possible.  Internally we have an API surface that exposes block data directly via a few different types:
- Block: A block in the world at an X, Y, Z
- BlockType: The "archetype" or "material" of a block (think block without any extra data) (example: cobble stone stairs)
- BlockPermutation: BlockType + data  (not exposed directly as NBT but these are the same values that you'd use NBT for) (example: cobble stone stairs upside down facing east)

At that point you can poke blocks directly and inspect their state/properties and branch logic based on that. 

Hopefully we can get these changes into an update soon!

**Comment by RavinMaddHatter** [comment]
Can i inspect those blocks directly via the javascript API? Because i could not find a method to inspect block state outside of assertBlockState.

I ran a search on all exposed methods for block, blockLocation, ETC. But there was no way to discover what states are exposed, what states names could be, or any information about what i can or cannot set the argument to.

Second, there is not currently a method that allows me to either call back or inspect a series of block states together in a complex way. If i could directly inspect the block states i could do this by recursively scheduling a check every tick, or running a loop. But as it stands if there is an must pass if State A occurs only after state B, i dont belive i can write a game test

Second, I am certain you have it for internal builds. But being able to query the remaining time left in a tick would be extremely useful for lag source tracking (this is what i started using game test for). We have had a game crippling bug where if a full shulker is hoppered into an empty shullker on a realm the realm nearly stops. I would like to be able to attach a game test behavior pack to these types of tickets to improve bug reporting.

**Comment by mammerla** [comment]
Arguments for assertBlockState and other methods in GameTest.Test should be better documented now.
