### ISSUE TITLE
[Skin ID] Information is correct, although potentially missleading.

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#50]
Descriptions (rightfully) identify `skin_id` as being used in the vanilla-files for picking a texture/skin to use. However, I think it overstates this relationship. 

In fact, as addon creators, we tend to use `skin_id` very generically, for *any* kind of place where we need an integer, for example in animation controllers. 

For an overview of how we are using this component internally, see these documents:
 - https://wiki.bedrock.dev/documentation/dummy-components
 - https://wiki.bedrock.dev/tutorials/entity-commands

I think it would be better to explain this as a "dummy" (do you need more PC word?) that has no pre-defined behavior, and must be paired with auxiliary behavior to do anything. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c1ff9f-ca6e-7903-33ff-f2b514be4fc4
* Version Independent ID: 619a8df6-513c-4df7-15fa-2904f63942b4
* Content: [minecraft:skin_id](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_skin_id)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_skin_id.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_skin_id.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-jeffreykim** [comment]
After speaking to the developers, we don't have a concrete idea of how a use-case like this will affect Minecraft in the future or how future updates will affect any implementations that use this component in that way. We're looking into how best to highlight creative uses for components like this on the Learning Portal, but, for now, we feel that the reference docs should remain tightly focused.

Thanks for this awesome feedback, it was really interesting to read more about your implementations of this and other components as triggers for auxiliary behaviors!

Jeff
