### ISSUE TITLE
minLevel in query options and lm= in target selectors always returns true on certain numbers

### ISSUE THREAD

**Issue by mrpatches123** [MicrosoftDocs/minecraft-creator#504]
**Type**: /Testfor and EntityQueryOptions

**Expected Results**:
I get two blank arrays in chat

**Observed Results:** 
prints two array with my name in it

**Code**:
set your xp level to less than 3000 
```js
(function () {
    try {
        let players;
        players = [...world.getPlayers({ minLevel: 3000 })];
        world.say('minLevel: 3000\n' + JSON.stringify({ map: players.map(({ name }) => name) }));
        players = [...world.getPlayers({ minLevel: 5750 })];
        world.say('minLevel: 5750\n' + JSON.stringify({ map: players.map(({ name }) => name) }));
    } catch (error) {
        console.warn('func', error, error.stack);
    }
})();```

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
