### ISSUE TITLE
Fix block example being outdated

### ISSUE THREAD

**Issue by ihategravel2** [MicrosoftDocs/minecraft-creator#505]
The current block example for the 1.19.40 format version contains two outdated component names and the wrong friction value. I went ahead and remade it with the fixes.

```json
{
	"format_version": "1.19.40",
	"minecraft:block": {
		"description": {
			"identifier": "design:lavenderstone"
		},
		"components": {
			"minecraft:loot": "loot_tables/chests/simple_dungeon.json",
			"minecraft:destructible_by_mining": {
				"seconds_to_destroy": 4
			},
			"minecraft:friction": 0.4,
			"minecraft:map_color": "#00ff00",
			"minecraft:flammable": {
				"catch_chance_modifier": 50,
				"destroy_chance_modifier": 0
			},
			"minecraft:light_emission": 15
		}
	}
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fd075b1-abd4-625e-5995-bb04ce54cdfd
* Version Independent ID: 0fd075b1-abd4-625e-5995-bb04ce54cdfd
* Content: [Block Documentation - Block Description](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockdescription)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockDescription.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockDescription.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by kakinnun** [comment]
I've fixed this on our internal repo. It should be fixed on the live docs in our next push.
