### ISSUE TITLE
Example is not using the correct default parm name

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#507]
You used RANGE instead of INTERVAL_RANGE.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3b91464-040d-48a2-28fc-300a16cce125
* Version Independent ID: e3b91464-040d-48a2-28fc-300a16cce125
* Content: [Block Documentation - minecraft:queued_ticking](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blocktriggers/minecraftblock_queued_ticking)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockTriggers/minecraftBlock_queued_ticking.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockTriggers/minecraftBlock_queued_ticking.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by JDHeaden** [comment]
Great catch! Thank you @DrinkWater623 - edit will be in the next release.
