### ISSUE TITLE
Add Simple Custom Block sample code problem

### ISSUE THREAD

**Issue by Epoch-A-MC** [MicrosoftDocs/minecraft-creator#510]
as far as right now i have discovered that at least the sample code for the manifest in add simple block section, dose not work. I have found a fix though- delete any space that serves no purpose to the code. i not sure why but when experimenting to try to fix it that is what i found, though i did upgrade the min engine version to 1 19 50, instead of 1 19 20. im not sure if its necessary but that seemed to fix it.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Version Independent ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Content: [How to Add a Simple Custom Block](https://learn.microsoft.com/en-us/minecraft/creator/documents/addcustomdieblock#feedback)
* Content Source: [creator/Documents/AddCustomDieBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AddCustomDieBlock.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JDHeaden** [comment]
Thanks for the catch! Changes are made and should be visible after the next release.
