### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by Salgod** [MicrosoftDocs/minecraft-creator#511]
I try to use location together with closest, but it always seems that location goes to position 0, 0, 0 even if I put location: <entity>location. Am I doing something wrong? Or could it be a bug?

const query = { excludeType: "armor_stand", name: `(s) gerador de ${machine[0]}`}
const entities = world.getDimension("overworld").getEntities(query)

```ts
//for (const machine_entity of entities) {
    //player.runCommandAsync(`tellraw @s {"rawtext":[{"text":"§c${machine_entity.location.x}"}]}`)
    const query = { location: machine_entity, closest: 1, type: "player", maxDistance: 10 };
    //const nearPlayer_i = world.getDimension("overworld").getEntities(query);
    //let nearPlayer = "";
    //for (const nearPlr of nearPlayer_i) { nearPlayer = nearPlr }
    //machine_entity.runCommandAsync(`summon armor_stand "generator of ${machine[0]}" ~~~`).then(() => {
        //player.runCommandAsync(`tellraw @s {"rawtext":[{"text":"§c7"}]}`)
        //machine_entity.runCommandAsync(`tag @e[type=armor_stand, c=1, r=1] add generator`).then(() => {
            //machine_entity.runCommandAsync(`tag @e[type=armor_stand, c=1, r=1] add owner:${nearPlayer.name}`)
            //machine_entity.runCommandAsync(`kill`);
        //});
    //});
//}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5091660-92c3-0efe-193d-106d303d302b
* Version Independent ID: a5091660-92c3-0efe-193d-106d303d302b
* Content: [minecraft/server.EntityQueryOptions Interface](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/entityqueryoptions)
* Content Source: [creator/ScriptAPI/minecraft/server/EntityQueryOptions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/minecraft/server/EntityQueryOptions.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by kinji2532** [comment]
`entities` looks like an **EntityIterator**.
Therefore, the data contained in `machine_entity `is most likely an **Entity**.
In other words, `machine_entity.location` should be used.
