### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#515]
`The` is misspelled as `hte` on two instances

![image](https://user-images.githubusercontent.com/84206875/208254823-980a87b8-ab1e-4a6c-934a-9553978db7b6.png)
![image](https://user-images.githubusercontent.com/84206875/208254833-4998b9c5-068d-4d84-b471-1a7e0504f395.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b64aa40-f231-4fa4-9641-df94f37d5ea2
* Version Independent ID: d10f887a-4b9b-5725-937b-99e1a4024891
* Content: [Entity Documentation - minecraft:projectile](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_projectile)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_projectile.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-jillheaden**

**Comment by JDHeaden** [comment]
Good catch! Thank you. Fixes will be apparent after the next release.
