### ISSUE TITLE
Advanced Code Blocks section references incorrect value "sushi.geo.json"

### ISSUE THREAD

**Issue by kjprice** [MicrosoftDocs/minecraft-creator#518]
**Describe the bug**
Codeblock references incorrect value - "sushi.geo.json" should be "geometry.sushi".

**To Reproduce**
1. Go to https://learn.microsoft.com/en-us/minecraft/creator/documents/advancedcustomblocks#behavior-pack
2. Scroll down to **Behavior Pack** JSON code block
4. Codeblock references `sushi.geo.json` which is incorrect

**Expected behavior**
Code block snipppet should be

```
"minecraft:geometry": "geometry.sushi",
````

**Screenshots**

![Code block issue](https://user-images.githubusercontent.com/2319673/209398623-6c83c479-ec06-4991-b6f5-467560e49a15.png)

**Comment by JDHeaden** [comment]
Thanks for the catch! Error is fixed and should be available after the next release.
