### ISSUE TITLE
warped crimson

### ISSUE THREAD

**Issue by agus3901** [MicrosoftDocs/minecraft-creator#521]
minecraft bedrock

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Packaging a Skin Pack](https://learn.microsoft.com/en-us/minecraft/creator/documents/packagingaskinpack)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingASkinPack.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**
![26a059b7-6f7a-4044-b666-4861503d43aa](https://user-images.githubusercontent.com/121591107/209895239-9e2e26a4-d412-47c5-95ad-55fd0206991d.png)
![b929ae13-8134-44c8-af11-feb29e89d8e3](https://user-images.githubusercontent.com/121591107/209895283-58ce1823-a761-4165-a19a-7e46f19e8f28.png)
![26a059b7-6f7a-4044-b666-4861503d43aa](https://user-images.githubusercontent.com/121591107/209895286-8931e973-73d1-48ed-8da0-e94a20ffe74a.png)
![631faa6a-6a05-418b-8e95-3d5c2e2d293b](https://user-images.githubusercontent.com/121591107/209895287-6355eead-16a9-4405-9fec-5dea6f816a3d.png)
![05bdef70-f630-4288-9d02-ff01738d8d1d](https://user-images.githubusercontent.com/121591107/209895289-17e1179d-461c-499c-bf9e-9739be0bf9a5.png)
![60251213-7d41-41ef-ba5b-a6ec46c5b159](https://user-images.githubusercontent.com/121591107/209895290-2def8cac-d5aa-4628-b239-10c55fe42de5.png)
![96e97045-429f-4c76-9b4a-731fc871da24](https://user-images.githubusercontent.com/121591107/209895291-3b107e9d-1701-4444-a615-71e074a1e7d6.png)
![c26535d3-3dea-4cd0-b6b0-b9c38cb35173](https://user-images.githubusercontent.com/121591107/209895292-49c1f53d-4b67-42c5-994f-63a23bd63def.png)
![7176a513-d1fc-40a1-bf83-d5798ea07292](https://user-images.githubusercontent.com/121591107/209895293-dfa359f3-15f3-4808-9e3a-c53bd4f62440.png)

**Comment by agus3901** [comment]
xD

**Comment by JDHeaden** [comment]
Hi @agus3901  - nice skins! Are you having an issue? I'd be glad to help if I can.

**Comment by agus3901** [comment]
Thanks 😃, if i need help I`ll let you knowEnviado desde Correo para Windows De: Jill HeadenEnviado: martes, 3 de enero de 2023 15:01Para: MicrosoftDocs/minecraft-creatorCC: agus3901; MentionAsunto: Re: [MicrosoftDocs/minecraft-creator] warped crimson (Issue #521) Hi @agus3901 - nice skins! Are you having an issue? I'd be glad to help if I can.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
