### ISSUE TITLE
web

### ISSUE THREAD

**Issue by shundebo** [MicrosoftDocs/minecraft-creator#522]
Why is it empty after I click the conversion
![image](https://user-images.githubusercontent.com/105134757/209920954-ff05ef34-27ea-42f3-82ab-49e2c2a85991.png)

**Comment by FormallyMyles** [comment]
Does this occur when using another browser? 

Otherwise, if you're able to open the Network tool (Ctrl+Shift+I or ... -> More tools -> Developer tools), then select the Network Tab and refresh and then providing a screenshot.

**Comment by shundebo** [comment]
> 使用其他浏览器时会发生这种情况吗？
> 
> 否则，如果能够打开“网络”工具（Ctrl+Shift+I 或 ... -> 更多工具 -> 开发人员工具），请选择“网络”选项卡并刷新，然后提供屏幕截图。

国人吗？
I can't use edge, but chrome works X (ctnnd（国人检测）)

**Comment by shundebo** [comment]
> 使用其他浏览器时会发生这种情况吗？
> 
> 否则，如果能够打开“网络”工具（Ctrl+Shift+I 或 ... -> 更多工具 -> 开发人员工具），请选择“网络”选项卡并刷新，然后提供屏幕截图。

I can't use edge, but chrome works,(The kernel old problem is coming ())

**Comment by kakinnun** [comment]
Closing as it looks like this is resolved by using Chrome.
