### ISSUE TITLE
Suggestion: clarify what's changed

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/minecraft-creator#523]
The tutorial worked and successfully produced 'attack cows.'  But since this is a very long JSON file, it takes a lot of reading/skimming to understand what portion of the JSON has changed to create the attack behavior.  It would be good to either highlight that portion of the JSON or include a separate snip of it with an explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab3ad989-cd74-1b9a-d07c-500fc80fdaf7
* Version Independent ID: 2403daea-89fc-ce01-badf-56e6752f562b
* Content: [Introduction To Behavior Packs](https://learn.microsoft.com/en-us/minecraft/creator/documents/behaviorpack)
* Content Source: [creator/Documents/BehaviorPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/BehaviorPack.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by JDHeaden** [comment]
Good point! I added the code to a new section with a brief explanation. The change should be apparent after the next release. Thanks!
