### ISSUE TITLE
This would work…

### ISSUE THREAD

**Issue by BrokenRecord7** [MicrosoftDocs/minecraft-creator#525]
The page was helpful though at the export segment I could not move on. I would download the file and it wouldn’t let me go on the next steps, nothing would change the way the page look it just stayed the name with the export button on the bottom left hand of the scree. You could attempt to fix this problem. The article was helpful! (I am on an IPad)

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79c7652f-5c4e-768c-ca52-1ac2ff1790f5
* Version Independent ID: 794cb3ed-7c30-59af-7d62-3f109de1d553
* Content: [Getting Started with Minecraft Entity Wizard](https://learn.microsoft.com/en-ca/minecraft/creator/documents/minecraftentitywizard)
* Content Source: [creator/Documents/MinecraftEntityWizard.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/MinecraftEntityWizard.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by kakinnun** [comment]
Sorry to hear you are running into issues. Blockbench has more documentation and help available on their website: https://www.blockbench.net/wiki. The Blockbench discord community may also be able to help with your issue.
