### ISSUE TITLE
Kee

### ISSUE THREAD

**Issue by Kevz21212121** [MicrosoftDocs/minecraft-creator#529]
Fff**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JDHeaden** [comment]
Hi @Kevz21212121  - Looks like this may have been opened in error. If I'm wrong, feel free to reach out and let me know how I can help.
