### ISSUE TITLE
Missing properties: minecraft:behavior.panic

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#53]
Missing documentation for the following properties:

from [strider](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/strider)
- [ ] panic_sound
- [ ] sound_interval 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0977018-c6e4-8e77-bbd7-896abcb0c6bd
* Version Independent ID: c92b09cf-a169-e4b6-5de8-ba182cfa03c1
* Content: [minecraft:behavior.panic](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_panic)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_panic.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_panic.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
I added these to some improvements we're making in our Reference documentation. I'll update when those changes go through.

**Comment by docsbryce** [comment]
This update has been made and will go out in early July. I'll update when it's live.

**Comment by docsbryce** [comment]
This is now live [here](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_panic). Closing!
