### ISSUE TITLE
Chunker: "Something went wrong communicating with the server."

### ISSUE THREAD

**Issue by bubasharba69** [MicrosoftDocs/minecraft-creator#531]
**Describe the bug**
Similar to older issue #442 but with a different server error response

**To Reproduce**
1. Go to https://chunker.app
2. Upload small Bedrock world
3. Wait for upload to reach ~99%

**Expected behavior**
World successfully uploads and the wizard resumes

**Screenshots**
![](https://i.imgur.com/ssD7x86.png)

**Desktop:**
Multiple desktops including:
 - Fedora Linux 37, latest Firefox and latest Chromium
 - Windows 7, latest Firefox
 - Windows 10, latest Chrome, latest Firefox and latest Edge

**Additional context**
Happens consistently even after switching lots of networks and devices. Looking in DevTools the server WebSocket response is an error, text "Invalid session". Tried uploading multiple formats (.zip, .mcworld) for the same exact error to occur. The world sizes are very small and definitively under the 512MB limit.

**Comment by FormallyMyles** [comment]
> Hi, thanks for responding quickly! uploadWorld goes well and the server returns a 200 with some JSON. I'm not using a proxy nor VPN or any traffic filter, but I am behind CGNAT. Here are some screenshots.
> 
> ![](https://camo.githubusercontent.com/651d16cd115b498d6eef7d834b372e7d217671f25374ed3ed360f2799ce144b9/68747470733a2f2f692e696d6775722e636f6d2f527630535952592e706e67) ![](https://camo.githubusercontent.com/94117996055c07bf8c06292c5ded7a5c09973626f828082f7c2520630c479112/68747470733a2f2f692e696d6775722e636f6d2f676272493975752e706e67) ![](https://camo.githubusercontent.com/2238056e548a804b6f374abed559aeaf88dc24674827c418e228a1541e6adefb/68747470733a2f2f692e696d6775722e636f6d2f5a4d44375465692e706e67)

I've had a deeper look into this, and I believe it's because your IP differs between the HTTP requests and the web socket requests, and we have a security check to ensure these match. 

I'd suggest one of the following as a workaround:
- Using IPv6 if possible (Chunker.app is fully IPv6 compatible)
- Using a VPN/Proxy (To ensure your IP doesn't change)

I've otherwise logged it internally.

**Comment by bubasharba69** [comment]
Hey, thanks. It might be my ISP or something in the middle messing with it in some way for some reason :P. I don't have IPv6 but I can try using a proxy.
