### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nekwo** [MicrosoftDocs/minecraft-creator#533]
This Doesn't Work 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by kakinnun** [comment]
Closing as we need more issue to help.
