### ISSUE TITLE
Missing information on how to hide particle effects for "minecraft:mob_effect"

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#536]
The "minecraft:mob_effect" component should have an argument to hide particle effects, I feel this may be undocumented can there be a check to see if this is the case or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3993467-7aa1-087a-c199-103138f936be
* Version Independent ID: edea3456-6917-eb63-6948-76bef8347999
* Content: [Entity Documentation - minecraft:mob_effect](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_mob_effect)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_mob_effect.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_mob_effect.md)
* Product: **gaming**
* GitHub Login: @JDHeaden
* Microsoft Alias: **v-jillheaden**

**Comment by kakinnun** [comment]
I did a quick look at the source-code, and it looks like there isn't an argument to hide particle effects. This component appears to be accurately documented.
