### ISSUE TITLE
Error uploading a marketplace world (Trident City)

### ISSUE THREAD

**Issue by MadisonMadi** [MicrosoftDocs/minecraft-creator#537]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/17278366/211671989-b96f9e17-0665-440b-a610-f7522663f922.png)

error appears  when uploading this world
![image](https://user-images.githubusercontent.com/17278366/211672058-e67a710a-9a72-4fc9-9538-44925273eb2d.png)

I'ts a template from 'My Template Worlds'
![image](https://user-images.githubusercontent.com/17278366/211672265-e7ba675a-671e-4532-84fd-7ccf8f223db5.png)
I've tried uploading this with locked and without locked settings both don't work..

I have no idea what could be causing it, but when i try to upload say my own created world it does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by MadisonMadi** [comment]
also contacting the 'Chunker Team' seems to be impossible. they don't have any Support outside this github page not any info on the website.. i can't find anything and the microsoft chunker documants don't help at all.

**Comment by FormallyMyles** [comment]
Unfortunately, Chunker cannot read worlds based on marketplace content due to how the worlds work. I'll see if we can improve the messaging in the error to make this clearer in the future.

**Comment by kakinnun** [comment]
Closing as this scenario is not supported by Chunker.
