### ISSUE TITLE
Minecraft dosesnt use the uwp verson of the minecraft folder anymore 

### ISSUE THREAD

**Issue by Ollytodd** [MicrosoftDocs/minecraft-creator#538]
Microsoft you own monang and you also own xbox you should know how much the community love modding minecraft and ever since the October 5th update for minecraft on xbox it has been unplayable for many.Pls go back to uwp and fix all of the issues YOUS HAVE CAUSED WITH THAT UPDATE

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63ee92b3-df1e-3f02-7b62-e13798b131a8
* Version Independent ID: 7d9f0488-2919-4cca-20ee-097af4e47a05
* Content: [Getting Started With Minecraft Add-Ons](https://learn.microsoft.com/en-us/minecraft/creator/documents/gettingstarted)
* Content Source: [creator/Documents/GettingStarted.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/GettingStarted.md)
* Product: **gaming**
* GitHub Login: @docsbryce
* Microsoft Alias: **v-bbortree**

**Comment by kakinnun** [comment]
Thank you for your feedback. For Minecraft product feedback, please use https://feedback.minecraft.net/.
