### ISSUE TITLE
List of Causes would be ever so helpful

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#539]
Who do I have to know to get a valid list of damage causes?  Or do I need to look inside of every entity file to find them?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9508d013-e181-fe37-cd9f-c1ee229b1575
* Version Independent ID: a8a78e2a-3fb7-6a67-2e44-76e6346d0c38
* Content: [Entity Documentation - minecraft:damage_sensor](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_damage_sensor)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_damage_sensor.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_damage_sensor.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by SmokeyStack** [comment]
[Is this not it?](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonentities#entity-damage-source)

![image](https://user-images.githubusercontent.com/84206875/212351704-ce7f17b2-702b-475f-9b38-4e81064a832d.png)
