### ISSUE TITLE
Missing property: minecraft:behavior.random_look_around

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#54]
from [witch](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/wither)
- look_distance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38085508-f36a-e8ae-1865-f990a4431fd5
* Version Independent ID: 6bb8317c-7018-8c47-5048-c63b7d7fd95b
* Content: [minecraft:behavior.random_look_around](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_random_look_around)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_random_look_around.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_random_look_around.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This change is [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_random_look_around). Thanks for reporting this!
