### ISSUE TITLE
Short Example is incorrect

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#542]
A value is required and your example is treating it as a boolean
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcce18c6-51da-9a52-ce46-659d45744b61
* Version Independent ID: 5b0fad3a-765d-49bb-70a0-4314706badda
* Content: [Entity Documentation - is_skin_id](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/filters/is_skin_id)
* Content Source: [creator/Reference/Content/EntityReference/Examples/Filters/is_skin_id.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/Filters/is_skin_id.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thank you for your feedback; the value in the example will be changed to an integer with the next release.
