### ISSUE TITLE
minecraft:foil item reference page is not listed in TOC

### ISSUE THREAD

**Issue by kakinnun** [MicrosoftDocs/minecraft-creator#544]
minecraft:foil item component page is not listed in TOC.
https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_foil
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 167f0357-2973-795c-c167-f7eca2ee0f8f
* Version Independent ID: 167f0357-2973-795c-c167-f7eca2ee0f8f
* Content: [Item Documentation - minecraft:foil](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_foil)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_foil.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_foil.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by JDHeaden** [comment]
Fixed! https://github.com/MicrosoftDocs/minecraft-creator-pr/pull/806
