### ISSUE TITLE
minecraft:random_ticking block reference page is not listed in TOC

### ISSUE THREAD

**Issue by kakinnun** [MicrosoftDocs/minecraft-creator#546]
minecraft:random_ticking block reference page is not listed in TOC

https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blocktriggers/minecraftblock_random_ticking

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4340e3c-a5a9-864b-cd24-f6c776dab060
* Version Independent ID: e4340e3c-a5a9-864b-cd24-f6c776dab060
* Content: [Block Documentation - minecraft:random_ticking](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blocktriggers/minecraftblock_random_ticking)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockTriggers/minecraftBlock_random_ticking.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockTriggers/minecraftBlock_random_ticking.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JDHeaden** [comment]
Fixed! https://github.com/MicrosoftDocs/minecraft-creator-pr/pull/804
