### ISSUE TITLE
Link to component list is broken (Entity Behavior Introduction)

### ISSUE THREAD

**Issue by JulianKalmbach** [MicrosoftDocs/minecraft-creator#549]
The link to the list of all components in the entity behavior introduction is broken.
The page you get forwarded to is missing.
This might be frutstrating for beginners who want to get started with bedrock addon development.

I assume this is the page the link is supposed to redirect to?
https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/componentlist

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a6ceb93-44e6-516d-1a1a-ca150749cf51
* Version Independent ID: 26800567-5bb0-e626-c958-0705b1321e04
* Content: [Entity Behavior Introduction](https://learn.microsoft.com/en-us/minecraft/creator/documents/entitybehaviorintroduction)
* Content Source: [creator/Documents/EntityBehaviorIntroduction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EntityBehaviorIntroduction.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by kakinnun** [comment]
I've fixed this on our internal repo. It should be fixed on the live docs in our next push.
