### ISSUE TITLE
Missing AI goals

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#55]
The following AI goals are missing

- [x] minecraft:behavior.avoid_block
- [x] minecraft:behavior.avoid_mob_type
- [x] minecraft:behavior.celebrate
- [x] minecraft:behavior.celebrate_survive
- [x] minecraft:behavior.charge_attack
- [x] minecraft:behavior.charge_held_item
- [x] minecraft:behavior.circle_around_anchor
- [x] minecraft:behavior.controlled_by_player
- [x] minecraft:behavior.defend_village_target
- [x] minecraft:behavior.delayed_attack
- [x] minecraft:behavior.dragonchargeplayer
- [x] minecraft:behavior.dragondeath
- [x] minecraft:behavior.dragonflaming
- [x] minecraft:behavior.dragonholdingpattern
- [x] minecraft:behavior.dragonlanding
- [x] minecraft:behavior.dragonscanning
- [x] minecraft:behavior.dragonstrafeplayer
- [x] minecraft:behavior.dragontakeoff
- [x] minecraft:behavior.drop_item_for
- [x] minecraft:behavior.eat_block
- [x] minecraft:behavior.enderman_leave_block
- [x] minecraft:behavior.enderman_take_block
- [x] minecraft:behavior.equip_item
- [x] minecraft:behavior.find_mount
- [x] minecraft:behavior.find_underwater_treasure
- [x] minecraft:behavior.float_wander
- [x] minecraft:behavior.guardian_attack
- [x] minecraft:behavior.harvest_farm_block
- [x] minecraft:behavior.leap_at_target
- [x] minecraft:behavior.mingle
- [x] minecraft:behavior.move_outdoors
- [x] minecraft:behavior.move_to_block
- [x] minecraft:behavior.move_to_liquid
- [x] minecraft:behavior.move_towards_dwelling_restriction
- [x] minecraft:behavior.move_towards_home_restriction
- [x] minecraft:behavior.move_towards_restriction
- [x] minecraft:behavior.nap
- [x] minecraft:behavior.ocelotattack
- [x] minecraft:behavior.random_fly
- [x] minecraft:behavior.random_hover
- [x] minecraft:behavior.random_swim
- [x] minecraft:behavior.ranged_attack
- [x] minecraft:behavior.receive_love
- [x] minecraft:behavior.roll
- [x] minecraft:behavior.send_event
- [x] minecraft:behavior.share_items
- [x] minecraft:behavior.skeleton_horse_trap
- [x] minecraft:behavior.sleep
- [x] minecraft:behavior.slime_attack
- [x] minecraft:behavior.slime_float
- [x] minecraft:behavior.slime_keep_on_jumping
- [x] minecraft:behavior.slime_random_direction
- [x] minecraft:behavior.sneeze
- [x] minecraft:behavior.squid_dive
- [x] minecraft:behavior.squid_flee
- [x] minecraft:behavior.squid_idle
- [x] minecraft:behavior.squid_move_away_from_ground
- [x] minecraft:behavior.squid_out_of_water
- [x] minecraft:behavior.stalk_and_pounce_on_target
- [x] minecraft:behavior.stomp_attack
- [x] minecraft:behavior.swim_idle
- [x] minecraft:behavior.swim_wander
- [x] minecraft:behavior.swim_with_entity
- [x] minecraft:behavior.swoop_attack
- [x] minecraft:behavior.target_when_pushed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad3eb77-a372-3f0e-0ef4-3adcea5a56cc
* Version Independent ID: cde5c434-ff4f-b70f-120e-a97fa9edec62
* Content: [AI Goal List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/aigoallist)
* Content Source: [creator/Reference/Content/EntityReference/Examples/AIGoalList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/AIGoalList.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by DaanV2** [comment]
Added two extra missing:

- [ ] minecraft:behavior.celebrate_survive
- [ ] minecraft:behavior.move_outdoors

**Comment by JDHeaden** [comment]
All are present and accounted for: articles exist, are in TOC and on AIGoals page. Woo!
