### ISSUE TITLE
World Converting Issue with Chunker.App

### ISSUE THREAD

**Issue by PizzaThatCodes** [MicrosoftDocs/minecraft-creator#550]
Tried using Chunker.App to convert a bedrock world to java and basically all slabs got wiped out without any errors, currently using the newest version of minecraft for both versions. tried multiple times to convert it to see if it was a one time thing, if you need the world file just lmk.

one type that is mainly affected is prismarine slabs. Its also random, sometimes it the top slab, sometimes its the bottom.

**Comment by PizzaThatCodes** [comment]
Contacted Hive games to see if they would help, but they redirected me to here.

**Comment by FormallyMyles** [comment]
Definitely sounds like something we can fix, would you be able to send the before & after worlds to chunker-public@hivemc.com and we'll get this looked into. 

Are your worlds new worlds? Have they ever been edited by other tools? and what Bedrock & Java versions do you use?

**Comment by PizzaThatCodes** [comment]
My world is roughly 2 years old, been consistently updating them whenever a new version comes out, the current versions I use are 1.19.3 Java & 1.19.51 for bedrock. I have used a bit of world painter on it but wouldn't see how it would affect slabs

**Comment by FormallyMyles** [comment]
> My world is roughly 2 years old, been consistently updating them whenever a new version comes out, the current versions I use are 1.19.3 Java & 1.19.51 for bedrock. I have used a bit of world painter & amulet before on it but wouldn't see how it would affect hand placed slabs

From a quick look seems like the Bedrock engine hasn't fully upgraded the slabs, we'll get a fix in to correct this in the future. Thank you for providing the world, it's a great help.

**Comment by FormallyMyles** [comment]
Just an update, we've rolled out a new version which should hopefully resolve this issue :)

**Comment by kakinnun** [comment]
Closing this issue as resolved.
