### ISSUE TITLE
Example is_block == to player?????

### ISSUE THREAD

**Issue by seeit360** [MicrosoftDocs/minecraft-creator#554]
The fox example is clear... but I'm sorry, the syntax usage with the 'player' as the value to check against makes no sense. I cannot even figure out how this is even possible. is_block is a filter to see if the block desired is being used. How can a block be a player? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab12a09-51a1-3bb1-2204-bfbfdec267ce
* Version Independent ID: 05c088c5-f211-93bf-1731-d1afcccb674a
* Content: [Entity Documentation - is_block](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/filters/is_block)
* Content Source: [creator/Reference/Content/EntityReference/Examples/Filters/is_block.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/Filters/is_block.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
The errant 'player' value will be removed from the samples on the next release.
