### ISSUE TITLE
Tutorial - Advanced Custom Blocks (Sushi blocks)

### ISSUE THREAD

**Issue by jskblack** [MicrosoftDocs/minecraft-creator#555]
hi, 

I referred to the method in the sushi blocks in "Advanced Custom Blocks", but when testing the block, I couldn't display the texture of the sushi successfully. 
The [attachment](https://drive.google.com/file/d/1UXKQ-9hAe77O6zhqgPNf-0wGvAf0B7Yb/view?usp=share_link) is the data structure of the resource packs and behavior packs. 

Please help me find where the problem is. 

Thanks

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 learn.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: a69abde4-29ff-b418-da93-d3f9a3674c26
* Version Independent ID: a69abde4-29ff-b418-da93-d3f9a3674c26
* Content: [Custom Blocks Part 2 Geometry and Materials](https://learn.microsoft.com/zh-tw/minecraft/creator/documents/advancedcustomblocks)
* Content Source: [creator/Documents/AdvancedCustomBlocks.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AdvancedCustomBlocks.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **JimSeaman42**

**Comment by kakinnun** [comment]
I'm sorry, but we cannot provide support for add-on development via this GitHub repo. There are some very helpful communities that exist that can help.
