### ISSUE TITLE
BeforeItemUseOnEvent.getBlockLocation() returns undefined

### ISSUE THREAD

**Issue by SIsilicon** [MicrosoftDocs/minecraft-creator#556]
As of 1.19.70.22, property `blockLocation` was replaced with `getBlockLocation()` for the relevant. For `BeforeItemUseOnEvent` however, this method returns `undefined` instead of a Vector3 interface as documented.
Relevant bug report: https://bugs.mojang.com/browse/MCPE-166945

**Comment by ConsoleTerm** [comment]
Hello, thank you for reporting, but you can close this issue now.

**Comment by JimSeaman42** [comment]
Thank you for reaching out.

We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
