### ISSUE TITLE
Link to Page from Components is Missing

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#557]
You can only get to this page via a web search.  It is not in the list of components for items
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 167f0357-2973-795c-c167-f7eca2ee0f8f
* Version Independent ID: 167f0357-2973-795c-c167-f7eca2ee0f8f
* Content: [Item Documentation - minecraft:foil](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_foil)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_foil.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_foil.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by kakinnun** [comment]
This has been fixed internally and will update with our next release.
