### ISSUE TITLE
Missing Entity Components / Properties

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#56]
The following components / properties are missing

- [x] minecraft:attack_damage
- [x] minecraft:balloonable
- [x] minecraft:block_climber
- [x] minecraft:dweller
- [ ] minecraft:fall_damage
- [x] minecraft:follow_range
- [x] minecraft:foot_size
- [x] minecraft:health
- [x] minecraft:hide
- [x] minecraft:horse.jump_strength
- [ ] minecraft:hurt_when_wet
- [x] minecraft:knockback_resistance
- [x] minecraft:lava_movement
- [ ] minecraft:movement
- [x] minecraft:movement.glide
- [ ] minecraft:npc
- [x] minecraft:player.saturation
- [x] minecraft:player.exhaustion
- [x] minecraft:player.level
- [x] minecraft:player.experience
- [x] minecraft:trade_resupply
- [x] minecraft:trust
- [x] minecraft:underwater_movement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296ef259-dfc5-929a-ed02-3c115f3e861a
* Version Independent ID: c975abda-12a9-8ff1-4c98-4bd0b01575ee
* Content: [Component List](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/componentlist)
* Content Source: [creator/Reference/Content/EntityReference/Examples/ComponentList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/ComponentList.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
These changes are in review now. I'll update when they're live.

**Comment by docsbryce** [comment]
Many of these changes are now live, but I will keep this issue open until all are resolved. The rest will still be documented.

Except for foot_size, which was deprecated. 

Here's a list of the updated pages:

- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_balloonable
- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_block_climber
- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_dweller
- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_hide
- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_knockback_resistance
- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_movement.glide
- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_trade_resupply
- https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_trust

**Comment by kakinnun** [comment]
Updated these with what is live or deprecated. Only 4 more to go!

**Comment by v-jeffkim** [comment]
Hello!

It looks like we've made some progress on this. Since it's been a while, I'm going to close this issue, but if you have any additional feedback, please reach out to us!

Thanks!
