### ISSUE TITLE
Nonsense example

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#563]
???
{ "test": "weather", "subject": "self", "operator": "==", "value": "player" }
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2831e8b8-5740-7525-30eb-86520c4fcfa7
* Version Independent ID: 18d922be-3315-5eef-e722-26c9d32edbc1
* Content: [Entity Documentation - weather](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/filters/weather)
* Content Source: [creator/Reference/Content/EntityReference/Examples/Filters/weather.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/Filters/weather.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-josjones**

**Comment by JimSeaman42** [comment]
The errant 'player' value will be removed from the examples as of the next release.
