### ISSUE TITLE
Question about entity models

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#566]
Hi, I want to create an entity that looks exactly like a vanilla crafting table. So a simple cube with a different texture on each face. Obviously, I don't want to redistribute vanilla assets; I want it to look exactly like a crafting table does in the user's texture pack.

I tried reading the documentation but don't see a way to accomplish this. How can it be done? Thanks

**Comment by kakinnun** [comment]
Hi tryashtar. It sounds like what you want to do is have a simple cube with a texture that is different on each face. This tutorial covers that scenario:
https://learn.microsoft.com/en-us/minecraft/creator/documents/addcustomdieblock

If you are looking to use the new material_instances component to manage the textures, that currently requires a geometry component, which in your scenario could be just a simple cube you create in a program like Blockbench Block Wizard: https://learn.microsoft.com/en-us/minecraft/creator/documents/minecraftblockwizard

**Comment by tryashtar** [comment]
Sorry, maybe I wasn't clear. I want this to be an entity that looks like a block, not an actual block.
