### ISSUE TITLE
Inconsistent formatting

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#569]
The JSON examples are all inconsistent in formatting. Some are proper json, others are just snippets. Indentation is messed up. Doesn't look professional. The examples [here](https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontoloottables#basic-usage) are all proper JSON. The examples in [functions](https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontoloottables#functions-and-modifying-items) and [conditions](https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontoloottables#conditions) are all improper

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd485b26-f072-c98a-9e59-e5b12a3ce3ea
* Version Independent ID: 36631caa-b8f2-e4c4-78a1-82618cf95901
* Content: [Introduction to Loot Tables](https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontoloottables)
* Content Source: [creator/Documents/IntroductionToLootTables.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/IntroductionToLootTables.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by JDHeaden** [comment]
Thank you for letting us know. The formatting has been fixed and should be visible after the next release.
