### ISSUE TITLE
Missing properties: minecraft:behavior.tempt

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#57]
from [strider](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/strider)

- [ ] can_tempt_while_ridden
- [ ] can_tempt_vertically
- [ ] sound_interval
- [ ] tempt_sound

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e51786d3-85e3-4283-5580-7739600ae4e4
* Version Independent ID: c7dabf7f-6ed6-da68-967f-00ac4db74dec
* Content: [minecraft:behavior.tempt](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_tempt)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_tempt.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_tempt.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by DaanV2** [comment]
Found the additional properties as well and updated the main post
- sound_interval
- tempt_sound

**Comment by docsbryce** [comment]
These changes are live! https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_tempt
