### ISSUE TITLE
Sr.CompuGamerYT

### ISSUE THREAD

**Issue by SrCompuGamer12** [MicrosoftDocs/minecraft-creator#570]
[Escriba sus comentarios aquí]

---
#### Detalles del documento
![Sr CompuGamerYT Minecraft skin ](https://user-images.githubusercontent.com/127153483/224516469-126a4850-9a14-41c1-bf12-738e9c8dbc85.png)
R

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Cómo empaquetar un pack de aspecto](https://learn.microsoft.com/es-es/minecraft/creator/documents/packagingaskinpack)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.es-MX/blob/live/creator/Documents/PackagingASkinPack.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by kakinnun** [comment]
Closing due to no information to action on.
