### ISSUE TITLE
Bad Example

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#571]
Example does not include page topic
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fd075b1-abd4-625e-5995-bb04ce54cdfd
* Version Independent ID: 0fd075b1-abd4-625e-5995-bb04ce54cdfd
* Content: [Block Documentation - Block Description](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockdescription)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockDescription.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockDescription.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
The page says this:

> The block "description" is a section inside the "minecraft:block" section of a custom block's behavior pack JSON file...


... and the example contains this...

> ...
> "minecraft:block": {
> 		"description": {
> 			"identifier": "design:lavenderstone"
> 		},
> ...

This might be a more recent update, so if you have a suggestion about how to make it better, I would appreciate the help. Feel free to reopen this ticket or open a new one. Thank you!
