### ISSUE TITLE
Hyperlink for target

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#572]
The hyperlink for target points to the entity filter list and not a list of target types like  self/other/item/etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b59bde4e-6c76-2042-9c2c-45abf98001cb
* Version Independent ID: 912bfae8-25e5-f427-a474-5fc8efa690ac
* Content: [Block Documentation - damage](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockevents/minecraftblock_damage)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_damage.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_damage.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JimSeaman42** [comment]
Thank you for your feedback; the errant link will be removed with the next release.
