### ISSUE TITLE
Trying to figure out the changes for the latest version

### ISSUE THREAD

**Issue by MattSpeakman** [MicrosoftDocs/minecraft-creator#574]
Hello,
I'm trying to teach my child programming through the Minecraft Typescript API but things have drastically changed and now we don't know how to adapt. Could you let me know how I could:

Get the Player's current location
How to hook into Events such as blockBreak. It used to be off the world object but now I just can't find it
How to access the scoreboard

Thanks,

Matt
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20c40e7e-d35b-209a-0614-caa868571b63
* Version Independent ID: 20c40e7e-d35b-209a-0614-caa868571b63
* Content: [minecraft/server.World Class](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/world)
* Content Source: [creator/ScriptAPI/minecraft/server/World.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/minecraft/server/World.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by kakinnun** [comment]
Hi Matt,

We aren't really setup to provide support here, especially with Experimental features. But to give you some directions to try:
- API changes are noted in the changelog: https://feedback.minecraft.net/hc/en-us/articles/13857979785613-Minecraft-1-19-70-Bedrock-
- There is a great Add-On creator community on Discord with a very active Script-API channel that may be able to help troubleshoot: Bedrock Add-Ons Discord: https://discord.gg/TDjXzThm Look for the script-api channel: https://discord.com/channels/523663022053392405/1067535382285135923

Sorry for disrupting your workflows with our changes!
