### ISSUE TITLE
Type desc error: EntityDamageCause

### ISSUE THREAD

**Issue by d4rkOfficial** [MicrosoftDocs/minecraft-creator#575]
![98e9e87f35c10e2.jpg](https://user-images.githubusercontent.com/100008396/225897839-d0303b20-3001-4898-b651-aae2000a6fb8.jpg)

Expected
```ts
Entity.prototype.applyDamage(amount: number, source?: mc.EntityDamageCause | undefined)
```

Mistake
```ts
Entity.prototype.applyDamage(amount: number, source?: mc.EntityDamageSource | undefined)
```

There is no enum `EntityDamageSource` declared,
but I found `EntityDamageCause`, is it a  typo?

**Comment by ConsoleTerm** [comment]
Hello, its ok. Second parameter of applyDamage is interface Object so you can not import it from module manually
Here is docs link: https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/entitydamagesource

Here is example how to use interfaces:
```js
entity.applyDamage(5, {cause: mc.EntityDamageCuase.lava});
```

**Comment by d4rkOfficial** [comment]
> Hello, its ok. Second parameter of applyDamage is interface Object so you can not import it from module manually
> Here is docs link: https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/entitydamagesource
> 
> Here is example how to use interfaces:
> ```js
> entity.applyDamage(5, {cause: mc.EntityDamageCuase.lava});
> ```
> 
> Please close this issue, Thank you.

OK
