### ISSUE TITLE
[Script API] EntityHitEvent doesn't get triggered by entity hits into the air.

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#582]
**Describe the bug**
When an entity(in this case a player) hits into the air without hitting an entity or a block, the `EntityHitEvent` doesn't get triggered. The documentation suggests that such case should still trigger the event with both `hitEntity` and `hitBlock` being undefined, which would be handy thing to have.

**To Reproduce**
1. Subscribe to the entity hit event in a script. Set it to print out values of `hitEntity` and `hitBlock` properties.
2. Left click with the mouse button while facing no entity nor block.
3. See no output by the event listener.

**Expected behavior**
Swiping into the air should trigger the event and print out the values of `hitEntity` and `hitBlock` both as undefined.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: Preview 1.19.80.21+

**Comment by ConsoleTerm** [comment]
Hi, this is no longer related to current design, in latest Preview 1.20.10.23 was event split into two separated events, blockHit and entityHit, Thank you for your report.
