### ISSUE TITLE
Extra entity included

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#583]
`minecraft:chest_minecart` does not have the `despawn` component included yet it is included in the list of vanilla entities usage

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0979d43-e5ce-35af-5876-b964a680ae76
* Version Independent ID: 5f51f187-0586-e031-fe26-f7868323e1a0
* Content: [Entity Documentation - minecraft:despawn](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_despawn)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_despawn.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_despawn.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by JimSeaman42** [comment]
Thanks for the feedback! The Vanilla Entity list in this article will be updated with the next release.
