### ISSUE TITLE
1.19.80.22 witch damage sensor

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#584]
In 1.19.80.22, the witch entity file was given an empty `damage_sensor` in its base components. It's unclear what is the purpose of including a damage sensor without any `triggers`. Can this please be explained?

**Comment by JimSeaman42** [comment]
Thank you for your issue. 

We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.

**Comment by tryashtar** [comment]
The specific issue is that I don't see any documentation on the `damage_sensor` page that describes the effect of using an empty component without any `triggers`.
