### ISSUE TITLE
[Script API] Script API UI forms open scrolled down

### ISSUE THREAD

**Issue by KevoMeister** [MicrosoftDocs/minecraft-creator#585]
**Describe the bug**
When a form is long and requires a scroll bar and there's no button at the top of the form view, the form is opened already scrolled down, it seems to only open a form with a button in sight, but the scroll bar is positioned at the top of the form. I tested this with an Windows 11 PC and an Android phone, both cause the same problem.

**To Reproduce**
1. Create a UI Form (`ModalFormData`, `ActionFormData`) with a long body, or many toggle buttons.
2. Open the Form on a player

**Expected behavior**
Open the form at the top regardless if there's a button visible or not. The player would have to scroll down to get to the button.

**Screenshots**
In this screenshot, I have a ModalFormData with 10 toggle buttons, when the form opens the form is scrolled down, but the scroll bar is positioned at the top.
![Screenshot 2023-03-24 080305](https://user-images.githubusercontent.com/37786069/227542572-4b5a9449-6f86-46ec-85b2-9680e1f4f729.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Minecraft Version: 1.19.72
 
**Additional context**
Module: @minecraft/server-ui
Version: 1.0.0-beta

**Comment by McMelonTV** [comment]
bump

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
