### ISSUE TITLE
[System][Bug][Creator API] Internal Errors aren´t handled at all

### ISSUE THREAD

**Issue by conmaster2112** [MicrosoftDocs/minecraft-creator#588]
I found that sometimes Native Internal Errors aren´t handled at all.

## What behavior it has?
It is almost impossible to find out what is causing the error, because code pass the point where internal error occurs, all current code is successfully executed with ghost internal error.

Can´t be tracked via `try{}catch(){}` by end API users.
## What happens when this errors occurs?
In the view of API end user, nothing happens, but in game that tick where ghost internal error occurs is last tick ever for this world session, game freezes for ever.

### First
Yes, i have one. I have encountered this problem twice already, first time it was `sendMessage` issue when lengths of messages were limited by native, in this case it wasn´t API problem only.
When someone uses `/tell` or `/tellraw` commands or API `sendMessage` and broke the limit of 500 bytes then error occurs as well for commands, but this got fixed in latest preview here limit was removed.
### Second
This time it was only in the case of the `applyImpulse` API method.
I have by incident pass `NaN` values to `Vector3` axis properties.
example:
```js
<entity>.applyImpulse({x:NaN,y:NaN,z:NaN}); //no errors were throwed, everything pass successfully
```

## Recapitulation
Internal Error could occurs but there is no way how to prevent it or catch it, is 100% internal and JS engine has no clue that something bad happens.
After these errors occurs game will stack in current Tick and next one never comes.
You have to close MC client, because client send world save request but server is responding at all.

Minecraft build: `Minecraft Preview v1.19.80.22`
API Module version: `minecraft/server@1.2.0-beta`
OS: `Windows 11 Pro`

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
