### ISSUE TITLE
Some issues completeing this tutorial

### ISSUE THREAD

**Issue by Mush713** [MicrosoftDocs/minecraft-creator#591]
I had a lot of issues completing this tutorial.  Each section of code, whether using the copy button or manually highlighting the text and copying, has a bunch of invalid characters in the tabs/whitespace.  This is impossible to see if you are using a simple text editor such as notepad.  

Additionally, the end of the tutorial claims that the block will be randomly rotated when placed.  It is not randomly rotated when placed and is always aligned the same way.   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Version Independent ID: 63bccc5e-a22b-a564-c0af-bcc0d4ebbe2a
* Content: [How to Add a Simple Custom Block](https://learn.microsoft.com/en-us/minecraft/creator/documents/addcustomdieblock)
* Content Source: [creator/Documents/AddCustomDieBlock.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AddCustomDieBlock.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **JimSeaman42**

**Comment by JimSeaman42** [comment]
Thank you for this feedback! The article will be updated with the next release to address these issues.
