### ISSUE TITLE
Packaging a WorldTemplate has files placed in the incorrect location

### ISSUE THREAD

**Issue by ThomasOrs** [MicrosoftDocs/minecraft-creator#592]
The below files do not go in the `worldtemplate/db` folder and instead go in the root of the world template folder.
- level.dat
- levelname.txt
- manifest.json
- world_behavior_packs.json
- world_resource_packs.json
- world_icon.jpeg
![image](https://user-images.githubusercontent.com/84604286/230470909-958cc4d9-c2a7-4a00-9c98-df66b9b7063c.png)

This is the correct root placement
![image](https://user-images.githubusercontent.com/84604286/230471186-45856e6a-2dec-4642-994e-9ba822f54ded.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45db6623-7d17-68da-867c-eba6ad80375b
* Version Independent ID: 3bd7fbd1-46da-2fe1-a8f1-1d4fbee797de
* Content: [Packaging a World Template](https://learn.microsoft.com/en-us/minecraft/creator/documents/packagingaworldtemplate)
* Content Source: [creator/Documents/PackagingAWorldTemplate.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingAWorldTemplate.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thank you so much for the feedback. The issue has been remedied, and the article will be updated with the next release. Have a great day!
