### ISSUE TITLE
[Script API][TS Imperfection] - From Builder Design is not extendable in scope of TS types

### ISSUE THREAD

**Issue by ConsoleTerm** [MicrosoftDocs/minecraft-creator#595]
From Builder Design is not extendable in scope of TS Types, Its FormBuilder Classes such as ActionFormData ModalFormData and MessageFormData
every builder method there return constant type (self Type) so classes cant be fully extendable in TS scope,
here is example:
```ts
class ExampleFormData extends ActionFormData{
  myMethod(){return this;}
}

const form = new ExampleFormData();
form.title("Hello").myMethod("Boom"); //issue here, there is no myMethod on ActionFormData type
```
That means builder methods returns constant types
```ts
class ActionFormData{
   title(content: string): ActionFormData
   //...
}
```
but it should return "this" type
```ts
class ActionFormData{
   title(content: string): this //fixed!
   //...
}
```
Now we can extend FormData classes in TS as well, should i do git hub report or its easy fix?

**Debug**
- Version: `multiple`,
- OS: `multiple`,
- Module: `@types/minecraft/server-ui@1.0.0-beta`

**Comment by JimSeaman42** [comment]
Thank you for reaching out. 
We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
