### ISSUE TITLE
[Script API][Items/Blocks Tags] - Imperfection of API Design

### ISSUE THREAD

**Issue by ConsoleTerm** [MicrosoftDocs/minecraft-creator#596]
Methods such as getTags and hasTag on ItemStacks and Blocks should be on thier Types,
sometimes you need to find out if a given type has a given tag, why shouldn't it be no data type classes?
The tags for the given items and blocks are constant and do not change during the game, so they should be reachable without creating a new item or laying a new block.
- Block.prototype.hasTag -> BlockType.prototype.hasTag
- ItemStack.prototype.hasTag -> ItemType.prototype.hasTag
- Block.prototype.getTags -> BlockType.prototype.getTags
- ItemStack.prototype.getTags -> ItemType.prototype.getTags

**Comment by MajestikButter** [comment]
> sometimes you need to find out if a given type has a given tag, why shouldn't it be no data type classes?
This can be done by creating a permutation for that BlockType and calling the tag methods on there. Defining the tag methods solely on the BlockType class would not work well due to permutations being able to declare different tags in the Holiday Creator Features experimental toggle.

**Comment by ConsoleTerm** [comment]
> > sometimes you need to find out if a given type has a given tag, why shouldn't it be no data type classes?
> 
> This can be done by creating a permutation for that BlockType and calling the tag methods on there. Defining the tag methods solely on the BlockType class would not work well due to permutations being able to declare different tags in the Holiday Creator Features experimental toggle.

Thx, i miss this, i thought its only on Block instances, about items its ok, you can create ItemStack any time.
