### ISSUE TITLE
[Script API] Specifiying playSound and playMusic methods to Dimensions.

### ISSUE THREAD

**Issue by PavelDobCZ23** [MicrosoftDocs/minecraft-creator#599]
**Is your feature request related to a problem? Please describe.**
I want to make some sound or a music in a specific place in world and that place is specific down to both location and dimension level, I do not want players in other dimension at that coordinate location to hear it.

**Describe the solution you'd like**
Simple move of the methods `playSound()` and `playMusic()` from `World` to `Dimension` class, which would make them specific on a dimension level.

**Describe alternatives you've considered**
There is currently no way to play sound specific to a location by scripting alone, however having a custom entity that produces the sound or music in that exact specific place is an alternative work-around I've thought of.

**Additional context**
None

**Comment by JimSeaman42** [comment]
Thank you for reaching out; we are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
