### ISSUE TITLE
Minecraft File Extensions Page Lists Irrelevant Extensions?

### ISSUE THREAD

**Issue by Ciosciaa** [MicrosoftDocs/minecraft-creator#600]
On the [Minecraft File Extensions](https://learn.microsoft.com/en-us/minecraft/creator/documents/minecraftfileextensions) page, a number of extensions seem not to be used for Bedrock edition.

The affected file extensions includes:
- `.mcgame`
- `.mca`
- `.mcr`
- `.mcmeta`

**Comment by iconicNurdle** [comment]
Good catch -  I have made the edits and they will be visible after the next document release. Thank you!
