### ISSUE TITLE
[Script API] playerLeave is difficult to work with

### ISSUE THREAD

**Issue by Metro420yt** [MicrosoftDocs/minecraft-creator#602]
**Is your feature request related to a problem? Please describe.**
while making a script to circumvent the "Player Offline" text on scoreboards and actually show the username of the player, im having to just hope that there's not more than 1 player offline
the object given with the event only contains player name and id (unsure if there's a way to get the score with that info)

issues:
- scoreboard display name gets updated to "commands.scoreboard.players.offlinePlayerName" before the function runs (cant search for playerName = displayName)
- participant#getEntity throws errors (feel like *something* could've been returned)
- participant doesn't contain the player id

these make it really difficult to find the appropriate scoreboard entry

**Describe the solution you'd like**
a full/semi-full player object for event object

**Describe alternatives you've considered**
either one:
- a beforePlayerLeave event?
- player id in participant object <- might be better

###### im relying on the typings (1.1.0-beta.1.19.70-stable) so it might just be that the typings are missing some things, idk

**Comment by ConsoleTerm** [comment]
Can I ask? Do you need to change scores for players even after they leave? Am I understanding this correctly?

**Comment by Metro420yt** [comment]
no, when a player leaves, the script makes a dummy score with the same name and score as the player to get rid of the "Offline Player" thing

**Comment by ConsoleTerm** [comment]
> no, when a player leaves, the script makes a dummy score with the same name and score as the player to get rid of the "Offline Player" thing

I dont think, this is the behavior. 
- Why display name is not saved has i valid reason, because player can change its nameTag any time.
- Why getEntity doesnt returning the player is, because player is no longer in the world
