### ISSUE TITLE
Chunker.app CLI?

### ISSUE THREAD

**Issue by marto55555** [MicrosoftDocs/minecraft-creator#603]
I was wondering if the conversion functionality of Chunker.app is offered in a command-line interface. I noticed that at the bottom of the website, a CLI version is mentioned, but I could not find any mentions or downloads of the CLI anywhere else.

Apologies if this isn't the correct place to ask for this.

**Comment by FormallyMyles** [comment]
Hi!

This is currently something we provide, the versions provided on the bottom of Chunker reference internal parts of the software (it does indeed use a CLI internally but isn't designed for use outside of that).

**Comment by kakinnun** [comment]
Closing as this has been answered.
