### ISSUE TITLE
[Script API] EntityHit hitBlock not working in adventure

### ISSUE THREAD

**Issue by KevinTMeister** [MicrosoftDocs/minecraft-creator#605]
**Describe the bug**
The event entityHit, doesn't trigger when a player hits a block while they're in adventure mode.

**To Reproduce**
Subscribe to the entityHit event, and console.log the hitBlock data. Then in-game place yourself in adventure mode and hit a block. You will see that it doesn't detect you hitting the block.

**Expected behavior**
You're literally hitting a block, by definition it should detect the action of you hitting a block.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 1.19.73

**Additional context**
The only exception is when you're in adventure mode and there's an allow block below the block you're hitting, this is the only time it triggers you hitting a block while in adventure. It seems to only trigger when you start breaking the block.

**Comment by JimSeaman42** [comment]
Thank you for reaching out, and I'm sorry to hear about your issue. 

Currently, we are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
