### ISSUE TITLE
Components missing

### ISSUE THREAD

**Issue by RZ302** [MicrosoftDocs/minecraft-creator#606]
Looks like there are essential components missing from this list, despite the page saying it lists all available components.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc33d99-62f2-dee9-c865-3517fa9d4589
* Version Independent ID: 1fc33d99-62f2-dee9-c865-3517fa9d4589
* Content: [Block Documentation - Block Components List](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/blockcomponentslist)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponents/BlockComponentsList.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponents/BlockComponentsList.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by iconicNurdle** [comment]
@RZ302 You're right. It is a moving target and I will look into what is missing. If you can send me any particular ones you see are missing, I would be grateful for the help!

**Comment by iconicNurdle** [comment]
Follow up: It looks like the list is up to date for the next release, but again, if you know of any Block Components that are still missing, I welcome your help. I'm closing this for now, but do please feel free to reopen it or create a new ticket. Thanks!
