### ISSUE TITLE
Supplement Document minecraft:bone_visibility

### ISSUE THREAD

**Issue by CoolLoong** [MicrosoftDocs/minecraft-creator#607]
**Describe the missing content**
A clear and concise description of what the content is. Ex. missing entries in reference documentation,  poor or incorrect examples, critical key features not covered. 
This item is missing from the document, which is new on 1.19.80

**Vanilla usage example**
An example of the content being used in Minecraft: Bedrock Edition. Ex. •	minecraft:behavior.avoid_mob_type is being used by vanilla mobs but is undocumented

**Additional context**

**Comment by JimSeaman42** [comment]
Thank you for your comment! Information on bone visibility can be found [here](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_geometry). I hope this helps!
