### ISSUE TITLE
Use new `lang` grammar for .lang code instead of `json`

### ISSUE THREAD

**Issue by AdamRaichu** [MicrosoftDocs/minecraft-creator#609]
**Is your feature request related to a problem? Please describe.**
Syntax highlighting for `lang` code blocks is not accurate.

**Describe the solution you'd like**
Use [the new highlight.js grammar](https://github.com/highlightjs/highlightjs-lang) (available as of [11.8.0](https://github.com/highlightjs/highlight.js/releases/tag/11.8.0)) instead of JSON.

**Describe alternatives you've considered**

**Additional context**
I am the author of the hljs grammar, and I don't know if this is a concern for some kind of conflict of interest? I don't know if there are any rules about that.

The grammar would have to be loaded through a script onto the pages it is required on, but it is lightweight (only 703 bytes).

Affected pages:

- https://learn.microsoft.com/en-us/minecraft/creator/documents/preparingrawtextforlocalization
- https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontoaddentity
- https://learn.microsoft.com/en-us/minecraft/creator/documents/packagingaskinpack
- https://learn.microsoft.com/en-us/minecraft/creator/documents/packagingaworldtemplate

Before:

![image](https://user-images.githubusercontent.com/91494019/235311725-ff7b468c-c6a7-42f2-bba4-3cabcdf5f22b.png)

After: 

![image](https://user-images.githubusercontent.com/91494019/235311720-ab569544-d477-480e-a876-540dc3c30db0.png)

**Comment by AdamRaichu** [comment]
Also supports comments.

![image](https://user-images.githubusercontent.com/91494019/235311794-c28ff6cb-b214-4879-85aa-7375b83b737b.png)

**Comment by JimSeaman42** [comment]
Thanks for your feedback! I will forward your suggestion on the team. Have a great day!
