### ISSUE TITLE
how to make multiple triggers for different events in entity sensor?

### ISSUE THREAD

**Issue by PinhoPlays** [MicrosoftDocs/minecraft-creator#612]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8aafbf9-cedb-0ec1-2792-8f2558449413
* Version Independent ID: fe4c7e0b-037a-fcfb-e496-46569dd69bff
* Content: [Entity Documentation - minecraft:entity_sensor](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_entity_sensor)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_entity_sensor.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_entity_sensor.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JimSeaman42** [comment]
Thank you for your issue. Unfortunately, we are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
