### ISSUE TITLE
 Unexpected "#"  on /scoreboard players set #red wool_placed 0

### ISSUE THREAD

**Issue by RSereno** [MicrosoftDocs/minecraft-creator#616]
Gettting Unexpected "#"  in the command:
`/scoreboard players set #red wool_placed 0`
Am I missing something?

Error from chat:
![image](https://user-images.githubusercontent.com/5967998/236254355-06750675-4a1a-4d74-a6c3-82cecd804f03.png)

Section:
"Anyway, to keep things nice and tidy, we are going to create three fake players so that the scoreboard will track whether red, green, or blue wool is placed. If we name our fake players #red, #green, and #blue, the hash (#) at the start of each name will prevent our fake players from appearing in the list of scores on the sidebar.

Use these commands to create fake players, add them to the wool_placed objective, and give each one a score of 0.

```
/scoreboard players set #red wool_placed 0
/scoreboard players set #green wool_placed 0
/scoreboard players set #blue wool_placed 0
```
"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 575e32c5-ac42-981a-f440-b7dfae1c0583
* Version Independent ID: 575e32c5-ac42-981a-f440-b7dfae1c0583
* Content: [How To Make a Complete the Monument World](https://learn.microsoft.com/en-us/minecraft/creator/documents/commandshowtomakeactmworld)
* Content Source: [creator/Documents/CommandsHowToMakeACTMWorld.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CommandsHowToMakeACTMWorld.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by RSereno** [comment]
So if I understand correctly from what I was following the "#red" player doesnt exist, its just a fake player. I will test it once I'm back home.

**Comment by iconicNurdle** [comment]
Hi! I'm going to close this for now. If you're still having trouble, let me know.

**Comment by ProsperoTheBun** [comment]
@RSereno has a valid issue, same as I do.
`#red` does not seem to be a valid player name. I get the same error: `Unexpected "#"`
I am currently on v1.20.72.
@iconicNurdle I think you should reopen this issue.

**Comment by kevocl** [comment]
If anyone is following the guide "Create an In-World Game with Commands" on the learn.microsoft.com website, try putting the player name in quote marks e.g.

`/scoreboard players set "#red" wool_placed 0`
