### ISSUE TITLE
Anger_level, incorrect documentation and missing properties

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#620]
Thanks to: https://github.com/Blockception/Minecraft-bedrock-json-schemas/pull/175

But default_annoyingness can be number but is specified as string
default_projectile_annoyingness is missing but can be found in the warden

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22b035f0-de4b-0cb1-a27a-2fb2d8209447
* Version Independent ID: 22b035f0-de4b-0cb1-a27a-2fb2d8209447
* Content: [Entity Documentation - minecraft:anger_level](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_anger_level)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_anger_level.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_anger_level.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by iconicNurdle** [comment]
@DaanV2 Good catch! Changes are made and should be visible after the next release. Thanks!
