### ISSUE TITLE
Missing documentation of minecraft:spell_effect

### ISSUE THREAD

**Issue by SWyoru** [MicrosoftDocs/minecraft-creator#627]
**Describe the missing content**

The entry of "minecraft:spell_effect" is missing, it is mentioned in the id lists in the entity json, and is used in minecraft:player.
I'd like to know all the parameters of minecraft:spell_effect.

**Vanilla usage example**

      "minecraft:add_bad_omen": {
        "minecraft:spell_effects": {
          "add_effects": [
            {
              "effect": "bad_omen",
              "duration": 6000,
              "visible": false,
              "display_on_screen_animation": true
            }
          ]
        }

**Comment by JimSeaman42** [comment]
Thank you for your feedback! You can find information on the 'minecraft:spell_effects' entity component [here](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_spell_effects). The table of contents has been updated to display a link to the article, and will be updated on the next release.
