### ISSUE TITLE
Chunker.app - Oops, Failed to connect to backend

### ISSUE THREAD

**Issue by skyofsimba** [MicrosoftDocs/minecraft-creator#629]
Oops, Failed to connect to backend
Something went wrong communicating with the server.

It asks me to RESTART everytime I uploaded my world.

On MS Edge 113.0.1774.57
From China using VPN
Trying to upload a world folder from latest Bedrock edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by FormallyMyles** [comment]
This means that Chunker cannot continue your session, when using a VPN you would need to ensure all your traffic is going through the VPN and that the VPN supports WebSockets. It may help to try a different browser, but I'd suspect it's down to your VPN configuration.

**Comment by kakinnun** [comment]
Closing as the question was answered.

**Comment by skyofsimba** [comment]
omg I forget to comment...
It's due to VPN yes thank you very much!
