### ISSUE TITLE
Missing documentation: minecraft.equipment, slot_drop_chance

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#63]
Documentation on the slot_drop_chance object structure is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0de294-7e38-8904-0f82-117baed9d78a
* Version Independent ID: eec92cc6-364a-03a1-495e-0a079444e88f
* Content: [minecraft:equipment](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_equipment)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_equipment.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_equipment.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This has been added [here](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_equipment). Thanks for submitting.
