### ISSUE TITLE
Incomplete list of Vanilla entities that are using it

### ISSUE THREAD

**Issue by Andexter8** [MicrosoftDocs/minecraft-creator#630]
The list of Vanilla entities using minecraft:variant is incomplete, it is missing these entities: lingering potion(it uses it for the potion ID), splash potion (it uses it for the potion ID), and falling block (it uses it for the block type). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 023be26f-ed56-ad5c-6b7b-a6e6ca81c417
* Version Independent ID: 023be26f-ed56-ad5c-6b7b-a6e6ca81c417
* Content: [Entity Documentation - minecraft:variant](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_variant)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_variant.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_variant.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by iconicNurdle** [comment]
I'm taking this one.

**Comment by iconicNurdle** [comment]
@Andexter8 - You are correct that there are ways to access variants for those entities, but it's not done exactly the same way as the other Vanilla Behavior Pack entities on the list. I will be updating the header of that section in this document for better clarity, and the entities you submitted may be used in future documentation relating to the other process.
