### ISSUE TITLE
Missing Parameter

### ISSUE THREAD

**Issue by Andexter8** [MicrosoftDocs/minecraft-creator#631]
The “min” parameter which sets the entities minimum health is missing from the parameters list on the minecraft:health page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9287f7a8-ab7c-b1ea-ddd5-cd1ae19b6ca2
* Version Independent ID: 9287f7a8-ab7c-b1ea-ddd5-cd1ae19b6ca2
* Content: [Entity Documentation - minecraft:health](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_health)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_health.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_health.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! Additional information has been added regarding maximum and minimum range options for the 'value' parameter; this will be updated as of the next release.

**Comment by Andexter8** [comment]
That is not what I meant, I was not talking about the value parameter, the min parameter that I was talking about is a separate parameter from the value parameter, just like the max parameter, and setting the min parameter to anything above 0 makes the entity invincible to everything, including the /kill command.
