### ISSUE TITLE
ageable and ambient_sound_interval component links go to the opposite pages

### ISSUE THREAD

**Issue by stsco** [MicrosoftDocs/minecraft-creator#632]
**Describe the bug**
The entity json components ageable and ambient_sound_interval links on the left go to the opposite pages.

**To Reproduce**
1. Click on the Entity JSON > Components > ageable
2. See ambient_sound_interval page load
3. Click on Entity JSON > Components > ambient_sound_interval
4. See ageable page load

**Expected behavior**
The opposite (ie. Matching) page loads when it's shortcut is clicked

**Screenshots**
![image-3](https://github.com/MicrosoftDocs/minecraft-creator/assets/57239664/d7d82177-7f1b-42b5-8d50-b419a9e037de)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Edge
 - Version: Unknown

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by JimSeaman42** [comment]
Thank you for your feedback! This issue has been remedied and will be updated with the next release.
