### ISSUE TITLE
Importing Worlds

### ISSUE THREAD

**Issue by DJW0lF710** [MicrosoftDocs/minecraft-creator#633]

**Comment by DJW0lF710** [comment]
Importing Words needs to be more informational. There is no information on how to import your Minecraft Bedrock edition worlds to Minecraft Bedrock Editor Mode and vise versa

**Comment by JimSeaman42** [comment]
Thank you for your feedback! There are instructions on both importing worlds into Editor and exporting projects in our editor overview, available [here](https://learn.microsoft.com/en-us/minecraft/creator/documents/editoroverview).
