### ISSUE TITLE
Add changing FOV to /camera command

### ISSUE THREAD

**Issue by DoneAccount** [MicrosoftDocs/minecraft-creator#634]
Suggestion: Add a way to change FOV on the fly with easings included. It is a very important part of camera work and I don't think it should be neglected.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f30b26ff-e7a7-1d1c-4684-38edcbe04628
* Version Independent ID: f30b26ff-e7a7-1d1c-4684-38edcbe04628
* Content: [Camera Command Introduction](https://learn.microsoft.com/en-us/minecraft/creator/documents/cameracommandintroduction)
* Content Source: [creator/Documents/CameraCommandIntroduction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CameraCommandIntroduction.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by iconicNurdle** [comment]
Neat idea! I will pass it along to the team. :)
