### ISSUE TITLE
Missing mention of needed experiemental toggle

### ISSUE THREAD

**Issue by DrinkWater623** [MicrosoftDocs/minecraft-creator#636]
[Enter feedback here]
Requires Experiment Upcoming Creator Features and the page does not mention it.  

Otherwise great page, thank you!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31213522-0a81-c695-f4cc-7b74c6816676
* Version Independent ID: 31213522-0a81-c695-f4cc-7b74c6816676
* Content: [Block Documentation - Block Traits](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blocktraits)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockTraits.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockTraits.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! The experimental status has been added to the page, and will update with the next release.
