### ISSUE TITLE
'Import java mods when converting worlds' - option suggestion

### ISSUE THREAD

**Issue by PersonWhoExists1929** [MicrosoftDocs/minecraft-creator#639]
hi, i was just wondering if you guys could add a feature to Chunker that allows you to import java edition mods. Im interested in converting my long-time bedrock world to java, but i dont want to lose my Old Stonecutters, nether reactor cores, etc. I figured if i could make a mod that adds those blocks to java, i could use the block mapping feature to convert those mcpe blocks to the my mod's equivalent of them, but i cant import mods is the problem. 

Could a chunker developer look into adding this as a possible feature, thanks!
i guess you can also add a bedrock addons equivalent as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by FormallyMyles** [comment]
Hi!

Chunker does technically already support this, you can use custom identifiers in block mappings which would allow you to make mappings from Bedrock -> Java that work with a mod.

**Comment by PersonWhoExists1929** [comment]
so from my understanding, ill need to do this:
BE = minecraft:stonecutter_block - JE = oldmcpeblocks:old_mcpe_stonecutter

And once ive done that, minecraft and my mod loadee can figure out the rest?

**Comment by FormallyMyles** [comment]
Indeed that would in theory work

**Comment by PersonWhoExists1929** [comment]
alrighty, i appreciate your help.

**Comment by JimSeaman42** [comment]
It looks like this has been cleared up in the comments, which is fantastic! As such, I am going to mark the issue closed. Thank you so much!
