### ISSUE TITLE
The version on the server-ui module is wrong

### ISSUE THREAD

**Issue by DavideVailati** [MicrosoftDocs/minecraft-creator#640]
[Enter feedback here]
it's not release 1.2.0 server-ui rather 1.0.0 server-ui

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be0af04e-cd1f-bf70-f929-88902c7fd785
* Version Independent ID: be0af04e-cd1f-bf70-f929-88902c7fd785
* Content: [1.20 Update Notes](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.20)
* Content Source: [creator/Documents/Update1.20.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/Update1.20.md)
* Product: **gaming**
* GitHub Login: @kakinnun
* Microsoft Alias: **kakinnun**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! After review we found that @Minecraft/server version 1.0.0 released with version 1.19.50 (notes [here](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.19.50)), and version 1.1.0 was released with the version 1.19.80 update (notes [here](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.19.80)), so this information looks to be correct.

**Comment by DavideVailati** [comment]
Hi,
No, the @minecraft/server version is correct, but the @minecraft/server-ui version is not.
![image](https://github.com/MicrosoftDocs/minecraft-creator/assets/70967385/1234c006-5d8e-4118-bffe-748af8e22e77)
the correct version for @minecraft/server-ui is 1.0.0. I know this because 1.2.0 throws versioning errors, while 1.0.0 works perfectly.

**Comment by JimSeaman42** [comment]
Thanks for the feedback, the information will be updated with the next release.
