### ISSUE TITLE
Chunker Y biome error

### ISSUE THREAD

**Issue by paj1s** [MicrosoftDocs/minecraft-creator#642]
With or without "Prevent Y Biome Blending" on, under 16 of world height, in the overworld and the nether, the biome is always plains.
Tested while converting from newer version to older (1.19.4 -> 1.17.1, 1.16.5).

**Comment by FormallyMyles** [comment]
This is expected, biomes that don't exist on older versions are automatically set to plains.

**Comment by paj1s** [comment]
I don't think so, it even changed biome in the nether and i got the old nether where there is "nether wastes" everywhere but now at level 16 there's the nether waste biome changing with plain on some kind of noise pattern and under this level there is just plains. The end got untouched thankfuly. And overworld is the same as nether. This is weird, i double checked and in the source world the biome is the same from bottom to the top and i think 1.17.1 knows what taiga is. I thought that 3d biomes were introduced in 1.18 first so how can 1.16.5 world have 2 different biomes in the same xz.

**Comment by FormallyMyles** [comment]
> thankfuly

The biomes became vertical from 1.15.2, so any version above that Chunker will attempt to put it into the format for that. The biomes over those versions did change a bit so 1:1 conversion isn't necessarily possible. 
I'll write up a suggestion to make the fallback dimension aware as indeed plains in the nether isn't preferred.

**Comment by paj1s** [comment]
Oh i wasn't aware that this feature dates back to 1.15.2. Thanks.

**Comment by JimSeaman42** [comment]
Thanks to the engagement here, it looks like this has been cleared up. As such, I am going to close the issue. Thanks so much!
