### ISSUE TITLE
Bedrock to Java (1.20): Hoppers don't move items until opened

### ISSUE THREAD

**Issue by Crimsn64** [MicrosoftDocs/minecraft-creator#649]
I have discovered that hoppers do not move items until opened (right clicked by the player)
The world used in my survival world converted from Bedrock 1.20 to Java 1.20

**Comment by FormallyMyles** [comment]
I've added this to our backlog to fix in the future, thank you for reporting it!

**Comment by JimSeaman42** [comment]
Thank you for your feedback! As per the comments, it seems that this issue can be closed. Have a great day!
