### ISSUE TITLE
Missing property: minecraft:is_stackable

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#65]
Missing property in the documentation: `value`, from the [chest_minecart](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/chest_minecart)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e359e3-22b9-e17d-e167-6cc49acada03
* Version Independent ID: 324e54ac-feba-847a-af96-013e59867795
* Content: [minecraft:is_stackable](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityproperties/minecraftproperty_is_stackable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_is_stackable.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityProperties/minecraftProperty_is_stackable.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by iconicNurdle** [comment]
I added the info and the example from chest minecart. Thanks for the info!
