### ISSUE TITLE
Chunker: Bedrock biomes aren't converted correctly

### ISSUE THREAD

**Issue by Crimsn64** [MicrosoftDocs/minecraft-creator#650]
My world has a mushroom island center and parts of the island are incorrectly converted as ocean and plains. some parts are successfully converted as mushroom fields. The incorrectly converted parts are somehow y level dependent, i can be around my chest area (which is mushroom fields (correct) and fly up 20 blocks to reach a plains biome in the air as well as an ocean biome a few blocks futher in the y axis. then goes ocean up to around 140 Y and after that its plains again onwards

**Comment by FormallyMyles** [comment]
Could you clarify what version and edition your world is? And the destination format?

Screenshots are also appreciated if possible with F3 on Java.

**Comment by Crimsn64** [comment]
its a Bedrock World on 1.20.1 (which was originally created around 1.15) converted to Java 1.19.3 (I apologize, i should've realized that this is probs a side affect of going back some versions)

**Comment by FormallyMyles** [comment]
If you're able to send a copy of the map to `chunker-public@hivemc.com` (feel free to use something like OneDrive if it's a big world) with coordinates and we'll get this investigated when we can. There is indeed a loss in biomes going backward in versions, but I don't believe what you've described should be impacted.

**Comment by FormallyMyles** [comment]
Thank you for submitting the world, we've reviewed the world and the biome issues come down to a few things:
- Java uses biome blobs of 4x4x4 whereas Bedrock can have a biome per block.
- Java does various blending, you can turn off Biome Blend in the settings, and in Chunker in Advanced you can use "Prevent Y Biome Blending"
- When a Chunk isn't present in the Java world, you'll see the plains biome (as it's the default biome).
- There was a bug in Chunker that led to biomes being incorrectly converted in some cases, this would be the reason you would see the ocean biome sometimes in the air. This should be fixed as of our latest update.
