### ISSUE TITLE
Chunker: World

### ISSUE THREAD

**Issue by Kaktusmc** [MicrosoftDocs/minecraft-creator#651]
I don't know what category to put it in, but this one seems the best for it.

Some time back I uploaded a map to Chunker which I later deleted from my device. I would need her back. That you have it? You must have it. You are my last hope. When your worlds uploaded to Chunker are saved somewhere, I'm able to write the name of it and maybe remember other things. I know the name for sure. 

Ideally, I would still need an unedited version of it, but if you only have an edited version, that will also be enough for me. I really need it, so I will be happy if you have it saved somewhere.

Thanks in advance
```[tasklist]
### Tasks
```

**Comment by FormallyMyles** [comment]
Unfortunately, we wouldn't have your world. As stated in our Privacy Policy, we don't hold the world data for longer than is needed and we're unable to access that data regardless. 

Sorry to be the bearer of sad news :(

**Comment by Kaktusmc** [comment]
Noooooooo :((((((((

**Comment by JimSeaman42** [comment]
I'm sorry to see your issue, and that there's not a viable solution to be found here. Based on the information in the comments, I am going to mark this issue as closed.
