### ISSUE TITLE
com.mojang doesnt seem to exist?

### ISSUE THREAD

**Issue by JustARandomFrozenPotato** [MicrosoftDocs/minecraft-creator#652]
the instructions say to go into your com.mojang file but my computer doesnt seem to have one? could someone tell me where to find it and if i cant, tell me why i wouldnt have one please?

**Comment by JimSeaman42** [comment]
Thanks for your feedback! The good news is, if you have Minecraft installed, you have the com.mojang folder; the issue may be finding it. If you're on Windows 11, try this:
- Open File Explorer and click the "..." menu
- Click on the "View" tab
- Click the "Show hidden files, folders, and drives" radio button
- De-select "Hide extensions for known file types"
- Click "Apply"

After this you should be able to follow the tutorial with no issue :) 

I hope this helps!
