### ISSUE TITLE
Water is fluida insted of fluid

### ISSUE THREAD

**Issue by avinaces** [MicrosoftDocs/minecraft-creator#653]
What is `fluida`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3824c7-7525-4841-4cd7-d6da28d500ee
* Version Independent ID: 5a3824c7-7525-4841-4cd7-d6da28d500ee
* Content: [.FluidType Enumeration](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/fluidtype)
* Content Source: [creator/ScriptAPI/minecraft/server/FluidType.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/minecraft/server/FluidType.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by JimSeaman42** [comment]
Hi, I believe it's safe to assume it is an easy-to-make spelling error that will be removed with the next update.
