### ISSUE TITLE
Why can't we use custom ingredients in smithing transform recipes?

### ISSUE THREAD

**Issue by jamiestay** [MicrosoftDocs/minecraft-creator#655]
[Enter feedback here]
In the addition component inside smithing transform recipes only netherite ingots can be used, otherwise the recipe simply doesn't work. The documentation states that only netherite ingots can be used, but it is still frustrating. It seems like a simple fix by the developers to allow custom addition ingredients but it has been this way for multiple updates. From what I've found there's no workaround for this issue, and if there is I would like to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00a8b3f0-2c7b-9e8b-87f1-951d70e074ee
* Version Independent ID: 00a8b3f0-2c7b-9e8b-87f1-951d70e074ee
* Content: [Recipe Documentation - Smithing Transform Recipe](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/recipedefinitions/minecraftrecipe_smithingtransform)
* Content Source: [creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_SmithingTransform.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_SmithingTransform.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jimseaman**

**Comment by JimSeaman42** [comment]
Thank you for the feedback! Unfortunately, this feedback channel is only for issues relating directly to the articles themselves; I would recommend submitting this suggestion to https://feedback.minecraft.net/ . I hope that helps! :)

**Comment by edAtronash** [comment]
Pues aquí va una sugerencia ,  que tal el hacer público  los archivos .json   se  la update
