### ISSUE TITLE
Broken links and missing pages

### ISSUE THREAD

**Issue by abrightmoore** [MicrosoftDocs/minecraft-creator#658]
**Describe the bug**
The table of contents to the left of the page https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_push_through links to missing pages (error 404)

**To Reproduce**
1. Go to https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_push_through
2. Click on 'collision_box' in the left navigation pane
3. Note the page linked does not exist: https://learn.microsoft.com/en-us/minecraft/creator/minecraftComponent_collision_box.md

**Expected behavior**
A page should load corresponding to the topic in question.

**Screenshots**
n/a.

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by JimSeaman42** [comment]
Thanks for the feedback! The errant link will be updated with the next release.
