### ISSUE TITLE
Chunker.app - Oops, failed to upload world

### ISSUE THREAD

**Issue by SkyKingPX** [MicrosoftDocs/minecraft-creator#659]
**Describe the bug**
Everything you try to upload doesn’t work

**To Reproduce**
1. Go to chunker.app
2. Upload File or Folder
3. See error

**Expected behavior**
That it would work and that I could change the version then.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: OperaGX, MS Edge
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: IOS 17.0 (21A5277j)
 - Browser: Safari

**Comment by FormallyMyles** [comment]
Would you be able to provide further information:
- What kind of internet setup do you have?
- Have you tried another browser like Chrome?
- Does this happen on both your phone and desktop?
- Could you provide the full error it shows?
- Have you ensured you've closed Minecraft when uploading?
- Any other information you might think is also useful

Thanks!

**Comment by FormallyMyles** [comment]
I can't see anything wrong with what you've provided.

Would you be able to provide a video of you uploading the world and getting the error?
Would you also be able to email a copy of your world so we can see if it might be related to that? The email is chunker-public@hivemc.com, please use OneDrive etc if the world is big.

Additionally, some further questions:
How big is your world (in megabytes)?
Would you say your internet connection was reliable?
How long does it take you to upload your world?
Do you upload as a zip or use the folder option, have you tried the other option?

**Comment by SkyKingPX** [comment]
I can record a video and send you the world, but not now.

My connection is good (5 Mbit/s).

The world is around 200 MB big.

I tried all options.

@FormallyMyles

**Comment by SkyKingPX** [comment]
Here the Video:


https://github.com/MicrosoftDocs/minecraft-creator/assets/95442431/b50d716a-380c-4b2d-a569-54053c0537a7

**Comment by FormallyMyles** [comment]
> I am sending the Mail with the Title "Github Issue #659 - world.mcworld"

Thank you for the world, how did you create the world.mcworld file? Could you try creating it again?

From looking at our internal logs, it reports that the zip is corrupted.

**Comment by FormallyMyles** [comment]
The issue should now be fixed, we've hardened our reading of .zip / .mcworld to recover in more cases where there is slight issues with reading it.

**Comment by SkyKingPX** [comment]
I will try it @FormallyMyles . Thanks.



>Could you try creating it again?

I already did and tried again, but there still was the error. I downloaded the World from our Aternos Server, because we wanted to switch the game version.

**Comment by SkyKingPX** [comment]
@FormallyMyles it works now thanks:

![image](https://github.com/MicrosoftDocs/minecraft-creator/assets/95442431/2f0382d6-e02a-46ab-9946-68b1cee324c0)
