### ISSUE TITLE
Missing property: minecraft:navigation.walk

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#66]
Missing property: `can_float`

From the [cat](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/cat)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9639c0-4b85-21bb-d209-680938d1cc5a
* Version Independent ID: 5b9e2082-909b-5dce-aa69-711aa450ac0f
* Content: [minecraft:navigation.walk](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.walk)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_navigation.walk.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_navigation.walk.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
This is now live [here](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.walk). Thanks for submitting!
