### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by Carlos293711** [MicrosoftDocs/minecraft-creator#665]
Cool but how do we do this for consoles
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4722db-3980-4b38-a102-53f10132095e
* Version Independent ID: 7d4722db-3980-4b38-a102-53f10132095e
* Content: [Getting Started with Deferred Lighting](https://learn.microsoft.com/en-us/minecraft/creator/documents/deferredlighting)
* Content Source: [creator/Documents/DeferredLighting.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DeferredLighting.md)
* Product: **gaming**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by kakinnun** [comment]
On Xbox, you would have to join a server that has a PBR-enabled resource pack installed.

**Comment by Carlos293711** [comment]
And if thats not possible what is another way?

**Comment by kakinnun** [comment]
Currently, that's the only way.
