### ISSUE TITLE
Incorrect Syntax?

### ISSUE THREAD

**Issue by x1devan** [MicrosoftDocs/minecraft-creator#668]
There is many example code sections on this page that have incorrect names, extra commas, and missing brackets that would not work when adding it to a pack. I am not referring to the places where you are meant to add your own code into some sections.

The only two that I checked are the Sample Smiley Block and the Sample Torch Block.

I was hoping this could be looked at

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31213522-0a81-c695-f4cc-7b74c6816676
* Version Independent ID: 31213522-0a81-c695-f4cc-7b74c6816676
* Content: [Block Documentation - Block Traits](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blocktraits)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockTraits.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockTraits.md)
* Product: **gaming**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! The issue has been remedied and will be updated with the next release.
