### ISSUE TITLE
Missing documentation: minecraft:ravager_blocked

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#67]
Missing documentation on the object structure of: `reaction_choices`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f0d6dc-2fdd-ca0a-b95e-0947a942321b
* Version Independent ID: f18879f5-65df-c0c4-8ceb-b4f95575f43f
* Content: [minecraft:ravager_blocked](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_ravager_blocked)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_ravager_blocked.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_ravager_blocked.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
This is live: https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_ravager_blocked
