### ISSUE TITLE
Fillblocks Does not works

### ISSUE THREAD

**Issue by gonblesses** [MicrosoftDocs/minecraft-creator#673]
**Describe the bug**
=> dimension method "fillBlocks" doesn't work
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JimSeaman42** [comment]
Thank you for your issue; sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
