### ISSUE TITLE
Docs issue：the problem of "trouble shooting"

### ISSUE THREAD

**Issue by AbbottMc** [MicrosoftDocs/minecraft-creator#674]
Following the instructions in the illustrated tutorial has no effect. Launched app is still Minecraft Stable, not Minecraft Preview.  The final solution is to change the path `minecraft:?Editor=true` to `minecraft-preview:?Editor=true`

![image](https://github.com/MicrosoftDocs/minecraft-creator/assets/16969459/be7bf805-f561-414a-9c08-04f6138b77a5)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Version Independent ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Content: [Minecraft Bedrock Editor Installation](https://learn.microsoft.com/en-us/minecraft/creator/documents/editorinstallation)
* Content Source: [creator/Documents/EditorInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EditorInstallation.md)
* Product: **gaming**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
You are correct. I fixed this and it should be visible in the published docs soon. Thanks for the catch!
