### ISSUE TITLE
Key frames are swapped

### ISSUE THREAD

**Issue by Guuss** [MicrosoftDocs/minecraft-creator#681]
The key frames described in the examples and diagrams are swapped - 0.0 is noon and 0.5 is midnight. The example provided actually demonstrates this correctly.

This diagram causes confusion in particular:
[https://learn.microsoft.com/en-us/minecraft/creator/documents/media/deferredlighting/key_frame_times_of_day.png](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4722db-3980-4b38-a102-53f10132095e
* Version Independent ID: 7d4722db-3980-4b38-a102-53f10132095e
* Content: [Getting Started with Deferred Lighting](https://learn.microsoft.com/en-us/minecraft/creator/documents/deferredlighting)
* Content Source: [creator/Documents/DeferredLighting.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DeferredLighting.md)
* Product: **gaming**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Thanks for the catch! Corrections are on the way.
