### ISSUE TITLE
Shortcut creation path suggestion

### ISSUE THREAD

**Issue by sjbutts2000** [MicrosoftDocs/minecraft-creator#687]
Instead of using the **minecraft:?Editor=true** shortcut path, use this path instead: **minecraft-preview:?Editor=true** It's easier and dosen't require modifying your default apps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Version Independent ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Content: [Minecraft Bedrock Editor Installation](https://learn.microsoft.com/en-us/minecraft/creator/documents/editorinstallation)
* Content Source: [creator/Documents/EditorInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EditorInstallation.md)
* Product: **gaming**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
You are correct and this fix will be implemented very soon. Thanks for the catch!
