### ISSUE TITLE
Missing property: minecraft:shooter

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#69]
Missing property: `type`

from the [enderdragon](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/ender_dragon)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 507a4c1f-a2ae-73f3-0d5e-70690c840ce8
* Version Independent ID: 5770be4e-4cdc-9c90-a6af-51442d5da172
* Content: [minecraft:shooter](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_shooter)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_shooter.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_shooter.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by JimSeaman42** [comment]
Thank you so much for the feedback!

It has been determined that the information in question is not a creator-usable property, and the lack of definition is expected.
