### ISSUE TITLE
Bare enchantable component documentation

### ISSUE THREAD

**Issue by SIsilicon** [MicrosoftDocs/minecraft-creator#691]
the enchantable component barely has any documentation. It doesn't say what slots you can use nor goes into detail about the value property.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67e60e82-fe38-45a8-cf0a-4adfe9f3cfd0
* Version Independent ID: 67e60e82-fe38-45a8-cf0a-4adfe9f3cfd0
* Content: [Item Documentation - minecraft:enchantable](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_enchantable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_enchantable.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_enchantable.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thank you for your feedback. Our team will review the documentation and make any updates as necessary.
