### ISSUE TITLE
What does read only mode mean and how can you disable that bs

### ISSUE THREAD

**Issue by ChipLag** [MicrosoftDocs/minecraft-creator#694]
[Enter feedback here]
Why is there a read only mode for SETTING LORE?!?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc6cb16-0151-7098-e395-ff3ba055c082
* Version Independent ID: 2cc6cb16-0151-7098-e395-ff3ba055c082
* Content: [minecraft/server.Entity Class](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/entity)
* Content Source: [creator/ScriptAPI/minecraft/server/Entity.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/minecraft/server/Entity.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by JimSeaman42** [comment]
Thank you for your issue. Sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
