### ISSUE TITLE
I can't reproduce this tutorial

### ISSUE THREAD

**Issue by Marc-3d** [MicrosoftDocs/minecraft-creator#696]
Hi, 

I can copy the sample behaviour pack with the angry cows and that works for me.

However, I have tried for a while to follow the tutorial and I can't get the game to print anything to the chat. 

Is there any setting that needs to be set (apart from activating cheats on the world)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3264465c-a1b7-3e3d-cccf-4aa294e95b29
* Version Independent ID: 3264465c-a1b7-3e3d-cccf-4aa294e95b29
* Content: [Introduction to Scripting in Minecraft](https://learn.microsoft.com/en-us/minecraft/creator/documents/scriptingintroduction)
* Content Source: [creator/Documents/ScriptingIntroduction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ScriptingIntroduction.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
I'll be glad to help! 

First, a question: Does your code use the `TicksPerSecond` import, like this?

```
import {
    world,
    system,
    TicksPerSecond
  } from "@minecraft/server";
```

There was a recent change to remove TicksPerSecond from the import section, and calculate the timing differently. 
Make sure "TicksPerSecond" is not used anywhere in your code.

Another solution: Increase the time before the message is displayed.  Change the "400" to "1000" in this line...

```
function mainTick() {
  if (system.currentTick === 400) {
```

If neither of these actions help, please copy/paste your .js file here and I will take a look.

If it DOES work, please let me know - thanks! :)

**Comment by iconicNurdle** [comment]
I'm going to close this for now. If you have any further questions, please feel free to re-open this issue or start a new one. Thanks!
