### ISSUE TITLE
Missing documentation for collision_box entity component

### ISSUE THREAD

**Issue by burymaddie** [MicrosoftDocs/minecraft-creator#697]
**Describe the missing content**
The documentation page for the collision_box entity component does not exist.

**Vanilla usage example**
minecraft:collision_box is used in almost every entity

**Additional context**
The link to this component in the table of contents goes to minecraftComponent_collision_box.md, but that page does not exist.

**Comment by JimSeaman42** [comment]
Thank you for your feedback! The issue has been remedied and will be updated with the next release.
