### ISSUE TITLE
Enchantment Level Limitations

### ISSUE THREAD

**Issue by KDCaptivity** [MicrosoftDocs/minecraft-creator#698]
When creating or editing items using the scripting api you are limited to the maximum level that the enchantment can have when in survival, e.g. sharpness 5 or unbreaking 3, which makes it very difficult to create items that for example deal high amounts of damage or have a lower chance of using durability. This results in map makers being forced to manually change the nbt data of the items to increase the level of an enchantment.

The enchantment component of items should not reduce the new enchantment's level to its current maximum but instead limit it to its actual maximum of 32767.

**Comment by wslp12** [comment]
i agreed

**Comment by JimSeaman42** [comment]
Thank you for your issue, however we are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
