### ISSUE TITLE
Missing documentation: minecraft:timer, random_time_choices

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#70]
Missing documentation on the object structure of `random_time_choices`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31083949-7771-42ce-b80f-c01feec3549e
* Version Independent ID: dc798064-b81c-c6b4-4e85-01611494e783
* Content: [minecraft:timer](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_timer)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_timer.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_timer.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
This change is now live [here](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_timer). Thanks for submitting!
