### ISSUE TITLE
Update editor shortcut

### ISSUE THREAD

**Issue by jdorman24** [MicrosoftDocs/minecraft-creator#700]
It seems the new shortcut URI for opening the editor is `minecraft-preview:?Editor=true` rather than `minecraft:?Editor=true`

Problem lines:
* [ ] https://github.com/MicrosoftDocs/minecraft-creator/blob/2610c7ce18bd5a218222548d6779f05eeb3024bf/creator/Documents/EditorInstallation.md?plain=1#L65
* [ ] https://github.com/MicrosoftDocs/minecraft-creator/blob/2610c7ce18bd5a218222548d6779f05eeb3024bf/creator/Documents/EditorInstallation.md?plain=1#L69 (update image)
* [ ] https://github.com/MicrosoftDocs/minecraft-creator/blob/2610c7ce18bd5a218222548d6779f05eeb3024bf/creator/Documents/EditorInstallation.md?plain=1#L98
* [ ] https://github.com/MicrosoftDocs/minecraft-creator/blob/2610c7ce18bd5a218222548d6779f05eeb3024bf/creator/Documents/EditorInstallation.md?plain=1#L116
* [ ] https://github.com/MicrosoftDocs/minecraft-creator/blob/2610c7ce18bd5a218222548d6779f05eeb3024bf/creator/Documents/EditorInstallation.md?plain=1#L118 (update image)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Version Independent ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Content: [Minecraft Bedrock Editor Installation](https://learn.microsoft.com/en-us/minecraft/creator/documents/editorinstallation)
* Content Source: [creator/Documents/EditorInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EditorInstallation.md)
* Product: **gaming**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Great catch! This has been fixed and the change will appear after the next document release. Thank you!

**Comment by iconicNurdle** [comment]
Great catch! This has been fixed and the change will appear after the next document release. Thank you!
