### ISSUE TITLE
J’ai essayé chez moi ça fonctionne pas 

### ISSUE THREAD

**Issue by Tabarcraft** [MicrosoftDocs/minecraft-creator#704]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1b292f8-c0c9-78dd-e17f-18121f727501
* Version Independent ID: c1b292f8-c0c9-78dd-e17f-18121f727501
* Content: [Getting Started with Minecraft Item Wizard](https://learn.microsoft.com/en-us/minecraft/creator/documents/minecraftitemwizard)
* Content Source: [creator/Documents/MinecraftItemWizard.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/MinecraftItemWizard.md)
* Product: **gaming**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
"I've tried it at home but it doesn't work"

Hello! I would like to help. I do not speak French, but I will do my best using a translator. 
Can you tell me more about what happened?

translated:

Bonjour! J’aimerais aider. Je ne parle pas français, mais je ferai de mon mieux en utilisant un traducteur. 
Pouvez-vous m’en dire plus sur ce qui s’est passé ?

**Comment by Tabarcraft** [comment]
Bonjour, 

Merci de vouloir m’aider,
J’ai suivi les indications du site web mais l’épée n’apparaît pas dans le jeu.
Maintenant ça fonctionne mais j’aimerais quand même savoir le(s)problème(s) pour que ça ne se produise plus.

Bonne journée,

Ce type qui a toujours un problème

**Comment by iconicNurdle** [comment]
Bonjour! Je suis tellement heureux d’avoir de vos nouvelles! 

Pourriez-vous s’il vous plaît m’envoyer votre pack de comportement et votre pack de ressources? Veuillez les mettre dans un dossier zippé et les joindre ici. 

Dans le cas où « dossier zippé » ne se traduit pas correctement, je veux dire celui que Microsoft Windows fait pour vous si vous faites un clic gauche et choisissez « Compresser dans un fichier zip ». 

Si vous avez des difficultés à envoyer cela ici, s’il vous plaît laissez-moi savoir.

Bonne journée,

Quelqu’un qui aime résoudre les problèmes de Minecraft

**Comment by iconicNurdle** [comment]
Bonjour! Je suis tellement heureux d’avoir de vos nouvelles!

Je suis heureux que votre épée personnalisée fonctionne. J’aimerais qu’il y ait un moyen facile de dire ce qui a mal tourné, mais il y a beaucoup de choses qui auraient pu être la cause du problème.

Je travaille sur un nouveau tutoriel qui expliquera comment créer des éléments personnalisés, mais sans utiliser l’Assistant Élément personnalisé (Custom Item Wizard). Il expliquera les fichiers, les structures de pack et le code qui entrent dans les packs complémentaires, afin que vous puissiez avoir une meilleure idée de la façon de personnaliser un élément et vous aider à trouver des problèmes.

Cela sera similaire aux deux guides pour faire des blocs personnalisés: 

celle de l’assistante - https://learn.microsoft.com/fr-fr/minecraft/creator/documents/minecraftblockwizard 

... avec celle du non-assistant- https://learn.microsoft.com/fr-fr/minecraft/creator/documents/addcustomdieblock

Si vous rencontrez à nouveau des problèmes, veuillez mettre vos packs complémentaires dans un dossier zippé et me les envoyer pour que je puisse y jeter un coup d’œil, d’accord?

Bonne journée,

Quelqu’un qui aime résoudre les problèmes de Minecraft

**Comment by iconicNurdle** [comment]
Je ferme ce numéro, mais n’hésitez pas à nous parler à nouveau! 

Merci!
