### ISSUE TITLE
more than  1 entity riding with this component breaks it.

### ISSUE THREAD

**Issue by sweetBR** [MicrosoftDocs/minecraft-creator#707]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a87b59b6-d7c0-d812-8a14-45f8a681ee33
* Version Independent ID: a87b59b6-d7c0-d812-8a14-45f8a681ee33
* Content: [Entity Documentation - minecraft:behavior.controlled_by_player](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_controlled_by_player)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_controlled_by_player.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_controlled_by_player.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thank you for your issue; we're sorry to hear you are having trouble. We are unable to provide general support via this feedback channel that isn’t related to specific documentation issues.
