### ISSUE TITLE
Missing properties: minecraft:behavior.defend_trusted_target

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#71]
Missing documentation on the following properties:

- [ ] on_defend_start
- [ ] sound_chance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c5dce6b-8286-7980-d240-9050f91ae35b
* Version Independent ID: fb48dc2c-9528-c3d7-6092-87a0cd69bd46
* Content: [minecraft:behavior.defend_trusted_target](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_defend_trusted_target)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_defend_trusted_target.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_defend_trusted_target.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This has been updated []([here](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_defend_trusted_target).) Thanks for submitting.
