### ISSUE TITLE
Chromebook not working

### ISSUE THREAD

**Issue by XLHAPOLLO112** [MicrosoftDocs/minecraft-creator#710]
[I play Minecraft Bedrock edition on chromebook and there is a com.mojang folder, but no development_resource_packs folder. Is this because I'm on Chromebook? If so, how do I make the resource pack?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://learn.microsoft.com/en-us/minecraft/creator/documents/resourcepack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JimSeaman42** [comment]
Thanks for your feedback; we're sorry to hear that you're having trouble. This channel is for documentation-specific issues, but let's see if this helps: Review [this article](https://learn.microsoft.com/en-us/minecraft/creator/documents/gettingstarted) and follow the instructions; hopefully it helps.
