### ISSUE TITLE
Says `entities` not `items`

### ISSUE THREAD

**Issue by smell-of-curry** [MicrosoftDocs/minecraft-creator#711]
This section talks about the items that use this component, but it says entities instead of items.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c75aef2d-9e62-ebbb-beb5-9835d876e755
* Version Independent ID: 7f4bac0e-e8f0-f678-f19a-802202f58bc6
* Content: [Item Documentation - minecraft:food](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_food)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_food.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_food.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thanks for your feedback! Changes will be made to the verbiage with the next release.
