### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Scaietele** [MicrosoftDocs/minecraft-creator#713]
On this page: https://learn.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/recipedefinitions/tagsrecipeinput

The link that should lead to the tags page is broken. Not sure but I believe it should point to: https://learn.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/recipedefinitions/recipetaglist

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d983c83-5810-961d-20cc-2806d93667b3
* Version Independent ID: 3d983c83-5810-961d-20cc-2806d93667b3
* Content: [Tags as Recipe Input](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/recipedefinitions/tagsrecipeinput)
* Content Source: [creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/TagsRecipeInput.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/TagsRecipeInput.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! The link will be updated with the next release.
