### ISSUE TITLE
No mention of how to enable "Editor" in the Minecraft Bedrock server

### ISSUE THREAD

**Issue by praxis-alpha** [MicrosoftDocs/minecraft-creator#719]
What is the command to enable Editor mode in the bedrock server, that is running Minecraft Preview, to allow windows clients to join?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd3ff69-4b8a-06bd-b033-08e1c4503ae5
* Version Independent ID: 2bd3ff69-4b8a-06bd-b033-08e1c4503ae5
* Content: [Minecraft Bedrock Editor Overview](https://learn.microsoft.com/en-us/minecraft/creator/documents/editoroverview)
* Content Source: [creator/Documents/EditorOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EditorOverview.md)
* Product: **gaming**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Editor is only enabled in the preview version of Win32 Bedrock Dedicated Server.

There are two ways to launch it

1. Launch the .exe with the command line, like this: 

`bedrock_server.exe Editor=true`

- This will only work if you're launching BDS from scratch (no existing world)
- You should see the output say

###################################
#                                                                         #
#              CREATING EDITOR PROJECT              #
#                                                                         #
####################################

2. Create an Editor project from Minecraft

- Launch Editor from Minecraft Bedrock UWP Preview build
- Create a new Editor Project
- Locate the Editor Project in the com.mojang/minecraftWorlds folder and copy it into the BDS worlds folder
- Ensure that the server.properties has the correct world name, etc
- Execute bedrock_server.exe
- If correctly set up, you should see the output say

`[2023-10-24 07:21:43:977 INFO] Enabling Editor Services`

Editor Mode is controlled by a flag in the level data (not by the command line), so you need to launch the server either by having the server create a new Editor project, or by launching the server USING an existing Editor project.
Once the server is up and running, any client connections from Minecraft Bedrock Preview Edition will connect as editor sessions and present the editor interface.  Connections from Non-Preview editions of Minecraft will be refused.
