### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by Someone10A** [MicrosoftDocs/minecraft-creator#720]
[Escribir comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 80279e41-dd49-0d02-06c4-9581998f5840
* Version Independent ID: 80279e41-dd49-0d02-06c4-9581998f5840
* Content: [minecraft/server.ScoreboardIdentity Class](https://learn.microsoft.com/es-mx/minecraft/creator/scriptapi/minecraft/server/scoreboardidentity)
* Content Source: [creator/ScriptAPI/minecraft/server/ScoreboardIdentity.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/minecraft/server/ScoreboardIdentity.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by iconicNurdle** [comment]
¡Hola! Si tiene alguna pregunta, puede publicarla aquí. ¡Gracias!
