### ISSUE TITLE
Syntax error in example command

### ISSUE THREAD

**Issue by haramori** [MicrosoftDocs/minecraft-creator#722]
The example given for the /execute command on this page generates a syntax error in the latest version of Minecraft Bedrock and doesn't match the reference documentation for the /execute command at https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/execute.

/execute @a ~ ~ ~ detect ~ ~-1 ~ grass 0 say Player is standing on top of grass.

Syntax error: Unexpected "@a": at "/execute >>@a<< ~ ~ ~ det"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e155a62-a6aa-25ba-97ca-8aece7c4f4bf
* Version Independent ID: 83bf6950-1a24-dfad-fa4b-190d1d1e150c
* Content: [Popular Commands](https://learn.microsoft.com/en-us/minecraft/creator/documents/commandspopularcommands)
* Content Source: [creator/Documents/CommandsPopularCommands.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CommandsPopularCommands.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by iconicNurdle** [comment]
You are correct! `/execute` was updated and the new syntax for the same command is:

`/execute as @s positioned as @s if block ~ ~-1 ~ grass run say Player is standing on grass.`

I am updating that article now with all the neat things `/execute` can do now. 

Thanks!
