### ISSUE TITLE
How to create an entity that acts like an arrow?

### ISSUE THREAD

**Issue by Rey2723** [MicrosoftDocs/minecraft-creator#726]
[Enter feedback here]

I want to create my own arrow. How do i make the item and the arrow entity?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d49c4980-7355-33bd-f70f-423b7ac521d9
* Version Independent ID: 730e1b5f-43b6-cda3-589f-e3be4ea666a5
* Content: [arrow](https://learn.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/arrow)
* Content Source: [creator/Reference/Source/VanillaBehaviorPack_Snippets/entities/arrow.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Source/VanillaBehaviorPack_Snippets/entities/arrow.md)
* Service: **minecraft-bedrock-edition**
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by Rey2723** [comment]
I want to add a whole new arrow to the game.

**Comment by iconicNurdle** [comment]
Well, darn...I confirmed with two sources that there is no way to add arrows to Minecraft. It's a really great idea, though. Thanks for writing. 

Just to make sure you know about this - there are ways to add other custom items to the game, like a custom weapon or object - like a giant wrench...

Here is how to do that with a Blockbench plug-in...
https://learn.microsoft.com/en-us/minecraft/creator/documents/minecraftitemwizard

... and here is how to do the same thing with the individual files and folders:
https://learn.microsoft.com/en-us/minecraft/creator/documents/addcustomitems

All the best,
Jill

**Comment by Rey2723** [comment]
Thanks for letting me know!
