### ISSUE TITLE
api

### ISSUE THREAD

**Issue by CarlosTFK** [MicrosoftDocs/minecraft-creator#728]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 156a5c71-e42d-7075-74ef-03230369797b
* Version Independent ID: e0fbfe84-ce3a-9a97-6b45-009ad16ae4a9
* Content: [Addons Documentation - manifest.json](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest)
* Content Source: [creator/Reference/Content/AddonsReference/Examples/AddonManifest.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AddonsReference/Examples/AddonManifest.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
If you could detail the documentation feedback you have we can review the issue; otherwise, I will close the issue. Thanks!
