### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Narengalla** [MicrosoftDocs/minecraft-creator#731]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37ca30c2-bbe8-119e-3d74-05d344211a06
* Version Independent ID: 59430e36-a29d-ba99-38d3-ba78fc873d1f
* Content: [Introduction to Resource Packs](https://learn.microsoft.com/en-us/minecraft/creator/documents/resourcepack#sample-resource-pack)
* Content Source: [creator/Documents/ResourcePack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ResourcePack.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by Narengalla** [comment]
Hi

**Comment by iconicNurdle** [comment]
Hello! If I can help with something I would be glad to. Just let me know. :)
