### ISSUE TITLE
Petite Question (FR)

### ISSUE THREAD

**Issue by AlexisChat** [MicrosoftDocs/minecraft-creator#735]
Bonjour, J'avais une question, si je vend des monde minecraft dans le Marketplace, puis-je faire les monde en java et les transferer en monde bedrock (avec un mod) et après vous le donner?

#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8293cbae-4896-4d03-9764-09e23027db99
* Version Independent ID: 6ada8e59-a330-e8ca-5967-8c5dc67db846
* Content: [Différences entre Minecraft Bedrock Edition et Minecraft Java Edition](https://learn.microsoft.com/fr-fr/minecraft/creator/documents/differencesbetweenbedrockandjava)
* Content Source: [creator/Documents/DifferencesBetweenBedrockAndJava.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.fr-FR/blob/live/creator/Documents/DifferencesBetweenBedrockAndJava.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JimSeaman42** [comment]
Thank you for your feedback; unfortunately, this channel is specifically for documentation-specific issues. [This](https://help.minecraft.net/hc/en-us) may be a good place to start. Have a great day!
