### ISSUE TITLE
[Script API] import("..."); not run the code

### ISSUE THREAD

**Issue by FaiBah** [MicrosoftDocs/minecraft-creator#738]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JimSeaman42** [comment]
Thank you for your feedback... this channel is for documentation-specific issues, which doesn't seem to be the case for this item. If there are specific issues with documentation, please don't hesitate to reach out. Thanks again!
