### ISSUE TITLE
Description of the block permutations limit is unclear

### ISSUE THREAD

**Issue by QuazChick** [MicrosoftDocs/minecraft-creator#739]
In the "Unlimited* Power" section, the block permutations limit is described:
> A cap of 65,536 permutations that all blocks on a map can generate has been placed due to performance concerns. Attempting to add a resource pack with more permutations than said cap will result in the following warning

- However, it isn't clear what this limit is a measure of:
  - the amount of permutations a custom block can have, or
  - the amount of permutations that can be placed and exist in the world.
- This could also be clarified further by reiterating that the amount of "permutations" is the amount of possible combinations of state values a block can have, not the number of entries in the custom block's `"permutations"` array.
- Resource packs are mentioned but seem irrelevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 569e663b-eab4-840d-00d6-3393bee89d2f
* Version Independent ID: 569e663b-eab4-840d-00d6-3393bee89d2f
* Content: [Block Documentation - Block States and Permutations](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockstatesandpermutations?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockStatesAndPermutations.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockStatesAndPermutations.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! As stated in the the article, the cap is for "all blocks on a map" as opposed to each block on a map. I hope that helps!
