### ISSUE TITLE
Missing property: minecraft:behavior.look_at_player

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#74]
The documentation on the property: `target_distance`

From [axolotl](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/axolotl)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393e1b27-639f-d4bb-1933-d70eaddb7bcc
* Version Independent ID: df23824b-714d-b03a-a33a-21575403484c
* Content: [minecraft:behavior.look_at_player](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_look_at_player)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_look_at_player.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_look_at_player.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This is now [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_look_at_player). Thanks!
