### ISSUE TITLE
Need to reference existing block names

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/minecraft-creator#742]
I came here because I was trying to find the list of names I could use to refer to existing vanilla blocks.  This article should link to such a list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3fecbaa-0e1c-8c66-6b00-4fcdf1ab6d6b
* Version Independent ID: 01fa8839-74ae-bbcd-dd1c-d1bca2615694
* Content: [Block Documentation - minecraft:display_name](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_display_name?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_display_name.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockComponents/minecraftBlock_display_name.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
@sloh-ms I agree! Good suggestion. I added a link to the block names found here:

https://learn.microsoft.com/minecraft/creator/reference/content/addonsreference/examples/addonblocks

Does this work?
