### ISSUE TITLE
Confusing deferred volumetric fog documentation

### ISSUE THREAD

**Issue by Veka0** [MicrosoftDocs/minecraft-creator#743]
The part which describes how luminance is calculated can be difficult to understand for some people as it involves a vector dot product operation:
`Luminance=RGB∙[0.2126, 0.7152, 0.0722]`
Instead, it can be rewritten in simpler way without dot product, which is easier to understand:
`Luminance = 0.2126*R + 0.7152*G + 0.0722*B`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4722db-3980-4b38-a102-53f10132095e
* Version Independent ID: 7d4722db-3980-4b38-a102-53f10132095e
* Content: [Getting Started with Deferred Lighting](https://learn.microsoft.com/en-us/minecraft/creator/documents/deferredlighting?view=minecraft-bedrock-stable#volumetric-fog-and-light-shafts)
* Content Source: [creator/Documents/DeferredLighting.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DeferredLighting.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Thank you for this! The team approved it and now your change is in there.
