### ISSUE TITLE
Format detail in example JSON should be in quotes

### ISSUE THREAD

**Issue by davidxn** [MicrosoftDocs/minecraft-creator#744]
Format version in example JSON should be in quotes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d94e127d-2d4e-d8a7-e621-e04dc4b8ef49
* Version Independent ID: 891d4e54-90cb-34d3-f515-4f583b8ee56e
* Content: [Features Documentation - minecraft:weighted_random_feature](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/featuresreference/examples/features/minecraftweighted_random_feature?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/FeaturesReference/Examples/Features/minecraftWeighted_random_feature.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/FeaturesReference/Examples/Features/minecraftWeighted_random_feature.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Ooh! Good catch. It is fixed and will be apparent after the next document push. 

THANK YOU!
