### ISSUE TITLE
add "condition": "has_variant" to Loot Table Conditions page

### ISSUE THREAD

**Issue by Synthestra** [MicrosoftDocs/minecraft-creator#745]
The loot table conditions page references "has_mark_variant", but not "has_variant".

An Example of "has_variant" can be seen in the frog.json loot table

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebd1d3a0-9e89-209a-6bd4-1266fb9d2ad0
* Version Independent ID: ebd1d3a0-9e89-209a-6bd4-1266fb9d2ad0
* Content: [Loot and Trade Table Conditions](https://learn.microsoft.com/en-us/minecraft/creator/documents/loottableconditions?view=minecraft-bedrock-stable#conditions)
* Content Source: [creator/Documents/LootTableConditions.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/LootTableConditions.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Good catch! I added the entry and you'll be able to see it after the next document update.
