### ISSUE TITLE
Keyframe inconsistencies

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#747]
Commit https://github.com/MicrosoftDocs/minecraft-creator/commit/4416fc35140a7a7df4923b789fd88938f4b8da0d updated the diagram to reference keyframes throughout the day. However, the example codes in the [key-frame-json-syntax](https://learn.microsoft.com/en-us/minecraft/creator/documents/deferredlighting?view=minecraft-bedrock-stable#key-frame-json-syntax) section has a comment where noon is 0.5 which does not align with the diagram. Every instance of the keyframe still shows 0.5 as noon. This is very confusing for us creators to know which reference is the correct one

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4722db-3980-4b38-a102-53f10132095e
* Version Independent ID: 7d4722db-3980-4b38-a102-53f10132095e
* Content: [Getting Started with Deferred Lighting](https://learn.microsoft.com/en-us/minecraft/creator/documents/deferredlighting?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/DeferredLighting.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DeferredLighting.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Good catch! The changes will be apparent soon. Thank you!!
