### ISSUE TITLE
There should be a note the 3d export, exports the entire terrain atlas. This is a copyright concern that needs to be Warned about

### ISSUE THREAD

**Issue by Jbenisek** [MicrosoftDocs/minecraft-creator#752]
Exporting 3d structures includes the entire terrain atlas. This is a massive copyright and security issue and needs to be warned about.

It also only works 60%pf the time. 
Entities are not included should be noted.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad779972-c39a-f5a6-8774-2c8c2690e176
* Version Independent ID: ad779972-c39a-f5a6-8774-2c8c2690e176
* Content: [Introduction to Structure Blocks](https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontostructureblocks?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/IntroductionToStructureBlocks.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/IntroductionToStructureBlocks.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by ihategravel2** [comment]
Isn't this submitted to the entirely wrong place? This is for documentation, not bugs.

**Comment by kakinnun** [comment]
Not a documentation bug.
