### ISSUE TITLE
Falling Block Component

### ISSUE THREAD

**Issue by CreepycreeperMw** [MicrosoftDocs/minecraft-creator#755]
Currently Script API has no way of modifying falling block data.

It would be very useful to be able to read and write things such as the blocks
- destroy time left - (time after the block gets destroyed and drops its item)
and get & set the
- block data / block permutation

as there currently is no way to read or write anything from the falling block.

Setting block properties would allow creators to do some really amazing stuff (such as seen in java) as falling blocks can act like a display for blocks or an rigid body like representive of a block.
This would also be great for parity

**Comment by JimSeaman42** [comment]
Thank you for your feedback. Unfortunately, we are unable to provide support via this channel that isn't related to specific documentation-related issues.
