### ISSUE TITLE
Taming unclear command

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#760]
`on_wake_with_owner` says:

> `minecraft:on_wake_with_owner` requires a `player` to be tagged as the entity's owner, via taming or console command.

What console command can be used here? It would be helpful if this page included this information.

**Comment by JimSeaman42** [comment]
Thanks for your feedback... The '/summon' command allows users to designate an owner. Hope that helps.

**Comment by tryashtar** [comment]
That's new to me. I'm not aware of any parameter in the summon command that can do this. Could you please be more specific and give a working example?

**Comment by tryashtar** [comment]
I think commands like that only work in the Java version of Minecraft
