### ISSUE TITLE
was fireballed by.entity.entity identifier<>.name

### ISSUE THREAD

**Issue by Twizzing05** [MicrosoftDocs/minecraft-creator#761]
[Enter feedback here]
I use  Minecraft Entity Wizard in Blockbench to make this
![2023-12-18 (1)](https://github.com/MicrosoftDocs/minecraft-creator/assets/154111000/e6cf30e4-82f4-42b3-878a-e6589d3085a4)
![2023-12-18 (2)](https://github.com/MicrosoftDocs/minecraft-creator/assets/154111000/987cc768-c594-47cb-823b-99f56f9ae0ef)
![2023-12-18](https://github.com/MicrosoftDocs/minecraft-creator/assets/154111000/b84bbf81-e667-455d-932e-a10ae4ee8f23)
work fine with 'slain'
![2023-12-18 (3)](https://github.com/MicrosoftDocs/minecraft-creator/assets/154111000/6878d91f-ea17-4b2b-9695-ea00f88b59cf)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79c7652f-5c4e-768c-ca52-1ac2ff1790f5
* Version Independent ID: 794cb3ed-7c30-59af-7d62-3f109de1d553
* Content: [Getting Started with Minecraft Entity Wizard](https://learn.microsoft.com/en-gb/minecraft/creator/documents/minecraftentitywizard?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/MinecraftEntityWizard.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/MinecraftEntityWizard.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thanks so much for your feedback, we're sorry to hear that you're having trouble. Unfortunately, this channel is only for documentation-specific issues. You may have success reaching out to the Blockbench Discord channel (there is a link to this on the Blockbench website). 

I hope this helps; best of luck with your entity!
