### ISSUE TITLE
Odd backticks

### ISSUE THREAD

**Issue by seeit360** [MicrosoftDocs/minecraft-creator#762]
there are backticks [ ` ] in the json example. not necessary 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 714edba8-4758-840c-d84d-9ca7a09b7c87
* Version Independent ID: 714edba8-4758-840c-d84d-9ca7a09b7c87
* Content: [Entity Events](https://learn.microsoft.com/en-us/minecraft/creator/documents/entityevents?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/EntityEvents.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EntityEvents.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **v-bbortree**

**Comment by JimSeaman42** [comment]
Thanks so much! The backticks have been removed, and the article will be updated with the next release.
