### ISSUE TITLE
misspelling "sensor"

### ISSUE THREAD

**Issue by seeit360** [MicrosoftDocs/minecraft-creator#763]
"List of blocks that will trigger the **senor**."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a09d8820-84ca-d267-1fc6-5592d9eb51fc
* Version Independent ID: afc98587-78e9-5054-5139-a00faaf372b6
* Content: [Entity Documentation - minecraft:block_sensor](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_block_sensor?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_block_sensor.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_block_sensor.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thanks for your feedback! The spelling error has been addressed, and will be updated with the next release.
