### ISSUE TITLE
Typing error "UtilizingUsing"

### ISSUE THREAD

**Issue by cordeirobrunocezar** [MicrosoftDocs/minecraft-creator#764]
[Enter feedback here]

Typing error in "Fortunately, tags may now be used as recipe input, streamlining the process greatly. **UtilizingUsing** this new functionality in the scenario above, your effort in creating a desk that can be made from planks will now look like this:".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8260c5a6-eb8d-7603-4db7-9e3ffbe81f58
* Version Independent ID: 8260c5a6-eb8d-7603-4db7-9e3ffbe81f58
* Content: [Utilizing Tags as Recipe Input](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/tagsrecipeinput?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/RecipeReference/Examples/TagsRecipeInput.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/RecipeReference/Examples/TagsRecipeInput.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by JimSeaman42** [comment]
Thanks for the feedback! The error has been fixed and the will be reflected in the article with the next release.
