### ISSUE TITLE
How to create an entity similar to minecart?

### ISSUE THREAD

**Issue by jhona200528** [MicrosoftDocs/minecraft-creator#766]
[hello Mojang, i have a question, i am creating an addon of train for Minecraft bedrock and well, i need to know like i make for that the entity is placed about him rail in a correct way and also, i need know like i make for that the entity be not a animal, monster and npc entity, if not that it be a boat, minecart or armor support type entity, that is to say that has no life and that the moment it hit it break and it releases the item.

excuse me for i write so, i write and i understand a little English. i hope they understand me.]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ded1495c-5233-8717-83d5-5e3092513c5e
* Version Independent ID: dcbe991c-bf73-690c-a9c2-988e1170e224
* Content: [Introducción a Agregar entidad](https://learn.microsoft.com/es-mx/minecraft/creator/documents/introductiontoaddentity)
* Content Source: [creator/Documents/IntroductionToAddEntity.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.es-MX/blob/live/creator/Documents/IntroductionToAddEntity.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by JimSeaman42** [comment]
Thank you for your feedback. While we wish we could help you with your issue, this channel is for documentation-specific issues. Personally, I would recommend checking out the official Minecraft discord channel to see if anyone can help with your issue. Thanks again!
