### ISSUE TITLE
Conflicting types

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#767]
## Issue
The [parameters](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_shooter?view=minecraft-bedrock-stable#parameters) section states `max_draw_duration` is a json object, but the default value is a float of 0.0. In the example section as well, it shows `max_draw_duration` is a value of `1.0`.

## Proposed Solution
Update the [parameters](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_shooter?view=minecraft-bedrock-stable#parameters) section to change the `max_draw_duration` type to `float` or provide an example of `max_draw_duration` using a json object

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d69d710e-7d85-f601-ef16-c802d57013b8
* Version Independent ID: 23d79a6b-e4c7-749a-9f58-04411aafe805
* Content: [Item Documentation - minecraft:shooter](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_shooter?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_shooter.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_shooter.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Great catch - thank you! The change will be visible after the next document release.  :)
