### ISSUE TITLE
Bedrock nether world to java nether world

### ISSUE THREAD

**Issue by derjoei99** [MicrosoftDocs/minecraft-creator#773]
Hi
I was wondering if you can transfer tghe nether world as well when converting a bedrockworld to java

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2e4afd0-2e7e-d74b-1fb4-08c367a79217
* Version Independent ID: 6a04d5ff-9139-0ba9-6409-4a2368543bad
* Content: [Chunker - How to Clear The Nether](https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkerthenether?view=minecraft-bedrock-stable#back-up-your-world)
* Content Source: [creator/Documents/ChunkerTheNether.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerTheNether.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by FormallyMyles** [comment]
Hi!

The nether world should convert when using Chunker to convert from Bedrock to Java, let us know if you have any problems with doing this :)

**Comment by JimSeaman42** [comment]
As Myles answered this question, I'm going to mark the issue as closed. Thanks!
