### ISSUE TITLE
minecraft:digger documentation is missing

### ISSUE THREAD

**Issue by Kaioga5** [MicrosoftDocs/minecraft-creator#776]
The documentation for minecraft:digger is completely inaccessible, returning a 404 error (check https://learn.microsoft.com/en-us/minecraft/creator/Reference/Content/ItemReference/Examples/ItemComponentList.md?view=minecraft-bedrock-stable).

This component is currently being used on every tool file of the game, but as mentioned above there is no documentation.

**Comment by JimSeaman42** [comment]
Thank you so much for the feedback! There was an error, and the page will be accessible with the next release.
