### ISSUE TITLE
Need Example

### ISSUE THREAD

**Issue by causal-guide** [MicrosoftDocs/minecraft-creator#777]
Need Example

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd7f963-cfae-5bc0-c652-811bc915347f
* Version Independent ID: 5fd7f963-cfae-5bc0-c652-811bc915347f
* Content: [Item Documentation - minecraft:interact_button](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_interact_button?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_interact_button.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_interact_button.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by tutacat** [comment]
Hi. I am not affiliated with Mojang or Microsoft. I think you need to use a tutorial for behavior packs and look at the items in the vanilla behaviour pack that use it (https://www.minecraft.net/creator/ download the example vanilla behavior pack). This part of the documentation is a reference for listing the methods, etc. it is basically an API explorer, which explains what each property does.

**Comment by iconicNurdle** [comment]
@causal-guide Did the answer from @tutacat help?

**Comment by iconicNurdle** [comment]
I'm going to go ahead and close this. Please feel free to open it back up if you have further questions on this topic. Thanks!
