### ISSUE TITLE
[CHUNKER] I'm looking forward to converting entities and inventory.

### ISSUE THREAD

**Issue by Alexander-alt-creator** [MicrosoftDocs/minecraft-creator#779]
I converted my world from Java to Bedrock, at first it didn’t work out for me, because... the world weighed more than 1GB, but by removing unnecessary chunks I reduced the size and did the conversion. However, all my residents with the trade items I needed were gone, as well as all other entities. I look forward to further development of Chuker,
and the possibility of transferring worlds between the computer version of java to the bedrock version on both PCs and phones (I know this is already possible through iTunes and Explorer).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @neonerz
![2024-01-14_16 36 35](https://github.com/MicrosoftDocs/minecraft-creator/assets/77934731/43471e22-7220-4798-9bb9-11be8c65be37)

![2024-01-14_16 31 35](https://github.com/MicrosoftDocs/minecraft-creator/assets/77934731/50965f4f-a355-4c1a-ac63-5771120eae67)

* Microsoft Alias: **mikeam**

**Comment by FormallyMyles** [comment]
Thank you for your feedback, I'll pass it on to our team :)
