### ISSUE TITLE
All directions followed but resource pack not appearing as an option to enable 

### ISSUE THREAD

**Issue by HiLowJack777** [MicrosoftDocs/minecraft-creator#782]
**Describe the bug**
After the My_RESOURCE_Pack was included in the development_resource_packs folder, My_RESOURCE_Pack is not appearing as an option to enable. I am doing this on an Xbox One.

**To Reproduce**
1. Copy My_RESOURCE_Pack into development_resource_packs and resource_packs folders on Xbox one
2. Launch Minecraft bedrock edition 1.20.51
3. Create a new world
4. See that My_RESOURCE_Pack is not listed as an option

**Expected behavior**
The pack should appear as available to be enabled. 

**Additional context**
I think this is occurring because the tutorial is out of date or it was not intended for use on Xbox One. I have seen people using .mcpack files instead of this file system with a manifest.json file included. I am new to this please help.

**Comment by kakinnun** [comment]
Unfortunately, it is not possible to perform these steps on an Xbox.

**Comment by HiLowJack777** [comment]
Are you aware of what makes it different?

**Comment by kakinnun** [comment]
Xbox is a secure platform that does not allow the manual editing/moving of files into and out of a game file directory. This is the same for PlayStation and Switch.
