### ISSUE TITLE
minecraft:anger_level has incorrect heading name using "minecraft:angry"

### ISSUE THREAD

**Issue by CrowdingFaun624** [MicrosoftDocs/minecraft-creator#784]
The heading "Vanilla entities using minecraft:angry" is incorrect, as this page is about "minecraft:anger_level".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22b035f0-de4b-0cb1-a27a-2fb2d8209447
* Version Independent ID: 22b035f0-de4b-0cb1-a27a-2fb2d8209447
* Content: [Entity Documentation - minecraft:anger_level](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_anger_level?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_anger_level.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_anger_level.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Very good catch - thank you! :)
