### ISSUE TITLE
vanilla example on Entity Documentation - minecraft:barter uses behavior instead of component

### ISSUE THREAD

**Issue by CrowdingFaun624** [MicrosoftDocs/minecraft-creator#786]
On Entity Documentation - minecraft:barter, the vanilla example given shows "minecraft:behavior.barter" instead of "minecraft:barter"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7c8f1e-36fd-f3b4-e3cb-23862e75fa2c
* Version Independent ID: a549c6a3-2dc8-1268-9932-ff91b4bd744e
* Content: [Entity Documentation - minecraft:barter](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_barter?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_barter.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_barter.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Great catch! Updated document will be visible after he next release. Thank you!
