### ISSUE TITLE
Entity Documentation - minecraft:home uses example from minecraft:behavior.go_home

### ISSUE THREAD

**Issue by CrowdingFaun624** [MicrosoftDocs/minecraft-creator#788]
The vanilla entities example on the minecraft:home entity documentation page shows "minecraft:behavior.go_home" instead of "minecraft:home".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23b1be57-4a47-85cf-e01b-ccd22beef6b2
* Version Independent ID: 8eb88da6-d2da-cc10-b448-03a241203559
* Content: [Entity Documentation - minecraft:home](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_home?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_home.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_home.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Good catch! Thank you so much :) - The fix will be visible after the next release.
