### ISSUE TITLE
typo in minecraft:hurt_on_condition damage_conditions table

### ISSUE THREAD

**Issue by CrowdingFaun624** [MicrosoftDocs/minecraft-creator#789]
The entity documentation minecraft:hurt_on_condition's damage_conditions table lists "damange_per_tick", which should be "damage_per_tick".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e20e419-7f97-2b27-cef1-43f8f9523602
* Version Independent ID: 03d4e4cd-ee20-770a-ba69-c7ce82ddb178
* Content: [Entity Documentation - minecraft:hurt_on_condition](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_hurt_on_condition?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_hurt_on_condition.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_hurt_on_condition.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Eek! Good catch! TYSM! :) The fix will be there after the next document release.
