### ISSUE TITLE
Properties unsorted: minecraft:behavior.play_dead

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#79]
It seems during auto conversion the properties didn't get sorted.

For documentation that would be the best.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9048cf-f9ee-5aa4-afa2-6bcb4ed37f4d
* Version Independent ID: 1bc1ee29-2911-ae0b-f00d-9053778bf746
* Content: [minecraft:behavior.play_dead](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_play_dead)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_play_dead.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_play_dead.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
This is [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_play_dead). Thanks!
