### ISSUE TITLE
Incorrect identifier in wrench texture data example

### ISSUE THREAD

**Issue by sereilly** [MicrosoftDocs/minecraft-creator#790]
```json
{
  "resource_pack_name": "Wrench Resource Pack",
  "texture_data": {
    "demo:goo": {
      "textures": "textures/items/wrench_ico"
    }
  }
}
```

Identifier should be demo:wrench, not demo:goo
The crown sample also has an incorrect identifier and texture path

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c809f82-b787-8972-d749-38b426999f59
* Version Independent ID: 7c809f82-b787-8972-d749-38b426999f59
* Content: [How to Add Custom Items](https://learn.microsoft.com/en-us/minecraft/creator/documents/addcustomitems?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/AddCustomItems.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/AddCustomItems.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Good catch! That was entirely me. I fixed the same issue in 'crown' too. Thank you!!!  :)
