### ISSUE TITLE
I'm pretty sure that block states go by a different name now.

### ISSUE THREAD

**Issue by asterrick** [MicrosoftDocs/minecraft-creator#791]
Title.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 569e663b-eab4-840d-00d6-3393bee89d2f
* Version Independent ID: 569e663b-eab4-840d-00d6-3393bee89d2f
* Content: [Block Documentation - Block States and Permutations](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockstatesandpermutations?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockStatesAndPermutations.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockStatesAndPermutations.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Thank you for bringing this to our attention. I will verify whether any changes should be made. Closing this issue for now.
