### ISSUE TITLE
Explain what "data" and "count" params mean

### ISSUE THREAD

**Issue by NetLightDev** [MicrosoftDocs/minecraft-creator#794]
Please add an explanation what "**data**" and "**count**" params mean
in the "Furnace Recipe Example" :
```
"input": {
    "item": "minecraft:beef",
    "data": 0,
    "count": 4
},
```
OR: provide a link to any docs explaining that

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f02b6b4-b9d3-9b27-ee37-bcbd91c88bce
* Version Independent ID: 5b9ffdd1-5cf0-48e2-897e-2f1340df96b2
* Content: [Recipe Documentation - Furnace Recipe](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/recipedefinitions/minecraftrecipe_furnace?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_Furnace.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_Furnace.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Done! 

This change will be visible after the next document release. 

`|input| item names| Items used as input for the furnace recipe. `data` is used to specify the data value of a block or item to an exact id, if the item has variations. `count` is the quantity of the item being input. |`
