### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#795]
The parameters have `slot` and `protection`. However, the example has the `dispensable` key. Testing this example in 1.20.60, the game throws a content log error saying this key is not present in the schema.

## Proposal
Update the example to include the `protection` key and remove the `dispensable` key.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0abbbbcc-bb5c-40b2-1c8d-8c2388264f19
* Version Independent ID: 1c5460fa-215f-ff13-4b7d-1d9a44f1d342
* Content: [Item Documentation - minecraft:projectile](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_projectile?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_projectile.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_projectile.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by SIsilicon** [comment]
This should be re-opened because the page still references `dispensable`.
![image](https://github.com/user-attachments/assets/972d1d7a-bef2-4014-a51c-b45e380a370f)
