### ISSUE TITLE
Missing property: minecraft:behavior.raid_garden

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#80]
Missing documentation on the property: `search_height`

From the [fox](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/fox)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db603a51-0793-cce6-2617-b2bba5718747
* Version Independent ID: e00e43b3-2bb9-9e77-e064-0e4fa3b1b567
* Content: [minecraft:behavior.raid_garden](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_raid_garden)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_raid_garden.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_raid_garden.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This is [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_raid_garden). Thanks!
