### ISSUE TITLE
pengdol

### ISSUE THREAD

**Issue by pengdol0301** [MicrosoftDocs/minecraft-creator#800]
[여기에 피드백 입력]

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. learn.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a8a88ce5-d418-c1bf-0edc-cc1836d68ee4
* Version Independent ID: 50d65cea-41e6-8478-048b-cf192b12503a
* Content: [Minecraft: Bedrock Edition에서 애드온 설치](https://learn.microsoft.com/ko-kr/minecraft/creator/documents/addonpackinstallation?tabs=android)
* Content Source: [creator/Documents/AddonPackInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.ko-KR/blob/live/creator/Documents/AddonPackInstallation.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by pengdol0301** [comment]
?

**Comment by mammerla** [comment]
Unfortunately, I don't believe there is a specific described issue here.

**Comment by iconicNurdle** [comment]
Closing this issue. I will be glad to help if you can send more information about the problem.
