### ISSUE TITLE
Missing property: minecraft:behavior.ram_attack

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#81]
Missing documentation on the property: `on_start`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd45b8d1-fc22-78db-5066-d030d780977a
* Version Independent ID: 1fcc99bd-dbc6-6afb-e43a-dc52dc621f12
* Content: [minecraft:behavior.ram_attack](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_ram_attack)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_ram_attack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_ram_attack.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by docsbryce** [comment]
This is [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_ram_attack). Thanks!
