### ISSUE TITLE
Repeated parameter

### ISSUE THREAD

**Issue by Kaioga5** [MicrosoftDocs/minecraft-creator#810]
`attack_duration` parameter is repeated in the example provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc90bb5f-6c4d-d2fd-1461-d3952a3dd32f
* Version Independent ID: dc90bb5f-6c4d-d2fd-1461-d3952a3dd32f
* Content: [Entity Documentation - minecraft:behavior.delayed_attack](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_delayed_attack?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_delayed_attack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_delayed_attack.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Great catch! Thank you so much. :)
