### ISSUE TITLE
Update command syntax

### ISSUE THREAD

**Issue by lunarwolf2008** [MicrosoftDocs/minecraft-creator#811]
This page uses outdated aux value syntax and should be updated with block states

![image](https://github.com/MicrosoftDocs/minecraft-creator/assets/141184225/80df372e-7e0f-48f0-8f23-010567710c4e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf7660a7-e7f1-f1e8-6cbf-2c5ae54c00e0
* Version Independent ID: cf7660a7-e7f1-f1e8-6cbf-2c5ae54c00e0
* Content: [Create an In-World Game with Commands](https://learn.microsoft.com/en-us/minecraft/creator/documents/createaninworldgame?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/CreateAnInWorldGame.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CreateAnInWorldGame.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Great catch! Thank you so much! I have made the update and it will be visible after the next document release.
