### ISSUE TITLE
Typo in Manifest.json

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#814]
In the [modules](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest?view=minecraft-bedrock-stable#modules) section, there is a typo, `lanugage`. The correct spelling is `language`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 156a5c71-e42d-7075-74ef-03230369797b
* Version Independent ID: e0fbfe84-ce3a-9a97-6b45-009ad16ae4a9
* Content: [Addons Documentation - manifest.json](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/AddonsReference/Examples/AddonManifest.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/AddonsReference/Examples/AddonManifest.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Thank you for catching this! I verified that it appears to be gone. If this is not the case please let me know. Thanks!
