### ISSUE TITLE
what does this means?

### ISSUE THREAD

**Issue by MasaharuShou** [MicrosoftDocs/minecraft-creator#816]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f283b3a-351e-6c23-0d6c-a0e9ad4779d1
* Version Independent ID: 9f283b3a-351e-6c23-0d6c-a0e9ad4779d1
* Content: [Data Driven Overworld Height and Void Generation](https://learn.microsoft.com/en-us/minecraft/creator/documents/datadrivenoverworldheight?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/DataDrivenOverworldHeight.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DataDrivenOverworldHeight.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **v-jillheaden**

**Comment by iconicNurdle** [comment]
Hi @MasaharuShou - can you give me a bit more detail about your question?

**Comment by iconicNurdle** [comment]
I'm going to close this issue. Please feel free to re-open it and provide more information and I will be glad to help.
