### ISSUE TITLE
the the

### ISSUE THREAD

**Issue by causal-guide** [MicrosoftDocs/minecraft-creator#820]
[the the]

---
![Uploading Screenshot_2024-04-06-09-50-10-779_com.android.chrome.jpg…]()

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2614b2e-66ad-5713-7643-11cad0a0f7ef
* Version Independent ID: b2614b2e-66ad-5713-7643-11cad0a0f7ef
* Content: [Scripting with Dedicated Servers](https://learn.microsoft.com/en-us/minecraft/creator/documents/scriptingservers?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/ScriptingServers.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ScriptingServers.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @MikeAM
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
I am unable to open the screenshot. 
Could you tell me more about the problem?

**Comment by ThomasOrs** [comment]
@iconicNurdle here is a fresh screenshot 
![image](https://github.com/MicrosoftDocs/minecraft-creator/assets/84604286/d7b28f4f-b754-4953-bb2d-141a0f7197d8)
It looks like `the` is part of the sentence and the links text so it appears twice :)

**Comment by iconicNurdle** [comment]
I found several more and they will be resolved after the next document push. Thank you so much!
