### ISSUE TITLE
Description of languages.json is missing

### ISSUE THREAD

**Issue by ChrisEt** [MicrosoftDocs/minecraft-creator#821]
This guide describes every step in detail, except for the `languages.json` file.

This sections seems to have been dropped accidentally in the English version, as it's still present in the German version: https://learn.microsoft.com/de-de/minecraft/creator/documents/packagingaskinpack#languagesjson

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Packaging a Skin Pack](https://learn.microsoft.com/en-us/minecraft/creator/documents/packagingaskinpack?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingASkinPack.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Hi! You are correct! I moved that section to a new article I wrote about "all" of the things that can go into an add-on pack. 

I put a link to that section at the bottom of the Skin Pack document.

Thank you for catching that!

[Comprehensive Pack Add-on Pack Contents](https://learn.microsoft.com/minecraft/creator/documents/comprehensivepackcontents
)
