### ISSUE TITLE
This doesn't seem valid. Please verify.

### ISSUE THREAD

**Issue by Jbenisek** [MicrosoftDocs/minecraft-creator#822]
Both these example don't seem valid

MSDocs Def for this field:
Range | [10, 10] | Vector [a, b] | The maximum horizontal and vertical distance another entity can be from this and have the filters checked against it.

Example 2
"minecraft:entity_sensor": {
          "sensor_range": 2.5,
          "relative_range": false,
          "minimum_count": 1,
          "event_filters": {
            "any_of": [
              { "test": "is_family", "subject": "other", "value": "mob" },
              { "all_of": [
                { "test": "is_family", "subject": "other", "value": "player" },
                { "none_of": 
                  { "test": "has_ability", "subject": "other", "value": "instabuild" } 
                }
              ]}
            ]
          },
          "event": "minecraft:start_half_puff"
        }
        
Example 1        
        "minecraft:entity_sensor":{
    "maximum_count": -1,
    "minimum_count": 1,
    "cooldown": -1,
    "require_all": false,
    "range": 10,
    "event_filters": {"test": "has_trade_supply"},
    "event": "minecraft:offer_trade"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8aafbf9-cedb-0ec1-2792-8f2558449413
* Version Independent ID: fe4c7e0b-037a-fcfb-e496-46569dd69bff
* Content: [Entity Documentation - minecraft:entity_sensor](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_entity_sensor?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_entity_sensor.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_entity_sensor.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
@Jbenisek You're right - I got a new set of examples and popped them in there. The changes should be visible after the next document push. Thanks! I'm closing this issue, but feel free to re-open and we can keep talking. Thanks!
