### ISSUE TITLE
Examples are outdated

### ISSUE THREAD

**Issue by Kaioga5** [MicrosoftDocs/minecraft-creator#823]
The examples given do not follow the new syntax, to update them:
First example:
```
"minecraft:entity_sensor": {
    "subsensors": [
        {
            "range": [10, 10],
            "cooldown": -1,
            "require_all": false,
            "event_filters": {
                "test": "has_trade_supply"
            },
            "event": "minecraft:offer_trade"
        }
    ]
}
```
Second example:
```
"minecraft:entity_sensor": {
    "subsensors": [
        {
            "range": 2.5,
            "relative_range": false,
            "minimum_count": 1,
            "event_filters": {
                "any_of": [
                    {
                        "test": "is_family",
                        "subject": "other",
                        "value": "mob"
                    },
                    {
                        "all_of": [
                            {
                                "test": "is_family",
                                "subject": "other",
                                "value": "player"
                            },
                            {
                                "none_of": {
                                    "test": "has_ability",
                                    "subject": "other",
                                    "value": "instabuild"
                                }
                            }
                        ]
                    }
                ]
            },
            "event": "minecraft:start_half_puff"
        }
    ]
}
```
These are the updated examples, following the new syntax. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8aafbf9-cedb-0ec1-2792-8f2558449413
* Version Independent ID: fe4c7e0b-037a-fcfb-e496-46569dd69bff
* Content: [Entity Documentation - minecraft:entity_sensor](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_entity_sensor?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_entity_sensor.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_entity_sensor.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Thank you so much! examples are updated and will be published next week.
