### ISSUE TITLE
Opportunity for more clarity around the differences 

### ISSUE THREAD

**Issue by cqueern** [MicrosoftDocs/minecraft-creator#826]
This paragraph is confusing:

> There are also differences per version in the way that redstone works, and while the majority of redstone circuits work well between versions, more complex circuits may not. This is because Bedrock doesn't support quasi-connectivity, while Java does. Systems that utilize mechanics such as Block Update Detector (BUD) switches won't work. Pistons require one tick to retract and won't leave blocks behind if given a one-tick pulse.

In the following paragraph you can see my suggested edits as they're in bold. I don't know if it should read "in Bedrock" or "in Java", but I'm hoping one of those two options can be added in the places bolded below.

> There are also differences per version in the way that redstone works, and while the majority of redstone circuits work well between versions, more complex circuits may not work well **in Bedrock**. This is because Bedrock doesn't support quasi-connectivity, while Java does. Systems that utilize mechanics such as Block Update Detector (BUD) switches won't work **in Bedrock**. Pistons require one tick to retract and won't leave blocks behind if given a one-tick pulse **in Bedrock**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8293cbae-4896-4d03-9764-09e23027db99
* Version Independent ID: 6ada8e59-a330-e8ca-5967-8c5dc67db846
* Content: [Differences between Minecraft Bedrock Edition and Minecraft Java Edition](https://learn.microsoft.com/en-us/minecraft/creator/documents/differencesbetweenbedrockandjava?view=minecraft-bedrock-stable#:~:text=Java%20can%20create%20custom%20fonts,and%20fogs%2C%20while%20Java%20cannot.)
* Content Source: [creator/Documents/DifferencesBetweenBedrockAndJava.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/DifferencesBetweenBedrockAndJava.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
I like your edits. I changed 'won't work well' to ' won't work the same way' - The new wording should be visible by the end of this week. Thank you so much!
