### ISSUE TITLE
Hyperlink is broken in the What's new in 1.20.80

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#829]
The hyperlink near the bottom of the page seems to be formatted incorrectly. It leads to an unknown website rather than the official minecraft site
![image](https://github.com/MicrosoftDocs/minecraft-creator/assets/84206875/d94cfca5-4996-4758-9e78-da9d37b20c15)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4c7c9de-8b1c-2791-15e7-505472028db9
* Version Independent ID: e4c7c9de-8b1c-2791-15e7-505472028db9
* Content: [1.20.80 Update Notes](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.20.80?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/Update1.20.80.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/Update1.20.80.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @kakinnun
* Microsoft Alias: **kakinnun**

**Comment by iconicNurdle** [comment]
Great catch! Thank you. Fix will be out there soon. 😸
