### ISSUE TITLE
Missing properties: minecraft:behavior.admire_item

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#83]
Missing documentation on properties:

- [ ] on_admire_item_start
- [ ] on_admire_item_stop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a24bf14b-792c-58b9-26d6-c1ca41fd860b
* Version Independent ID: 89f53f0f-54a7-21ab-8c99-cbae1fae87a4
* Content: [minecraft:behavior.admire_item](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_admire_item)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_admire_item.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_admire_item.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This is [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_admire_item). Thanks!
