### ISSUE TITLE
Minecraft Bedrock Edition 1.20.50 Update

### ISSUE THREAD

**Issue by hamza1123740** [MicrosoftDocs/minecraft-creator#834]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7488fe4f-d6ac-a815-d1eb-262d09ebcbcc
* Version Independent ID: 7488fe4f-d6ac-a815-d1eb-262d09ebcbcc
* Content: [1.20.50 Update Notes](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.20.50?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/Update1.20.50.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/Update1.20.50.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @kakinnun
* Microsoft Alias: **kakinnun**

**Comment by iconicNurdle** [comment]
Hi! Can you tell me more about the problem?

**Comment by iconicNurdle** [comment]
Closing this for now - please feel free to write back with any further info. Thanks!
