### ISSUE TITLE
minecraft:on_use has been deprecated

### ISSUE THREAD

**Issue by jjkubik** [MicrosoftDocs/minecraft-creator#836]
The table at the end lists (at least one) deprecated component.

[Item][error]-minecraft:on_use has been deprecated and is not available in json format 1.20.50

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0a2c7a9-3387-2fb3-63b5-dd2819d323e4
* Version Independent ID: f0a2c7a9-3387-2fb3-63b5-dd2819d323e4
* Content: [Introducing Custom Components](https://learn.microsoft.com/en-us/minecraft/creator/documents/customcomponents?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/CustomComponents.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/CustomComponents.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Hi! It looks like this got resolved at some point. I'm going to close this issue. If that's not yet, feel free to reopen this issue or make a new one. Thanks!
