### ISSUE TITLE
kateryna 

### ISSUE THREAD

**Issue by LOND91** [MicrosoftDocs/minecraft-creator#851]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8365e46c-0e94-a585-e2f0-58d828db77e0
* Version Independent ID: 8365e46c-0e94-a585-e2f0-58d828db77e0
* Content: [1.19.60 Update Notes](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.19.60?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/Update1.19.60.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/Update1.19.60.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @kakinnun
* Microsoft Alias: **kakinnun**

**Comment by iconicNurdle** [comment]
Hi @LOND91  - Can I get a bit more information about the issue?

**Comment by v-jeffkim** [comment]
Thanks for reaching out to us! We're going to close this issue, for now, but if you have any additional feedback, feel free to comment here and we can reopen it, if needed.
