### ISSUE TITLE
DENIS

### ISSUE THREAD

**Issue by LOND91** [MicrosoftDocs/minecraft-creator#852]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4c7c9de-8b1c-2791-15e7-505472028db9
* Version Independent ID: e4c7c9de-8b1c-2791-15e7-505472028db9
* Content: [1.20.80 Update Notes](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.20.80?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/Update1.20.80.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/Update1.20.80.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @kakinnun
* Microsoft Alias: **kakinnun**
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/minecraft-creator/issues/851
```

**Comment by iconicNurdle** [comment]
Hi @LOND91 - Can I get more information about the issue?
