### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ModMaker101** [MicrosoftDocs/minecraft-creator#853]
**Describe the bug**

**To Reproduce**
1. Go to 'Resource pack manifest'

**Expected behavior**
not to be a comma after min_engine_version

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser edge

**Comment by iconicNurdle** [comment]
Hi @ModMaker101 - could you tell me which Resource pack manifest you mean? I will be glad to go fix it.

**Comment by mammerla** [comment]
Fixed this in AddonManifest
