### ISSUE TITLE
C doesn't have null coalescing operator

### ISSUE THREAD

**Issue by FoxieFlakey** [MicrosoftDocs/minecraft-creator#854]
In "Null Coalescing Operator ??" section
> Similar to how the null-coalescing operator works in C

From what I have searched, C doesn't have that operator but C# have. Base on that I believe its a mistake to write it as C instead C# ^w^

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b502d2e-471f-d263-1635-f32aaa375fce
* Version Independent ID: 0ce04ad7-8cbb-4a96-8778-6d995ee94903
* Content: [Molang Documentation - Introduction to Molang](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/molangintroduction?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/MolangReference/Examples/MolangConcepts/MolangIntroduction.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/MolangReference/Examples/MolangConcepts/MolangIntroduction.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by mammerla** [comment]
Added

**Comment by FoxieFlakey** [comment]
> Added

Thank you very much
