### ISSUE TITLE
Get cool skins

### ISSUE THREAD

**Issue by Lol7575** [MicrosoftDocs/minecraft-creator#857]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Packaging a Skin Pack](https://learn.microsoft.com/en-us/minecraft/creator/documents/packagingaskinpack?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/PackagingASkinPack.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Hi! I don't see a question, so I am going to close this. If there is anything we can do to help, please feel free to let us know in another issue to reopen this one, okay? Thanks!
