### ISSUE TITLE
Missing % in localappdata path in ScriptDeveloperTools.md

### ISSUE THREAD

**Issue by ThomasOrs** [MicrosoftDocs/minecraft-creator#858]
Step 3 in `Get insight into your code with Minecraft script debugging` has a path to the development_behaviour_packs which is missing the leading `%` in `%localappdata%`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd2a345-6330-8634-ab6c-3a2f21964d1e
* Version Independent ID: 2aae94eb-162c-433e-9ad5-5236af9bee82
* Content: [Use Visual Studio Code tools to write script](https://learn.microsoft.com/en-us/minecraft/creator/documents/scriptdevelopertools?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/ScriptDeveloperTools.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ScriptDeveloperTools.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @MikeAM
* Microsoft Alias: **mikeam**

**Comment by mammerla** [comment]
Added

**Comment by iconicNurdle** [comment]
Closing this issue. If there is still a problem please let us know!
