### ISSUE TITLE
wrong formatting on new post

### ISSUE THREAD

**Issue by DavideVailati** [MicrosoftDocs/minecraft-creator#860]
![image](https://github.com/MicrosoftDocs/minecraft-creator/assets/70967385/707e8e93-2284-4e64-93da-2a9525a8db7e)
wrong formatting, needs another ** at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b27155a7-4a2b-a22a-533e-7dafd53710b5
* Version Independent ID: b27155a7-4a2b-a22a-533e-7dafd53710b5
* Content: [1.21 Update Notes](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.21?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/Update1.21.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/Update1.21.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @kakinnun
* Microsoft Alias: **kakinnun**

**Comment by mammerla** [comment]
Added

**Comment by DavideVailati** [comment]
thanks
