### ISSUE TITLE
[@minecraft/server-net] Add support for PATCH requests

### ISSUE THREAD

**Issue by ProtocolPav** [MicrosoftDocs/minecraft-creator#862]
**Is your feature request related to a problem? Please describe.**
As of now, the server-net module supports GET, POST, PUT, HEAD and DELETE. But for some reason not PATCH.

**Describe the solution you'd like**
Add an option to send PATCH requests

**Describe alternatives you've considered**
If you have access to any API's, you can change any PATCH requests to be instead PUT requests, but this is not so simple if the API has been around for a while, or if you don't own the API.

**Comment by mammerla** [comment]
Thanks for the feedback! Opened up an internal request for tracking.
