### ISSUE TITLE
Which slime chunks are true slime chunks?

### ISSUE THREAD

**Issue by drake-dot-o** [MicrosoftDocs/minecraft-creator#864]
Hello, we recently used Chunker to convert a world from Bedrock -> Java edition. I simply wanted to inquire about the "slime chunks" inside of the world. Do the slime chunks stay the same on the world *before* it was converted, do they become slime chunks on the version *after* it was converted, or do already generated chunks retain "slime chunks" from the old version before the conversion?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fb27f-0ce1-9541-e617-7fe8148f8297
* Version Independent ID: 6777fa19-93ad-1984-5fd8-a9adc3dc3a3a
* Content: [Chunker - Overview](https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/ChunkerOverview.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ChunkerOverview.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by FormallyMyles** [comment]
Hi! Slime chunks are based on the seed and not saved to the world, so it would use slime chunks specific to Java edition, which I believe will be different to Bedrock.

Hopefully this helps :)

**Comment by iconicNurdle** [comment]
I can confirm that there are no slime chunks in Bedrock. Thanks, @FormallyMyles !
