### ISSUE TITLE
Incorrect Example for surface_relative_threshold_feature

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#866]
The schema states that the key is `feature_to_place`, but in the example it uses `feature_to_snap`. When testing the example in Minecraft, the game throws a content log: `"feature_to_snap" not valid here`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df64d1de-0482-1187-faef-d653289a3e39
* Version Independent ID: df64d1de-0482-1187-faef-d653289a3e39
* Content: [Features Documentation - minecraft:surface_relative_threshold_feature](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/featuresreference/examples/features/minecraftsurface_relative_threshold_feature?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/FeaturesReference/Examples/Features/minecraftSurface_Relative_threshold_feature.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/FeaturesReference/Examples/Features/minecraftSurface_Relative_threshold_feature.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Fixed! Thank you. :)
