### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by Perdimaulana** [MicrosoftDocs/minecraft-creator#872]
![Uploading Screenshot_2024-07-06-17-51-09-63.jpg…]()
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iconicNurdle** [comment]
Hi @Perdimaulana - looks like this was opened in error. Please feel free to re-open with more information or create a new ticket and I will be glad to take a look. Cheers!
