### ISSUE TITLE
B

### ISSUE THREAD

**Issue by zhiwar404M** [MicrosoftDocs/minecraft-creator#874]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ded1495c-5233-8717-83d5-5e3092513c5e
* Version Independent ID: dcbe991c-bf73-690c-a9c2-988e1170e224
* Content: [Creating New Entity Types](https://learn.microsoft.com/en-gb/minecraft/creator/documents/introductiontoaddentity?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/IntroductionToAddEntity.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/IntroductionToAddEntity.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @neonerz
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Hi! Looks like this was opened in error. I am closing this issue - if there is something I can do to help, please feel free to open another issue. Thanks!
