### ISSUE TITLE
Missing property: minecraft:behavior.leap_at_target

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#88]
Missing documentation on: `target_dist`

From the [cat](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/cat)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9535ddcc-eabc-c90d-1929-1de10f72096f
* Version Independent ID: 199b22a2-4e69-d1ff-085e-d65d7759a488
* Content: [minecraft:behavior.leap_at_target](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_leap_at_target)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_leap_at_target.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_leap_at_target.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This is [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_leap_at_target). Thanks!
