### ISSUE TITLE
Bears

### ISSUE THREAD

**Issue by Naniviin** [MicrosoftDocs/minecraft-creator#880]
![bear-22710995 (1)](https://github.com/user-attachments/assets/2fd183af-98d8-4d74-99fa-31cacbdb0635)
[](url)
![bear-22710995 (1)](https://github.com/user-attachments/assets/a99df62f-d894-428f-9590-9986f8200d29)

**Comment by iconicNurdle** [comment]
Those are so cool! If there is anything I can do to help you with anything, please let us know. Thanks for sharing your bears!
