### ISSUE TITLE
pixel craft

### ISSUE THREAD

**Issue by Didi266-glich** [MicrosoftDocs/minecraft-creator#886]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63ee92b3-df1e-3f02-7b62-e13798b131a8
* Version Independent ID: 7d9f0488-2919-4cca-20ee-097af4e47a05
* Content: [Getting Started With Minecraft Add-Ons](https://learn.microsoft.com/en-us/minecraft/creator/documents/gettingstarted?view=minecraft-bedrock-stable&tabs=Windows10)
* Content Source: [creator/Documents/GettingStarted.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/GettingStarted.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Hi! Do you have a particular question or issue I can help you with here?

**Comment by iconicNurdle** [comment]
Okay. I'm closing this issue. If you have a question, feel free to open a new issue.
