### ISSUE TITLE
Wrong biome tag for Frozen Peaks (typo)

### ISSUE THREAD

**Issue by ForestOfLight** [MicrosoftDocs/minecraft-creator#891]
**Describe the bug**
In the biome filter docs: creator/Reference/Content/EntityReference/Examples/Definitions/NestedTables/biome_filter.md
The Tagged Biomes table shows that Frozen Peaks has the "mountain" tag. Instead, it has the "mountains" tag.

**Expected behavior**
Replace the typo.

**Comment by ForestOfLight** [comment]
The same typo exists for Snowy Slopes. The docs read "mountain", but the actual biome tag is "mountains".

**Comment by iconicNurdle** [comment]
I see it was already fixed for those two, but it needed to be fixed for Cherry Grove, Grove, Jagged Peaks, Meadow, and Stony Peaks.

Thank you for your help! The changes will be apparent after the next document push. 

-Nurdle
