### ISSUE TITLE
Needs support for larger world files. 

### ISSUE THREAD

**Issue by Equinoxe1** [MicrosoftDocs/minecraft-creator#894]
This really needs support for larger worlds. My world is over 1GB in size so being able to upload worlds up to 2GB in size would be highly appreciated. I can’t stress enough how important this is because I really need it to work.

**Comment by kakinnun** [comment]
Assuming this is related to Chunker. This has been commented on in multiple issues already. The current implementation has this limitation. But there is a potential solution on the horizon. Closing this issue. Stay tuned for announcements on the future of Chunker.
