### ISSUE TITLE
What is "Dispensible"?

### ISSUE THREAD

**Issue by magius96** [MicrosoftDocs/minecraft-creator#895]
The example includes Dispensible, but the documentation does not include that in the parameters.
protection is included in the documentation, but not in the example.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e8f9c51-9151-a04f-d092-2b033651176f
* Version Independent ID: 5d569a13-7897-22b4-9014-f4e6dcfbc44f
* Content: [Item Documentation - minecraft:wearable](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_wearable?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_wearable.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_wearable.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
You're right. There's a casual mention on the Item Use Priority page:

"Certain components have a 'dispensed' behavior. For these items, first `minecraft:projectile` attempts to shoot from the dispenser, and then `minecraft:entity_placer` tries to spawn entities."

I'll remedy that and it should be visible after the next document push. Thanks for the help!
