### ISSUE TITLE
Example and links needed

### ISSUE THREAD

**Issue by magius96** [MicrosoftDocs/minecraft-creator#899]
Please add json example for Minecraft:digger, include examples that select by block name as well as by tags.  Also, add link to list of existing tags and blocks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2be9c1b-320f-744e-a038-31c857bb8faf
* Version Independent ID: fa2cc1d5-361f-6237-0b77-5038319fbced
* Content: [Item Documentation - minecraft:digger](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_digger?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_digger.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/ItemReference/Examples/ItemComponents/minecraft_digger.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @JimSeaman42
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Hi! So, digger has been updated with a JSON example and links to these articles: 

https://learn.microsoft.com/minecraft/creator/reference/content/blockreference/examples/vanillablocktags

https://learn.microsoft.com/minecraft/creator/reference/content/addonsreference/examples/addonblocks
