### ISSUE TITLE
Missing property: minecraft.behavior.pickup_items

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#90]
Missing documentation on `cooldown_after_being_attacked`

From the [piglin](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/piglin)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1a9c7b-f04c-4460-9586-7281e824ec40
* Version Independent ID: 313ad175-5cd9-8202-fc3b-a2815f335bd6
* Content: [minecraft:behavior.pickup_items](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_pickup_items)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_pickup_items.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityGoals/minecraftBehavior_pickup_items.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by docsbryce** [comment]
This is [live](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_pickup_items). Thanks!
