### ISSUE TITLE
Behavior Pack dosent show!

### ISSUE THREAD

**Issue by Sourtcat0** [MicrosoftDocs/minecraft-creator#900]
I have been trying to make the behavior pack work (Im not using the angry cow pack) But I have the manifest, it just wont show up, I orginally thought you have to compress the folder then make it a "MCaddon" file but that did nothing at all when enabled so I have been wondering how to make it show up, I already redid the UUID 3 times none work it never shows up

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab3ad989-cd74-1b9a-d07c-500fc80fdaf7
* Version Independent ID: 2403daea-89fc-ce01-badf-56e6752f562b
* Content: [Create an Angry Cow: An Introduction To Behavior Packs](https://learn.microsoft.com/en-us/minecraft/creator/documents/behaviorpack?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/BehaviorPack.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/BehaviorPack.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by Sourtcat0** [comment]
Update! It shows up finally when used as Mcaddon file, before it would give import error, now it imports but it dosent show anything entirely (Im using a behavior and resource pack and have connected them using Dependencies..

**Comment by iconicNurdle** [comment]
Would you mind zipping up your packs and sending them to me on here so I can take a look?

**Comment by iconicNurdle** [comment]
Also, there's a new process for creating add-on packs that makes it where you don't have to edit UUIDs:

https://learn.microsoft.com/minecraft/creator/documents/behaviorpack

Take a look and let me know what you think.

**Comment by iconicNurdle** [comment]
Hi again. I'm going to go ahead and close this for now. Please let me know if the new way to create packs helps - or what you wish you knew so it could.
