### ISSUE TITLE
Skins for Friends

### ISSUE THREAD

**Issue by BikyGamingCar** [MicrosoftDocs/minecraft-creator#904]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: d2ad0506-2b3b-50e8-ef48-00b019a92013
* Version Independent ID: 32f6c106-14df-da0b-b0e2-97f412eb674f
* Content: [Verpacken eines Skinpakets](https://learn.microsoft.com/de-de/minecraft/creator/documents/packagingaskinpack)
* Content Source: [creator/Documents/PackagingASkinPack.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.de-DE/blob/live/creator/Documents/PackagingASkinPack.md)
* Product: **gaming**
* GitHub Login: @neonerz
* Microsoft Alias: **v-jeffreykim**

**Comment by iconicNurdle** [comment]
Ich helfe Ihnen gerne weiter. Ich benutze die Sprachübersetzung, also verzeihen Sie mir bitte, wenn mein Deutsch nicht so gut ist.

Fühlen Sie sich frei, um weitere Klärung zu bitten, wenn meine Sprache unklar ist.


:)

Können Sie mir bitte mehr über das Problem erzählen?

**Comment by iconicNurdle** [comment]
Hallo nochmal. Ich habe nichts gehört, daher werde ich diese Ausgabe schließen, damit wir uns auf andere konzentrieren können. Bitte zögern Sie nicht, ein neues zu eröffnen, wenn Sie eine Frage haben. Auf Wiedersehen!
