### ISSUE TITLE
Incorrect formatting in "Shapeless Recipe Example"

### ISSUE THREAD

**Issue by Shronky** [MicrosoftDocs/minecraft-creator#906]
Under the ingredients section, a square bracket should enclose the ingredient items, as shown in the other examples and shown below.

"ingredients": [
     {
        "item": "minecraft:fireball",
        "data": 0,
        "count": 4
     }
],

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6116e441-e949-f5bd-0f52-01f10474c481
* Version Independent ID: f4f7ad28-b2f5-6a8a-267b-46df67256de9
* Content: [Recipe Documentation - Shapeless Recipe](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/recipereference/examples/recipedefinitions/minecraftrecipe_shapeless?view=minecraft-bedrock-stable)
* Content Source: [creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_Shapeless.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/RecipeReference/Examples/RecipeDefinitions/minecraftRecipe_Shapeless.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Good catch! I have updated the page and the changes will be apparent after the next document push. Thank you so much!
