### ISSUE TITLE
Failed to connect to Backend?

### ISSUE THREAD

**Issue by ViennyJ** [MicrosoftDocs/minecraft-creator#908]
**Describe the bug**
When Uploading a world (specifically .mcworld file) it wouldn't work and says "Oops, Failed to connect to backend
Something went wrong communicating with the server."

**To Reproduce**
1. Go to chunker.app/#
2. Click on Upload archive 
3. Uploaded world.mcworld file

**Expected behavior**
I expected it work as it should :(

**Screenshot**
![Screenshot_20240815-222929](https://github.com/user-attachments/assets/60310c19-dce3-4dbc-89bc-f1870cdf578b)

**Smartphone**
 - Device: [Infinix Hot 30 Play]
 - OS: [XOS 13]
 - Browser [Chrome]
 - Version [127.0.6533.103]

**Additional context**
I downloaded it from my server and have tested it in my minecraft bedrock. Thx.

**Comment by FormallyMyles** [comment]
Could you confirm what internet provider you use? Have you tried a different device? This error sometimes happens when a VPN / Proxy is in use.

**Comment by ViennyJ** [comment]
> > Could you confirm what internet provider you use? Have you tried a different device? This error sometimes happens when a VPN / Proxy is in use.
> 
> I use NetGuard, it only blocks network from an app

my ISP is Converge btw, it works on mobile data.

**Comment by FormallyMyles** [comment]
> > > Could you confirm what internet provider you use? Have you tried a different device? This error sometimes happens when a VPN / Proxy is in use.
> > 
> > 
> > I use NetGuard, it only blocks network from an app
> 
> my ISP is Converge btw, it works on mobile data.

Are you able to try a different device? I suspect it might be to do with how your ISP does handling of ports if you're not using a VPN.

**Comment by ViennyJ** [comment]
> > > > Could you confirm what internet provider you use? Have you tried a different device? This error sometimes happens when a VPN / Proxy is in use.
> > > 
> > > 
> > > I use NetGuard, it only blocks network from an app
> > 
> > 
> > my ISP is Converge btw, it works on mobile data.
> 
> Are you able to try a different device? I suspect it might be to do with how your ISP does handling of ports if you're not using a VPN.

i have tried it now, and it works. I think its the Port forwarding :/

**Comment by FormallyMyles** [comment]
> > > > > Could you confirm what internet provider you use? Have you tried a different device? This error sometimes happens when a VPN / Proxy is in use.
> > > > 
> > > > 
> > > > I use NetGuard, it only blocks network from an app
> > > 
> > > 
> > > my ISP is Converge btw, it works on mobile data.
> > 
> > 
> > Are you able to try a different device? I suspect it might be to do with how your ISP does handling of ports if you're not using a VPN.
> 
> i have tried it now, and it works. I think its the Port forwarding :/
> 
> I deleted the port i forwarded and now it works, it just wont let me download the converted worlds.

I believe this is because your internet provider is using a different IP for when connecting to chunker and requesting a download which unfortunately trips up how the download system works. You might find with a VPN it works if by chance you have access to one to try.

**Comment by ViennyJ** [comment]
> > > > > > Could you confirm what internet provider you use? Have you tried a different device? This error sometimes happens when a VPN / Proxy is in use.
> > > > > 
> > > > > 
> > > > > I use NetGuard, it only blocks network from an app
> > > > 
> > > > 
> > > > my ISP is Converge btw, it works on mobile data.
> > > 
> > > 
> > > Are you able to try a different device? I suspect it might be to do with how your ISP does handling of ports if you're not using a VPN.
> > 
> > 
> > i have tried it now, and it works. I think its the Port forwarding :/
> > I deleted the port i forwarded and now it works, it just wont let me download the converted worlds.
> 
> I believe this is because your internet provider is using a different IP for when connecting to chunker and requesting a download which unfortunately trips up how the download system works. You might find with a VPN it works if by chance you have access to one to try.

Thanks, i found this solution working!
