### ISSUE TITLE
help me please with the editor

### ISSUE THREAD

**Issue by adeel-dot** [MicrosoftDocs/minecraft-creator#915]
[Enter feedback here]

when i try to install the editor it just gives me the normal preview and yes ive tried everything so why does it not work?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Version Independent ID: 7f970d29-d692-24c3-0ebb-53c97f19c9c8
* Content: [Minecraft Bedrock Editor Installation](https://learn.microsoft.com/en-us/minecraft/creator/documents/editorinstallation?view=minecraft-bedrock-stable)
* Content Source: [creator/Documents/EditorInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/EditorInstallation.md)
* Service: **minecraft-bedrock-edition**
* GitHub Login: @iconicNurdle
* Microsoft Alias: **mikeam**

**Comment by iconicNurdle** [comment]
Hi! I'll be glad to help. When you launch Editor from the special shortcut, do you get this screen:

![image](https://github.com/user-attachments/assets/314b3fc2-cb3b-42a5-b4ac-e2d704c157ca)

...

Or this screen:

![image](https://github.com/user-attachments/assets/9e941d82-5a0c-4c48-9ef2-42ef56e28d2a)

**Comment by adeel-dot** [comment]
I get the second screen  Sent from Mail for Windows From: Jill HeadenSent: 20 September 2024 20:52To: MicrosoftDocs/minecraft-creatorCc: adeel-dot; AuthorSubject: Re: [MicrosoftDocs/minecraft-creator] help me please with the editor (Issue #915) Hi! I'll be glad to help. When you launch Editor from the special shortcut, do you get this screen:image.png (view on web)...Or this screen:image.png (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by iconicNurdle** [comment]
And your shortcut has exactly this path:   

minecraft-preview:?Editor=true

![image](https://github.com/user-attachments/assets/1b609b26-833f-466b-8191-a922efc54ec6)

Can you send me a screenshot?
(Hint: Windows button + Shift Key and S, then draw a box just around your shortcut properties and Paste it into your reply.)

p.s. Just curious - what is the code at the top of your reply?

**Comment by adeel-dot** [comment]
Sent from Mail for Windows From: Jill HeadenSent: 23 September 2024 16:04To: MicrosoftDocs/minecraft-creatorCc: adeel-dot; AuthorSubject: Re: [MicrosoftDocs/minecraft-creator] help me please with the editor (Issue #915) And your shortcut has exactly this path:minecraft-preview:?Editor=trueimage.png (view on web)Can you send me a screenshot?(Hint: Windows button + Shift Key and S, then draw a box just around your shortcut properties and Paste it into your reply.)p.s. Just curious - what is the code at the top of your reply?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by iconicNurdle** [comment]
Oh! The code is from replying through email. Well, I learn something new every day. 

If you can't attach a screen shot through email, you could try copy-pasting it into the issue directly on GitHub.

This is a link to the issue:

https://github.com/MicrosoftDocs/minecraft-creator/issues/915

**Comment by adeel-dot** [comment]
![Screenshot 2024-09-23 202521](https://github.com/user-attachments/assets/be1b7b66-3968-4fbb-ac31-50ac4e97ba6a)

**Comment by iconicNurdle** [comment]
Hmmm... That really should be working....

What version of Minecraft Preview are you using?

**Comment by adeel-dot** [comment]
in using v1.20.70.21

**Comment by adeel-dot** [comment]
it opens the preview

**Comment by iconicNurdle** [comment]
Hmmm... what if you install a new version of Preview?

**Comment by adeel-dot** [comment]
how do i do that exactly?

**Comment by adeel-dot** [comment]
i cant it takes 10 hrs

**Comment by iconicNurdle** [comment]
Did you ever get that version of Preview to open the Editor?

Also, you're on a Windows 10 or Windows 11 PC, right?

**Comment by adeel-dot** [comment]
windows 11 and no

**Comment by iconicNurdle** [comment]
At this point, the next troubleshooting step would be to install a newer version of Minecraft Preview. I know takes 10 hours, but the good news is that there are more tools in the newer version.

Here is a link to a page about Preview version 1.21.30.23

https://www.minecraft.net/article/minecraft-preview-1-21-30-23

And here is a link to download the .zip to install that newer version of Preview: https://github.com/Mojang/bedrock-samples/archive/refs/tags/v1.21.30.23-preview.zip

I wish I had something else to tell you to try. 

Please let me know if you do upgrade and whether that helps, okay?

**Comment by iconicNurdle** [comment]
I'm closing this for now. Please let me know if you get a new version of Preview and if it works, okay?
