### ISSUE TITLE
`query.state_time` appears in the expiremental molang list when it is stable.

### ISSUE THREAD

**Issue by ThomasOrs** [MicrosoftDocs/minecraft-creator#917]
**Describe the bug**
`query.state_time` appears in the [Molang Documentation - Experimental Query Functions](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/experimentalqueryfunctions?view=minecraft-bedrock-experimental) list, but it was stabilised in [1.21.20](https://learn.microsoft.com/en-us/minecraft/creator/documents/update1.21.20?view=minecraft-bedrock-stable)

**To Reproduce**
1. Go to [Molang Documentation - Experimental Query Functions](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/molangreference/examples/molangconcepts/experimentalqueryfunctions?view=minecraft-bedrock-experimental)
2. Observe `query.state_time` is listed in experimental and requiring the upcoming creator features toggle

**Expected behavior**
Experimental features are no longer listed as experimental after stabilisation.

**Screenshots**
![image](https://github.com/user-attachments/assets/f45348e5-4aa2-4d50-87ee-48cc39119ef0)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Edge
 - Version 128.0.2739.42

**Comment by iconicNurdle** [comment]
Hi! I just confirmed that that change was made at the last release. Thanks!
