### ISSUE TITLE
Dyeable component is documented incorrectly

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#918]
https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_dyeable?view=minecraft-bedrock-stable

![image](https://github.com/user-attachments/assets/5566d5f4-8747-42ed-85a9-e56aa1e9df8f)
The parameter section contains `dyed` as part of the `dyeable` component which is incorrect. This parameter is part of the `minecraft:icon` component instead.

**Comment by iconicNurdle** [comment]
Good catch - page is fixed and changes will be apparent after the next document push. Thank you!
