### ISSUE TITLE
Duplicate namespaces - Deferred Lighting Customization Example

### ISSUE THREAD

**Issue by SmokeyStack** [MicrosoftDocs/minecraft-creator#919]
https://learn.microsoft.com/en-us/minecraft/creator/documents/deferredlighting/lightingcustomization?view=minecraft-bedrock-stable

![image](https://github.com/user-attachments/assets/296a09fe-0823-484e-8962-5d96055a0e19)

In the code snippet above, the object has two namespaces `minecraft:minecraft:` when the proper one should be `minecraft:`

**Comment by iconicNurdle** [comment]
Good catch! Typo is fixed and it will be apparent after the next doc release. Thank you!
