### ISSUE TITLE
Missing documentation: minecraft:givable

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#92]
Missing documentation on the `trigger` object structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8bbde5f-4ced-ab9a-950f-875848113f05
* Version Independent ID: 48a7ced5-056f-3fb1-304f-aabcbc9a3bd1
* Content: [minecraft:giveable](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_giveable)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_giveable.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_giveable.md)
* Product: **gaming**
* GitHub Login: @v-jeffreykim
* Microsoft Alias: **v-jeffreykim**

**Comment by JimSeaman42** [comment]
Thank you for your feedback! This issue seems to no longer be applicable, and will be closed.

**Comment by DaanV2** [comment]
> Thank you for your feedback! This issue seems to no longer be applicable, and will be closed.

@JimSeaman42 Has it been fixed?
Im still seeing vanilla examples that use the trigger object, but no documentation
