### ISSUE TITLE
on_death contradiction

### ISSUE THREAD

**Issue by tryashtar** [MicrosoftDocs/minecraft-creator#923]
The [queue_command page](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entityevents/minecraftevents_queue_command?view=minecraft-bedrock-stable) uses an example entity that uses the `on_death` component. However, the [on_death page](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitytriggers/minecrafttrigger_on_death?view=minecraft-bedrock-stable) says:
> minecraft:on_death can only be used by the ender_dragon entity.

Therefore, either this quote is false or the example does not work.

**Comment by iconicNurdle** [comment]
Good point! Times have changed. Incorrect note is eradicated. Thanks for the catch!
