### ISSUE TITLE
minecraft:vibration_listener component can't be used on any custom entities still? 1.21.40

### ISSUE THREAD

**Issue by StealthyExpertX** [MicrosoftDocs/minecraft-creator#928]
**Describe the bug**
minecraft:vibration_listener component can't be used on any custom entities still? tested as of 1.21.40

**To Reproduce**
1. Go to Minecraft
2. Test with an Add-on that tries to recreate a warden without a Runtime Identifier and add the component it can be a blank entity too which ever is easier and the game will tell you that you can not do that yet, its been giving us this message since wardens were first added it should be added to the game and finished.

**Expected behavior**
The component can be added to custom entities to ensure creators can create custom wardens.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows 11, Android, Xbox One, PS5, Switch, IOS
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
I gave plenty, the in-game content log errors, are out dated and thus the documentation is wrong about the component and cant be used by creators at present.

**Comment by mammerla** [comment]
Noted this feedback in our tracker -- for making this functionality better exposed to creators.  We'll also add more documentation (well, that the component is essentially internal and limited to the Warden and Allay.)
