### ISSUE TITLE
Missing components: spawn rules

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/minecraft-creator#93]
Missing documentation on the following properties:

- [x] minecraft:delay_filter
- [x] minecraft:distance_filter
- [x] minecraft:height_filter
- [x] minecraft:player_in_village_filter
- [x] minecraft:permute_type
- [x] minecraft:mob_event_filter
- [x] minecraft:spawn_event
- [x] minecraft:spawns_on_block_filter
- [x] minecraft:spawns_on_block_prevented_filter
- [x] minecraft:spawns_lava
- [x] minecraft:spawns_underground
- [x] minecraft:weight
- [x] minecraft:world_age_filter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbb56c6-1b3f-effd-e17d-4293cd4ecb28
* Version Independent ID: 212d4b6c-84d1-8786-3647-1a0a32212918
* Content: [Spawn Rules and Data-Driven Spawning](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/cliententitydocumenation/datadrivenspawning)
* Content Source: [creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/DataDrivenSpawning.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/DataDrivenSpawning.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by stirante** [comment]
Additionally those components are missing:
```
minecraft:disallow_spawns_in_bubble
minecraft:is_experimental
minecraft:is_persistent
minecraft:spawns_above_block_filter
```

**Comment by docsbryce** [comment]
Hi @DaanV2, many of these are available now in the docs. I will follow up on the couple you had reported and the ones listed by @stirante above. Thanks! 

[Data Driven Spawning Filters Docs](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/cliententitydocumentation/datadrivenspawning)

**Comment by iconicNurdle** [comment]
Thanks for the help!

 - minecraft:spawn_event has been added
- minecraft:disallow_spawns_in_bubble has been added
- minecraft:is_experimental - not a spawn rule. It is part of the description, usually seen alongside `is_spawnable` and `is_summonable`
- minecraft:is_persistent - not a spawn rule, used as a test, exists in the "filters" section
- minecraft:spawns_above_block_filter - Not found in use... may be the same as minecraft:spawns_on_block_filter
