### ISSUE TITLE
[Vanilla Pack Feedback] 'minecraft:fire_immune' is improperly formatted. 

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#95]
All entity component in Minecraft are this format: `'minecraft:something': { ... }`.

On this page, the NPC is shown using this: `'minecraft:fire_immune': true`.

While I am willing to accept that somebody hard-coded this functionality into the `fire_immune` component, and that the syntax isn't *technically* wrong, its extremely frustrating to see this kind of inconsistent syntax inside of the vanilla behavior pack. 

We use the vanilla behavior pack as a reference, so it would be really awesome if it could conform to accepted style guidelines. 

⚠I am not asking for the documentation to be updated. I am asking for the vanilla behavior pack to be updated ⚠

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb6b3a81-8091-0173-5f81-53f32d5000d3
* Version Independent ID: a40bcbbc-2fe6-48ea-8dcf-665f79495ece
* Content: [npc](https://docs.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/npc)
* Content Source: [creator/Reference/Source/VanillaBehaviorPack_Snippets/entities/npc.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Source/VanillaBehaviorPack_Snippets/entities/npc.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by JimSeaman42** [comment]
Thank you for your feedback. This channel is specifically for documentation-related issues and we are unable to make changes to the Vanilla behavior pack, however I will pass this on to the proper channels.
