### ISSUE TITLE
Missing population control groups

### ISSUE THREAD

**Issue by ItsRichHeart** [MicrosoftDocs/minecraft-creator#96]
[Enter feedback here]

In the documentation. It states it has 
> There are 3 pools that entities can be assigned to: -animal -water_animal -monster

However the game actually has 5 of them used and a 6th one, but that isn't used but could still be mentioned.

The 6 pools/population control groups are: Animal, Water_Animal, Monster, Cat, Pillager and Villager. Villager isn't used as villagers don't spawn using the natural spawning rules

Cat is used in the documentations, however it doesn't serve anything in game, maybe add anything about that (The amount of cats is based per village rather than the spawning rules)

Also there are some spelling mistakes:
> population control.Each pool

Needs a space after the dot

> spawn limit, By setting an entity

comma should be a dot

> The minecraft namespace is reserved for the vanilla Minecraft rules.When changing an existing mob

Needs space after the dot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbb56c6-1b3f-effd-e17d-4293cd4ecb28
* Version Independent ID: 212d4b6c-84d1-8786-3647-1a0a32212918
* Content: [Spawn Rules and Data-Driven Spawning](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/cliententitydocumenation/datadrivenspawning)
* Content Source: [creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/DataDrivenSpawning.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/ClientEntityDocumenation/DataDrivenSpawning.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment]
This has been updated to include cats as an added pool, with a note attached talking about villagers and pillagers. 

The spelling and grammar changes have been made as well.

**Comment by v-josjones** [comment]
Marking as closed. If there are any other issues with what's been put in place, please feel free to open this issue back up.
