### ISSUE TITLE
[PRIVACY] [GAMETEST] Privacy issue for common gametest functionality

### ISSUE THREAD

**Issue by GTB3NW** [MicrosoftDocs/minecraft-creator#99]
**Is your feature request related to a problem? Please describe.**

Users are commonly catching chat messages and applying rank prefixes via cancelling and doing a `rawtext` command. This stops users privacy settings from being applied due to the xbox account not being associated with the message printed anymore.

**Describe the solution you'd like**

Not quite sure of a solution, potentially add the ability to edit a traditional message, or add specific recommendations not to do this.

**Describe alternatives you've considered**

N/A

**Additional context**

See various examples in `#js-gametests` of chat prefixes

**Comment by tryashtar** [comment]
This is the intended way to do "rank prefixes": https://minecraft.fandom.com/wiki/Commands/team
